package com.mg.merp.security.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="SEC_GROUPS"
)
public class Groups extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private SysClient SysClient;
     private String Name;
     private Set<ModuleAccess> SecModulesAccess = new HashSet<ModuleAccess>(0);
     private Set<LinkUsersGroups> SecLinkUsersGroups = new HashSet<LinkUsersGroups>(0);

    public Groups() {
    }

	
    public Groups(String Name) {
        this.Name = Name;
    }
    public Groups(SysClient SysClient, String Name, Set<ModuleAccess> SecModulesAccess, Set<LinkUsersGroups> SecLinkUsersGroups) {
       this.SysClient = SysClient;
       this.Name = Name;
       this.SecModulesAccess = SecModulesAccess;
       this.SecLinkUsersGroups = SecLinkUsersGroups;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEC_GROUPS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="NAME", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="Group")
    public Set<ModuleAccess> getSecModulesAccess() {
        return this.SecModulesAccess;
    }
    
    public void setSecModulesAccess(Set<ModuleAccess> SecModulesAccess) {
        this.SecModulesAccess = SecModulesAccess;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="Group")
    public Set<LinkUsersGroups> getSecLinkUsersGroups() {
        return this.SecLinkUsersGroups;
    }
    
    public void setSecLinkUsersGroups(Set<LinkUsersGroups> SecLinkUsersGroups) {
        this.SecLinkUsersGroups = SecLinkUsersGroups;
    }




}


