package com.mg.merp.security.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LinkUsersGroups generated by hbm2java
 */
@Entity
@Table(name="SEC_LINK_USERS_GROUPS"
)
public class LinkUsersGroups extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private Groups Group;
     private SysClient SysClient;
     private SecUser User;

    public LinkUsersGroups() {
    }

    public LinkUsersGroups(Groups Group, SysClient SysClient, SecUser User) {
       this.Group = Group;
       this.SysClient = SysClient;
       this.User = User;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEC_LINK_USERS_GROUPS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GROUP_ID")
    public Groups getGroup() {
        return this.Group;
    }
    
    public void setGroup(Groups Group) {
        this.Group = Group;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public SecUser getUser() {
        return this.User;
    }
    
    public void setUser(SecUser User) {
        this.User = User;
    }




}


