package com.mg.merp.security.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.core.model.SysModule;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ModuleAccess generated by hbm2java
 */
@Entity
@Table(name="SEC_MODULE_ACCESS"
)
public class ModuleAccess extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private Groups Group;
     private SysModule Module;
     private SysClient SysClient;

    public ModuleAccess() {
    }

    public ModuleAccess(Groups Group, SysModule Module, SysClient SysClient) {
       this.Group = Group;
       this.Module = Module;
       this.SysClient = SysClient;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SEC_MODULE_ACCESS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GROUP_ID")
    public Groups getGroup() {
        return this.Group;
    }
    
    public void setGroup(Groups Group) {
        this.Group = Group;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODULE_ID")
    public SysModule getModule() {
        return this.Module;
    }
    
    public void setModule(SysModule Module) {
        this.Module = Module;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }




}


