package com.mg.merp.baiengine.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.framework.support.orm.EnumUserType;
import com.mg.merp.core.model.Folder;
import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Constant generated by hbm2java
 */
@Entity
@Table(name="ALG_CONST"
)
public class Constant extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Folder Folder;
     private SysClient SysClient;
     private String Code;
     private String Description;
     private EnumUserType DataType;
     private Set<ConstantValue> ConstValues = new HashSet<ConstantValue>(0);

    public Constant() {
    }

    public Constant(Folder Folder, SysClient SysClient, String Code, String Description, EnumUserType DataType, Set<ConstantValue> ConstValues) {
       this.Folder = Folder;
       this.SysClient = SysClient;
       this.Code = Code;
       this.Description = Description;
       this.DataType = DataType;
       this.ConstValues = ConstValues;
    }
   
     @SequenceGenerator(name="generator", sequenceName="ALG_CONST_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FOLDER_ID")
    public Folder getFolder() {
        return this.Folder;
    }
    
    public void setFolder(Folder Folder) {
        this.Folder = Folder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CODE", columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="DESCRIPTION", columnDefinition="VARCHAR", length=256)
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    
    @Column(name="DATATYPE", columnDefinition="INTEGER")
    public EnumUserType getDataType() {
        return this.DataType;
    }
    
    public void setDataType(EnumUserType DataType) {
        this.DataType = DataType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="Const")
    public Set<ConstantValue> getConstValues() {
        return this.ConstValues;
    }
    
    public void setConstValues(Set<ConstantValue> ConstValues) {
        this.ConstValues = ConstValues;
    }




}


