package com.mg.merp.baiengine.model;

import com.mg.merp.core.model.SysClass;
import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CustomUserAction generated by hbm2java
 */
@Entity
@Table(name = "ALG_CUSTOM_USER_ACTION")
public class CustomUserAction extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Repository BAi;

    private SysClass SysClass;

    private SysClient SysClient;

    private String Code;

    private String Description;

    private String Caption;

    private String Hint;

    private String KeyStroke;

    private boolean FromMenu;

    private boolean FromToolbar;

    private boolean ForceRefresh;

    private boolean SeparatorBefore;

    private boolean SeparatorAfter;

    private String Icon;

    private Short Priority;

    private boolean Active;

    private Set<CustomUserActionPermiss> Permissions = new HashSet<CustomUserActionPermiss>(0);

    public CustomUserAction() {
    }

    public CustomUserAction(String Code) {
        this.Code = Code;
    }

    public CustomUserAction(Repository BAi, SysClass SysClass, SysClient SysClient, String Code, String Description, String Caption, String Hint, String KeyStroke, boolean FromMenu, boolean FromToolbar, boolean ForceRefresh, boolean SeparatorBefore, boolean SeparatorAfter, String Icon, Short Priority, boolean Active, Set<CustomUserActionPermiss> Permissions) {
        this.BAi = BAi;
        this.SysClass = SysClass;
        this.SysClient = SysClient;
        this.Code = Code;
        this.Description = Description;
        this.Caption = Caption;
        this.Hint = Hint;
        this.KeyStroke = KeyStroke;
        this.FromMenu = FromMenu;
        this.FromToolbar = FromToolbar;
        this.ForceRefresh = ForceRefresh;
        this.SeparatorBefore = SeparatorBefore;
        this.SeparatorAfter = SeparatorAfter;
        this.Icon = Icon;
        this.Priority = Priority;
        this.Active = Active;
        this.Permissions = Permissions;
    }

    @SequenceGenerator(name = "generator", sequenceName = "ALG_CUSTOM_USER_ACTION_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ALGORITHM_ID")
    public Repository getBAi() {
        return this.BAi;
    }

    public void setBAi(Repository BAi) {
        this.BAi = BAi;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLASS_ID")
    public SysClass getSysClass() {
        return this.SysClass;
    }

    public void setSysClass(SysClass SysClass) {
        this.SysClass = SysClass;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 20)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 256)
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    @Column(name = "CAPTION", columnDefinition = "VARCHAR", length = 80)
    public String getCaption() {
        return this.Caption;
    }

    public void setCaption(String Caption) {
        this.Caption = Caption;
    }

    @Column(name = "HINT", columnDefinition = "VARCHAR", length = 80)
    public String getHint() {
        return this.Hint;
    }

    public void setHint(String Hint) {
        this.Hint = Hint;
    }

    @Column(name = "KEY_STROKE", columnDefinition = "VARCHAR", length = 40)
    public String getKeyStroke() {
        return this.KeyStroke;
    }

    public void setKeyStroke(String KeyStroke) {
        this.KeyStroke = KeyStroke;
    }

    @Column(name = "FROM_MENU", columnDefinition = "SMALLINT")
    public boolean isFromMenu() {
        return this.FromMenu;
    }

    public void setFromMenu(boolean FromMenu) {
        this.FromMenu = FromMenu;
    }

    @Column(name = "FROM_TOOLBAR", columnDefinition = "SMALLINT")
    public boolean isFromToolbar() {
        return this.FromToolbar;
    }

    public void setFromToolbar(boolean FromToolbar) {
        this.FromToolbar = FromToolbar;
    }

    @Column(name = "FORCE_REFRESH", columnDefinition = "SMALLINT")
    public boolean isForceRefresh() {
        return this.ForceRefresh;
    }

    public void setForceRefresh(boolean ForceRefresh) {
        this.ForceRefresh = ForceRefresh;
    }

    @Column(name = "SEPARATOR_BEFORE", columnDefinition = "SMALLINT")
    public boolean isSeparatorBefore() {
        return this.SeparatorBefore;
    }

    public void setSeparatorBefore(boolean SeparatorBefore) {
        this.SeparatorBefore = SeparatorBefore;
    }

    @Column(name = "SEPARATOR_AFTER", columnDefinition = "SMALLINT")
    public boolean isSeparatorAfter() {
        return this.SeparatorAfter;
    }

    public void setSeparatorAfter(boolean SeparatorAfter) {
        this.SeparatorAfter = SeparatorAfter;
    }

    @Column(name = "ICON", columnDefinition = "VARCHAR", length = 256)
    public String getIcon() {
        return this.Icon;
    }

    public void setIcon(String Icon) {
        this.Icon = Icon;
    }

    @Column(name = "PRIORITY", columnDefinition = "SMALLINT")
    public Short getPriority() {
        return this.Priority;
    }

    public void setPriority(Short Priority) {
        this.Priority = Priority;
    }

    @Column(name = "IS_ACTIVE", columnDefinition = "SMALLINT")
    public boolean isActive() {
        return this.Active;
    }

    public void setActive(boolean Active) {
        this.Active = Active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "CustomUserAction")
    public Set<CustomUserActionPermiss> getPermissions() {
        return this.Permissions;
    }

    public void setPermissions(Set<CustomUserActionPermiss> Permissions) {
        this.Permissions = Permissions;
    }
}

