package com.mg.merp.planning.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.warehouse.model.Warehouse;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * MrpReport generated by hbm2java
 */
@Entity
@Table(name = "PP_MRP_REPORT")
public class MrpReport extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private MrpVersionControl MrpVersionControl;

    private Warehouse Warehouse;

    private Catalog Catalog;

    private Date RequiredDate;

    private MRPOrderType MrpOrderType;

    private String PpReference;

    private BigDecimal QtyAvailable;

    private BigDecimal MrpQuantity;

    private MRPSource MrpSource;

    private InputOutputFlag MrpInputOutputFlag;

    private boolean FixedInput;

    private Date OrderDate;

    private boolean MrpArrearsFlag;

    private Date OriginalDate;

    private BigDecimal OriginalQuantity;

    private Integer Sequence;

    private RescheduleFlag MrpRescheduleFlag;

    public MrpReport() {
    }

    public MrpReport(SysClient SysClient, MrpVersionControl MrpVersionControl, Warehouse Warehouse, Catalog Catalog, Date RequiredDate, MRPOrderType MrpOrderType, String PpReference, BigDecimal QtyAvailable, BigDecimal MrpQuantity, MRPSource MrpSource, InputOutputFlag MrpInputOutputFlag, boolean FixedInput, Date OrderDate, boolean MrpArrearsFlag, Date OriginalDate, BigDecimal OriginalQuantity, Integer Sequence, RescheduleFlag MrpRescheduleFlag) {
        this.SysClient = SysClient;
        this.MrpVersionControl = MrpVersionControl;
        this.Warehouse = Warehouse;
        this.Catalog = Catalog;
        this.RequiredDate = RequiredDate;
        this.MrpOrderType = MrpOrderType;
        this.PpReference = PpReference;
        this.QtyAvailable = QtyAvailable;
        this.MrpQuantity = MrpQuantity;
        this.MrpSource = MrpSource;
        this.MrpInputOutputFlag = MrpInputOutputFlag;
        this.FixedInput = FixedInput;
        this.OrderDate = OrderDate;
        this.MrpArrearsFlag = MrpArrearsFlag;
        this.OriginalDate = OriginalDate;
        this.OriginalQuantity = OriginalQuantity;
        this.Sequence = Sequence;
        this.MrpRescheduleFlag = MrpRescheduleFlag;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PP_MRP_REPORT_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MRP_VERSION_CONTROL_ID")
    public MrpVersionControl getMrpVersionControl() {
        return this.MrpVersionControl;
    }

    public void setMrpVersionControl(MrpVersionControl MrpVersionControl) {
        this.MrpVersionControl = MrpVersionControl;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WAREHOUSE_ID")
    public Warehouse getWarehouse() {
        return this.Warehouse;
    }

    public void setWarehouse(Warehouse Warehouse) {
        this.Warehouse = Warehouse;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATALOG_ID")
    public Catalog getCatalog() {
        return this.Catalog;
    }

    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

    @Column(name = "REQUIRED_DATE", columnDefinition = "TIMESTAMP")
    @DataItemName("Planning.MRPRecommendation.RequiredDate")
    public Date getRequiredDate() {
        return this.RequiredDate;
    }

    public void setRequiredDate(Date RequiredDate) {
        this.RequiredDate = RequiredDate;
    }

    @Column(name = "MRP_ORDER_TYPE")
    @Enumerated(EnumType.ORDINAL)
    public MRPOrderType getMrpOrderType() {
        return this.MrpOrderType;
    }

    public void setMrpOrderType(MRPOrderType MrpOrderType) {
        this.MrpOrderType = MrpOrderType;
    }

    @Column(name = "PP_REFERENCE", columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Planning.MRPRecommendation.Reference")
    public String getPpReference() {
        return this.PpReference;
    }

    public void setPpReference(String PpReference) {
        this.PpReference = PpReference;
    }

    @Column(name = "QTY_AVAILABLE", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Planning.MRPReport.QtyAvailable")
    public BigDecimal getQtyAvailable() {
        return this.QtyAvailable;
    }

    public void setQtyAvailable(BigDecimal QtyAvailable) {
        this.QtyAvailable = QtyAvailable;
    }

    @Column(name = "MRP_QUANTITY", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Planning.MRPReport.MrpQuantity")
    public BigDecimal getMrpQuantity() {
        return this.MrpQuantity;
    }

    public void setMrpQuantity(BigDecimal MrpQuantity) {
        this.MrpQuantity = MrpQuantity;
    }

    @Column(name = "MRP_SOURCE")
    @Enumerated(EnumType.ORDINAL)
    public MRPSource getMrpSource() {
        return this.MrpSource;
    }

    public void setMrpSource(MRPSource MrpSource) {
        this.MrpSource = MrpSource;
    }

    @Column(name = "MRP_INPUT_OUTPUT_FLAG")
    @Enumerated(EnumType.ORDINAL)
    public InputOutputFlag getMrpInputOutputFlag() {
        return this.MrpInputOutputFlag;
    }

    public void setMrpInputOutputFlag(InputOutputFlag MrpInputOutputFlag) {
        this.MrpInputOutputFlag = MrpInputOutputFlag;
    }

    @Column(name = "FIXED_INPUT", columnDefinition = "SMALLINT")
    @DataItemName("Planning.MRPReport.FixedInput")
    public boolean isFixedInput() {
        return this.FixedInput;
    }

    public void setFixedInput(boolean FixedInput) {
        this.FixedInput = FixedInput;
    }

    @Column(name = "ORDER_DATE", columnDefinition = "TIMESTAMP")
    @DataItemName("Planning.MRPRecommendation.OrderDate")
    public Date getOrderDate() {
        return this.OrderDate;
    }

    public void setOrderDate(Date OrderDate) {
        this.OrderDate = OrderDate;
    }

    @Column(name = "MRP_ARREARS_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("Planning.MRPRecommendation.MRPArrearsFlag")
    public boolean isMrpArrearsFlag() {
        return this.MrpArrearsFlag;
    }

    public void setMrpArrearsFlag(boolean MrpArrearsFlag) {
        this.MrpArrearsFlag = MrpArrearsFlag;
    }

    @Column(name = "ORIGINAL_DATE", columnDefinition = "TIMESTAMP")
    @DataItemName("Planning.MRPRecommendation.OriginalDate")
    public Date getOriginalDate() {
        return this.OriginalDate;
    }

    public void setOriginalDate(Date OriginalDate) {
        this.OriginalDate = OriginalDate;
    }

    @Column(name = "ORIGINAL_QUANTITY", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Planning.MRPRecommendation.OriginalQuantity")
    public BigDecimal getOriginalQuantity() {
        return this.OriginalQuantity;
    }

    public void setOriginalQuantity(BigDecimal OriginalQuantity) {
        this.OriginalQuantity = OriginalQuantity;
    }

    @Column(name = "SEQUENCE", columnDefinition = "INTEGER")
    @DataItemName("Planning.MRPSequence")
    public Integer getSequence() {
        return this.Sequence;
    }

    public void setSequence(Integer Sequence) {
        this.Sequence = Sequence;
    }

    @Column(name = "MRP_RESCHEDULE_FLAG")
    @Enumerated(EnumType.ORDINAL)
    public RescheduleFlag getMrpRescheduleFlag() {
        return this.MrpRescheduleFlag;
    }

    public void setMrpRescheduleFlag(RescheduleFlag MrpRescheduleFlag) {
        this.MrpRescheduleFlag = MrpRescheduleFlag;
    }
}

