package com.mg.merp.planning.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.framework.support.orm.EnumUserType;
import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.warehouse.model.Warehouse;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MrpReport generated by hbm2java
 */
@Entity
@Table(name="PP_MRP_REPORT"
)
public class MrpReport extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private SysClient SysClient;
     private MrpVersionControl MrpVersionControl;
     private Warehouse Warehouse;
     private Catalog Catalog;
     private Date RequiredDate;
     private EnumUserType MrpOrderType;
     private String PpReference;
     private BigDecimal QtyAvailable;
     private BigDecimal MrpQuantity;
     private EnumUserType MrpSource;
     private EnumUserType MrpInputOutputFlag;
     private boolean FixedInput;
     private Date OrderDate;
     private boolean MrpArrearsFlag;
     private Date OriginalDate;
     private BigDecimal OriginalQuantity;
     private Integer Sequence;
     private EnumUserType MrpRescheduleFlag;

    public MrpReport() {
    }

    public MrpReport(SysClient SysClient, MrpVersionControl MrpVersionControl, Warehouse Warehouse, Catalog Catalog, Date RequiredDate, EnumUserType MrpOrderType, String PpReference, BigDecimal QtyAvailable, BigDecimal MrpQuantity, EnumUserType MrpSource, EnumUserType MrpInputOutputFlag, boolean FixedInput, Date OrderDate, boolean MrpArrearsFlag, Date OriginalDate, BigDecimal OriginalQuantity, Integer Sequence, EnumUserType MrpRescheduleFlag) {
       this.SysClient = SysClient;
       this.MrpVersionControl = MrpVersionControl;
       this.Warehouse = Warehouse;
       this.Catalog = Catalog;
       this.RequiredDate = RequiredDate;
       this.MrpOrderType = MrpOrderType;
       this.PpReference = PpReference;
       this.QtyAvailable = QtyAvailable;
       this.MrpQuantity = MrpQuantity;
       this.MrpSource = MrpSource;
       this.MrpInputOutputFlag = MrpInputOutputFlag;
       this.FixedInput = FixedInput;
       this.OrderDate = OrderDate;
       this.MrpArrearsFlag = MrpArrearsFlag;
       this.OriginalDate = OriginalDate;
       this.OriginalQuantity = OriginalQuantity;
       this.Sequence = Sequence;
       this.MrpRescheduleFlag = MrpRescheduleFlag;
    }
   
     @SequenceGenerator(name="generator", sequenceName="PP_MRP_REPORT_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MRP_VERSION_CONTROL_ID")
    public MrpVersionControl getMrpVersionControl() {
        return this.MrpVersionControl;
    }
    
    public void setMrpVersionControl(MrpVersionControl MrpVersionControl) {
        this.MrpVersionControl = MrpVersionControl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WAREHOUSE_ID")
    public Warehouse getWarehouse() {
        return this.Warehouse;
    }
    
    public void setWarehouse(Warehouse Warehouse) {
        this.Warehouse = Warehouse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATALOG_ID")
    public Catalog getCatalog() {
        return this.Catalog;
    }
    
    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

    
    @Column(name="REQUIRED_DATE", columnDefinition="TIMESTAMP")
    public Date getRequiredDate() {
        return this.RequiredDate;
    }
    
    public void setRequiredDate(Date RequiredDate) {
        this.RequiredDate = RequiredDate;
    }

    
    @Column(name="MRP_ORDER_TYPE", columnDefinition="SMALLINT")
    public EnumUserType getMrpOrderType() {
        return this.MrpOrderType;
    }
    
    public void setMrpOrderType(EnumUserType MrpOrderType) {
        this.MrpOrderType = MrpOrderType;
    }

    
    @Column(name="PP_REFERENCE", columnDefinition="VARCHAR", length=80)
    public String getPpReference() {
        return this.PpReference;
    }
    
    public void setPpReference(String PpReference) {
        this.PpReference = PpReference;
    }

    
    @Column(name="QTY_AVAILABLE", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getQtyAvailable() {
        return this.QtyAvailable;
    }
    
    public void setQtyAvailable(BigDecimal QtyAvailable) {
        this.QtyAvailable = QtyAvailable;
    }

    
    @Column(name="MRP_QUANTITY", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getMrpQuantity() {
        return this.MrpQuantity;
    }
    
    public void setMrpQuantity(BigDecimal MrpQuantity) {
        this.MrpQuantity = MrpQuantity;
    }

    
    @Column(name="MRP_SOURCE", columnDefinition="SMALLINT")
    public EnumUserType getMrpSource() {
        return this.MrpSource;
    }
    
    public void setMrpSource(EnumUserType MrpSource) {
        this.MrpSource = MrpSource;
    }

    
    @Column(name="MRP_INPUT_OUTPUT_FLAG", columnDefinition="SMALLINT")
    public EnumUserType getMrpInputOutputFlag() {
        return this.MrpInputOutputFlag;
    }
    
    public void setMrpInputOutputFlag(EnumUserType MrpInputOutputFlag) {
        this.MrpInputOutputFlag = MrpInputOutputFlag;
    }

    
    @Column(name="FIXED_INPUT", columnDefinition="SMALLINT")
    public boolean isFixedInput() {
        return this.FixedInput;
    }
    
    public void setFixedInput(boolean FixedInput) {
        this.FixedInput = FixedInput;
    }

    
    @Column(name="ORDER_DATE", columnDefinition="TIMESTAMP")
    public Date getOrderDate() {
        return this.OrderDate;
    }
    
    public void setOrderDate(Date OrderDate) {
        this.OrderDate = OrderDate;
    }

    
    @Column(name="MRP_ARREARS_FLAG", columnDefinition="SMALLINT")
    public boolean isMrpArrearsFlag() {
        return this.MrpArrearsFlag;
    }
    
    public void setMrpArrearsFlag(boolean MrpArrearsFlag) {
        this.MrpArrearsFlag = MrpArrearsFlag;
    }

    
    @Column(name="ORIGINAL_DATE", columnDefinition="TIMESTAMP")
    public Date getOriginalDate() {
        return this.OriginalDate;
    }
    
    public void setOriginalDate(Date OriginalDate) {
        this.OriginalDate = OriginalDate;
    }

    
    @Column(name="ORIGINAL_QUANTITY", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getOriginalQuantity() {
        return this.OriginalQuantity;
    }
    
    public void setOriginalQuantity(BigDecimal OriginalQuantity) {
        this.OriginalQuantity = OriginalQuantity;
    }

    
    @Column(name="SEQUENCE", columnDefinition="INTEGER")
    public Integer getSequence() {
        return this.Sequence;
    }
    
    public void setSequence(Integer Sequence) {
        this.Sequence = Sequence;
    }

    
    @Column(name="MRP_RESCHEDULE_FLAG", columnDefinition="SMALLINT")
    public EnumUserType getMrpRescheduleFlag() {
        return this.MrpRescheduleFlag;
    }
    
    public void setMrpRescheduleFlag(EnumUserType MrpRescheduleFlag) {
        this.MrpRescheduleFlag = MrpRescheduleFlag;
    }




}


