package com.mg.merp.planning.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.mfreference.model.ResourceGroup;
import com.mg.merp.reference.model.Measure;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Formula;

/**
 * RccpDetail generated by hbm2java
 */
@Entity
@Table(name="PP_RCCP_DETAIL"
)
public class RccpDetail extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private RccpHeader RccpHeader;
     private ResourceGroup ResourceGroup;
     private Measure Measure;
     private SysClient SysClient;
     private GenericItem GenericItem;
     private Short BucketOffset;
     private Short MpsBucketOffset;
     private BigDecimal LoadValue;
     private BigDecimal LoadAdjustmentValue;
     private BigDecimal LoadProductionValue;
     private BigDecimal LoadDemandValue;
     private Date BucketStartDate;
     private Date BucketEndDate;

    public RccpDetail() {
    }

	
    public RccpDetail(Integer Id) {
        this.Id = Id;
    }
    public RccpDetail(Integer Id, RccpHeader RccpHeader, ResourceGroup ResourceGroup, Measure Measure, SysClient SysClient, GenericItem GenericItem, Short BucketOffset, Short MpsBucketOffset, BigDecimal LoadValue, BigDecimal LoadAdjustmentValue, BigDecimal LoadProductionValue, BigDecimal LoadDemandValue) {
       this.Id = Id;
       this.RccpHeader = RccpHeader;
       this.ResourceGroup = ResourceGroup;
       this.Measure = Measure;
       this.SysClient = SysClient;
       this.GenericItem = GenericItem;
       this.BucketOffset = BucketOffset;
       this.MpsBucketOffset = MpsBucketOffset;
       this.LoadValue = LoadValue;
       this.LoadAdjustmentValue = LoadAdjustmentValue;
       this.LoadProductionValue = LoadProductionValue;
       this.LoadDemandValue = LoadDemandValue;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RCCP_HEADER_ID")
    public RccpHeader getRccpHeader() {
        return this.RccpHeader;
    }
    
    public void setRccpHeader(RccpHeader RccpHeader) {
        this.RccpHeader = RccpHeader;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_GROUP_ID")
    public ResourceGroup getResourceGroup() {
        return this.ResourceGroup;
    }
    
    public void setResourceGroup(ResourceGroup ResourceGroup) {
        this.ResourceGroup = ResourceGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOAD_MEASURE_ID")
    public Measure getMeasure() {
        return this.Measure;
    }
    
    public void setMeasure(Measure Measure) {
        this.Measure = Measure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PLANNING_ITEM_ID")
    public GenericItem getGenericItem() {
        return this.GenericItem;
    }
    
    public void setGenericItem(GenericItem GenericItem) {
        this.GenericItem = GenericItem;
    }

    
    @Column(name="BUCKET_OFFSET", columnDefinition="SMALLINT")
    public Short getBucketOffset() {
        return this.BucketOffset;
    }
    
    public void setBucketOffset(Short BucketOffset) {
        this.BucketOffset = BucketOffset;
    }

    
    @Column(name="MPS_BUCKET_OFFSET", columnDefinition="SMALLINT")
    public Short getMpsBucketOffset() {
        return this.MpsBucketOffset;
    }
    
    public void setMpsBucketOffset(Short MpsBucketOffset) {
        this.MpsBucketOffset = MpsBucketOffset;
    }

    
    @Column(name="LOAD_VALUE", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getLoadValue() {
        return this.LoadValue;
    }
    
    public void setLoadValue(BigDecimal LoadValue) {
        this.LoadValue = LoadValue;
    }

    
    @Column(name="LOAD_ADJUSTMENT_VALUE", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getLoadAdjustmentValue() {
        return this.LoadAdjustmentValue;
    }
    
    public void setLoadAdjustmentValue(BigDecimal LoadAdjustmentValue) {
        this.LoadAdjustmentValue = LoadAdjustmentValue;
    }

    
    @Column(name="LOAD_PRODUCTION_VALUE", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getLoadProductionValue() {
        return this.LoadProductionValue;
    }
    
    public void setLoadProductionValue(BigDecimal LoadProductionValue) {
        this.LoadProductionValue = LoadProductionValue;
    }

    
    @Column(name="LOAD_DEMAND_VALUE", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getLoadDemandValue() {
        return this.LoadDemandValue;
    }
    
    public void setLoadDemandValue(BigDecimal LoadDemandValue) {
        this.LoadDemandValue = LoadDemandValue;
    }

    
    @Formula(value="(select lb.start_date from pp_rccp_header rh left join pp_mps mp on mp.id = rh.mps_id
        left join pp_planning_level_bucket lb on (BUCKET_OFFSET = lb.bucket_offset) and
        (LB.planning_level_id = mp.planning_level_id) where RH.id = RCCP_HEADER_ID)
      ")
    public Date getBucketStartDate() {
        return this.BucketStartDate;
    }
    
    public void setBucketStartDate(Date BucketStartDate) {
        this.BucketStartDate = BucketStartDate;
    }

    
    @Formula(value="(select lb.end_date from pp_rccp_header rh left join pp_mps mp on mp.id = rh.mps_id
        left join pp_planning_level_bucket lb on (BUCKET_OFFSET = lb.bucket_offset) and
        (LB.planning_level_id = mp.planning_level_id) where RH.id = RCCP_HEADER_ID)
      ")
    public Date getBucketEndDate() {
        return this.BucketEndDate;
    }
    
    public void setBucketEndDate(Date BucketEndDate) {
        this.BucketEndDate = BucketEndDate;
    }




}


