package com.mg.merp.document.model;

import com.mg.merp.core.model.SysClass;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DocSection generated by hbm2java
 */
@Entity
@Table(name = "DOCSECTION")
@DataItemName("Document.DocSection")
public class DocSection extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private SysClass ModelSysClass;

    private SysClass ModelSpecSysClass;

    private SysClass SysClass;

    private SysClass SpecSysClass;

    private String DSName;

    private int FolderType;

    private Integer ModelFolderType;

    private boolean WithTaxes;

    private boolean WithSpec;

    private short Direction;

    private boolean Dummy;

    private String DocumentSearchHelp;

    private String DocumentModelSearchHelp;

    public DocSection() {
    }

    public DocSection(int Id, String DSName, int FolderType, boolean WithTaxes, boolean WithSpec, short Direction, boolean Dummy) {
        this.Id = Id;
        this.DSName = DSName;
        this.FolderType = FolderType;
        this.WithTaxes = WithTaxes;
        this.WithSpec = WithSpec;
        this.Direction = Direction;
        this.Dummy = Dummy;
    }

    public DocSection(int Id, SysClass ModelSysClass, SysClass ModelSpecSysClass, SysClass SysClass, SysClass SpecSysClass, String DSName, int FolderType, Integer ModelFolderType, boolean WithTaxes, boolean WithSpec, short Direction, boolean Dummy, String DocumentSearchHelp, String DocumentModelSearchHelp) {
        this.Id = Id;
        this.ModelSysClass = ModelSysClass;
        this.ModelSpecSysClass = ModelSpecSysClass;
        this.SysClass = SysClass;
        this.SpecSysClass = SpecSysClass;
        this.DSName = DSName;
        this.FolderType = FolderType;
        this.ModelFolderType = ModelFolderType;
        this.WithTaxes = WithTaxes;
        this.WithSpec = WithSpec;
        this.Direction = Direction;
        this.Dummy = Dummy;
        this.DocumentSearchHelp = DocumentSearchHelp;
        this.DocumentModelSearchHelp = DocumentModelSearchHelp;
    }

    public DocSection(Integer id) {
        this.Id = id;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MODEL_CLASS_ID")
    public SysClass getModelSysClass() {
        return this.ModelSysClass;
    }

    public void setModelSysClass(SysClass ModelSysClass) {
        this.ModelSysClass = ModelSysClass;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MODEL_SPEC_CLASS_ID")
    public SysClass getModelSpecSysClass() {
        return this.ModelSpecSysClass;
    }

    public void setModelSpecSysClass(SysClass ModelSpecSysClass) {
        this.ModelSpecSysClass = ModelSpecSysClass;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLASS_ID")
    public SysClass getSysClass() {
        return this.SysClass;
    }

    public void setSysClass(SysClass SysClass) {
        this.SysClass = SysClass;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SPEC_CLASS_ID")
    public SysClass getSpecSysClass() {
        return this.SpecSysClass;
    }

    public void setSpecSysClass(SysClass SpecSysClass) {
        this.SpecSysClass = SpecSysClass;
    }

    @Column(name = "DSNAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Reference.Name")
    public String getDSName() {
        return this.DSName;
    }

    public void setDSName(String DSName) {
        this.DSName = DSName;
    }

    @Column(name = "FOLDERTYPE", nullable = false, columnDefinition = "INTEGER")
    public int getFolderType() {
        return this.FolderType;
    }

    public void setFolderType(int FolderType) {
        this.FolderType = FolderType;
    }

    @Column(name = "MODEL_FOLDERTYPE", columnDefinition = "INTEGER")
    public Integer getModelFolderType() {
        return this.ModelFolderType;
    }

    public void setModelFolderType(Integer ModelFolderType) {
        this.ModelFolderType = ModelFolderType;
    }

    @Column(name = "WITH_TAXES", nullable = false, columnDefinition = "SMALLINT")
    public boolean isWithTaxes() {
        return this.WithTaxes;
    }

    public void setWithTaxes(boolean WithTaxes) {
        this.WithTaxes = WithTaxes;
    }

    @Column(name = "WITH_SPEC", nullable = false, columnDefinition = "SMALLINT")
    public boolean isWithSpec() {
        return this.WithSpec;
    }

    public void setWithSpec(boolean WithSpec) {
        this.WithSpec = WithSpec;
    }

    @Column(name = "DIRECTION", nullable = false, columnDefinition = "SMALLINT")
    public short getDirection() {
        return this.Direction;
    }

    public void setDirection(short Direction) {
        this.Direction = Direction;
    }

    @Column(name = "DUMMY", nullable = false, columnDefinition = "SMALLINT")
    public boolean isDummy() {
        return this.Dummy;
    }

    public void setDummy(boolean Dummy) {
        this.Dummy = Dummy;
    }

    @Column(name = "DOC_SEARCH_HELP", columnDefinition = "VARCHAR", length = 256)
    public String getDocumentSearchHelp() {
        return this.DocumentSearchHelp;
    }

    public void setDocumentSearchHelp(String DocumentSearchHelp) {
        this.DocumentSearchHelp = DocumentSearchHelp;
    }

    @Column(name = "DOCMODEL_SEARCH_HELP", columnDefinition = "VARCHAR", length = 256)
    public String getDocumentModelSearchHelp() {
        return this.DocumentModelSearchHelp;
    }

    public void setDocumentModelSearchHelp(String DocumentModelSearchHelp) {
        this.DocumentModelSearchHelp = DocumentModelSearchHelp;
    }
}

