package com.mg.merp.document.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DocumentLink generated by hbm2java
 */
@Entity
@Table(name = "DOCUMENT_LINK")
public class DocumentLink extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private DocHead Dochead;

    private DocHead Dochead_1;

    private SysClient SysClient;

    public DocumentLink() {
    }

    public DocumentLink(int Id) {
        this.Id = Id;
    }

    public DocumentLink(int Id, DocHead Dochead, DocHead Dochead_1, SysClient SysClient) {
        this.Id = Id;
        this.Dochead = Dochead;
        this.Dochead_1 = Dochead_1;
        this.SysClient = SysClient;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BASEDOC_ID")
    public DocHead getDochead() {
        return this.Dochead;
    }

    public void setDochead(DocHead Dochead) {
        this.Dochead = Dochead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOC_ID")
    public DocHead getDochead_1() {
        return this.Dochead_1;
    }

    public void setDochead_1(DocHead Dochead_1) {
        this.Dochead_1 = Dochead_1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }
}

