package com.mg.merp.contract.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.PriceListHead;
import com.mg.merp.reference.model.PriceType;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ContractSpec generated by hbm2java
 */
@Entity
@Table(name="CONTRACTSPEC"
)
public class ContractSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Catalog Catalog;
     private PriceType PriceType;
     private SysClient SysClient;
     private PhaseFactItem PhaseItemFact;
     private PhasePlanItem PhaseItemPlan;
     private PriceListHead PriceListHead;
     private BigDecimal Quantity;
     private BigDecimal Price;
     private BigDecimal Summa;

    public ContractSpec() {
    }

    public ContractSpec(Catalog Catalog, PriceType PriceType, SysClient SysClient, PhaseFactItem PhaseItemFact, PhasePlanItem PhaseItemPlan, PriceListHead PriceListHead, BigDecimal Quantity, BigDecimal Price, BigDecimal Summa) {
       this.Catalog = Catalog;
       this.PriceType = PriceType;
       this.SysClient = SysClient;
       this.PhaseItemFact = PhaseItemFact;
       this.PhaseItemPlan = PhaseItemPlan;
       this.PriceListHead = PriceListHead;
       this.Quantity = Quantity;
       this.Price = Price;
       this.Summa = Summa;
    }
   
     @SequenceGenerator(name="generator", sequenceName="CONTRACTSPEC_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATALOG_ID")
    public Catalog getCatalog() {
        return this.Catalog;
    }
    
    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRICETYPE_ID")
    public PriceType getPriceType() {
        return this.PriceType;
    }
    
    public void setPriceType(PriceType PriceType) {
        this.PriceType = PriceType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PHASEITEMFACT_ID")
    public PhaseFactItem getPhaseItemFact() {
        return this.PhaseItemFact;
    }
    
    public void setPhaseItemFact(PhaseFactItem PhaseItemFact) {
        this.PhaseItemFact = PhaseItemFact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PHASEITEMPLAN_ID")
    public PhasePlanItem getPhaseItemPlan() {
        return this.PhaseItemPlan;
    }
    
    public void setPhaseItemPlan(PhasePlanItem PhaseItemPlan) {
        this.PhaseItemPlan = PhaseItemPlan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRICELIST_ID")
    public PriceListHead getPriceListHead() {
        return this.PriceListHead;
    }
    
    public void setPriceListHead(PriceListHead PriceListHead) {
        this.PriceListHead = PriceListHead;
    }

    
    @Column(name="QUANTITY", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getQuantity() {
        return this.Quantity;
    }
    
    public void setQuantity(BigDecimal Quantity) {
        this.Quantity = Quantity;
    }

    
    @Column(name="PRICE", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getPrice() {
        return this.Price;
    }
    
    public void setPrice(BigDecimal Price) {
        this.Price = Price;
    }

    
    @Column(name="SUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSumma() {
        return this.Summa;
    }
    
    public void setSumma(BigDecimal Summa) {
        this.Summa = Summa;
    }




}


