package com.mg.merp.contract.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocType;
import com.mg.merp.reference.model.Contractor;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * PhaseFactItem generated by hbm2java
 */
@Entity
@Table(name = "PHASEITEMFACT")
public class PhaseFactItem extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private DocHead DocHead;

    private SysClient SysClient;

    private Contractor Contractor;

    private Date RegDate;

    private BigDecimal FactSum;

    private BigDecimal DistSum;

    private ItemKind Kind;

    private DocType DocType;

    private String DocNumber;

    private Date DocDate;

    private DocHead Document;

    public PhaseFactItem() {
    }

    public PhaseFactItem(DocHead DocHead, SysClient SysClient, Contractor Contractor, Date RegDate, BigDecimal FactSum, BigDecimal DistSum, ItemKind Kind, DocType DocType, String DocNumber, Date DocDate, DocHead Document) {
        this.DocHead = DocHead;
        this.SysClient = SysClient;
        this.Contractor = Contractor;
        this.RegDate = RegDate;
        this.FactSum = FactSum;
        this.DistSum = DistSum;
        this.Kind = Kind;
        this.DocType = DocType;
        this.DocNumber = DocNumber;
        this.DocDate = DocDate;
        this.Document = Document;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PHASEITEMFACT_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    //$NON-NLS-1$
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCHEAD_ID")
    public DocHead getDocHead() {
        return this.DocHead;
    }

    public void setDocHead(DocHead DocHead) {
        this.DocHead = DocHead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONTRACTOR_ID")
    //$NON-NLS-1$
    @DataItemName("Contract.ItemFact.Contractor")
    public Contractor getContractor() {
        return this.Contractor;
    }

    public void setContractor(Contractor Contractor) {
        this.Contractor = Contractor;
    }

    @Column(name = "REGDATE", columnDefinition = "TIMESTAMP")
    //$NON-NLS-1$
    @DataItemName("Contract.ItemFact.RegDate")
    public Date getRegDate() {
        return this.RegDate;
    }

    public void setRegDate(Date RegDate) {
        this.RegDate = RegDate;
    }

    @Column(name = "FACTSUM", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    //$NON-NLS-1$
    @DataItemName("Contract.ItemFact.FactSum")
    public BigDecimal getFactSum() {
        return this.FactSum;
    }

    public void setFactSum(BigDecimal FactSum) {
        this.FactSum = FactSum;
    }

    @Column(name = "DISTSUM", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    //$NON-NLS-1$
    @DataItemName("Contract.ItemFact.Distsum")
    public BigDecimal getDistSum() {
        return this.DistSum;
    }

    public void setDistSum(BigDecimal DistSum) {
        this.DistSum = DistSum;
    }

    @Column(name = "KIND")
    @Enumerated(EnumType.ORDINAL)
    public ItemKind getKind() {
        return this.Kind;
    }

    public void setKind(ItemKind Kind) {
        this.Kind = Kind;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCTYPE")
    //$NON-NLS-1$
    @DataItemName("Document.DocType")
    public DocType getDocType() {
        return this.DocType;
    }

    public void setDocType(DocType DocType) {
        this.DocType = DocType;
    }

    @Column(name = "DOCNUMBER", columnDefinition = "CHAR", length = 20)
    //$NON-NLS-1$
    @DataItemName("Document.DocNumber")
    public String getDocNumber() {
        return this.DocNumber;
    }

    public void setDocNumber(String DocNumber) {
        this.DocNumber = DocNumber;
    }

    @Column(name = "DOCDATE", columnDefinition = "TIMESTAMP")
    //$NON-NLS-1$
    @DataItemName("Document.DocDate")
    public Date getDocDate() {
        return this.DocDate;
    }

    public void setDocDate(Date DocDate) {
        this.DocDate = DocDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOC_ID")
    public DocHead getDocument() {
        return this.Document;
    }

    public void setDocument(DocHead Document) {
        this.Document = Document;
    }
}

