package com.mg.merp.lbschedule.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocSpec;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Measure;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItemSpec generated by hbm2java
 */
@Entity
@Table(name="LS_ITEMSPEC"
)
public class ItemSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Item Item;
     private Catalog Catalog;
     private DocSpec DocSpec;
     private Measure Measure2;
     private SysClient SysClient;
     private Measure Measure1;
     private BigDecimal Price;
     private BigDecimal ClearPrice;
     private BigDecimal Summa;
     private BigDecimal ClearSumma;
     private BigDecimal Qty1;
     private BigDecimal Qty2;
     private Set<ItemSpecTax> LsItemSpecTaxes = new HashSet<ItemSpecTax>(0);
     private Set<ItemSpecAlt> LsItemSpecAlts = new HashSet<ItemSpecAlt>(0);

    public ItemSpec() {
    }

    public ItemSpec(Item Item, Catalog Catalog, DocSpec DocSpec, Measure Measure2, SysClient SysClient, Measure Measure1, BigDecimal Price, BigDecimal ClearPrice, BigDecimal Summa, BigDecimal ClearSumma, BigDecimal Qty1, BigDecimal Qty2, Set<ItemSpecTax> LsItemSpecTaxes, Set<ItemSpecAlt> LsItemSpecAlts) {
       this.Item = Item;
       this.Catalog = Catalog;
       this.DocSpec = DocSpec;
       this.Measure2 = Measure2;
       this.SysClient = SysClient;
       this.Measure1 = Measure1;
       this.Price = Price;
       this.ClearPrice = ClearPrice;
       this.Summa = Summa;
       this.ClearSumma = ClearSumma;
       this.Qty1 = Qty1;
       this.Qty2 = Qty2;
       this.LsItemSpecTaxes = LsItemSpecTaxes;
       this.LsItemSpecAlts = LsItemSpecAlts;
    }
   
     @SequenceGenerator(name="generator", sequenceName="LS_ITEMSPEC_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM_ID")
    public Item getItem() {
        return this.Item;
    }
    
    public void setItem(Item Item) {
        this.Item = Item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATALOG_ID")
    public Catalog getCatalog() {
        return this.Catalog;
    }
    
    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCSPEC_ID")
    public DocSpec getDocSpec() {
        return this.DocSpec;
    }
    
    public void setDocSpec(DocSpec DocSpec) {
        this.DocSpec = DocSpec;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MEASURE2_ID")
    public Measure getMeasure2() {
        return this.Measure2;
    }
    
    public void setMeasure2(Measure Measure2) {
        this.Measure2 = Measure2;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MEASURE1_ID")
    public Measure getMeasure1() {
        return this.Measure1;
    }
    
    public void setMeasure1(Measure Measure1) {
        this.Measure1 = Measure1;
    }

    
    @Column(name="PRICE", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getPrice() {
        return this.Price;
    }
    
    public void setPrice(BigDecimal Price) {
        this.Price = Price;
    }

    
    @Column(name="CLEARPRICE", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getClearPrice() {
        return this.ClearPrice;
    }
    
    public void setClearPrice(BigDecimal ClearPrice) {
        this.ClearPrice = ClearPrice;
    }

    
    @Column(name="SUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSumma() {
        return this.Summa;
    }
    
    public void setSumma(BigDecimal Summa) {
        this.Summa = Summa;
    }

    
    @Column(name="CLEARSUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getClearSumma() {
        return this.ClearSumma;
    }
    
    public void setClearSumma(BigDecimal ClearSumma) {
        this.ClearSumma = ClearSumma;
    }

    
    @Column(name="QTY1", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getQty1() {
        return this.Qty1;
    }
    
    public void setQty1(BigDecimal Qty1) {
        this.Qty1 = Qty1;
    }

    
    @Column(name="QTY2", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getQty2() {
        return this.Qty2;
    }
    
    public void setQty2(BigDecimal Qty2) {
        this.Qty2 = Qty2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ItemSpec")
    public Set<ItemSpecTax> getLsItemSpecTaxes() {
        return this.LsItemSpecTaxes;
    }
    
    public void setLsItemSpecTaxes(Set<ItemSpecTax> LsItemSpecTaxes) {
        this.LsItemSpecTaxes = LsItemSpecTaxes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ItemSpec")
    public Set<ItemSpecAlt> getLsItemSpecAlts() {
        return this.LsItemSpecAlts;
    }
    
    public void setLsItemSpecAlts(Set<ItemSpecAlt> LsItemSpecAlts) {
        this.LsItemSpecAlts = LsItemSpecAlts;
    }




}


