package com.mg.merp.warehouse.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSpec;
import com.mg.merp.document.model.DocumentSpecSerialNum;
import com.mg.merp.document.model.DocumentSpecTax;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Country;
import com.mg.merp.reference.model.CustomsDeclaration;
import com.mg.merp.reference.model.Measure;
import com.mg.merp.reference.model.PriceListSpec;
import com.mg.merp.reference.model.TaxGroup;
import com.mg.merp.reference.model.TimePeriodKind;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * BillSpec generated by hbm2java
 */
@Entity
@Table(name = "BILLSPEC")
public class BillSpec extends BaseStockDocumentSpec implements java.io.Serializable {

    private BigDecimal AcceptanceQuan;

    private BigDecimal AcceptanceSum;

    private BigDecimal AcceptancePackingQuan;

    public BillSpec() {
    }

    @Column(name = "ACCEPTANCEQUAN", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Warehouse.BillSpec.AcceptanceQuan")
    public BigDecimal getAcceptanceQuan() {
        return this.AcceptanceQuan;
    }

    public void setAcceptanceQuan(BigDecimal AcceptanceQuan) {
        this.AcceptanceQuan = AcceptanceQuan;
    }

    @Column(name = "ACCEPTANCESUM", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Warehouse.BillSpec.AcceptanceSum")
    public BigDecimal getAcceptanceSum() {
        return this.AcceptanceSum;
    }

    public void setAcceptanceSum(BigDecimal AcceptanceSum) {
        this.AcceptanceSum = AcceptanceSum;
    }

    @Column(name = "ACCEPTANCEPACKINGQUAN", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Warehouse.BillSpec.AcceptancePackingQuan")
    public BigDecimal getAcceptancePackingQuan() {
        return this.AcceptancePackingQuan;
    }

    public void setAcceptancePackingQuan(BigDecimal AcceptancePackingQuan) {
        this.AcceptancePackingQuan = AcceptancePackingQuan;
    }
}

