package com.mg.merp.warehouse.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSpec;
import com.mg.merp.document.model.DocumentSpecSerialNum;
import com.mg.merp.document.model.DocumentSpecTax;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Country;
import com.mg.merp.reference.model.CustomsDeclaration;
import com.mg.merp.reference.model.Measure;
import com.mg.merp.reference.model.PriceListSpec;
import com.mg.merp.reference.model.TaxGroup;
import com.mg.merp.reference.model.TimePeriodKind;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * OrderSpec generated by hbm2java
 */
@Entity
@Table(name = "ORDERSPEC")
public class OrderSpec extends BaseStockDocumentSpec implements java.io.Serializable {

    private Contractor Warehouse;

    private Date RequiredDate;

    private Date PromisedDate;

    private String VendorItemCode;

    private BigDecimal QtyAccepted;

    private BigDecimal QtyInvoiced;

    private BigDecimal QtyReturned;

    private BigDecimal QtyShipped;

    private BigDecimal QtyPicked;

    private BigDecimal QtyOutstanding;

    private boolean ClosedForPlanning;

    private OrderStatus Status;

    public OrderSpec() {
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WAREHOUSE_ID")
    public Contractor getWarehouse() {
        return this.Warehouse;
    }

    public void setWarehouse(Contractor Warehouse) {
        this.Warehouse = Warehouse;
    }

    @Column(name = "REQUIRED_DATE", columnDefinition = "TIMESTAMP")
    public Date getRequiredDate() {
        return this.RequiredDate;
    }

    public void setRequiredDate(Date RequiredDate) {
        this.RequiredDate = RequiredDate;
    }

    @Column(name = "PROMISED_DATE", columnDefinition = "TIMESTAMP")
    public Date getPromisedDate() {
        return this.PromisedDate;
    }

    public void setPromisedDate(Date PromisedDate) {
        this.PromisedDate = PromisedDate;
    }

    @Column(name = "VENDOR_ITEM_CODE", columnDefinition = "CHAR", length = 20)
    public String getVendorItemCode() {
        return this.VendorItemCode;
    }

    public void setVendorItemCode(String VendorItemCode) {
        this.VendorItemCode = VendorItemCode;
    }

    @Column(name = "QTY_ACCEPTED", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQtyAccepted() {
        return this.QtyAccepted;
    }

    public void setQtyAccepted(BigDecimal QtyAccepted) {
        this.QtyAccepted = QtyAccepted;
    }

    @Column(name = "QTY_INVOICED", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQtyInvoiced() {
        return this.QtyInvoiced;
    }

    public void setQtyInvoiced(BigDecimal QtyInvoiced) {
        this.QtyInvoiced = QtyInvoiced;
    }

    @Column(name = "QTY_RETURNED", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQtyReturned() {
        return this.QtyReturned;
    }

    public void setQtyReturned(BigDecimal QtyReturned) {
        this.QtyReturned = QtyReturned;
    }

    @Column(name = "QTY_SHIPPED", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQtyShipped() {
        return this.QtyShipped;
    }

    public void setQtyShipped(BigDecimal QtyShipped) {
        this.QtyShipped = QtyShipped;
    }

    @Column(name = "QTY_PICKED", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQtyPicked() {
        return this.QtyPicked;
    }

    public void setQtyPicked(BigDecimal QtyPicked) {
        this.QtyPicked = QtyPicked;
    }

    @Column(name = "QTY_OUTSTANDING", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQtyOutstanding() {
        return this.QtyOutstanding;
    }

    public void setQtyOutstanding(BigDecimal QtyOutstanding) {
        this.QtyOutstanding = QtyOutstanding;
    }

    @Column(name = "CLOSED_FOR_PLANNING", columnDefinition = "SMALLINT")
    public boolean isClosedForPlanning() {
        return this.ClosedForPlanning;
    }

    public void setClosedForPlanning(boolean ClosedForPlanning) {
        this.ClosedForPlanning = ClosedForPlanning;
    }

    @Column(name = "STATUS")
    @Enumerated(EnumType.ORDINAL)
    public OrderStatus getStatus() {
        return this.Status;
    }

    public void setStatus(OrderStatus Status) {
        this.Status = Status;
    }
}

