package com.mg.merp.warehouse.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.framework.support.orm.EnumUserType;
import com.mg.merp.core.model.Folder;
import com.mg.merp.core.model.SysClient;
import com.mg.merp.core.model.SysCompany;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSection;
import com.mg.merp.document.model.DocType;
import com.mg.merp.reference.model.CalcTaxesKind;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.CurrencyRateAuthority;
import com.mg.merp.reference.model.CurrencyRateType;
import com.mg.merp.reference.model.PriceListHead;
import com.mg.merp.reference.model.PriceType;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderHeadModel generated by hbm2java
 */
@Entity
@Table(name="ORDERHEADMODEL"
)
public class OrderHeadModel extends com.mg.merp.document.model.DocHeadModel implements java.io.Serializable {


     private Contractor Responsible;
     private Contractor Consumer;
     private BigDecimal SummaCurWithDiscount;
     private BigDecimal SummaNatWithDiscount;
     private BigDecimal AddExpenses;
     private BigDecimal DiscountOnDoc;
     private BigDecimal DiscountOnLine;
     private EnumUserType DueDateKind;
     private BigDecimal DueDateQuan;
     private Date DueDate;
     private Short CreditTerm;
     private BigDecimal Penalty;
     private String Comment;
     private boolean FixedInput;
     private EnumUserType Status;

    public OrderHeadModel() {
    }

	
    public OrderHeadModel(DocSection DocSection, boolean ManualDocNumber) {
        super(DocSection, ManualDocNumber);        
    }
    public OrderHeadModel(SysCompany SysCompany, Contractor Through, Folder ModelDestFolder, Contractor From, Contractor To, Contractor DstMol, CurrencyRateAuthority CurrencyRateAuthority, Contractor SrcMol, Folder Folder, SysClient SysClient, Contractor DstStock, CurrencyRateType CurrencyRateType, Contractor SrcStock, DocSection DocSection, String ModelName, DocType DocType, String DocNumber, Date DocDate, Currency Currency, BigDecimal CurCource, BigDecimal SumCur, BigDecimal SumNat, DocHead BaseDocument, DocType BaseDocType, String BaseDocNumber, Date BaseDocDate, DocHead Contract, DocType ContractType, String ContractNumber, Date ContractDate, BigDecimal Weight, BigDecimal Volume, PriceListHead PriceList, PriceType PriceType, CalcTaxesKind CalcTaxesKind, Folder DiscountFolder, boolean ManualDocNumber, String Description, Contractor Responsible, Contractor Consumer, BigDecimal SummaCurWithDiscount, BigDecimal SummaNatWithDiscount, BigDecimal AddExpenses, BigDecimal DiscountOnDoc, BigDecimal DiscountOnLine, EnumUserType DueDateKind, BigDecimal DueDateQuan, Date DueDate, Short CreditTerm, BigDecimal Penalty, String Comment, boolean FixedInput, EnumUserType Status) {
        super(SysCompany, Through, ModelDestFolder, From, To, DstMol, CurrencyRateAuthority, SrcMol, Folder, SysClient, DstStock, CurrencyRateType, SrcStock, DocSection, ModelName, DocType, DocNumber, DocDate, Currency, CurCource, SumCur, SumNat, BaseDocument, BaseDocType, BaseDocNumber, BaseDocDate, Contract, ContractType, ContractNumber, ContractDate, Weight, Volume, PriceList, PriceType, CalcTaxesKind, DiscountFolder, ManualDocNumber, Description);        
       this.Responsible = Responsible;
       this.Consumer = Consumer;
       this.SummaCurWithDiscount = SummaCurWithDiscount;
       this.SummaNatWithDiscount = SummaNatWithDiscount;
       this.AddExpenses = AddExpenses;
       this.DiscountOnDoc = DiscountOnDoc;
       this.DiscountOnLine = DiscountOnLine;
       this.DueDateKind = DueDateKind;
       this.DueDateQuan = DueDateQuan;
       this.DueDate = DueDate;
       this.CreditTerm = CreditTerm;
       this.Penalty = Penalty;
       this.Comment = Comment;
       this.FixedInput = FixedInput;
       this.Status = Status;
    }
   

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESPONSIBLE")
    public Contractor getResponsible() {
        return this.Responsible;
    }
    
    public void setResponsible(Contractor Responsible) {
        this.Responsible = Responsible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONSUMER")
    public Contractor getConsumer() {
        return this.Consumer;
    }
    
    public void setConsumer(Contractor Consumer) {
        this.Consumer = Consumer;
    }

    
    @Column(name="SUMMACUR_WITH_DISCOUNT", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSummaCurWithDiscount() {
        return this.SummaCurWithDiscount;
    }
    
    public void setSummaCurWithDiscount(BigDecimal SummaCurWithDiscount) {
        this.SummaCurWithDiscount = SummaCurWithDiscount;
    }

    
    @Column(name="SUMMANAT_WITH_DISCOUNT", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSummaNatWithDiscount() {
        return this.SummaNatWithDiscount;
    }
    
    public void setSummaNatWithDiscount(BigDecimal SummaNatWithDiscount) {
        this.SummaNatWithDiscount = SummaNatWithDiscount;
    }

    
    @Column(name="ADD_EXPENSES", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getAddExpenses() {
        return this.AddExpenses;
    }
    
    public void setAddExpenses(BigDecimal AddExpenses) {
        this.AddExpenses = AddExpenses;
    }

    
    @Column(name="DISCOUNT_ON_DOC", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getDiscountOnDoc() {
        return this.DiscountOnDoc;
    }
    
    public void setDiscountOnDoc(BigDecimal DiscountOnDoc) {
        this.DiscountOnDoc = DiscountOnDoc;
    }

    
    @Column(name="DISCOUNT_ON_LINE", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getDiscountOnLine() {
        return this.DiscountOnLine;
    }
    
    public void setDiscountOnLine(BigDecimal DiscountOnLine) {
        this.DiscountOnLine = DiscountOnLine;
    }

    
    @Column(name="DUEDATE_KIND", columnDefinition="SMALLINT")
    public EnumUserType getDueDateKind() {
        return this.DueDateKind;
    }
    
    public void setDueDateKind(EnumUserType DueDateKind) {
        this.DueDateKind = DueDateKind;
    }

    
    @Column(name="DUEDATE_QUAN", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getDueDateQuan() {
        return this.DueDateQuan;
    }
    
    public void setDueDateQuan(BigDecimal DueDateQuan) {
        this.DueDateQuan = DueDateQuan;
    }

    
    @Column(name="DUEDATE", columnDefinition="TIMESTAMP")
    public Date getDueDate() {
        return this.DueDate;
    }
    
    public void setDueDate(Date DueDate) {
        this.DueDate = DueDate;
    }

    
    @Column(name="CREDITTERM", columnDefinition="SMALLINT")
    public Short getCreditTerm() {
        return this.CreditTerm;
    }
    
    public void setCreditTerm(Short CreditTerm) {
        this.CreditTerm = CreditTerm;
    }

    
    @Column(name="PENALTY", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getPenalty() {
        return this.Penalty;
    }
    
    public void setPenalty(BigDecimal Penalty) {
        this.Penalty = Penalty;
    }

    
    @Column(name="COMMENT", columnDefinition="VARCHAR", length=1024)
    public String getComment() {
        return this.Comment;
    }
    
    public void setComment(String Comment) {
        this.Comment = Comment;
    }

    
    @Column(name="FIXED_INPUT", columnDefinition="SMALLINT")
    public boolean isFixedInput() {
        return this.FixedInput;
    }
    
    public void setFixedInput(boolean FixedInput) {
        this.FixedInput = FixedInput;
    }

    
    @Column(name="STATUS", columnDefinition="SMALLINT")
    public EnumUserType getStatus() {
        return this.Status;
    }
    
    public void setStatus(EnumUserType Status) {
        this.Status = Status;
    }




}


