package com.mg.merp.warehouse.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSpec;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;
import com.mg.framework.api.annotations.DataItemName;

/**
 * StockPlanHistory generated by hbm2java
 */
@Entity
@Table(name = "STOCKPLANHISTORY")
public class StockPlanHistory extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private StockCard StockCard;

    private DocSpec DocSpec;

    private DocHead DocHead;

    private SysClient SysClient;

    private StockPlanHistoryKind Kind;

    private StockPlanHistoryDirection Direction;

    private Date ProcessDate;

    private Date SysDateTime;

    private BigDecimal Quantity;

    private BigDecimal Quantity2;

    public StockPlanHistory() {
    }

    public StockPlanHistory(StockPlanHistoryKind Kind, StockPlanHistoryDirection Direction) {
        this.Kind = Kind;
        this.Direction = Direction;
    }

    public StockPlanHistory(StockCard StockCard, DocSpec DocSpec, DocHead DocHead, SysClient SysClient, StockPlanHistoryKind Kind, StockPlanHistoryDirection Direction, Date ProcessDate, Date SysDateTime, BigDecimal Quantity, BigDecimal Quantity2) {
        this.StockCard = StockCard;
        this.DocSpec = DocSpec;
        this.DocHead = DocHead;
        this.SysClient = SysClient;
        this.Kind = Kind;
        this.Direction = Direction;
        this.ProcessDate = ProcessDate;
        this.SysDateTime = SysDateTime;
        this.Quantity = Quantity;
        this.Quantity2 = Quantity2;
    }

    @SequenceGenerator(name = "generator", sequenceName = "STOCKPLANHISTORY_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STOCKCARD_ID")
    public StockCard getStockCard() {
        return this.StockCard;
    }

    public void setStockCard(StockCard StockCard) {
        this.StockCard = StockCard;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCSPEC_ID")
    public DocSpec getDocSpec() {
        return this.DocSpec;
    }

    public void setDocSpec(DocSpec DocSpec) {
        this.DocSpec = DocSpec;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCHEAD_ID")
    public DocHead getDocHead() {
        return this.DocHead;
    }

    public void setDocHead(DocHead DocHead) {
        this.DocHead = DocHead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "KIND", nullable = false)
    @Enumerated(EnumType.ORDINAL)
    public StockPlanHistoryKind getKind() {
        return this.Kind;
    }

    public void setKind(StockPlanHistoryKind Kind) {
        this.Kind = Kind;
    }

    @Column(name = "DIRECTION", nullable = false)
    @Enumerated(EnumType.ORDINAL)
    public StockPlanHistoryDirection getDirection() {
        return this.Direction;
    }

    public void setDirection(StockPlanHistoryDirection Direction) {
        this.Direction = Direction;
    }

    @Column(name = "PROCESSDATE", columnDefinition = "TIMESTAMP")
    public Date getProcessDate() {
        return this.ProcessDate;
    }

    public void setProcessDate(Date ProcessDate) {
        this.ProcessDate = ProcessDate;
    }

    @Column(name = "SYSDATETIME", columnDefinition = "TIMESTAMP")
    public Date getSysDateTime() {
        return this.SysDateTime;
    }

    public void setSysDateTime(Date SysDateTime) {
        this.SysDateTime = SysDateTime;
    }

    @Column(name = "QUANTITY", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    public BigDecimal getQuantity() {
        return this.Quantity;
    }

    public void setQuantity(BigDecimal Quantity) {
        this.Quantity = Quantity;
    }

    @Column(name = "QUANTITY2", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getQuantity2() {
        return this.Quantity2;
    }

    public void setQuantity2(BigDecimal Quantity2) {
        this.Quantity2 = Quantity2;
    }
}

