package com.mg.merp.warehouse.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Employees;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import com.mg.framework.api.annotations.DataItemName;

/**
 * StockCard generated by hbm2java
 */
@Entity
@Table(name = "STOCKCARD")
public class StockCard extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Date SysVersion;

    private Catalog Catalog;

    private Warehouse Stock;

    private SysClient SysClient;

    private Employees Mol;

    private String CardNumber;

    private BigDecimal SupplyNorm;

    private BigDecimal Reserve;

    private BigDecimal Quantity;

    private BigDecimal PlanIn;

    private BigDecimal PlanOut;

    private BigDecimal SupplyNorm2;

    private BigDecimal Reserve2;

    private BigDecimal Quantity2;

    private BigDecimal PlanIn2;

    private BigDecimal PlanOut2;

    public StockCard() {
    }

    public StockCard(Catalog Catalog, Warehouse Stock, SysClient SysClient, Employees Mol, String CardNumber, BigDecimal SupplyNorm, BigDecimal Reserve, BigDecimal Quantity, BigDecimal PlanIn, BigDecimal PlanOut, BigDecimal SupplyNorm2, BigDecimal Reserve2, BigDecimal Quantity2, BigDecimal PlanIn2, BigDecimal PlanOut2) {
        this.Catalog = Catalog;
        this.Stock = Stock;
        this.SysClient = SysClient;
        this.Mol = Mol;
        this.CardNumber = CardNumber;
        this.SupplyNorm = SupplyNorm;
        this.Reserve = Reserve;
        this.Quantity = Quantity;
        this.PlanIn = PlanIn;
        this.PlanOut = PlanOut;
        this.SupplyNorm2 = SupplyNorm2;
        this.Reserve2 = Reserve2;
        this.Quantity2 = Quantity2;
        this.PlanIn2 = PlanIn2;
        this.PlanOut2 = PlanOut2;
    }

    @SequenceGenerator(name = "generator", sequenceName = "STOCKCARD_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @Version
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SYS_VERSION", nullable = false)
    public Date getSysVersion() {
        return this.SysVersion;
    }

    public void setSysVersion(Date SysVersion) {
        this.SysVersion = SysVersion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATALOG_ID")
    @DataItemName("Warehouse.StockCard.Catalog")
    public Catalog getCatalog() {
        return this.Catalog;
    }

    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STOCK_ID")
    public Warehouse getStock() {
        return this.Stock;
    }

    public void setStock(Warehouse Stock) {
        this.Stock = Stock;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MOL_ID")
    @DataItemName("Warehouse.StockCard.Mol")
    public Employees getMol() {
        return this.Mol;
    }

    public void setMol(Employees Mol) {
        this.Mol = Mol;
    }

    @Column(name = "CARDNUMBER", columnDefinition = "CHAR", length = 20)
    @DataItemName("Warehouse.StockCard.CardNumber")
    public String getCardNumber() {
        return this.CardNumber;
    }

    public void setCardNumber(String CardNumber) {
        this.CardNumber = CardNumber;
    }

    @Column(name = "SUPPLYNORM", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Warehouse.StockCard.SupplyNorm")
    public BigDecimal getSupplyNorm() {
        return this.SupplyNorm;
    }

    public void setSupplyNorm(BigDecimal SupplyNorm) {
        this.SupplyNorm = SupplyNorm;
    }

    @Column(name = "RESERVE", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Warehouse.StockCard.Reserve")
    public BigDecimal getReserve() {
        return this.Reserve;
    }

    public void setReserve(BigDecimal Reserve) {
        this.Reserve = Reserve;
    }

    @Column(name = "QUANTITY", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("Warehouse.StockCard.Quantity")
    public BigDecimal getQuantity() {
        return this.Quantity;
    }

    public void setQuantity(BigDecimal Quantity) {
        this.Quantity = Quantity;
    }

    @Column(name = "PLAN_IN", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Warehouse.StockCard.PlanIn")
    public BigDecimal getPlanIn() {
        return this.PlanIn;
    }

    public void setPlanIn(BigDecimal PlanIn) {
        this.PlanIn = PlanIn;
    }

    @Column(name = "PLAN_OUT", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Warehouse.StockCard.PlanOut")
    public BigDecimal getPlanOut() {
        return this.PlanOut;
    }

    public void setPlanOut(BigDecimal PlanOut) {
        this.PlanOut = PlanOut;
    }

    @Column(name = "SUPPLYNORM2", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getSupplyNorm2() {
        return this.SupplyNorm2;
    }

    public void setSupplyNorm2(BigDecimal SupplyNorm2) {
        this.SupplyNorm2 = SupplyNorm2;
    }

    @Column(name = "RESERVE2", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Warehouse.StockCard.Reserve2")
    public BigDecimal getReserve2() {
        return this.Reserve2;
    }

    public void setReserve2(BigDecimal Reserve2) {
        this.Reserve2 = Reserve2;
    }

    @Column(name = "QUANTITY2", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("Warehouse.StockCard.Quantity2")
    public BigDecimal getQuantity2() {
        return this.Quantity2;
    }

    public void setQuantity2(BigDecimal Quantity2) {
        this.Quantity2 = Quantity2;
    }

    @Column(name = "PLAN_IN2", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Warehouse.StockCard.PlanIn2")
    public BigDecimal getPlanIn2() {
        return this.PlanIn2;
    }

    public void setPlanIn2(BigDecimal PlanIn2) {
        this.PlanIn2 = PlanIn2;
    }

    @Column(name = "PLAN_OUT2", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("Warehouse.StockCard.PlanOut2")
    public BigDecimal getPlanOut2() {
        return this.PlanOut2;
    }

    public void setPlanOut2(BigDecimal PlanOut2) {
        this.PlanOut2 = PlanOut2;
    }
}

