package com.mg.merp.warehouse.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.Folder;
import com.mg.merp.core.model.SysClient;
import com.mg.merp.core.model.SysCompany;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSection;
import com.mg.merp.document.model.DocType;
import com.mg.merp.reference.model.CalcTaxesKind;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.CurrencyRateAuthority;
import com.mg.merp.reference.model.CurrencyRateType;
import com.mg.merp.reference.model.PriceListHead;
import com.mg.merp.reference.model.PriceType;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StockDocumentHeadModel generated by hbm2java
 */
@Entity
@Table(name="STOCKDOCUMENTHEADMODEL"
)
public class StockDocumentHeadModel extends com.mg.merp.document.model.DocHeadModel implements java.io.Serializable {


     private BigDecimal SummaCurWithDiscount;
     private BigDecimal SummaNatWithDiscount;
     private BigDecimal AddExpenses;
     private BigDecimal DiscountOnDoc;
     private BigDecimal DiscountOnLine;

    public StockDocumentHeadModel() {
    }

	
    public StockDocumentHeadModel(DocSection DocSection, boolean ManualDocNumber) {
        super(DocSection, ManualDocNumber);        
    }
    public StockDocumentHeadModel(SysCompany SysCompany, Contractor Through, Folder ModelDestFolder, Contractor From, Contractor To, Contractor DstMol, CurrencyRateAuthority CurrencyRateAuthority, Contractor SrcMol, Folder Folder, SysClient SysClient, Contractor DstStock, CurrencyRateType CurrencyRateType, Contractor SrcStock, DocSection DocSection, String ModelName, DocType DocType, String DocNumber, Date DocDate, Currency Currency, BigDecimal CurCource, BigDecimal SumCur, BigDecimal SumNat, DocHead BaseDocument, DocType BaseDocType, String BaseDocNumber, Date BaseDocDate, DocHead Contract, DocType ContractType, String ContractNumber, Date ContractDate, BigDecimal Weight, BigDecimal Volume, PriceListHead PriceList, PriceType PriceType, CalcTaxesKind CalcTaxesKind, Folder DiscountFolder, boolean ManualDocNumber, String Description, BigDecimal SummaCurWithDiscount, BigDecimal SummaNatWithDiscount, BigDecimal AddExpenses, BigDecimal DiscountOnDoc, BigDecimal DiscountOnLine) {
        super(SysCompany, Through, ModelDestFolder, From, To, DstMol, CurrencyRateAuthority, SrcMol, Folder, SysClient, DstStock, CurrencyRateType, SrcStock, DocSection, ModelName, DocType, DocNumber, DocDate, Currency, CurCource, SumCur, SumNat, BaseDocument, BaseDocType, BaseDocNumber, BaseDocDate, Contract, ContractType, ContractNumber, ContractDate, Weight, Volume, PriceList, PriceType, CalcTaxesKind, DiscountFolder, ManualDocNumber, Description);        
       this.SummaCurWithDiscount = SummaCurWithDiscount;
       this.SummaNatWithDiscount = SummaNatWithDiscount;
       this.AddExpenses = AddExpenses;
       this.DiscountOnDoc = DiscountOnDoc;
       this.DiscountOnLine = DiscountOnLine;
    }
   

    
    @Column(name="SUMMACUR_WITH_DISCOUNT", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSummaCurWithDiscount() {
        return this.SummaCurWithDiscount;
    }
    
    public void setSummaCurWithDiscount(BigDecimal SummaCurWithDiscount) {
        this.SummaCurWithDiscount = SummaCurWithDiscount;
    }

    
    @Column(name="SUMMANAT_WITH_DISCOUNT", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSummaNatWithDiscount() {
        return this.SummaNatWithDiscount;
    }
    
    public void setSummaNatWithDiscount(BigDecimal SummaNatWithDiscount) {
        this.SummaNatWithDiscount = SummaNatWithDiscount;
    }

    
    @Column(name="ADD_EXPENSES", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getAddExpenses() {
        return this.AddExpenses;
    }
    
    public void setAddExpenses(BigDecimal AddExpenses) {
        this.AddExpenses = AddExpenses;
    }

    
    @Column(name="DISCOUNT_ON_DOC", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getDiscountOnDoc() {
        return this.DiscountOnDoc;
    }
    
    public void setDiscountOnDoc(BigDecimal DiscountOnDoc) {
        this.DiscountOnDoc = DiscountOnDoc;
    }

    
    @Column(name="DISCOUNT_ON_LINE", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getDiscountOnLine() {
        return this.DiscountOnLine;
    }
    
    public void setDiscountOnLine(BigDecimal DiscountOnLine) {
        this.DiscountOnLine = DiscountOnLine;
    }




}


