package com.mg.merp.warehouse.model;

import com.mg.merp.baiengine.model.Repository;
import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.OrgUnitType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;
import com.mg.framework.api.annotations.DataItemName;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "WH_WAREHOUSE")
//$NON-NLS-1$
@DataItemName("Warehouse.Warehouse")
public class Warehouse extends com.mg.merp.reference.model.OrgUnit implements java.io.Serializable {

    private Repository BatchPriceBAi;

    private StockPolicy StockPolicy;

    private WarehouseType WarehouseType;

    private boolean CalcFact;

    private boolean CalcFactSign;

    private boolean CalcPlanIn;

    private boolean CalcPlanInSign;

    private boolean CalcPlanOut;

    private boolean CalcPlanOutSign;

    private boolean CalcReserve;

    private boolean CalcReserveSign;

    private boolean UseBinLocation;

    private boolean BinSizing;

    private boolean CheckTransactionDay;

    private boolean WarehouseTransactionClosed;

    private Date ClosedDateTill;

    private String UserStockClosed;

    private Date OperationDate;

    private Repository DisposalStrategy;

    public Warehouse() {
    }

    public Warehouse(String Code, String UpCode, String FullName, short Kind) {
        super(Code, UpCode, FullName, Kind);
    }

    public Warehouse(SysClient SysClient, String Code, String UpCode, String FullName, Integer FolderId, short Kind, Contractor Partner, OrgUnitType OrgUnitKind, Boolean IsOffice, Boolean IsStore, String FolderTag, Repository BatchPriceBAi, StockPolicy StockPolicy, WarehouseType WarehouseType, boolean CalcFact, boolean CalcFactSign, boolean CalcPlanIn, boolean CalcPlanInSign, boolean CalcPlanOut, boolean CalcPlanOutSign, boolean CalcReserve, boolean CalcReserveSign, boolean UseBinLocation, boolean BinSizing, boolean CheckTransactionDay, boolean WarehouseTransactionClosed, Date ClosedDateTill, String UserStockClosed, Date OperationDate, Repository DisposalStrategy) {
        super(SysClient, Code, UpCode, FullName, FolderId, Kind, Partner, OrgUnitKind, IsOffice, IsStore, FolderTag);
        this.BatchPriceBAi = BatchPriceBAi;
        this.StockPolicy = StockPolicy;
        this.WarehouseType = WarehouseType;
        this.CalcFact = CalcFact;
        this.CalcFactSign = CalcFactSign;
        this.CalcPlanIn = CalcPlanIn;
        this.CalcPlanInSign = CalcPlanInSign;
        this.CalcPlanOut = CalcPlanOut;
        this.CalcPlanOutSign = CalcPlanOutSign;
        this.CalcReserve = CalcReserve;
        this.CalcReserveSign = CalcReserveSign;
        this.UseBinLocation = UseBinLocation;
        this.BinSizing = BinSizing;
        this.CheckTransactionDay = CheckTransactionDay;
        this.WarehouseTransactionClosed = WarehouseTransactionClosed;
        this.ClosedDateTill = ClosedDateTill;
        this.UserStockClosed = UserStockClosed;
        this.OperationDate = OperationDate;
        this.DisposalStrategy = DisposalStrategy;
    }

    @Override
    //$NON-NLS-1$
    @DataItemName("ID")
    public int getId() {
        return super.getId();
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ALGORITHM_ID")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.AlgRepository")
    public Repository getBatchPriceBAi() {
        return this.BatchPriceBAi;
    }

    public void setBatchPriceBAi(Repository BatchPriceBAi) {
        this.BatchPriceBAi = BatchPriceBAi;
    }

    @Column(name = "STOCKPOLICY")
    @Enumerated(EnumType.ORDINAL)
    public StockPolicy getStockPolicy() {
        return this.StockPolicy;
    }

    public void setStockPolicy(StockPolicy StockPolicy) {
        this.StockPolicy = StockPolicy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WAREHOUSE_TYPE_ID")
    public WarehouseType getWarehouseType() {
        return this.WarehouseType;
    }

    public void setWarehouseType(WarehouseType WarehouseType) {
        this.WarehouseType = WarehouseType;
    }

    @Column(name = "CALC_FACT", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcFact")
    public boolean isCalcFact() {
        return this.CalcFact;
    }

    public void setCalcFact(boolean CalcFact) {
        this.CalcFact = CalcFact;
    }

    @Column(name = "CALC_FACT_SIGN", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcFactSign")
    public boolean isCalcFactSign() {
        return this.CalcFactSign;
    }

    public void setCalcFactSign(boolean CalcFactSign) {
        this.CalcFactSign = CalcFactSign;
    }

    @Column(name = "CALC_PLAN_IN", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcPlanIn")
    public boolean isCalcPlanIn() {
        return this.CalcPlanIn;
    }

    public void setCalcPlanIn(boolean CalcPlanIn) {
        this.CalcPlanIn = CalcPlanIn;
    }

    @Column(name = "CALC_PLAN_IN_SIGN", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcPlanInSign")
    public boolean isCalcPlanInSign() {
        return this.CalcPlanInSign;
    }

    public void setCalcPlanInSign(boolean CalcPlanInSign) {
        this.CalcPlanInSign = CalcPlanInSign;
    }

    @Column(name = "CALC_PLAN_OUT", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcPlanOut")
    public boolean isCalcPlanOut() {
        return this.CalcPlanOut;
    }

    public void setCalcPlanOut(boolean CalcPlanOut) {
        this.CalcPlanOut = CalcPlanOut;
    }

    @Column(name = "CALC_PLAN_OUT_SIGN", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcPlanOutSign")
    public boolean isCalcPlanOutSign() {
        return this.CalcPlanOutSign;
    }

    public void setCalcPlanOutSign(boolean CalcPlanOutSign) {
        this.CalcPlanOutSign = CalcPlanOutSign;
    }

    @Column(name = "CALC_RESERVE", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcReserve")
    public boolean isCalcReserve() {
        return this.CalcReserve;
    }

    public void setCalcReserve(boolean CalcReserve) {
        this.CalcReserve = CalcReserve;
    }

    @Column(name = "CALC_RESERVE_SIGN", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.CalcReserveSign")
    public boolean isCalcReserveSign() {
        return this.CalcReserveSign;
    }

    public void setCalcReserveSign(boolean CalcReserveSign) {
        this.CalcReserveSign = CalcReserveSign;
    }

    @Column(name = "USE_BIN_LOCATION", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.UseBinLocat")
    public boolean isUseBinLocation() {
        return this.UseBinLocation;
    }

    public void setUseBinLocation(boolean UseBinLocation) {
        this.UseBinLocation = UseBinLocation;
    }

    @Column(name = "BIN_SIZING", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.Warehouse.BinSizing")
    public boolean isBinSizing() {
        return this.BinSizing;
    }

    public void setBinSizing(boolean BinSizing) {
        this.BinSizing = BinSizing;
    }

    @Column(name = "CHECK_TRANSACTION_DAY", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.CheckTransactionDay")
    public boolean isCheckTransactionDay() {
        return this.CheckTransactionDay;
    }

    public void setCheckTransactionDay(boolean CheckTransactionDay) {
        this.CheckTransactionDay = CheckTransactionDay;
    }

    @Column(name = "WAREHOUSE_TRANSACTION_CLOSED", columnDefinition = "SMALLINT")
    //$NON-NLS-1$
    @DataItemName("Warehouse.WarehouseTransactionClosed")
    public boolean isWarehouseTransactionClosed() {
        return this.WarehouseTransactionClosed;
    }

    public void setWarehouseTransactionClosed(boolean WarehouseTransactionClosed) {
        this.WarehouseTransactionClosed = WarehouseTransactionClosed;
    }

    @Column(name = "CLOSED_DATE_TILL", columnDefinition = "TIMESTAMP")
    //$NON-NLS-1$
    @DataItemName("Warehouse.ClosedDateTill")
    public Date getClosedDateTill() {
        return this.ClosedDateTill;
    }

    public void setClosedDateTill(Date ClosedDateTill) {
        this.ClosedDateTill = ClosedDateTill;
    }

    @Column(name = "USER_STOCK_CLOSED", unique = true, columnDefinition = "CHAR", length = 31)
    //$NON-NLS-1$
    @DataItemName("Warehouse.UserStockClosed")
    public String getUserStockClosed() {
        return this.UserStockClosed;
    }

    public void setUserStockClosed(String UserStockClosed) {
        this.UserStockClosed = UserStockClosed;
    }

    @Column(name = "OPERATION_DATE", columnDefinition = "TIMESTAMP")
    //$NON-NLS-1$
    @DataItemName("Warehouse.OperationDate")
    public Date getOperationDate() {
        return this.OperationDate;
    }

    public void setOperationDate(Date OperationDate) {
        this.OperationDate = OperationDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DISPOSAL_STRAT_ID")
    public Repository getDisposalStrategy() {
        return this.DisposalStrategy;
    }

    public void setDisposalStrategy(Repository DisposalStrategy) {
        this.DisposalStrategy = DisposalStrategy;
    }
}

