DECLARE EXTERNAL FUNCTION ABS
    DOUBLE PRECISION
    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'IBAbs' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION ANLTOSTR
    CSTRING(11),
    CSTRING(11),
    CSTRING(11),
    CSTRING(11),
    CSTRING(11)
    RETURNS CSTRING(51) FREE_IT
    ENTRY_POINT 'AnaliticaToString' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION COMPARE
    DOUBLE PRECISION,
    DOUBLE PRECISION,
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'CompareFloat' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION CREATEUID
    CSTRING(36)
    RETURNS PARAMETER 1
    ENTRY_POINT 'CreateUID' MODULE_NAME 'mcommon_udf';


DECLARE EXTERNAL FUNCTION DATETOSTR
    TIMESTAMP
    RETURNS CSTRING(11) FREE_IT
    ENTRY_POINT 'IBDateToStr' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION DAYSPERMONTH
    INTEGER,
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'DaysPerMonth' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION DB

    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'DB' MODULE_NAME 'ITD';


DECLARE EXTERNAL FUNCTION DE

    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'DE' MODULE_NAME 'ITD';


DECLARE EXTERNAL FUNCTION DELSPACE
    CSTRING(200)
    RETURNS CSTRING(200) FREE_IT
    ENTRY_POINT 'DeleteSpace' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION DIV
    INTEGER,
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'IBDiv' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION DM
    CSTRING(128)
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'DM' MODULE_NAME 'ITD';


DECLARE EXTERNAL FUNCTION DNVL
    DOUBLE PRECISION,
    DOUBLE PRECISION
    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'DNvl' MODULE_NAME 'mcommon_udf';


DECLARE EXTERNAL FUNCTION ESFEATURESTOSTR
    CSTRING(11),
    CSTRING(11),
    CSTRING(11),
    CSTRING(11),
    CSTRING(11)
    RETURNS CSTRING(51) FREE_IT
    ENTRY_POINT 'EconomicSpecFeaturesToString' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION EXTRACTWORD
    INTEGER,
    CSTRING(255)
    RETURNS CSTRING(255) FREE_IT
    ENTRY_POINT 'IBExtractWord' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION EXTRACTWORDEX
    INTEGER,
    CSTRING(255),
    CSTRING(5)
    RETURNS CSTRING(255) FREE_IT
    ENTRY_POINT 'IBExtractWordEx' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION FINANLTOSTR
    CSTRING(21),
    CSTRING(21),
    CSTRING(21),
    CSTRING(21),
    CSTRING(21)
    RETURNS CSTRING(101) FREE_IT
    ENTRY_POINT 'FinAnalyticToString' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION FORMATDATETIME
    TIMESTAMP,
    CSTRING(40)
    RETURNS CSTRING(40) FREE_IT
    ENTRY_POINT 'IBFormatDateTime' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION FORMATNUM
    DOUBLE PRECISION,
    CSTRING(40)
    RETURNS CSTRING(40) FREE_IT
    ENTRY_POINT 'FormatNumber' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION FORMATNUMEX
    DOUBLE PRECISION,
    CSTRING(40),
    CSTRING(40)
    RETURNS PARAMETER 3
    ENTRY_POINT 'FormatNumberEx' MODULE_NAME 'mcommon_udf';


DECLARE EXTERNAL FUNCTION IIF
    NUMERIC(18,4),
    CSTRING(3),
    NUMERIC(18,4),
    NUMERIC(18,4),
    NUMERIC(18,4)
    RETURNS NUMERIC(18,4) BY VALUE
    ENTRY_POINT 'iif' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION ISEQUALZERO
    DOUBLE PRECISION,
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'CompareFloatWithZero' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION MONEY2STR
    DOUBLE PRECISION,
    INTEGER,
    INTEGER,
    INTEGER
    RETURNS CSTRING(255) FREE_IT
    ENTRY_POINT 'MoneyToString' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION NUMBER2STR
    DOUBLE PRECISION,
    SMALLINT
    RETURNS CSTRING(256) FREE_IT
    ENTRY_POINT 'NumberToString' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RAISECONTRACTOR
    CSTRING(21),
    CSTRING(21),
    CSTRING(21)
    RETURNS CSTRING(21) FREE_IT
    ENTRY_POINT 'RaiseContractor' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RAISECONTRACTORNAME
    CSTRING(81),
    CSTRING(81),
    CSTRING(81)
    RETURNS CSTRING(81) FREE_IT
    ENTRY_POINT 'RaiseContractor' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RAISEDOCUMENTCAPTION
    CSTRING(16),
    CSTRING(21),
    TIMESTAMP
    RETURNS CSTRING(300) FREE_IT
    ENTRY_POINT 'RaiseDocumentCaption' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RAISEECONOPERCAPTION
    TIMESTAMP,
    CSTRING(257)
    RETURNS CSTRING(300) FREE_IT
    ENTRY_POINT 'RaiseEconOperCaption' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RAISESPECNAME
    CSTRING(81),
    CSTRING(81)
    RETURNS CSTRING(81) FREE_IT
    ENTRY_POINT 'RaiseSpecificationName' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RAND

    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'IB_UDF_rand' MODULE_NAME 'ib_udf';


DECLARE EXTERNAL FUNCTION RIGHTSTR
    CSTRING(256),
    INTEGER
    RETURNS CSTRING(256) FREE_IT
    ENTRY_POINT 'IBRightStr' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION ROUND
    DOUBLE PRECISION,
    SMALLINT
    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'RoundPrec' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION ROUND3
    NUMERIC(18,3)
    RETURNS NUMERIC(18,3) BY VALUE
    ENTRY_POINT 'RoundNum3' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION ROUND4
    NUMERIC(18,4)
    RETURNS NUMERIC(18,4) BY VALUE
    ENTRY_POINT 'RoundNum4' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION RTRIM
    CSTRING(256)
    RETURNS CSTRING(256) FREE_IT
    ENTRY_POINT 'TrimR' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION SAVE_LOG
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'SaveLog' MODULE_NAME 'SPC.DLL';


DECLARE EXTERNAL FUNCTION SETSOFTWAREPRECESION
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'SetSoftwarePrecesion' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION STR2DOUBLE
    CSTRING(40),
    CSTRING(5)
    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'IBStrToNumber' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION STRCOPY
    CSTRING(8192),
    INTEGER,
    INTEGER
    RETURNS CSTRING(256) FREE_IT
    ENTRY_POINT 'IBCopy' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION STRLEFT
    CSTRING(8192),
    INTEGER
    RETURNS CSTRING(256) FREE_IT
    ENTRY_POINT 'Left' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION STRLEN
    CSTRING(32767)
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'IB_UDF_strlen' MODULE_NAME 'ib_udf';


DECLARE EXTERNAL FUNCTION TYPEISMEMBER
    INTEGER,
    INTEGER,
    SMALLINT
    RETURNS SMALLINT BY VALUE
    ENTRY_POINT 'BitIsSet' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION WD
    CSTRING(128),
    TIMESTAMP
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'WD' MODULE_NAME 'ITD';


DECLARE EXTERNAL FUNCTION WF
    CSTRING(128),
    INTEGER,
    INTEGER,
    DOUBLE PRECISION
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'WF' MODULE_NAME 'ITD';


DECLARE EXTERNAL FUNCTION WI
    CSTRING(128),
    INTEGER
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'WI' MODULE_NAME 'ITD';


DECLARE EXTERNAL FUNCTION WORDCOUNT
    CSTRING(255)
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'IBWordCount' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION WORDCOUNTEX
    CSTRING(255),
    CSTRING(5)
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'IBWordCountEx' MODULE_NAME 'Millennium.dll';


DECLARE EXTERNAL FUNCTION WS
    CSTRING(128),
    CSTRING(128)
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'WS' MODULE_NAME 'ITD';




CREATE DOMAIN D_ABBREVIATION AS
CHAR(11);

CREATE DOMAIN D_ACCOUNT AS
VARCHAR(30);

CREATE DOMAIN D_ADDRESS AS
VARCHAR(256);

CREATE DOMAIN D_ADDR_BUILDING AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_HOUSE AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_PREFIX AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_ROOM AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_STREET AS
VARCHAR(128);

CREATE DOMAIN D_ALGORITHM AS
BLOB SUB_TYPE 1 SEGMENT SIZE 80;

CREATE DOMAIN D_ANLCODE AS
CHAR(15);

CREATE DOMAIN D_AUDIT_EVENT AS
SMALLINT;

CREATE DOMAIN D_BEAN_NAME AS
VARCHAR(128);

CREATE DOMAIN D_BIGCODE AS
CHAR(20);

CREATE DOMAIN D_BIGNAME AS
VARCHAR(256);

CREATE DOMAIN D_BIG_INT_IDEN AS
NUMERIC(18,0);

CREATE DOMAIN D_BOOLEAN AS
SMALLINT
default 0
CHECK (VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_CALCTAXESSUBJECT AS
SMALLINT
check(value between 1 and 2);

CREATE DOMAIN D_CATALOG_GROUPS_TYPE AS
SMALLINT;

CREATE DOMAIN D_COMMENT AS
VARCHAR(256);

CREATE DOMAIN D_CONST_VAL AS
VARCHAR(80);

CREATE DOMAIN D_CONTARCT_CALC_SUM_KIND AS
SMALLINT;

CREATE DOMAIN D_CONTPHASE_CALC_SUM_KIND AS
SMALLINT;

CREATE DOMAIN D_CONTRACTORCARD_HIST_KIND AS
SMALLINT
DEFAULT 0
CHECK(VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_CONTRACTORCARD_PLAN_KIND AS
SMALLINT
DEFAULT 0
CHECK(VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_CONTRACTOR_KIND AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK (value between 0 and 2);

CREATE DOMAIN D_CONTRACTSTATUS AS
SMALLINT;

CREATE DOMAIN D_CONTRACT_COMMENT AS
VARCHAR(2048);

CREATE DOMAIN D_CRM_INFO AS
VARCHAR(2048);

CREATE DOMAIN D_CRM_SWOT AS
VARCHAR(1024);

CREATE DOMAIN D_CURCOURCE AS
NUMERIC(15,5);

CREATE DOMAIN D_CUSTOMALGORITHM AS
VARCHAR(8196);

CREATE DOMAIN D_DATE AS
TIMESTAMP;

CREATE DOMAIN D_DATENOTNULL AS
TIMESTAMP
NOT NULL;

CREATE DOMAIN D_DATETIME AS
TIMESTAMP;

CREATE DOMAIN D_DESCRIPTION AS
VARCHAR(1024);

CREATE DOMAIN D_DISABLE_EXCEED_QUANT AS
SMALLINT
default 0
NOT NULL
check (value between 0 and 2);

CREATE DOMAIN D_DOCDATE AS
TIMESTAMP
DEFAULT 'today';

CREATE DOMAIN D_DOCKIND AS
SMALLINT;

CREATE DOMAIN D_DOCNUMBER AS
CHAR(20);

CREATE DOMAIN D_DOCSECTION AS
SMALLINT;

CREATE DOMAIN D_DOCTYPE AS
CHAR(15);

CREATE DOMAIN D_ECONSPEC_FEATURE_CODE AS
CHAR(10);

CREATE DOMAIN D_EMAIL AS
VARCHAR(50);

CREATE DOMAIN D_EXCH_EXPORT_STATUS AS
SMALLINT
default 0
check (value between 0 and 4);

CREATE DOMAIN D_EXP_DATE_CALC_KIND AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK (value between 0 and 2);

CREATE DOMAIN D_FEATURE AS
VARCHAR(80);

CREATE DOMAIN D_FEATURE_INT AS
INTEGER;

CREATE DOMAIN D_FEATURE_STR AS
VARCHAR(2048);

CREATE DOMAIN D_FILENAME AS
VARCHAR(256);

CREATE DOMAIN D_FINANL_KIND AS
SMALLINT;

CREATE DOMAIN D_FINCENTER_KIND AS
SMALLINT;

CREATE DOMAIN D_FORMAT AS
VARCHAR(80);

CREATE DOMAIN D_FORMULA AS
VARCHAR(2048);

CREATE DOMAIN D_HOUR AS
NUMERIC(18,6)
DEFAULT 0;

CREATE DOMAIN D_INT AS
INTEGER;

CREATE DOMAIN D_INT_IDEN AS
INTEGER
NOT NULL;

CREATE DOMAIN D_MASS AS
NUMERIC(15,3);

CREATE DOMAIN D_MEASURE_CONTROL AS
SMALLINT;

CREATE DOMAIN D_MEASURE_CONVERSION AS
VARCHAR(512);

CREATE DOMAIN D_MEDIUMCODE AS
CHAR(10);

CREATE DOMAIN D_MF_BOM_STATUS AS
SMALLINT;

CREATE DOMAIN D_MF_BOM_TYPE AS
SMALLINT;

CREATE DOMAIN D_MF_CAPACITY AS
NUMERIC(18,0)
DEFAULT 0;

CREATE DOMAIN D_MF_JOB_STATUS AS
SMALLINT;

CREATE DOMAIN D_MF_LBR_OH_ALLOC_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_LBR_TIME_RATE_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MCH_OH_ALLOCATION_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MCH_RECOVERY_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MTL_OH_ACCLOC_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MTL_QUAN_RATE_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_RESOURCE_TYPE AS
SMALLINT;

CREATE DOMAIN D_MF_SCHEDULE_DIR AS
SMALLINT;

CREATE DOMAIN D_MF_TICK AS
NUMERIC(18,0);

CREATE DOMAIN D_MONTH AS
SMALLINT
default 1
CHECK (VALUE BETWEEN 1 AND 12);

CREATE DOMAIN D_NAME AS
VARCHAR(80)
NOT NULL;

CREATE DOMAIN D_NAME_N AS
VARCHAR(80);

CREATE DOMAIN D_ORDER_STATUS AS
SMALLINT;

CREATE DOMAIN D_ORIGINAL AS
BLOB SUB_TYPE 0 SEGMENT SIZE 80;

CREATE DOMAIN D_PASSWORD AS
VARCHAR(80);

CREATE DOMAIN D_PHASEITEMKIND AS
SMALLINT;

CREATE DOMAIN D_PHONE AS
VARCHAR(80);

CREATE DOMAIN D_PHONELIST AS
VARCHAR(40);

CREATE DOMAIN D_PROCESSMGR_STATE AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_QUANTITY AS
NUMERIC(18,3);

CREATE DOMAIN D_QUANTITY_EXT AS
NUMERIC(18,6);

CREATE DOMAIN D_QUERY AS
VARCHAR(8192);

CREATE DOMAIN D_RATIO AS
NUMERIC(18,6);

CREATE DOMAIN D_SERIAL_NUMBER AS
VARCHAR(50);

CREATE DOMAIN D_SHORT AS
SMALLINT;

CREATE DOMAIN D_SIZE AS
VARCHAR(15);

CREATE DOMAIN D_SMALLCODE AS
CHAR(5);

CREATE DOMAIN D_SMALLNAME AS
VARCHAR(40)
NOT NULL;

CREATE DOMAIN D_STOCKBATCHHISTORY_KIND AS
SMALLINT
NOT NULL
CHECK (VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_STOCKPOLICY AS
SMALLINT
default 0
check (value between 0 and 2);

CREATE DOMAIN D_STORED_PROC_NAME AS
CHAR(31);

CREATE DOMAIN D_SUMMA AS
NUMERIC(15,4)
default 0;

CREATE DOMAIN D_SUMMA_EXT AS
NUMERIC(18,6);

CREATE DOMAIN D_SYSPART_NODE AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK(VALUE BETWEEN 0 AND 3);

CREATE DOMAIN D_TABLE_NAME AS
CHAR(31);

CREATE DOMAIN D_TIME_PERIOD_KIND AS
SMALLINT
DEFAULT 0
CHECK (VALUE BETWEEN 0 AND 4);

CREATE DOMAIN D_USERNAME AS
CHAR(31);

CREATE DOMAIN D_VOLUME AS
NUMERIC(15,3);

CREATE DOMAIN D_WEIGHT AS
NUMERIC(15,3);

CREATE DOMAIN D_WF_EVENT AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_WF_HOW_CLOSED AS
SMALLINT;

CREATE DOMAIN D_WF_PRIORITY AS
SMALLINT
NOT NULL
CHECK (value between 1 and 5);

CREATE DOMAIN D_WF_PROCESS_RESULT AS
VARCHAR(1024)
NOT NULL;

CREATE DOMAIN D_WF_REQUESTER_KIND AS
SMALLINT;

CREATE DOMAIN D_WF_RESOURCE_KIND AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_WF_STATE_STR AS
VARCHAR(100);

CREATE DOMAIN D_WF_TIME AS
TIMESTAMP;

CREATE DOMAIN D_WF_WHILE_OPEN AS
SMALLINT;

CREATE DOMAIN D_WF_WHY_NOT_RUNNING AS
SMALLINT;

CREATE DOMAIN D_WF_WHY_SUSPENDED AS
SMALLINT;

CREATE DOMAIN D_WORKFLOW_STATE AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_ZIPCODE AS
VARCHAR(20);

CREATE DOMAIN D_RPT_ENUMVALUES AS 
VARCHAR(1024);

CREATE GENERATOR ACCBATCHHISTORY_ID_GEN;
CREATE GENERATOR ACCBATCH_ID_GEN;
CREATE GENERATOR ACCPLAN_ID_GEN;
CREATE GENERATOR ACC_ACCGROUP_ID_GEN;
CREATE GENERATOR ACC_ACCKIND_ID_GEN;
CREATE GENERATOR ACC_ADVANCEREPHEADMODEL_ID_GEN;
CREATE GENERATOR ACC_ADVANCEREPHEAD_ID_GEN;
CREATE GENERATOR ACC_ADVANCEREPSPEC_ID_GEN;
CREATE GENERATOR ACC_AMCODE_ID_GEN;
CREATE GENERATOR ACC_AMORTIZATION_BATCH_GEN;
CREATE GENERATOR ACC_AMORTIZATION_ID_GEN;
CREATE GENERATOR ACC_AMRATE_ID_GEN;
CREATE GENERATOR ACC_INVHEAD_ID_GEN;
CREATE GENERATOR ACC_INVPRODUCTION_ID_GEN;
CREATE GENERATOR ALG_CONST_ID_GEN;
CREATE GENERATOR ALG_CONST_VAL_ID_GEN;
CREATE GENERATOR ALG_CUSTOM_USER_ACTION_ID_GEN;
CREATE GENERATOR ALG_REPOSITORY_ID_GEN;
CREATE GENERATOR ALG_USER_ACT_PERM_ID_GEN;
CREATE GENERATOR ANLPLAN_ID_GEN;
CREATE GENERATOR AUDITINGCOMMISSION_ID_GEN;
CREATE GENERATOR BANKDOCUMENTMODEL_ID_GEN;
CREATE GENERATOR BANKDOCUMENT_ID_GEN;
CREATE GENERATOR BANKREQUIS_ID_GEN;
CREATE GENERATOR BILLHEADMODEL_ID_GEN;
CREATE GENERATOR BILLHEAD_ID_GEN;
CREATE GENERATOR BILLSPECMODEL_ID_GEN;
CREATE GENERATOR BILLSPEC_ID_GEN;
CREATE GENERATOR BUYBOOK_ID_GEN;
CREATE GENERATOR CALCTAXESKIND_ID_GEN;
CREATE GENERATOR CALCTAXESLINK_ID_GEN;
CREATE GENERATOR CASHDOCUMENTMODEL_ID_GEN;
CREATE GENERATOR CASHDOCUMENT_ID_GEN;
CREATE GENERATOR CATALOGFOLDER_ID_GEN;
CREATE GENERATOR CATALOGPRICE_ID_GEN;
CREATE GENERATOR CATALOG_ID_GEN;
CREATE GENERATOR CONTRACTMODIFYDOC_ID_GEN;
CREATE GENERATOR CONTRACTORCARDHIST_ID_GEN;
CREATE GENERATOR CONTRACTORCARDPLAN_ID_GEN;
CREATE GENERATOR CONTRACTORCARD_ID_GEN;
CREATE GENERATOR CONTRACTOR_ID_GEN;
CREATE GENERATOR CONTRACTPHASE_ID_GEN;
CREATE GENERATOR CONTRACTSPEC_ID_GEN;
CREATE GENERATOR CONTRACT_ID_GEN;
CREATE GENERATOR CRM_ACTIVITY_KIND_ID_GEN;
CREATE GENERATOR CRM_ACTIVITY_SPHERE_ID_GEN;
CREATE GENERATOR CRM_BRANCH_ID_GEN;
CREATE GENERATOR CRM_CLIENT_RANK_ID_GEN;
CREATE GENERATOR CRM_CLIENT_TYPE_ID_GEN;
CREATE GENERATOR CRM_CONTACT_ID_GEN;
CREATE GENERATOR CRM_DELIVERY_KIND_ID_GEN;
CREATE GENERATOR CRM_LINKED_DOC_ID_GEN;
CREATE GENERATOR CRM_MARKET_ID_GEN;
CREATE GENERATOR CRM_OFFER_FORECAST_ID_GEN;
CREATE GENERATOR CRM_OFFER_ID_GEN;
CREATE GENERATOR CRM_OFFER_KIND_ID_GEN;
CREATE GENERATOR CRM_OFFER_REASON_ID_GEN;
CREATE GENERATOR CRM_OFFER_STATUS_ID_GEN;
CREATE GENERATOR CRM_OPERATION_ID_GEN;
CREATE GENERATOR CRM_OPERATION_KIND_ID_GEN;
CREATE GENERATOR CRM_OPERATION_PRIORITY_ID_GEN;
CREATE GENERATOR CRM_OPERATION_PURPOSE_ID_GEN;
CREATE GENERATOR CRM_OPERATION_STATUS_ID_GEN;
CREATE GENERATOR CRM_OWNERSHIP_FORM_ID_GEN;
CREATE GENERATOR CRM_PAYMENT_COND_ID_GEN;
CREATE GENERATOR CRM_PERSON_REFER_ID_GEN;
CREATE GENERATOR CRM_PERSON_TITLE_ID_GEN;
CREATE GENERATOR CRM_POSITION_ID_GEN;
CREATE GENERATOR CRM_PROBLEM_ID_GEN;
CREATE GENERATOR CRM_PROBLEM_TYPE_ID_GEN;
CREATE GENERATOR CRM_RELATION_ID_GEN;
CREATE GENERATOR CRM_RELATION_STATUS_ID_GEN;
CREATE GENERATOR CRM_SOLUTION_ID_GEN;
CREATE GENERATOR CRM_SOLUTION_TYPE_ID_GEN;
CREATE GENERATOR CRM_SYMPTOM_ID_GEN;
CREATE GENERATOR CRM_USER_ID_GEN;
CREATE GENERATOR CURRENCYCOUR_ID_GEN;
CREATE GENERATOR CURRENCY_ID_GEN;
CREATE GENERATOR DISCOUNT_ID_GEN;
CREATE GENERATOR DIS_CARD_HIST_ID_GEN;
CREATE GENERATOR DIS_CARD_ID_GEN;
CREATE GENERATOR DIS_CARD_USER_ID_GEN;
CREATE GENERATOR DIS_COEF_ID_GEN;
CREATE GENERATOR DIS_EXTRA_DISCOUNT_ID_GEN;
CREATE GENERATOR DOCACTION_ID_GEN;
CREATE GENERATOR DOCHEADMODEL_ID_GEN;
CREATE GENERATOR DOCHEADSTATE_ID_GEN;
CREATE GENERATOR DOCHEAD_ID_GEN;
CREATE GENERATOR DOCPROCESSSTAGERIGHTS_ID_GEN;
CREATE GENERATOR DOCPROCESSSTAGE_ID_GEN;
CREATE GENERATOR DOCSPECMODEL_ID_GEN;
CREATE GENERATOR DOCSPECSTATE_ID_GEN;
CREATE GENERATOR DOCSPEC_ID_GEN;
CREATE GENERATOR DOCSPEC_PACKAGE_ID_GEN;
CREATE GENERATOR DOCTYPE_DOCSECTION_LINK_ID_GEN;
CREATE GENERATOR DOCTYPE_RIGHTS_ID_GEN;
CREATE GENERATOR DOCUMENT_LINK_ID_GEN;
CREATE GENERATOR DOC_SPEC_PACKAGE_ID_GEN;
CREATE GENERATOR DOC_SPEC_SERIAL_NUM_ID_GEN;
CREATE GENERATOR ECONOMICOPERMODEL_ID_GEN;
CREATE GENERATOR ECONOMICOPER_ID_GEN;
CREATE GENERATOR ECONOMICSPECMODEL_ID_GEN;
CREATE GENERATOR ECONOMICSPEC_ID_GEN;
CREATE GENERATOR ECONSPECFEATURE_ID_GEN;
CREATE GENERATOR EMPLOYEE_ID_GEN;
CREATE GENERATOR EXCH_EXPORT_ID_GEN;
CREATE GENERATOR EXCH_IMPORT_ID_GEN;
CREATE GENERATOR EXCH_SITE_ID_GEN;
CREATE GENERATOR FACTURAHEADIN_ID_GEN;
CREATE GENERATOR FACTURAHEADMODEL_ID_GEN;
CREATE GENERATOR FACTURAHEAD_ID_GEN;
CREATE GENERATOR FACTURAINSPEC_ID_GEN;
CREATE GENERATOR FACTURASPECMODEL_ID_GEN;
CREATE GENERATOR FACTURASPEC_ID_GEN;
CREATE GENERATOR FEATURELINK_ID_GEN;
CREATE GENERATOR FEATUREVAL_ID_GEN;
CREATE GENERATOR FEATURE_DOCSECTION_LINK_ID_GEN;
CREATE GENERATOR FEATURE_ID_GEN;
CREATE GENERATOR FINACCOUNT_ID_GEN;
CREATE GENERATOR FINANL_ID_GEN;
CREATE GENERATOR FINOPERMODEL_ID_GEN;
CREATE GENERATOR FINOPER_ID_GEN;
CREATE GENERATOR FINPERIOD_ID_GEN;
CREATE GENERATOR FINSPECMODEL_ID_GEN;
CREATE GENERATOR FINSPEC_ID_GEN;
CREATE GENERATOR FINSTRUCTURE_ID_GEN;
CREATE GENERATOR FINTURNACC_ID_GEN;
CREATE GENERATOR FINTURNFEAT_ID_GEN;
CREATE GENERATOR FINTURN_ID_GEN;
CREATE GENERATOR FOLDER_ID_GEN;
CREATE GENERATOR FOLDER_RIGHTS_ID_GEN;
CREATE GENERATOR FUEL_DENSITY_HEAD_ID_GEN;
CREATE GENERATOR FUEL_DENSITY_SPEC_ID_GEN;
CREATE GENERATOR GROUPS_ID_GEN;
CREATE GENERATOR HR_ORDER_ID_GEN;
CREATE GENERATOR HR_ORDER_IKIND_PARAM_ID_GEN;
CREATE GENERATOR HR_ORDER_ITEM_ID_GEN;
CREATE GENERATOR HR_ORDER_ITEM_KIND_ID_GEN;
CREATE GENERATOR HR_ORDER_ITEM_PARAM_ID_GEN;
CREATE GENERATOR HR_ORDER_ITEM_ROLLBACK_ID_GEN;
CREATE GENERATOR HR_ORDER_MODEL_ID_GEN;
CREATE GENERATOR HR_ORDER_MODEL_ITEM_ID_GEN;
CREATE GENERATOR HR_ORD_MODEL_ITEM_PARAM_ID_GEN;
CREATE GENERATOR INTERNALACTHEADMODEL_ID_GEN;
CREATE GENERATOR INTERNALACTHEAD_ID_GEN;
CREATE GENERATOR INTERNALACTSPECMODEL_ID_GEN;
CREATE GENERATOR INTERNALACTSPEC_ID_GEN;
CREATE GENERATOR INTERNALINVOICEHEADMODEL_ID_GEN;
CREATE GENERATOR INTERNALINVOICEHEAD_ID_GEN;
CREATE GENERATOR INTERNALINVOICESPECMODEL_ID_GEN;
CREATE GENERATOR INTERNALINVOICESPEC_ID_GEN;
CREATE GENERATOR INVENTORYACTHEAD_ID_GEN;
CREATE GENERATOR INVENTORYACTSPEC_ID_GEN;
CREATE GENERATOR INVENTORY_ID_GEN;
CREATE GENERATOR INVHISTORY_ID_GEN;
CREATE GENERATOR INVLOCATION_ID_GEN;
CREATE GENERATOR INVMETAL_ID_GEN;
CREATE GENERATOR INVOICEHEADMODEL_ID_GEN;
CREATE GENERATOR INVOICEHEAD_ID_GEN;
CREATE GENERATOR INVOICESPECMODEL_ID_GEN;
CREATE GENERATOR INVOICESPEC_ID_GEN;
CREATE GENERATOR LINKSTAGE_ID_GEN;
CREATE GENERATOR LS_ITEMKIND_ID_GEN;
CREATE GENERATOR LS_ITEMSPECALT_ID_GEN;
CREATE GENERATOR LS_ITEMSPECTAX_ID_GEN;
CREATE GENERATOR LS_ITEMSPEC_ID_GEN;
CREATE GENERATOR LS_ITEM_ID_GEN;
CREATE GENERATOR LS_SCHEDULE_ID_GEN;
CREATE GENERATOR MEASURE_ID_GEN;
CREATE GENERATOR MF_BOM_ID_GEN;
CREATE GENERATOR MF_BOM_LABOR_ID_GEN;
CREATE GENERATOR MF_BOM_MACHINE_ID_GEN;
CREATE GENERATOR MF_BOM_MATERIAL_ID_GEN;
CREATE GENERATOR MF_BOM_ROUTE_ID_GEN;
CREATE GENERATOR MF_BOM_ROUTE_RESOURCE_ID_GEN;
CREATE GENERATOR MF_CELL_ID_GEN;
CREATE GENERATOR MF_COST_CATEGORIES_ID_GEN;
CREATE GENERATOR MF_COST_DETAIL_ID_GEN;
CREATE GENERATOR MF_COST_DETAIL_LINE_ID_GEN;
CREATE GENERATOR MF_CREW_ID_GEN;
CREATE GENERATOR MF_DAY_CAL_ID_GEN;
CREATE GENERATOR MF_DAY_TIME_ID_GEN;
CREATE GENERATOR MF_INPUT_DOC_HEAD_ID_GEN;
CREATE GENERATOR MF_INPUT_DOC_HEAD_MODEL_ID_GEN;
CREATE GENERATOR MF_INPUT_DOC_SPEC_ID_GEN;
CREATE GENERATOR MF_JOB_ID_GEN;
CREATE GENERATOR MF_JOB_LABOR_ID_GEN;
CREATE GENERATOR MF_JOB_MACHINE_ID_GEN;
CREATE GENERATOR MF_JOB_MATERIAL_ID_GEN;
CREATE GENERATOR MF_JOB_ROUTE_ID_GEN;
CREATE GENERATOR MF_JOB_ROUTE_RESOURCE_ID_GEN;
CREATE GENERATOR MF_LABOR_CLASS_ID_GEN;
CREATE GENERATOR MF_OUTPUT_DOC_HEAD_ID_GEN;
CREATE GENERATOR MF_OUTPUT_DOC_HEAD_MODEL_ID_GEN;
CREATE GENERATOR MF_RESOURCE_FAMILY_ID_GEN;
CREATE GENERATOR MF_RESOURCE_GROUP_CAP_ID_GEN;
CREATE GENERATOR MF_RESOURCE_GROUP_ID_GEN;
CREATE GENERATOR MF_ROUTE_ID_GEN;
CREATE GENERATOR MF_SCRAP_DOC_HEAD_ID_GEN;
CREATE GENERATOR MF_SCRAP_DOC_HEAD_MODEL_ID_GEN;
CREATE GENERATOR MF_SCRAP_DOC_SPEC_ID_GEN;
CREATE GENERATOR MF_TRANSACTION_ID_GEN;
CREATE GENERATOR MF_VARIANCE_DOC_HEAD_ID_GEN;
CREATE GENERATOR MF_VARIANCE_DOC_SPEC_ID_GEN;
CREATE GENERATOR MF_VARIANCE_D_H_MODEL_ID_GEN;
CREATE GENERATOR MF_WC_RATES_ID_GEN;
CREATE GENERATOR MF_WEEK_CAL_CHANGE_ID_GEN;
CREATE GENERATOR MF_WEEK_CAL_ID_GEN;
CREATE GENERATOR MF_WORK_CENTER_ID_GEN;
CREATE GENERATOR NORMAMOR_ID_GEN;
CREATE GENERATOR OKOF_ID_GEN;
CREATE GENERATOR OLAP_DATAPUMP_ID_GEN;
CREATE GENERATOR ORDERHEADMODEL_ID_GEN;
CREATE GENERATOR ORDERHEAD_ID_GEN;
CREATE GENERATOR ORDERSPECMODEL_ID_GEN;
CREATE GENERATOR ORDERSPEC_ID_GEN;
CREATE GENERATOR ORGUNIT_ID_GEN;
CREATE GENERATOR OVR_CANCELLATION_ID_GEN;
CREATE GENERATOR OVR_CARD_DOCUMENT_LINK_ID_GEN;
CREATE GENERATOR OVR_CARD_HIST_ID_GEN;
CREATE GENERATOR OVR_CARD_ID_GEN;
CREATE GENERATOR OVR_CHIST_DOCSPEC_LINK_ID_GEN;
CREATE GENERATOR OVR_HIST_STATUS_ID_GEN;
CREATE GENERATOR OVR_NORM_HEAD_ID_GEN;
CREATE GENERATOR OVR_NORM_SPEC_ID_GEN;
CREATE GENERATOR OVR_NORM_SPEC_LINK_ID_GEN;
CREATE GENERATOR OVR_N_SPEC_D_SPEC_LINK_ID_GEN;
CREATE GENERATOR OVR_SIZE_ID_GEN;
CREATE GENERATOR PACKING_ID_GEN;
CREATE GENERATOR PARTNEMPL_ID_GEN;
CREATE GENERATOR PARTNER_ID_GEN;
CREATE GENERATOR PERIOD_ID_GEN;
CREATE GENERATOR PERMISSIBLEACCOUNTS_ID_GEN;
CREATE GENERATOR PHASEITEMFACT_ID_GEN;
CREATE GENERATOR PHASEITEMPLAN_ID_GEN;
CREATE GENERATOR PHASEITEM_LINK_ID_GEN;
CREATE GENERATOR PMA_DOCGROUPLINK_ID_GEN;
CREATE GENERATOR PMA_DOCGROUP_ID_GEN;
CREATE GENERATOR PMA_PAYMENT_ID_GEN;
CREATE GENERATOR PMA_TRHEAD_ID_GEN;
CREATE GENERATOR PMA_TRSPEC_ID_GEN;
CREATE GENERATOR PMA_TRTAX_ID_GEN;
CREATE GENERATOR PMC_EXECUTION_ID_GEN;
CREATE GENERATOR PMC_LIABILITY_ID_GEN;
CREATE GENERATOR PMC_PERIOD_ID_GEN;
CREATE GENERATOR PMC_PLAN_ID_GEN;
CREATE GENERATOR PMC_RESOURCE_ID_GEN;
CREATE GENERATOR PMC_VERSION_ID_GEN;
CREATE GENERATOR PMC_VERSTATUS_ID_GEN;
CREATE GENERATOR PP_CATALOG_WAREHOUSE_ID_GEN;
CREATE GENERATOR PP_FIRM_PLANNED_ORDER_ID_GEN;
CREATE GENERATOR PP_FORECAST_VERSION_ID_GEN;
CREATE GENERATOR PP_GENERIC_ITEM_ID_GEN;
CREATE GENERATOR PP_INVENTORY_FORECAST_ID_GEN;
CREATE GENERATOR PP_INV_FORECAST_LINE_ID_GEN;
CREATE GENERATOR PP_ITEM_FAMILY_ID_GEN;
CREATE GENERATOR PP_MPS_ID_GEN;
CREATE GENERATOR PP_MPS_LINE_ID_GEN;
CREATE GENERATOR PP_MRP_INPUTS_ID_GEN;
CREATE GENERATOR PP_MRP_OUTPUTS_ID_GEN;
CREATE GENERATOR PP_MRP_RECOMMENDATION_ID_GEN;
CREATE GENERATOR PP_MRP_REPORT_ID_GEN;
CREATE GENERATOR PP_MRP_SHORTAGE_ID_GEN;
CREATE GENERATOR PP_MRP_TOTALS_BY_DATE_ID_GEN;
CREATE GENERATOR PP_MRP_VERSION_CONTROL_ID_GEN;
CREATE GENERATOR PP_MRP_VERSION_FORECAST_ID_GEN;
CREATE GENERATOR PP_MRP_VERSION_MPS_ID_GEN;
CREATE GENERATOR PP_PLANNING_FORECAST_ID_GEN;
CREATE GENERATOR PP_PLANNING_LEVEL_BUCKT_ID_GEN;
CREATE GENERATOR PP_PLANNING_LEVEL_ID_GEN;
CREATE GENERATOR PP_PRODUCTION_PROFILE_ID_GEN;
CREATE GENERATOR PP_RCCP_DETAIL_ID_GEN;
CREATE GENERATOR PP_RCCP_HEADER_ID_GEN;
CREATE GENERATOR PP_RCCP_RESOURCE_LOAD_ID_GEN;
CREATE GENERATOR PREF_ABBREVIATION_ID_GEN;
CREATE GENERATOR PREF_ADDRESS_ID_GEN;
CREATE GENERATOR PREF_ADD_EDUCATION_KIND_ID_GEN;
CREATE GENERATOR PREF_AREA_ID_GEN;
CREATE GENERATOR PREF_CALC_PERIOD_ID_GEN;
CREATE GENERATOR PREF_CITY_ID_GEN;
CREATE GENERATOR PREF_COSTS_ANL_ID_GEN;
CREATE GENERATOR PREF_COUNTRY_ID_GEN;
CREATE GENERATOR PREF_DEDUCTION_KIND_ID_GEN;
CREATE GENERATOR PREF_DISTRICT_ID_GEN;
CREATE GENERATOR PREF_EDUCATION_DEGREE_ID_GEN;
CREATE GENERATOR PREF_FAMILYDEDUCTIONS_ID_GEN;
CREATE GENERATOR PREF_FAMILYMEMBERS_ID_GEN;
CREATE GENERATOR PREF_FAMILYRELATION_ID_GEN;
CREATE GENERATOR PREF_FAMILYSTATUS_ID_GEN;
CREATE GENERATOR PREF_FAMILYSTATUS_KIND_ID_GEN;
CREATE GENERATOR PREF_FOREIGN_LANGUAGE_ID_GEN;
CREATE GENERATOR PREF_IDENTDOC_ID_GEN;
CREATE GENERATOR PREF_IDENTDOC_KIND_ID_GEN;
CREATE GENERATOR PREF_INSUREDCLASS_ID_GEN;
CREATE GENERATOR PREF_JOB_ID_GEN;
CREATE GENERATOR PREF_KLADR_ID_GEN;
CREATE GENERATOR PREF_LANGUAGE_KNOWLEDGE_ID_GEN;
CREATE GENERATOR PREF_LEAVE_KIND_ID_GEN;
CREATE GENERATOR PREF_MILITARY_RANK_ID_GEN;
CREATE GENERATOR PREF_MILITARY_RANK_KIND_ID_GEN;
CREATE GENERATOR PREF_MILITARY_VALIDITY_ID_GEN;
CREATE GENERATOR PREF_NATIONALITY_ID_GEN;
CREATE GENERATOR PREF_PCK_IN_SERVICEKIND_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_GROUP_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_GROUP_TYPE_GEN;
CREATE GENERATOR PREF_PERSONNEL_HIST_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_LANGUAGE_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_LEAVE_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_PHONE_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_RECORD_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_REWARD_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_SERVICE_ID_GEN;
CREATE GENERATOR PREF_PERSONNEL_TRANSFER_ID_GEN;
CREATE GENERATOR PREF_PERS_ATTESTATION_ID_GEN;
CREATE GENERATOR PREF_PERS_EDUCATION_ID_GEN;
CREATE GENERATOR PREF_PERS_LAB_CONTRACT_ID_GEN;
CREATE GENERATOR PREF_PERS_PROFESSION_ID_GEN;
CREATE GENERATOR PREF_PERS_SKILL_RAISING_ID_GEN;
CREATE GENERATOR PREF_PERS_SOC_BENEFIT_ID_GEN;
CREATE GENERATOR PREF_PERS_VOCATNL_TRAIN_ID_GEN;
CREATE GENERATOR PREF_PFCODE_IN_SERVICE_ID_GEN;
CREATE GENERATOR PREF_POSITION_FILL_KIND_ID_GEN;
CREATE GENERATOR PREF_POSITION_ID_GEN;
CREATE GENERATOR PREF_REGION_ID_GEN;
CREATE GENERATOR PREF_RESERVE_CATEGORY_ID_GEN;
CREATE GENERATOR PREF_RISE_ID_GEN;
CREATE GENERATOR PREF_RISE_PERCENT_ID_GEN;
CREATE GENERATOR PREF_RISE_SCALE_ID_GEN;
CREATE GENERATOR PREF_SERVICE_KIND_ID_GEN;
CREATE GENERATOR PREF_SERVICE_PFCODE_ID_GEN;
CREATE GENERATOR PREF_SKILL_RAISING_KIND_ID_GEN;
CREATE GENERATOR PREF_SL_POSITION_UNIQUE_ID_GEN;
CREATE GENERATOR PREF_SPECIALITY_ID_GEN;
CREATE GENERATOR PREF_STAFF_CATEGORY_ID_GEN;
CREATE GENERATOR PREF_STAFF_LIST_ID_GEN;
CREATE GENERATOR PREF_STAFF_LIST_UNIT_ID_GEN;
CREATE GENERATOR PREF_STAFF_LST_POSITION_ID_GEN;
CREATE GENERATOR PREF_STREET_ID_GEN;
CREATE GENERATOR PREF_TARIFFING_CATEGORY_ID_GEN;
CREATE GENERATOR PREF_TARIFFING_ID_GEN;
CREATE GENERATOR PREF_TARIFF_SCALE_CLASS_ID_GEN;
CREATE GENERATOR PREF_TARIFF_SCALE_ID_GEN;
CREATE GENERATOR PREF_TAX_CALC_KIND_ID_GEN;
CREATE GENERATOR PREF_WORKTIME_NORM_ID_GEN;
CREATE GENERATOR PREF_WORK_CONDITION_ID_GEN;
CREATE GENERATOR PREF_WORK_SCHEDULE_ID_GEN;
CREATE GENERATOR PRICELIST_PT_LINK_ID_GEN;
CREATE GENERATOR PRICELISTFOLDER_ID_GEN;
CREATE GENERATOR PRICELISTHEAD_ID_GEN;
CREATE GENERATOR PRICELISTHEAD_RIGHTS_ID_GEN;
CREATE GENERATOR PRICELISTSPEC_ID_GEN;
CREATE GENERATOR PRICETYPE_ID_GEN;
CREATE GENERATOR PROVIDER_PRICELISTFOLDER_ID_GEN;
CREATE GENERATOR PROVIDER_PRICELISTHEAD_ID_GEN;
CREATE GENERATOR PROVIDER_PRICELISTSPEC_ID_GEN;
CREATE GENERATOR PR_CONTACT_HIST_FILES_ID_GEN;
CREATE GENERATOR PR_CONTACT_HIST_ID_GEN;
CREATE GENERATOR PR_CONTACT_KIND_ID_GEN;
CREATE GENERATOR PR_POSSIBLE_RESULT_ID_GEN;
CREATE GENERATOR QC_SCRAP_REASON_ID_GEN;
CREATE GENERATOR QC_SCRAP_TYPE_ID_GEN;
CREATE GENERATOR REF_BANK_ACCOUNT_ID_GEN;
CREATE GENERATOR REF_BANK_ACCOUNT_TYPE_ID_GEN;
CREATE GENERATOR REF_BANK_ID_GEN;
CREATE GENERATOR REF_CONFIDENTIAL_DATA_ID_GEN;
CREATE GENERATOR REF_CONTRACTOR_EADDRESS_ID_GEN;
CREATE GENERATOR REF_CONTRACTOR_PHONE_ID_GEN;
CREATE GENERATOR REF_COUNTRY_ID_GEN;
CREATE GENERATOR REF_CUR_RATE_AUTHORITY_ID_GEN;
CREATE GENERATOR REF_CUR_RATE_ID_GEN;
CREATE GENERATOR REF_CUR_RATE_TYPE_ID_GEN;
CREATE GENERATOR REF_DISTRICT_ID_GEN;
CREATE GENERATOR REF_EADDRESS_KIND_ID_GEN;
CREATE GENERATOR REF_FAMILY_MEMBER_ID_GEN;
CREATE GENERATOR REF_FAMILY_RELATION_ID_GEN;
CREATE GENERATOR REF_FAMILY_STATUS_ID_GEN;
CREATE GENERATOR REF_FAMILY_STATUS_KIND_ID_GEN;
CREATE GENERATOR REF_HOLIDAYS_ID_GEN;
CREATE GENERATOR REF_IDENT_DOC_ID_GEN;
CREATE GENERATOR REF_IDENT_DOC_KIND_ID_GEN;
CREATE GENERATOR REF_KBK_ID_GEN;
CREATE GENERATOR REF_MEASURE_CONV_ID_GEN;
CREATE GENERATOR REF_NATIONALITY_ID_GEN;
CREATE GENERATOR REF_NATURAL_PERSON_HIST_ID_GEN;
CREATE GENERATOR REF_NATURAL_PERSON_ID_GEN;
CREATE GENERATOR REF_OKATO_ID_GEN;
CREATE GENERATOR REF_OKP_ID_GEN;
CREATE GENERATOR REF_ORIGINAL_DOCUMENT_ID_GEN;
CREATE GENERATOR REF_PARTN_EMPL_EMAIL_ID_GEN;
CREATE GENERATOR REF_PARTN_EMPL_LINK_ID_GEN;
CREATE GENERATOR REF_PARTN_EMPL_PHONE_ID_GEN;
CREATE GENERATOR REF_PERSON_ADDRESS_ID_GEN;
CREATE GENERATOR REF_PERSON_EADDRESS_ID_GEN;
CREATE GENERATOR REF_PERSON_EMAIL_ID_GEN;
CREATE GENERATOR REF_PERSON_PHONE_ID_GEN;
CREATE GENERATOR REF_PHONE_KIND_ID_GEN;
CREATE GENERATOR REF_PLACE_ID_GEN;
CREATE GENERATOR REF_REGION_ID_GEN;
CREATE GENERATOR REF_ZIPCODE_ID_GEN;
CREATE GENERATOR REMNACC_ID_GEN;
CREATE GENERATOR REMNANL_ID_GEN;
CREATE GENERATOR REMNDBKT_ID_GEN;
CREATE GENERATOR REMNVAL_ID_GEN;
CREATE GENERATOR RPTBANDS_ID_GEN;
CREATE GENERATOR RPTFIELDS_ID_GEN;
CREATE GENERATOR RPTMAIN_ID_GEN;
CREATE GENERATOR RPTPARAMS_ID_GEN;
CREATE GENERATOR RPTQUERIES_ID_GEN;
CREATE GENERATOR RPT_CLASS_LINK_ID_GEN;
CREATE GENERATOR RPT_RIGHTS_ID_GEN;
CREATE GENERATOR RPT_TEMPLATE_ID_GEN;
CREATE GENERATOR RTL_INVOICEHEADMODEL_ID_GEN;
CREATE GENERATOR RTL_INVOICEHEAD_ID_GEN;
CREATE GENERATOR RTL_INVOICESPEC_ID_GEN;
CREATE GENERATOR SALEBOOK_ID_GEN;
CREATE GENERATOR SAL_CALC_LIST_FEE_ID_GEN;
CREATE GENERATOR SAL_CALC_LIST_FEE_PARAM_ID_GEN;
CREATE GENERATOR SAL_CALC_LIST_ID_GEN;
CREATE GENERATOR SAL_CALC_LIST_SECTION_ID_GEN;
CREATE GENERATOR SAL_CLIST_SECTION_REF_ID_GEN;
CREATE GENERATOR SAL_DISCOUNTKIND_ID_GEN;
CREATE GENERATOR SAL_FEE_MODEL_ID_GEN;
CREATE GENERATOR SAL_FEE_MODEL_PARAM_ID_GEN;
CREATE GENERATOR SAL_FEE_REF_ID_GEN;
CREATE GENERATOR SAL_FEE_REF_PARAM_ID_GEN;
CREATE GENERATOR SAL_FEE_SUMMARY_HEAD_ID_GEN;
CREATE GENERATOR SAL_FEE_SUMMARY_SPEC_ID_GEN;
CREATE GENERATOR SAL_GNS_CODE_ID_GEN;
CREATE GENERATOR SAL_INCLUDED_FEE_ID_GEN;
CREATE GENERATOR SAL_INCOMEKIND_ID_GEN;
CREATE GENERATOR SAL_MINSALARY_ID_GEN;
CREATE GENERATOR SAL_PAY_ROLL_ID_GEN;
CREATE GENERATOR SAL_PAY_SHEET_ID_GEN;
CREATE GENERATOR SAL_PAY_SHEET_SPEC_ID_GEN;
CREATE GENERATOR SAL_PERSONAL_ACCOUNT_ID_GEN;
CREATE GENERATOR SAL_POSITION_FILL_ID_GEN;
CREATE GENERATOR SAL_REPLACED_FEE_ID_GEN;
CREATE GENERATOR SAL_ROLL_KIND_ID_GEN;
CREATE GENERATOR SAL_TARIFFING_IN_FEE_ID_GEN;
CREATE GENERATOR SAL_TAXHEAD_ID_GEN;
CREATE GENERATOR SAL_TAXRATE_ID_GEN;
CREATE GENERATOR SAL_TAXSCALE_ID_GEN;
CREATE GENERATOR SCH_TASK_ID_GEN;
CREATE GENERATOR SEC_GROUPS_ID_GEN;
CREATE GENERATOR SEC_LINK_USERS_GROUPS_ID_GEN;
CREATE GENERATOR SEC_METHOD_ACCESS_ID_GEN;
CREATE GENERATOR SEC_MODULE_ACCESS_ID_GEN;
CREATE GENERATOR SEC_USER_ID_GEN;
CREATE GENERATOR SEC_USER_PROFILE_ID_GEN;
CREATE GENERATOR SEC_USER_PROFILE_ITEM_ID_GEN;
CREATE GENERATOR SETOFGOOD_ID_GEN;
CREATE GENERATOR STOCKBATCHHISTORY_ID_GEN;
CREATE GENERATOR STOCKBATCH_ID_GEN;
CREATE GENERATOR STOCKCARD_ID_GEN;
CREATE GENERATOR STOCKDOCUMENTHEADMODEL_ID_GEN;
CREATE GENERATOR STOCKDOCUMENTHEAD_ID_GEN;
CREATE GENERATOR STOCKDOCUMENTSPECMODEL_ID_GEN;
CREATE GENERATOR STOCKDOCUMENTSPEC_ID_GEN;
CREATE GENERATOR STOCKPLANHISTORY_ID_GEN;
CREATE GENERATOR SYSPART_METHOD_ID_GEN;
CREATE GENERATOR SYSPART_RIGHTS_ID_GEN;
CREATE GENERATOR SYS_AUDIT_ID_GEN;
CREATE GENERATOR SYS_CLASS_ID_GEN;
CREATE GENERATOR SYS_METHOD_ID_GEN;
CREATE GENERATOR SYS_MODULE_ID_GEN;
CREATE GENERATOR TAB_PATTERN_HEAD_ID_GEN;
CREATE GENERATOR TAB_PATTERN_SPEC_ID_GEN;
CREATE GENERATOR TAB_SCHEDULE_HEAD_ID_GEN;
CREATE GENERATOR TAB_SCHEDULE_SPEC_ID_GEN;
CREATE GENERATOR TAB_TIME_BOARD_HEAD_ID_GEN;
CREATE GENERATOR TAB_TIME_BOARD_POSITION_ID_GEN;
CREATE GENERATOR TAB_TIME_BOARD_SPEC_ID_GEN;
CREATE GENERATOR TAB_TIME_KIND_ID_GEN;
CREATE GENERATOR TAXGROUP_ID_GEN;
CREATE GENERATOR TAXLINK_ID_GEN;
CREATE GENERATOR TAXSUMM_ID_GEN;
CREATE GENERATOR TAX_ID_GEN;
CREATE GENERATOR TURNONESFEATURES_ID_GEN;
CREATE GENERATOR TURNVAL_ID_GEN;
CREATE GENERATOR TURNVAL_SESSION_GEN;
CREATE GENERATOR TYPEDOC_ID_GEN;
CREATE GENERATOR WF_ACTIVITY_ID_GEN;
CREATE GENERATOR WF_ACTIVITY_MODEL_ID_GEN;
CREATE GENERATOR WF_ASSIGNMENT_ID_GEN;
CREATE GENERATOR WF_AUDIT_ID_GEN;
CREATE GENERATOR WF_AVAILABLE_RESOURCE_ID_GEN;
CREATE GENERATOR WF_LINK_GROUP_RESOURCE_ID_GEN;
CREATE GENERATOR WF_MAP_EDGE_ID_GEN;
CREATE GENERATOR WF_PROCESS_ID_GEN;
CREATE GENERATOR WF_PROCESS_MGR_ID_GEN;
CREATE GENERATOR WF_REQUESTER_ID_GEN;
CREATE GENERATOR WF_RESOURCE_ID_GEN;
CREATE GENERATOR WF_RESULT_ID_GEN;
CREATE GENERATOR WF_ROLLBACK_SEGMENT_ID_GEN;
CREATE GENERATOR WH_BIN_LOCATION_DETAIL_ID_GEN;
CREATE GENERATOR WH_BIN_LOCATION_ID_GEN;
CREATE GENERATOR WH_BIN_LOCATION_TYPE_ID_GEN;
CREATE GENERATOR WH_BT_CAP_BY_PRODUCT_ID_GEN;
CREATE GENERATOR WH_INVACT_COMMISSION_ID_GEN;
CREATE GENERATOR WH_SECURITY_ID_GEN;
CREATE GENERATOR WH_SERIAL_NUM_ID_GEN;
CREATE GENERATOR WH_STOCK_KIND_ID_GEN;
CREATE GENERATOR WH_WAREHOUSE_ID_GEN;
CREATE GENERATOR WH_ZONE_ID_GEN;


CREATE EXCEPTION E_ACTMONTH_EXISTS 'ActMonth already exists';

CREATE EXCEPTION E_CANNOT_DEL_BASEPRICE 'Can not delete base price';

CREATE EXCEPTION E_CANNOT_DEL_DOCPROCESSTAGE 'Cannot delete stage because some documents use it.';

CREATE EXCEPTION E_CANNOT_UPDATE_CONTRACTORCARD 'Cannot update ContractorCard';

CREATE EXCEPTION E_CONTRACTOR_EMPTY 'Contractor empty';

CREATE EXCEPTION E_CONTRACTOR_FROM_EMPTY 'Contractor "from" empty';

CREATE EXCEPTION E_CONTRACTOR_TO_EMPTY 'Contractor "to" empty';

CREATE EXCEPTION E_DOCUMENTS_CANNOT_BE_MERGED 'Documents can not be merged';

CREATE EXCEPTION E_FINPERIODS_IS_CROSS 'Finance periods cross';

CREATE EXCEPTION E_FINPERIOD_IS_CLOSED 'Finance period is closed';

CREATE EXCEPTION E_FOREIGN_KEY_VIOLATION 'Violation of foreign key';

CREATE EXCEPTION E_INVALID_ACCBATCH 'Accbatch ID is wrong';

CREATE EXCEPTION E_INVALID_ACCBATCHHISTORY 'AccBtachHistory ID is wrong';

CREATE EXCEPTION E_INVALID_ACCOUNT 'Account not exists';

CREATE EXCEPTION E_INVALID_ANALITIC_RELATED 'Invalid analitic related';

CREATE EXCEPTION E_INVALID_CATALOGCODE 'Catalog code is wrong';

CREATE EXCEPTION E_INVALID_FINPERIOD 'Finance period not exists';

CREATE EXCEPTION E_INVALID_NEXT_STAGE 'Next stage type is wrong';

CREATE EXCEPTION E_INVALID_PERIOD 'Period not be exist';

CREATE EXCEPTION E_INVHISTORY_NOT_LAST 'Only last history record can be deleted';

CREATE EXCEPTION E_IS_NOT_ENOUGH_QUAN_ON_STOCK 'Is not enough quantity on stock';

CREATE EXCEPTION E_LOCK_CONFLICT_REMNACC 'Lock conflict on table REMNACC';

CREATE EXCEPTION E_LOCK_CONFLICT_REMNANL 'Lock conflict on table REMNANL';

CREATE EXCEPTION E_LOCK_CONFLICT_REMNDBKT 'Lock conflict on table REMNDBKT';

CREATE EXCEPTION E_LOCK_CONFLICT_REMNVAL 'Lock conflict on table REMNVAL';

CREATE EXCEPTION E_MERGE_INCOMPATIBLE_DOCSECTION 'Documents merging error: incompatible docsection';

CREATE EXCEPTION E_PERIODS_IS_CROSS 'Periods is cross';

CREATE EXCEPTION E_PERIOD_IS_CLOSE 'Period is close';

CREATE EXCEPTION E_PERMISSIBLEACCOUNTS_UNIQUE 'Permissible accounts no can have duplicate';

CREATE EXCEPTION E_PERMISSIBLEACC_WRONG 'Permissible accounts is wrong';

CREATE EXCEPTION E_REVALUE_NOT_EXIST_ACCBATCH 'Can''t revalue not exist accbatch';

CREATE EXCEPTION E_STOCKBATCHHISTORY_EXISTS 'Stock batch history exists';

CREATE EXCEPTION E_STOCKCARD_IS_NOT_EMPTY 'StockCard is not empty';

CREATE EXCEPTION FIN_E_LOCK_CONFLICT_TURN 'Lock conflict';

CREATE EXCEPTION REF_E_FEATUREVAL_IS_USED 'Feature value is used and can not be modified or deleted';
