package com.mg.merp.personnelref.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * Abbreviation generated by hbm2java
 */
@Entity
@Table(name = "PREF_ABBREVIATION")
public class Abbreviation extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private SysClient SysClient;

    private Integer ALevel;

    private String ScName;

    private String SocrName;

    private String KodTSt;

    public Abbreviation() {
    }

    public Abbreviation(SysClient SysClient, Integer ALevel, String ScName, String SocrName, String KodTSt) {
        this.SysClient = SysClient;
        this.ALevel = ALevel;
        this.ScName = ScName;
        this.SocrName = SocrName;
        this.KodTSt = KodTSt;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PREF_ABBREVIATION_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "ALEVEL", columnDefinition = "INTEGER")
    @DataItemName("PersonnelRef.Abbreviation.ALevel")
    public Integer getALevel() {
        return this.ALevel;
    }

    public void setALevel(Integer ALevel) {
        this.ALevel = ALevel;
    }

    @Column(name = "SCNAME", columnDefinition = "CHAR", length = 11)
    @DataItemName("PersonnelRef.Abbreviation.ScName")
    public String getScName() {
        return this.ScName;
    }

    public void setScName(String ScName) {
        this.ScName = ScName;
    }

    @Column(name = "SOCRNAME", columnDefinition = "VARCHAR", length = 30)
    @DataItemName("PersonnelRef.Abbreviation.SocrName")
    public String getSocrName() {
        return this.SocrName;
    }

    public void setSocrName(String SocrName) {
        this.SocrName = SocrName;
    }

    @Column(name = "KOD_T_ST", columnDefinition = "CHAR", length = 3)
    public String getKodTSt() {
        return this.KodTSt;
    }

    public void setKodTSt(String KodTSt) {
        this.KodTSt = KodTSt;
    }
}

