package com.mg.merp.personnelref.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.PersonAddressKind;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "PREF_ADDRESS")
public class Address extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private Personnel Personnel;

    private SysClient SysClient;

    private PersonAddressKind AddressKind;

    private Date BeginDate;

    private String FullAddress;

    private String PostIndex;

    private String Country;

    private String Region;

    private String District;

    private String DistrictType;

    private String City;

    private String CityType;

    private String Area;

    private String AreaType;

    private String Street;

    private String StreetType;

    private String House;

    private String Block;

    private String Flat;

    private String RegionType;

    private String KladrCode;

    public Address() {
    }

    public Address(String Country, String Region, String District, String City, String Area, String Street) {
        this.Country = Country;
        this.Region = Region;
        this.District = District;
        this.City = City;
        this.Area = Area;
        this.Street = Street;
    }

    public Address(Personnel Personnel, SysClient SysClient, PersonAddressKind AddressKind, Date BeginDate, String FullAddress, String PostIndex, String Country, String Region, String District, String DistrictType, String City, String CityType, String Area, String AreaType, String Street, String StreetType, String House, String Block, String Flat, String RegionType, String KladrCode) {
        this.Personnel = Personnel;
        this.SysClient = SysClient;
        this.AddressKind = AddressKind;
        this.BeginDate = BeginDate;
        this.FullAddress = FullAddress;
        this.PostIndex = PostIndex;
        this.Country = Country;
        this.Region = Region;
        this.District = District;
        this.DistrictType = DistrictType;
        this.City = City;
        this.CityType = CityType;
        this.Area = Area;
        this.AreaType = AreaType;
        this.Street = Street;
        this.StreetType = StreetType;
        this.House = House;
        this.Block = Block;
        this.Flat = Flat;
        this.RegionType = RegionType;
        this.KladrCode = KladrCode;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PREF_ADDRESS_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERSONNEL_ID")
    public Personnel getPersonnel() {
        return this.Personnel;
    }

    public void setPersonnel(Personnel Personnel) {
        this.Personnel = Personnel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "ADDRESS_KIND")
    @Enumerated(EnumType.ORDINAL)
    public PersonAddressKind getAddressKind() {
        return this.AddressKind;
    }

    public void setAddressKind(PersonAddressKind AddressKind) {
        this.AddressKind = AddressKind;
    }

    @Column(name = "BEGINDATE", columnDefinition = "TIMESTAMP")
    public Date getBeginDate() {
        return this.BeginDate;
    }

    public void setBeginDate(Date BeginDate) {
        this.BeginDate = BeginDate;
    }

    @Column(name = "FULL_ADDRESS", columnDefinition = "VARCHAR", length = 256)
    public String getFullAddress() {
        return this.FullAddress;
    }

    public void setFullAddress(String FullAddress) {
        this.FullAddress = FullAddress;
    }

    @Column(name = "POST_INDEX", columnDefinition = "CHAR", length = 10)
    public String getPostIndex() {
        return this.PostIndex;
    }

    public void setPostIndex(String PostIndex) {
        this.PostIndex = PostIndex;
    }

    @Column(name = "COUNTRY", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getCountry() {
        return this.Country;
    }

    public void setCountry(String Country) {
        this.Country = Country;
    }

    @Column(name = "REGION", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getRegion() {
        return this.Region;
    }

    public void setRegion(String Region) {
        this.Region = Region;
    }

    @Column(name = "DISTRICT", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getDistrict() {
        return this.District;
    }

    public void setDistrict(String District) {
        this.District = District;
    }

    @Column(name = "DISTRICT_TYPE", columnDefinition = "CHAR", length = 11)
    public String getDistrictType() {
        return this.DistrictType;
    }

    public void setDistrictType(String DistrictType) {
        this.DistrictType = DistrictType;
    }

    @Column(name = "CITY", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getCity() {
        return this.City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    @Column(name = "CITY_TYPE", columnDefinition = "CHAR", length = 11)
    public String getCityType() {
        return this.CityType;
    }

    public void setCityType(String CityType) {
        this.CityType = CityType;
    }

    @Column(name = "AREA", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getArea() {
        return this.Area;
    }

    public void setArea(String Area) {
        this.Area = Area;
    }

    @Column(name = "AREA_TYPE", columnDefinition = "CHAR", length = 11)
    public String getAreaType() {
        return this.AreaType;
    }

    public void setAreaType(String AreaType) {
        this.AreaType = AreaType;
    }

    @Column(name = "STREET", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getStreet() {
        return this.Street;
    }

    public void setStreet(String Street) {
        this.Street = Street;
    }

    @Column(name = "STREET_TYPE", columnDefinition = "CHAR", length = 11)
    public String getStreetType() {
        return this.StreetType;
    }

    public void setStreetType(String StreetType) {
        this.StreetType = StreetType;
    }

    @Column(name = "HOUSE", columnDefinition = "CHAR", length = 10)
    public String getHouse() {
        return this.House;
    }

    public void setHouse(String House) {
        this.House = House;
    }

    @Column(name = "BLOCK", columnDefinition = "CHAR", length = 10)
    public String getBlock() {
        return this.Block;
    }

    public void setBlock(String Block) {
        this.Block = Block;
    }

    @Column(name = "FLAT", columnDefinition = "CHAR", length = 10)
    public String getFlat() {
        return this.Flat;
    }

    public void setFlat(String Flat) {
        this.Flat = Flat;
    }

    @Column(name = "REGION_TYPE", columnDefinition = "CHAR", length = 11)
    public String getRegionType() {
        return this.RegionType;
    }

    public void setRegionType(String RegionType) {
        this.RegionType = RegionType;
    }

    @Column(name = "KLADR_CODE", columnDefinition = "CHAR", length = 15)
    public String getKladrCode() {
        return this.KladrCode;
    }

    public void setKladrCode(String KladrCode) {
        this.KladrCode = KladrCode;
    }
}

