package com.mg.merp.personnelref.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.FamilyMember;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FamilyDeductions generated by hbm2java
 */
@Entity
@Table(name="PREF_FAMILYDEDUCTIONS"
)
public class FamilyDeductions extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private SysClient SysClient;
     private DeductionKind DeductionKind;
     private FamilyMember FamilyMember;
     private Date BeginDate;
     private Date EndDate;
     private BigDecimal Ratio;

    public FamilyDeductions() {
    }

    public FamilyDeductions(SysClient SysClient, DeductionKind DeductionKind, FamilyMember FamilyMember, Date BeginDate, Date EndDate, BigDecimal Ratio) {
       this.SysClient = SysClient;
       this.DeductionKind = DeductionKind;
       this.FamilyMember = FamilyMember;
       this.BeginDate = BeginDate;
       this.EndDate = EndDate;
       this.Ratio = Ratio;
    }
   
     @SequenceGenerator(name="generator", sequenceName="PREF_FAMILYDEDUCTIONS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEDUCTIONKIND_ID")
    public DeductionKind getDeductionKind() {
        return this.DeductionKind;
    }
    
    public void setDeductionKind(DeductionKind DeductionKind) {
        this.DeductionKind = DeductionKind;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FAMILY_MEMBER_ID")
    public FamilyMember getFamilyMember() {
        return this.FamilyMember;
    }
    
    public void setFamilyMember(FamilyMember FamilyMember) {
        this.FamilyMember = FamilyMember;
    }

    
    @Column(name="BEGINDATE", columnDefinition="TIMESTAMP")
    public Date getBeginDate() {
        return this.BeginDate;
    }
    
    public void setBeginDate(Date BeginDate) {
        this.BeginDate = BeginDate;
    }

    
    @Column(name="ENDDATE", columnDefinition="TIMESTAMP")
    public Date getEndDate() {
        return this.EndDate;
    }
    
    public void setEndDate(Date EndDate) {
        this.EndDate = EndDate;
    }

    
    @Column(name="RATIO", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getRatio() {
        return this.Ratio;
    }
    
    public void setRatio(BigDecimal Ratio) {
        this.Ratio = Ratio;
    }




}


