package com.mg.merp.personnelref.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * InsuredClass generated by hbm2java
 */
@Entity
@Table(name="PREF_INSUREDCLASS"
)
public class InsuredClass extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private SysClient SysClient;
     private String CCode;
     private String CName;
     private BigDecimal InsuredPercent;
     private BigDecimal EmployerPercent;

    public InsuredClass() {
    }

	
    public InsuredClass(String CCode, String CName) {
        this.CCode = CCode;
        this.CName = CName;
    }
    public InsuredClass(SysClient SysClient, String CCode, String CName, BigDecimal InsuredPercent, BigDecimal EmployerPercent) {
       this.SysClient = SysClient;
       this.CCode = CCode;
       this.CName = CName;
       this.InsuredPercent = InsuredPercent;
       this.EmployerPercent = EmployerPercent;
    }
   
     @SequenceGenerator(name="generator", sequenceName="PREF_INSUREDCLASS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CCODE", unique=true, nullable=false, columnDefinition="CHAR", length=20)
    public String getCCode() {
        return this.CCode;
    }
    
    public void setCCode(String CCode) {
        this.CCode = CCode;
    }

    
    @Column(name="CNAME", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getCName() {
        return this.CName;
    }
    
    public void setCName(String CName) {
        this.CName = CName;
    }

    
    @Column(name="INSURED_PERCENT", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getInsuredPercent() {
        return this.InsuredPercent;
    }
    
    public void setInsuredPercent(BigDecimal InsuredPercent) {
        this.InsuredPercent = InsuredPercent;
    }

    
    @Column(name="EMPLOYER_PERCENT", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getEmployerPercent() {
        return this.EmployerPercent;
    }
    
    public void setEmployerPercent(BigDecimal EmployerPercent) {
        this.EmployerPercent = EmployerPercent;
    }




}


