package com.mg.merp.personnelref.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.PhoneKind;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonnelPhone generated by hbm2java
 */
@Entity
@Table(name="PREF_PERSONNEL_PHONE"
)
public class PersonnelPhone extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Personnel Personnel;
     private SysClient SysClient;
     private PhoneKind PhoneKind;
     private String TownCode;
     private String Phone;

    public PersonnelPhone() {
    }

	
    public PersonnelPhone(Integer Id) {
        this.Id = Id;
    }
    public PersonnelPhone(Integer Id, Personnel Personnel, SysClient SysClient, PhoneKind PhoneKind, String TownCode, String Phone) {
       this.Id = Id;
       this.Personnel = Personnel;
       this.SysClient = SysClient;
       this.PhoneKind = PhoneKind;
       this.TownCode = TownCode;
       this.Phone = Phone;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSONNEL_ID")
    public Personnel getPersonnel() {
        return this.Personnel;
    }
    
    public void setPersonnel(Personnel Personnel) {
        this.Personnel = Personnel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PHONE_KIND_ID")
    public PhoneKind getPhoneKind() {
        return this.PhoneKind;
    }
    
    public void setPhoneKind(PhoneKind PhoneKind) {
        this.PhoneKind = PhoneKind;
    }

    
    @Column(name="TOWN_CODE", columnDefinition="VARCHAR", length=80)
    public String getTownCode() {
        return this.TownCode;
    }
    
    public void setTownCode(String TownCode) {
        this.TownCode = TownCode;
    }

    
    @Column(name="PHONE", columnDefinition="VARCHAR", length=80)
    public String getPhone() {
        return this.Phone;
    }
    
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }




}


