package com.mg.merp.personnelref.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.CurrencyRateAuthority;
import com.mg.merp.reference.model.CurrencyRateType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonnelConfig generated by hbm2java
 */
@Entity
@Table(name="PREF_CONFIG"
)
public class PersonnelConfig extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private SysClient SysClient;
     private Catalog CostsAnl;
     private CurrencyRateType CurRateType;
     private CurrencyRateAuthority CurRateAuthority;
     private Currency BaseCurrency;
     private Currency NatCurrency;
     private Short CurrencyPrec;

    public PersonnelConfig() {
    }

	
    public PersonnelConfig(Integer Id) {
        this.Id = Id;
    }
    public PersonnelConfig(Integer Id, SysClient SysClient, Catalog CostsAnl, CurrencyRateType CurRateType, CurrencyRateAuthority CurRateAuthority, Currency BaseCurrency, Currency NatCurrency, Short CurrencyPrec) {
       this.Id = Id;
       this.SysClient = SysClient;
       this.CostsAnl = CostsAnl;
       this.CurRateType = CurRateType;
       this.CurRateAuthority = CurRateAuthority;
       this.BaseCurrency = BaseCurrency;
       this.NatCurrency = NatCurrency;
       this.CurrencyPrec = CurrencyPrec;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTS_ANL_ID")
    public Catalog getCostsAnl() {
        return this.CostsAnl;
    }
    
    public void setCostsAnl(Catalog CostsAnl) {
        this.CostsAnl = CostsAnl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_TYPE_ID")
    public CurrencyRateType getCurRateType() {
        return this.CurRateType;
    }
    
    public void setCurRateType(CurrencyRateType CurRateType) {
        this.CurRateType = CurRateType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_AUTHORITY_ID")
    public CurrencyRateAuthority getCurRateAuthority() {
        return this.CurRateAuthority;
    }
    
    public void setCurRateAuthority(CurrencyRateAuthority CurRateAuthority) {
        this.CurRateAuthority = CurRateAuthority;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BASE_CURRENCY")
    public Currency getBaseCurrency() {
        return this.BaseCurrency;
    }
    
    public void setBaseCurrency(Currency BaseCurrency) {
        this.BaseCurrency = BaseCurrency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NAT_CURRENCY")
    public Currency getNatCurrency() {
        return this.NatCurrency;
    }
    
    public void setNatCurrency(Currency NatCurrency) {
        this.NatCurrency = NatCurrency;
    }

    
    @Column(name="CURRENCY_PREC", columnDefinition="SMALLINT")
    public Short getCurrencyPrec() {
        return this.CurrencyPrec;
    }
    
    public void setCurrencyPrec(Short CurrencyPrec) {
        this.CurrencyPrec = CurrencyPrec;
    }




}


