package com.mg.merp.personnelref.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PersonnelLanguage generated by hbm2java
 */
@Entity
@Table(name = "PREF_PERSONNEL_LANGUAGE")
public class PersonnelLanguage extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Personnel Personnel;

    private SysClient SysClient;

    private LanguageKnowledge LanguageKnowledge;

    private ForeignLanguage ForeignLanguage;

    public PersonnelLanguage() {
    }

    public PersonnelLanguage(Personnel Personnel, ForeignLanguage ForeignLanguage) {
        this.Personnel = Personnel;
        this.ForeignLanguage = ForeignLanguage;
    }

    public PersonnelLanguage(Personnel Personnel, SysClient SysClient, LanguageKnowledge LanguageKnowledge, ForeignLanguage ForeignLanguage) {
        this.Personnel = Personnel;
        this.SysClient = SysClient;
        this.LanguageKnowledge = LanguageKnowledge;
        this.ForeignLanguage = ForeignLanguage;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PREF_PERSONNEL_LANGUAGE_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERSONNEL_ID", nullable = false)
    public Personnel getPersonnel() {
        return this.Personnel;
    }

    public void setPersonnel(Personnel Personnel) {
        this.Personnel = Personnel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LANGUAGE_KNOWLEDGE_ID")
    public LanguageKnowledge getLanguageKnowledge() {
        return this.LanguageKnowledge;
    }

    public void setLanguageKnowledge(LanguageKnowledge LanguageKnowledge) {
        this.LanguageKnowledge = LanguageKnowledge;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FOREIGN_LANGUAGE_ID", nullable = false)
    public ForeignLanguage getForeignLanguage() {
        return this.ForeignLanguage;
    }

    public void setForeignLanguage(ForeignLanguage ForeignLanguage) {
        this.ForeignLanguage = ForeignLanguage;
    }
}

