package com.mg.merp.personnelref.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.OriginalDocument;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PersonnelRecord generated by hbm2java
 */
@Entity
@Table(name = "PREF_PERSONNEL_RECORD")
public class PersonnelRecord extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Personnel Personnel;

    private SysClient SysClient;

    private OriginalDocument OriginalDocument;

    private String Name;

    private String Description;

    public PersonnelRecord() {
    }

    public PersonnelRecord(String Name) {
        this.Name = Name;
    }

    public PersonnelRecord(Personnel Personnel, SysClient SysClient, OriginalDocument OriginalDocument, String Name, String Description) {
        this.Personnel = Personnel;
        this.SysClient = SysClient;
        this.OriginalDocument = OriginalDocument;
        this.Name = Name;
        this.Description = Description;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PREF_PERSONNEL_RECORD_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERSONNEL_ID")
    public Personnel getPersonnel() {
        return this.Personnel;
    }

    public void setPersonnel(Personnel Personnel) {
        this.Personnel = Personnel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORIGINAL_DOCUMENT_ID")
    public OriginalDocument getOriginalDocument() {
        return this.OriginalDocument;
    }

    public void setOriginalDocument(OriginalDocument OriginalDocument) {
        this.OriginalDocument = OriginalDocument;
    }

    @Column(name = "NAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 2048)
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }
}

