package com.mg.merp.personnelref.model;

import com.mg.merp.core.model.SysClient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * PersonnelEducation generated by hbm2java
 */
@Entity
@Table(name = "PREF_PERSONNEL_EDUCATION")
public class PersonnelEducation extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private AdditionalEducationKind AdditionalEducationKind;

    private Speciality Speciality;

    private Personnel Personnel;

    private SysClient SysClient;

    private String InstitutionName;

    private String DiplomaQualification;

    private String DiplomaNumber;

    private Date DiplomaDate;

    private Integer GraduationYear;

    private PrefIsAdditionalEducation IsAdditional;

    public PersonnelEducation() {
    }

    public PersonnelEducation(String InstitutionName) {
        this.InstitutionName = InstitutionName;
    }

    public PersonnelEducation(AdditionalEducationKind AdditionalEducationKind, Speciality Speciality, Personnel Personnel, SysClient SysClient, String InstitutionName, String DiplomaQualification, String DiplomaNumber, Date DiplomaDate, Integer GraduationYear, PrefIsAdditionalEducation IsAdditional) {
        this.AdditionalEducationKind = AdditionalEducationKind;
        this.Speciality = Speciality;
        this.Personnel = Personnel;
        this.SysClient = SysClient;
        this.InstitutionName = InstitutionName;
        this.DiplomaQualification = DiplomaQualification;
        this.DiplomaNumber = DiplomaNumber;
        this.DiplomaDate = DiplomaDate;
        this.GraduationYear = GraduationYear;
        this.IsAdditional = IsAdditional;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PREF_PERS_EDUCATION_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    //$NON-NLS-1$
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ADDITIONAL_EDUCATION_KIND_ID")
    public AdditionalEducationKind getAdditionalEducationKind() {
        return this.AdditionalEducationKind;
    }

    public void setAdditionalEducationKind(AdditionalEducationKind AdditionalEducationKind) {
        this.AdditionalEducationKind = AdditionalEducationKind;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SPECIALITY_ID")
    //$NON-NLS-1$
    @DataItemName("PersonnelRef.Personnel.Speciality")
    public Speciality getSpeciality() {
        return this.Speciality;
    }

    public void setSpeciality(Speciality Speciality) {
        this.Speciality = Speciality;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERSONNEL_ID")
    public Personnel getPersonnel() {
        return this.Personnel;
    }

    public void setPersonnel(Personnel Personnel) {
        this.Personnel = Personnel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "INSTITUTION_NAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    //$NON-NLS-1$
    @DataItemName("PersonnelRef.Personnel.InstitutionName")
    public String getInstitutionName() {
        return this.InstitutionName;
    }

    public void setInstitutionName(String InstitutionName) {
        this.InstitutionName = InstitutionName;
    }

    @Column(name = "DIPLOMA_QUALIFICATION", columnDefinition = "VARCHAR", length = 80)
    //$NON-NLS-1$
    @DataItemName("PersonnelRef.Personnel.DiplomaQualification")
    public String getDiplomaQualification() {
        return this.DiplomaQualification;
    }

    public void setDiplomaQualification(String DiplomaQualification) {
        this.DiplomaQualification = DiplomaQualification;
    }

    @Column(name = "DIPLOMA_NUMBER", columnDefinition = "CHAR", length = 20)
    //$NON-NLS-1$
    @DataItemName("PersonnelRef.Personnel.DiplomaNumber")
    public String getDiplomaNumber() {
        return this.DiplomaNumber;
    }

    public void setDiplomaNumber(String DiplomaNumber) {
        this.DiplomaNumber = DiplomaNumber;
    }

    @Column(name = "DIPLOMA_DATE", columnDefinition = "TIMESTAMP")
    //$NON-NLS-1$
    @DataItemName("PersonnelRef.Personnel.DiplomaDate")
    public Date getDiplomaDate() {
        return this.DiplomaDate;
    }

    public void setDiplomaDate(Date DiplomaDate) {
        this.DiplomaDate = DiplomaDate;
    }

    @Column(name = "GRADUATION_YEAR", columnDefinition = "INTEGER")
    //$NON-NLS-1$
    @DataItemName("PersonnelRef.Personnel.GraduationYear")
    public Integer getGraduationYear() {
        return this.GraduationYear;
    }

    public void setGraduationYear(Integer GraduationYear) {
        this.GraduationYear = GraduationYear;
    }

    @Column(name = "IS_ADDITIONAL", columnDefinition = "SMALLINT")
    public PrefIsAdditionalEducation isAdditional() {
        return this.IsAdditional;
    }

    public void setAdditional(PrefIsAdditionalEducation IsAdditional) {
        this.IsAdditional = IsAdditional;
    }
}

