package com.mg.merp.personnelref.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PfCodeInService generated by hbm2java
 */
@Entity
@Table(name="PREF_PFCODE_IN_SERVICE"
)
public class PfCodeInService extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private ServicePfCode PfCode;
     private SysClient SysClient;
     private PersonnelService PersonnelService;
     private String Comment;

    public PfCodeInService() {
    }

    public PfCodeInService(ServicePfCode PfCode, SysClient SysClient, PersonnelService PersonnelService, String Comment) {
       this.PfCode = PfCode;
       this.SysClient = SysClient;
       this.PersonnelService = PersonnelService;
       this.Comment = Comment;
    }
   
     @SequenceGenerator(name="generator", sequenceName="PREF_PFCODE_IN_SERVICE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PFCODE_ID")
    public ServicePfCode getPfCode() {
        return this.PfCode;
    }
    
    public void setPfCode(ServicePfCode PfCode) {
        this.PfCode = PfCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSONNELSERVICE_ID")
    public PersonnelService getPersonnelService() {
        return this.PersonnelService;
    }
    
    public void setPersonnelService(PersonnelService PersonnelService) {
        this.PersonnelService = PersonnelService;
    }

    
    @Column(name="COMMENT", columnDefinition="VARCHAR", length=256)
    public String getComment() {
        return this.Comment;
    }
    
    public void setComment(String Comment) {
        this.Comment = Comment;
    }




}


