package com.mg.merp.personnelref.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.baiengine.model.Repository;
import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ServiceKind generated by hbm2java
 */
@Entity
@Table(name="PREF_SERVICE_KIND"
)
public class ServiceKind extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private SysClient SysClient;
     private Repository BeginServiceAlg;
     private Repository EndServiceAlg;
     private Repository LengthServiceAlg;
     private String KName;
     private Integer ParentId;
     private String KCode;
     private String FolderTag;
     private Set<PfCodeKindInServiceKind> SetOfPrefPfCodeKindInServiceKind = new HashSet<PfCodeKindInServiceKind>(0);

    public ServiceKind() {
    }

	
    public ServiceKind(String KName, String KCode) {
        this.KName = KName;
        this.KCode = KCode;
    }
    public ServiceKind(SysClient SysClient, Repository BeginServiceAlg, Repository EndServiceAlg, Repository LengthServiceAlg, String KName, Integer ParentId, String KCode, String FolderTag, Set<PfCodeKindInServiceKind> SetOfPrefPfCodeKindInServiceKind) {
       this.SysClient = SysClient;
       this.BeginServiceAlg = BeginServiceAlg;
       this.EndServiceAlg = EndServiceAlg;
       this.LengthServiceAlg = LengthServiceAlg;
       this.KName = KName;
       this.ParentId = ParentId;
       this.KCode = KCode;
       this.FolderTag = FolderTag;
       this.SetOfPrefPfCodeKindInServiceKind = SetOfPrefPfCodeKindInServiceKind;
    }
   
     @SequenceGenerator(name="generator", sequenceName="PREF_SERVICE_KIND_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BEGINSERVICE_ALG_ID")
    public Repository getBeginServiceAlg() {
        return this.BeginServiceAlg;
    }
    
    public void setBeginServiceAlg(Repository BeginServiceAlg) {
        this.BeginServiceAlg = BeginServiceAlg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ENDSERVICE_ALG_ID")
    public Repository getEndServiceAlg() {
        return this.EndServiceAlg;
    }
    
    public void setEndServiceAlg(Repository EndServiceAlg) {
        this.EndServiceAlg = EndServiceAlg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LENGTHSERVICE_ALG_ID")
    public Repository getLengthServiceAlg() {
        return this.LengthServiceAlg;
    }
    
    public void setLengthServiceAlg(Repository LengthServiceAlg) {
        this.LengthServiceAlg = LengthServiceAlg;
    }

    
    @Column(name="KNAME", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getKName() {
        return this.KName;
    }
    
    public void setKName(String KName) {
        this.KName = KName;
    }

    
    @Column(name="PARENT_ID", columnDefinition="INTEGER")
    public Integer getParentId() {
        return this.ParentId;
    }
    
    public void setParentId(Integer ParentId) {
        this.ParentId = ParentId;
    }

    
    @Column(name="KCODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getKCode() {
        return this.KCode;
    }
    
    public void setKCode(String KCode) {
        this.KCode = KCode;
    }

    
    @Column(name="FOLDER_TAG", columnDefinition="VARCHAR", length=80)
    public String getFolderTag() {
        return this.FolderTag;
    }
    
    public void setFolderTag(String FolderTag) {
        this.FolderTag = FolderTag;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ServiceKind")
    public Set<PfCodeKindInServiceKind> getSetOfPrefPfCodeKindInServiceKind() {
        return this.SetOfPrefPfCodeKindInServiceKind;
    }
    
    public void setSetOfPrefPfCodeKindInServiceKind(Set<PfCodeKindInServiceKind> SetOfPrefPfCodeKindInServiceKind) {
        this.SetOfPrefPfCodeKindInServiceKind = SetOfPrefPfCodeKindInServiceKind;
    }




}


