package com.mg.merp.exchange.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImportProcessor generated by hbm2java
 */
@Entity
@Table(name="EXCH_IMPORT"
)
public class ImportProcessor extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Site ExchSite;
     private SysClient SysClient;
     private String BeanName;
     private String Origin;
     private BigDecimal OldKey;
     private BigDecimal NewKey;
     private Integer Packet;
     private Date PacketTime;

    public ImportProcessor() {
    }

	
    public ImportProcessor(Integer Id) {
        this.Id = Id;
    }
    public ImportProcessor(Integer Id, Site ExchSite, SysClient SysClient, String BeanName, String Origin, BigDecimal OldKey, BigDecimal NewKey, Integer Packet, Date PacketTime) {
       this.Id = Id;
       this.ExchSite = ExchSite;
       this.SysClient = SysClient;
       this.BeanName = BeanName;
       this.Origin = Origin;
       this.OldKey = OldKey;
       this.NewKey = NewKey;
       this.Packet = Packet;
       this.PacketTime = PacketTime;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SITE_ID")
    public Site getExchSite() {
        return this.ExchSite;
    }
    
    public void setExchSite(Site ExchSite) {
        this.ExchSite = ExchSite;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="BEAN_NAME", columnDefinition="VARCHAR", length=128)
    public String getBeanName() {
        return this.BeanName;
    }
    
    public void setBeanName(String BeanName) {
        this.BeanName = BeanName;
    }

    
    @Column(name="ORIGIN", columnDefinition="CHAR", length=31)
    public String getOrigin() {
        return this.Origin;
    }
    
    public void setOrigin(String Origin) {
        this.Origin = Origin;
    }

    
    @Column(name="OLD_KEY", columnDefinition="NUMERIC", precision=18, scale=0)
    public BigDecimal getOldKey() {
        return this.OldKey;
    }
    
    public void setOldKey(BigDecimal OldKey) {
        this.OldKey = OldKey;
    }

    
    @Column(name="NEW_KEY", columnDefinition="NUMERIC", precision=18, scale=0)
    public BigDecimal getNewKey() {
        return this.NewKey;
    }
    
    public void setNewKey(BigDecimal NewKey) {
        this.NewKey = NewKey;
    }

    
    @Column(name="PACKET", columnDefinition="INTEGER")
    public Integer getPacket() {
        return this.Packet;
    }
    
    public void setPacket(Integer Packet) {
        this.Packet = Packet;
    }

    
    @Column(name="PACKET_TIME", columnDefinition="TIMESTAMP")
    public Date getPacketTime() {
        return this.PacketTime;
    }
    
    public void setPacketTime(Date PacketTime) {
        this.PacketTime = PacketTime;
    }




}


