package com.mg.merp.exchange.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Table generated by hbm2java
 */
@Entity
@javax.persistence.Table(name="EXCH_TABLE"
)
public class Table extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer ClassId;
     private SysClient SysClient;
     private String TableName;

    public Table() {
    }


    public Table(Integer ClassId) {
        this.ClassId = ClassId;
    }
    public Table(Integer ClassId, SysClient SysClient, String TableName) {
       this.ClassId = ClassId;
       this.SysClient = SysClient;
       this.TableName = TableName;
    }

     @Id


    @Column(name="CLASS_ID", unique=true, columnDefinition="INTEGER")
    public Integer getClassId() {
        return this.ClassId;
    }

    public void setClassId(Integer ClassId) {
        this.ClassId = ClassId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }


    @Column(name="TABLE_NAME", columnDefinition="CHAR", length=31)
    public String getTableName() {
        return this.TableName;
    }

    public void setTableName(String TableName) {
        this.TableName = TableName;
    }




}


