package com.mg.merp.paymentalloc.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DocGroupLink generated by hbm2java
 */
@Entity
@Table(name = "PMA_DOCGROUPLINK")
public class DocGroupLink extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private DocGroup DocGroup;

    private DocType DocType;

    public DocGroupLink() {
    }

    public DocGroupLink(SysClient SysClient, DocGroup DocGroup, DocType DocType) {
        this.SysClient = SysClient;
        this.DocGroup = DocGroup;
        this.DocType = DocType;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PMA_DOCGROUPLINK_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "DOCGROUP_ID")
    public DocGroup getDocGroup() {
        return this.DocGroup;
    }

    public void setDocGroup(DocGroup DocGroup) {
        this.DocGroup = DocGroup;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCTYPE")
    public DocType getDocType() {
        return this.DocType;
    }

    public void setDocType(DocType DocType) {
        this.DocType = DocType;
    }
}

