package com.mg.merp.paymentalloc.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocSpec;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * TransactSpec generated by hbm2java
 */
@Entity
@Table(name = "PMA_TRSPEC")
public class TransactSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private DocSpec DocSpec;

    private SysClient SysClient;

    private TransactHead TrHead;

    private BigDecimal TotalQty;

    private BigDecimal TotalSum;

    private BigDecimal AllocQty;

    private BigDecimal AllocSum;

    private Set<TransactTax> SetOfPmaTrtax = new HashSet<TransactTax>(0);

    public TransactSpec() {
    }

    public TransactSpec(DocSpec DocSpec, SysClient SysClient, TransactHead TrHead, BigDecimal TotalQty, BigDecimal TotalSum, BigDecimal AllocQty, BigDecimal AllocSum, Set<TransactTax> SetOfPmaTrtax) {
        this.DocSpec = DocSpec;
        this.SysClient = SysClient;
        this.TrHead = TrHead;
        this.TotalQty = TotalQty;
        this.TotalSum = TotalSum;
        this.AllocQty = AllocQty;
        this.AllocSum = AllocSum;
        this.SetOfPmaTrtax = SetOfPmaTrtax;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PMA_TRSPEC_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCSPEC_ID")
    public DocSpec getDocSpec() {
        return this.DocSpec;
    }

    public void setDocSpec(DocSpec DocSpec) {
        this.DocSpec = DocSpec;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRHEAD_ID")
    public TransactHead getTrHead() {
        return this.TrHead;
    }

    public void setTrHead(TransactHead TrHead) {
        this.TrHead = TrHead;
    }

    @Column(name = "TOTALQTY", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("PaymentAlloc.TransactSpec.TotalQty")
    public BigDecimal getTotalQty() {
        return this.TotalQty;
    }

    public void setTotalQty(BigDecimal TotalQty) {
        this.TotalQty = TotalQty;
    }

    @Column(name = "TOTALSUM", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("PaymentAlloc.TransactSpec.TotalSum")
    public BigDecimal getTotalSum() {
        return this.TotalSum;
    }

    public void setTotalSum(BigDecimal TotalSum) {
        this.TotalSum = TotalSum;
    }

    @Column(name = "ALLOCQTY", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("PaymentAlloc.TransactSpec.AllocQty")
    public BigDecimal getAllocQty() {
        return this.AllocQty;
    }

    public void setAllocQty(BigDecimal AllocQty) {
        this.AllocQty = AllocQty;
    }

    @Column(name = "ALLOCSUM", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("PaymentAlloc.TransactSpec.AllocSum")
    public BigDecimal getAllocSum() {
        return this.AllocSum;
    }

    public void setAllocSum(BigDecimal AllocSum) {
        this.AllocSum = AllocSum;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "TRSPEC_ID", updatable = false)
    public Set<TransactTax> getSetOfPmaTrtax() {
        return this.SetOfPmaTrtax;
    }

    public void setSetOfPmaTrtax(Set<TransactTax> SetOfPmaTrtax) {
        this.SetOfPmaTrtax = SetOfPmaTrtax;
    }
}

