
INSERT INTO SYSTEMCONFIG (MAJOR_VERSION,MINOR_VERSION,"RELEASE",BASE_CURRENCY,NATIONAL_CURRENCY,USE_ANALITIC_LINK,RECURSE_FOLDER,RECURSE_CATFOLDER,RECURSE_ORGUNIT,DELAYS_ON,CURRENCY_PREC,DEFER_REMNACC,LOG_V1_DOC_DEL,LOG_V1_ROLLBACK,LOG_V1_PARTNER,LOG_V1_CATALOG) VALUES (2,54,0,NULL,NULL,1,1,0,1,1,2,0,0,0,0,0);

INSERT INTO SEC_GROUPS (ID,NAME) VALUES (gen_id(SEC_GROUPS_ID_GEN, 1),'Администраторы');
INSERT INTO SEC_GROUPS (ID,NAME) VALUES (gen_id(SEC_GROUPS_ID_GEN, 1),'SYSTEM');

INSERT INTO SEC_USERS (ID,NAME,FULLNAME,PASSW,ACTIVE_FLAG,SMART_CARD_ONLY,EMAIL,MOBILE,PAGER,USE_REMOTE_PROFILE,USER_TYPE) VALUES (gen_id(SEC_USER_ID_GEN, 1),'ADMIN','Системный администратор','',0,0,'','','',1,1);
INSERT INTO SEC_USERS (ID,NAME,FULLNAME,PASSW,ACTIVE_FLAG,SMART_CARD_ONLY,EMAIL,MOBILE,PAGER,USE_REMOTE_PROFILE,USER_TYPE) VALUES (gen_id(SEC_USER_ID_GEN, 1),'SYSTEM','System','',0,0,'','','',1,0);

INSERT INTO SEC_LINK_USERS_GROUPS (ID,USER_ID,GROUP_ID) VALUES (1,1,1);

INSERT INTO SEC_USER_PROFILE (ID,USER_ID,PROFILE_TYPE) VALUES (gen_id(SEC_USER_PROFILE_ID_GEN, 1),1,0);
