INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (1, 'Создание', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (2, 'Создание на основе', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (3, 'Создание документа на основании текущего', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (4, 'Связать с другим документом', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10004, 'Отработать документ как факт по заказу', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12001, 'Отработка акта выпуска готовой продукции по заказ - наряду на производство', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12002, 'Отработка обратного списания', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12003, 'Отработка по регистру фактической себестоимости', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12004, 'Отработка акта списания потерь по заказ - наряду на производство', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12005, 'Создание актов на списание потерь', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13000, 'Создание записи журнала платежей', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13001, 'Отработка в журнале платежей', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13, 'Создать хозяйственную операцию', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (14, 'Регистрация счета фактуры', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (15, 'Регистрация даты оприходования', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (16, 'Регистрация даты оплаты', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (17, 'Регистрация в книге покупок', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (18, 'Регистрация в книге продаж', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (19, 'Отработка по складу', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (20, 'Электронная подпись', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (21, 'Отработка планируемого движения по складу', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (22, 'Снятие с плана движения по складу', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (23, 'Резервирование по складу', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (24, 'Снятие с резерва по складу', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (25, 'Отработать документ как факт по договору', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (26, 'Отработать документ как план по договору', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (27, 'Собрать комплект', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (28, 'Разобрать комплект', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (29, 'Создать документ на комплектующие', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (30, 'Рассчитать цены в документе на основании данных склада', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (31, 'Отработать в расчетах', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (33, 'Акцептовать счет', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (34, 'Настраиваемый пользователем', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (35, 'Создание финансовой операции', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (36, 'Поставить в план расчетов с партнером', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (37, 'Снять с плана расчетов с партнером', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10001, 'Отработка по складу интерактивная', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (11001, 'Отработать в ЛКС выдачу по норме', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13002, 'Отработка в журнале платежей интерактивная', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (11002, 'Отработать в ЛКС ввод в эксплуатацию', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (11003, 'Отработать в ЛКС вывод из эксплуатации', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10002, 'Отработка по складу с вычислением цены списания', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10003, 'Отработка по складу интерактивная с вычислением цены списания', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (50, 'Создание документа пользовательским алгоритмом', 1);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13100, 'Создание записи реестра обязательств', 0);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13101, 'Подтверждение исполнения обязательства', 1);
