package com.mg.merp.overall.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocType;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Cancellation generated by hbm2java
 */
@Entity
@Table(name="OVR_CANCELLATION"
)
public class Cancellation extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private OvrCardHist OvrCardHist;
     private SysClient SysClient;
     private Date CancellationDate;
     private BigDecimal CurrentCancellationSumma;
     private Integer DocHeadId;
     private DocType DocType;
     private String DocNumber;
     private Date DocDate;
     private String CancellationReason;

    public Cancellation() {
    }

    public Cancellation(OvrCardHist OvrCardHist, SysClient SysClient, Date CancellationDate, BigDecimal CurrentCancellationSumma, Integer DocHeadId, DocType DocType, String DocNumber, Date DocDate, String CancellationReason) {
       this.OvrCardHist = OvrCardHist;
       this.SysClient = SysClient;
       this.CancellationDate = CancellationDate;
       this.CurrentCancellationSumma = CurrentCancellationSumma;
       this.DocHeadId = DocHeadId;
       this.DocType = DocType;
       this.DocNumber = DocNumber;
       this.DocDate = DocDate;
       this.CancellationReason = CancellationReason;
    }
   
     @SequenceGenerator(name="generator", sequenceName="OVR_CANCELLATION_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OVR_CARD_HIST_ID")
    public OvrCardHist getOvrCardHist() {
        return this.OvrCardHist;
    }
    
    public void setOvrCardHist(OvrCardHist OvrCardHist) {
        this.OvrCardHist = OvrCardHist;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CANCELLATION_DATE", columnDefinition="TIMESTAMP")
    public Date getCancellationDate() {
        return this.CancellationDate;
    }
    
    public void setCancellationDate(Date CancellationDate) {
        this.CancellationDate = CancellationDate;
    }

    
    @Column(name="CURRENT_CANCELLATION_SUMMA", columnDefinition="INTEGER")
    public BigDecimal getCurrentCancellationSumma() {
        return this.CurrentCancellationSumma;
    }
    
    public void setCurrentCancellationSumma(BigDecimal CurrentCancellationSumma) {
        this.CurrentCancellationSumma = CurrentCancellationSumma;
    }

    
    @Column(name="DOCHEAD_ID", columnDefinition="INTEGER")
    public Integer getDocHeadId() {
        return this.DocHeadId;
    }
    
    public void setDocHeadId(Integer DocHeadId) {
        this.DocHeadId = DocHeadId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCTYPE")
    public DocType getDocType() {
        return this.DocType;
    }
    
    public void setDocType(DocType DocType) {
        this.DocType = DocType;
    }

    
    @Column(name="DOCNUMBER", columnDefinition="CHAR", length=20)
    public String getDocNumber() {
        return this.DocNumber;
    }
    
    public void setDocNumber(String DocNumber) {
        this.DocNumber = DocNumber;
    }

    
    @Column(name="DOCDATE", columnDefinition="TIMESTAMP")
    public Date getDocDate() {
        return this.DocDate;
    }
    
    public void setDocDate(Date DocDate) {
        this.DocDate = DocDate;
    }

    
    @Column(name="CANCELLATION_REASON", columnDefinition="VARCHAR", length=256)
    public String getCancellationReason() {
        return this.CancellationReason;
    }
    
    public void setCancellationReason(String CancellationReason) {
        this.CancellationReason = CancellationReason;
    }




}


