package com.mg.merp.overall.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * HistStatus generated by hbm2java
 */
@Entity
@Table(name="OVR_HIST_STATUS"
)
public class HistStatus extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private OvrCardHist OvrCardHist;
     private SysClient SysClient;
     private Integer DocHeadId;
     private Integer DocSpecId;
     private String DocType;
     private String DocNumber;
     private Date DocDate;
     private Integer OvrHistStatusId;
     private Date OvrHistStatusDate;

    public HistStatus() {
    }

    public HistStatus(OvrCardHist OvrCardHist, SysClient SysClient, Integer DocHeadId, Integer DocSpecId, String DocType, String DocNumber, Date DocDate, Integer OvrHistStatusId, Date OvrHistStatusDate) {
       this.OvrCardHist = OvrCardHist;
       this.SysClient = SysClient;
       this.DocHeadId = DocHeadId;
       this.DocSpecId = DocSpecId;
       this.DocType = DocType;
       this.DocNumber = DocNumber;
       this.DocDate = DocDate;
       this.OvrHistStatusId = OvrHistStatusId;
       this.OvrHistStatusDate = OvrHistStatusDate;
    }
   
     @SequenceGenerator(name="generator", sequenceName="OVR_HIST_STATUS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OVR_CARD_HIST_ID")
    public OvrCardHist getOvrCardHist() {
        return this.OvrCardHist;
    }
    
    public void setOvrCardHist(OvrCardHist OvrCardHist) {
        this.OvrCardHist = OvrCardHist;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="DOCHEAD_ID", columnDefinition="INTEGER")
    public Integer getDocHeadId() {
        return this.DocHeadId;
    }
    
    public void setDocHeadId(Integer DocHeadId) {
        this.DocHeadId = DocHeadId;
    }

    
    @Column(name="DOCSPEC_ID", columnDefinition="INTEGER")
    public Integer getDocSpecId() {
        return this.DocSpecId;
    }
    
    public void setDocSpecId(Integer DocSpecId) {
        this.DocSpecId = DocSpecId;
    }

    
    @Column(name="DOCTYPE", columnDefinition="CHAR", length=15)
    public String getDocType() {
        return this.DocType;
    }
    
    public void setDocType(String DocType) {
        this.DocType = DocType;
    }

    
    @Column(name="DOCNUMBER", columnDefinition="CHAR", length=20)
    public String getDocNumber() {
        return this.DocNumber;
    }
    
    public void setDocNumber(String DocNumber) {
        this.DocNumber = DocNumber;
    }

    
    @Column(name="DOCDATE", columnDefinition="TIMESTAMP")
    public Date getDocDate() {
        return this.DocDate;
    }
    
    public void setDocDate(Date DocDate) {
        this.DocDate = DocDate;
    }

    
    @Column(name="OVR_HIST_STATUS_ID", columnDefinition="INTEGER")
    public Integer getOvrHistStatusId() {
        return this.OvrHistStatusId;
    }
    
    public void setOvrHistStatusId(Integer OvrHistStatusId) {
        this.OvrHistStatusId = OvrHistStatusId;
    }

    
    @Column(name="OVR_HIST_STATUS_DATE", columnDefinition="DATE")
    public Date getOvrHistStatusDate() {
        return this.OvrHistStatusDate;
    }
    
    public void setOvrHistStatusDate(Date OvrHistStatusDate) {
        this.OvrHistStatusDate = OvrHistStatusDate;
    }




}


