package com.mg.merp.overall.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OvrCardDocumentLink generated by hbm2java
 */
@Entity
@Table(name = "OVR_CARD_DOCUMENT_LINK")
public class OvrCardDocumentLink extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private NormHead OvrNormHead;

    private OvrCard OvrCard;

    private DocHead DocHead;

    private SysClient SysClient;

    private Integer RemoveTypeId;

    public OvrCardDocumentLink() {
    }

    public OvrCardDocumentLink(int Id) {
        this.Id = Id;
    }

    public OvrCardDocumentLink(int Id, NormHead OvrNormHead, OvrCard OvrCard, DocHead DocHead, SysClient SysClient, Integer RemoveTypeId) {
        this.Id = Id;
        this.OvrNormHead = OvrNormHead;
        this.OvrCard = OvrCard;
        this.DocHead = DocHead;
        this.SysClient = SysClient;
        this.RemoveTypeId = RemoveTypeId;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OVR_NORM_HEAD_ID")
    public NormHead getOvrNormHead() {
        return this.OvrNormHead;
    }

    public void setOvrNormHead(NormHead OvrNormHead) {
        this.OvrNormHead = OvrNormHead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OVR_CARD_ID")
    public OvrCard getOvrCard() {
        return this.OvrCard;
    }

    public void setOvrCard(OvrCard OvrCard) {
        this.OvrCard = OvrCard;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCHEAD_ID")
    public DocHead getDocHead() {
        return this.DocHead;
    }

    public void setDocHead(DocHead DocHead) {
        this.DocHead = DocHead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "REMOVE_TYPE_ID", columnDefinition = "INTEGER")
    public Integer getRemoveTypeId() {
        return this.RemoveTypeId;
    }

    public void setRemoveTypeId(Integer RemoveTypeId) {
        this.RemoveTypeId = RemoveTypeId;
    }
}

