package com.mg.merp.overall.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocSpec;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OvrCardHistDocSpecLink generated by hbm2java
 */
@Entity
@Table(name = "OVR_CARD_HIST_DOC_SPEC_LINK")
public class OvrCardHistDocSpecLink extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private OvrCardHist OvrCardHist;

    private DocSpec DocSpec;

    private SysClient SysClient;

    public OvrCardHistDocSpecLink() {
    }

    public OvrCardHistDocSpecLink(Integer Id) {
        this.Id = Id;
    }

    public OvrCardHistDocSpecLink(Integer Id, OvrCardHist OvrCardHist, DocSpec DocSpec, SysClient SysClient) {
        this.Id = Id;
        this.OvrCardHist = OvrCardHist;
        this.DocSpec = DocSpec;
        this.SysClient = SysClient;
    }

    @Id
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OVR_CARD_HIST_ID")
    public OvrCardHist getOvrCardHist() {
        return this.OvrCardHist;
    }

    public void setOvrCardHist(OvrCardHist OvrCardHist) {
        this.OvrCardHist = OvrCardHist;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCSPEC_ID")
    public DocSpec getDocSpec() {
        return this.DocSpec;
    }

    public void setDocSpec(DocSpec DocSpec) {
        this.DocSpec = DocSpec;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }
}

