package com.mg.merp.overall.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Size generated by hbm2java
 */
@Entity
@Table(name = "OVR_SIZE")
public class Size extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private OvrCard OvrCard;

    private SysClient SysClient;

    private CatalogGroupsType CatalogGroupsTypeId;

    private String ClothesSize;

    private String ShoesSize;

    private String HatSize;

    private String GasMaskSize;

    private String RespiratorSize;

    private String MittensSize;

    private String GlovesSize;

    public Size() {
    }

    public Size(OvrCard OvrCard, SysClient SysClient, CatalogGroupsType CatalogGroupsTypeId, String ClothesSize, String ShoesSize, String HatSize, String GasMaskSize, String RespiratorSize, String MittensSize, String GlovesSize) {
        this.OvrCard = OvrCard;
        this.SysClient = SysClient;
        this.CatalogGroupsTypeId = CatalogGroupsTypeId;
        this.ClothesSize = ClothesSize;
        this.ShoesSize = ShoesSize;
        this.HatSize = HatSize;
        this.GasMaskSize = GasMaskSize;
        this.RespiratorSize = RespiratorSize;
        this.MittensSize = MittensSize;
        this.GlovesSize = GlovesSize;
    }

    @SequenceGenerator(name = "generator", sequenceName = "OVR_SIZE_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OVR_CARD_ID")
    public OvrCard getOvrCard() {
        return this.OvrCard;
    }

    public void setOvrCard(OvrCard OvrCard) {
        this.OvrCard = OvrCard;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CATALOG_GROUPS_TYPE_ID", columnDefinition = "INTEGER")
    public CatalogGroupsType getCatalogGroupsTypeId() {
        return this.CatalogGroupsTypeId;
    }

    public void setCatalogGroupsTypeId(CatalogGroupsType CatalogGroupsTypeId) {
        this.CatalogGroupsTypeId = CatalogGroupsTypeId;
    }

    @Column(name = "CLOTHES_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getClothesSize() {
        return this.ClothesSize;
    }

    public void setClothesSize(String ClothesSize) {
        this.ClothesSize = ClothesSize;
    }

    @Column(name = "SHOES_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getShoesSize() {
        return this.ShoesSize;
    }

    public void setShoesSize(String ShoesSize) {
        this.ShoesSize = ShoesSize;
    }

    @Column(name = "HAT_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getHatSize() {
        return this.HatSize;
    }

    public void setHatSize(String HatSize) {
        this.HatSize = HatSize;
    }

    @Column(name = "GAS_MASK_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getGasMaskSize() {
        return this.GasMaskSize;
    }

    public void setGasMaskSize(String GasMaskSize) {
        this.GasMaskSize = GasMaskSize;
    }

    @Column(name = "RESPIRATOR_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getRespiratorSize() {
        return this.RespiratorSize;
    }

    public void setRespiratorSize(String RespiratorSize) {
        this.RespiratorSize = RespiratorSize;
    }

    @Column(name = "MITTENS_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getMittensSize() {
        return this.MittensSize;
    }

    public void setMittensSize(String MittensSize) {
        this.MittensSize = MittensSize;
    }

    @Column(name = "GLOVES_SIZE", columnDefinition = "VARCHAR", length = 15)
    public String getGlovesSize() {
        return this.GlovesSize;
    }

    public void setGlovesSize(String GlovesSize) {
        this.GlovesSize = GlovesSize;
    }
}

