package com.mg.merp.account.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Contractor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccBatch generated by hbm2java
 */
@Entity
@Table(name="ACCBATCH"
)
public class AccBatch extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private AccPlan AccPlan;
     private SysClient SysClient;
     private Contractor Contractor;
     private Date InComeDate;
     private BigDecimal InComeCostNat;
     private BigDecimal InComeCostCur;
     private Integer CatalogId;
     private Short DocSection;
     private Integer DocId;
     private String DocType;
     private String DocNumber;
     private Date DocDate;
     private BigDecimal BeginQuan;
     private BigDecimal EndQuan;
     private Integer AnlPlan1Id;
     private Integer AnlPlan2Id;
     private Integer AnlPlan3Id;
     private Integer AnlPlan4Id;
     private Integer AnlPlan5Id;
     private Set<AccBatchHistory> SetOfAccBatchHistory = new HashSet<AccBatchHistory>(0);

    public AccBatch() {
    }

	
    public AccBatch(Integer Id, Date InComeDate, BigDecimal InComeCostNat, BigDecimal BeginQuan) {
        this.Id = Id;
        this.InComeDate = InComeDate;
        this.InComeCostNat = InComeCostNat;
        this.BeginQuan = BeginQuan;
    }
    public AccBatch(Integer Id, AccPlan AccPlan, SysClient SysClient, Contractor Contractor, Date InComeDate, BigDecimal InComeCostNat, BigDecimal InComeCostCur, Integer CatalogId, Short DocSection, Integer DocId, String DocType, String DocNumber, Date DocDate, BigDecimal BeginQuan, BigDecimal EndQuan, Integer AnlPlan1Id, Integer AnlPlan2Id, Integer AnlPlan3Id, Integer AnlPlan4Id, Integer AnlPlan5Id, Set<AccBatchHistory> SetOfAccBatchHistory) {
       this.Id = Id;
       this.AccPlan = AccPlan;
       this.SysClient = SysClient;
       this.Contractor = Contractor;
       this.InComeDate = InComeDate;
       this.InComeCostNat = InComeCostNat;
       this.InComeCostCur = InComeCostCur;
       this.CatalogId = CatalogId;
       this.DocSection = DocSection;
       this.DocId = DocId;
       this.DocType = DocType;
       this.DocNumber = DocNumber;
       this.DocDate = DocDate;
       this.BeginQuan = BeginQuan;
       this.EndQuan = EndQuan;
       this.AnlPlan1Id = AnlPlan1Id;
       this.AnlPlan2Id = AnlPlan2Id;
       this.AnlPlan3Id = AnlPlan3Id;
       this.AnlPlan4Id = AnlPlan4Id;
       this.AnlPlan5Id = AnlPlan5Id;
       this.SetOfAccBatchHistory = SetOfAccBatchHistory;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACC_ID")
    public AccPlan getAccPlan() {
        return this.AccPlan;
    }
    
    public void setAccPlan(AccPlan AccPlan) {
        this.AccPlan = AccPlan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACTOR_ID")
    public Contractor getContractor() {
        return this.Contractor;
    }
    
    public void setContractor(Contractor Contractor) {
        this.Contractor = Contractor;
    }

    
    @Column(name="INCOMEDATE", nullable=false, columnDefinition="TIMESTAMP")
    public Date getInComeDate() {
        return this.InComeDate;
    }
    
    public void setInComeDate(Date InComeDate) {
        this.InComeDate = InComeDate;
    }

    
    @Column(name="INCOMECOSTNAT", nullable=false, columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getInComeCostNat() {
        return this.InComeCostNat;
    }
    
    public void setInComeCostNat(BigDecimal InComeCostNat) {
        this.InComeCostNat = InComeCostNat;
    }

    
    @Column(name="INCOMECOSTCUR", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getInComeCostCur() {
        return this.InComeCostCur;
    }
    
    public void setInComeCostCur(BigDecimal InComeCostCur) {
        this.InComeCostCur = InComeCostCur;
    }

    
    @Column(name="CATALOG_ID", columnDefinition="INTEGER")
    public Integer getCatalogId() {
        return this.CatalogId;
    }
    
    public void setCatalogId(Integer CatalogId) {
        this.CatalogId = CatalogId;
    }

    
    @Column(name="DOCSECTION", columnDefinition="SMALLINT")
    public Short getDocSection() {
        return this.DocSection;
    }
    
    public void setDocSection(Short DocSection) {
        this.DocSection = DocSection;
    }

    
    @Column(name="DOC_ID", columnDefinition="INTEGER")
    public Integer getDocId() {
        return this.DocId;
    }
    
    public void setDocId(Integer DocId) {
        this.DocId = DocId;
    }

    
    @Column(name="DOCTYPE", columnDefinition="CHAR", length=15)
    public String getDocType() {
        return this.DocType;
    }
    
    public void setDocType(String DocType) {
        this.DocType = DocType;
    }

    
    @Column(name="DOCNUMBER", columnDefinition="CHAR", length=20)
    public String getDocNumber() {
        return this.DocNumber;
    }
    
    public void setDocNumber(String DocNumber) {
        this.DocNumber = DocNumber;
    }

    
    @Column(name="DOCDATE", columnDefinition="TIMESTAMP")
    public Date getDocDate() {
        return this.DocDate;
    }
    
    public void setDocDate(Date DocDate) {
        this.DocDate = DocDate;
    }

    
    @Column(name="BEGINQUAN", nullable=false, columnDefinition="NUMERIC", precision=15, scale=3)
    public BigDecimal getBeginQuan() {
        return this.BeginQuan;
    }
    
    public void setBeginQuan(BigDecimal BeginQuan) {
        this.BeginQuan = BeginQuan;
    }

    
    @Column(name="ENDQUAN", columnDefinition="NUMERIC", precision=15, scale=3)
    public BigDecimal getEndQuan() {
        return this.EndQuan;
    }
    
    public void setEndQuan(BigDecimal EndQuan) {
        this.EndQuan = EndQuan;
    }

    
    @Column(name="ANLPLAN1_ID", columnDefinition="INTEGER")
    public Integer getAnlPlan1Id() {
        return this.AnlPlan1Id;
    }
    
    public void setAnlPlan1Id(Integer AnlPlan1Id) {
        this.AnlPlan1Id = AnlPlan1Id;
    }

    
    @Column(name="ANLPLAN2_ID", columnDefinition="INTEGER")
    public Integer getAnlPlan2Id() {
        return this.AnlPlan2Id;
    }
    
    public void setAnlPlan2Id(Integer AnlPlan2Id) {
        this.AnlPlan2Id = AnlPlan2Id;
    }

    
    @Column(name="ANLPLAN3_ID", columnDefinition="INTEGER")
    public Integer getAnlPlan3Id() {
        return this.AnlPlan3Id;
    }
    
    public void setAnlPlan3Id(Integer AnlPlan3Id) {
        this.AnlPlan3Id = AnlPlan3Id;
    }

    
    @Column(name="ANLPLAN4_ID", columnDefinition="INTEGER")
    public Integer getAnlPlan4Id() {
        return this.AnlPlan4Id;
    }
    
    public void setAnlPlan4Id(Integer AnlPlan4Id) {
        this.AnlPlan4Id = AnlPlan4Id;
    }

    
    @Column(name="ANLPLAN5_ID", columnDefinition="INTEGER")
    public Integer getAnlPlan5Id() {
        return this.AnlPlan5Id;
    }
    
    public void setAnlPlan5Id(Integer AnlPlan5Id) {
        this.AnlPlan5Id = AnlPlan5Id;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="AccBatch")
    public Set<AccBatchHistory> getSetOfAccBatchHistory() {
        return this.SetOfAccBatchHistory;
    }
    
    public void setSetOfAccBatchHistory(Set<AccBatchHistory> SetOfAccBatchHistory) {
        this.SetOfAccBatchHistory = SetOfAccBatchHistory;
    }




}


