package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AccGroup generated by hbm2java
 */
@Entity
@Table(name = "ACC_ACCGROUP")
@DataItemName("Account.AccGroup")
public class AccGroup extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private SysClient SysClient;

    private AccKind AccKind;

    private String GCode;

    private String GName;

    private Integer MinUsagePeriod;

    private Integer MaxUsagePeriod;

    public AccGroup() {
    }

    public AccGroup(String GName) {
        this.GName = GName;
    }

    public AccGroup(SysClient SysClient, AccKind AccKind, String GCode, String GName, Integer MinUsagePeriod, Integer MaxUsagePeriod) {
        this.SysClient = SysClient;
        this.AccKind = AccKind;
        this.GCode = GCode;
        this.GName = GName;
        this.MinUsagePeriod = MinUsagePeriod;
        this.MaxUsagePeriod = MaxUsagePeriod;
    }

    @SequenceGenerator(name = "generator", sequenceName = "ACC_ACCGROUP_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCKIND_ID")
    public AccKind getAccKind() {
        return this.AccKind;
    }

    public void setAccKind(AccKind AccKind) {
        this.AccKind = AccKind;
    }

    @Column(name = "GCODE", columnDefinition = "CHAR", length = 20)
    @DataItemName("Account.AccGroup.GCode")
    public String getGCode() {
        return this.GCode;
    }

    public void setGCode(String GCode) {
        this.GCode = GCode;
    }

    @Column(name = "GNAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Account.AccGroup.GName")
    public String getGName() {
        return this.GName;
    }

    public void setGName(String GName) {
        this.GName = GName;
    }

    @Column(name = "MIN_USAGEPERIOD", columnDefinition = "INTEGER")
    @DataItemName("Account.AccGroup.MinUsagePeriod")
    public Integer getMinUsagePeriod() {
        return this.MinUsagePeriod;
    }

    public void setMinUsagePeriod(Integer MinUsagePeriod) {
        this.MinUsagePeriod = MinUsagePeriod;
    }

    @Column(name = "MAX_USAGEPERIOD", columnDefinition = "INTEGER")
    @DataItemName("Account.AccGroup.MaxUsagePeriod")
    public Integer getMaxUsagePeriod() {
        return this.MaxUsagePeriod;
    }

    public void setMaxUsagePeriod(Integer MaxUsagePeriod) {
        this.MaxUsagePeriod = MaxUsagePeriod;
    }
}

