package com.mg.merp.account.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CodeAmor generated by hbm2java
 */
@Entity
@Table(name="CODEAMOR"
)
public class CodeAmor extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private String UpCode;
     private SysClient SysClient;
     private String Code;
     private String CaName;

    public CodeAmor() {
    }

	
    public CodeAmor(String UpCode, String Code) {
        this.UpCode = UpCode;
        this.Code = Code;
    }
    public CodeAmor(String UpCode, SysClient SysClient, String Code, String CaName) {
       this.UpCode = UpCode;
       this.SysClient = SysClient;
       this.Code = Code;
       this.CaName = CaName;
    }
   
     @Id 

    
    @Column(name="UPCODE", unique=true, nullable=false, columnDefinition="CHAR", length=20)
    public String getUpCode() {
        return this.UpCode;
    }
    
    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="CANAME", columnDefinition="VARCHAR", length=80)
    public String getCaName() {
        return this.CaName;
    }
    
    public void setCaName(String CaName) {
        this.CaName = CaName;
    }




}


