package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Catalog;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import com.mg.framework.api.annotations.DataItemName;

/**
 * EconomicSpec generated by hbm2java
 */
@Entity
@Table(name = "ECONOMICSPEC")
public class EconomicSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private EconomicSpecFeature Feature1;

    private AccBatchHistory AccBatchHistoryDb;

    private AccBatchHistory AccBatchHistoryKt;

    private AccPlan AccKt;

    private RemnAnl RemnAnlDb;

    private AnlPlan AnlKt3;

    private EconomicSpecFeature Feature4;

    private RemnDbKt RemnDb;

    private AnlPlan AnlDb5;

    private RemnVal RemnValDb;

    private AnlPlan AnlKt1;

    private RemnAcc RemnAccDb;

    private RemnAcc RemnAccKt;

    private Catalog Catalog;

    private EconomicSpecFeature Feature2;

    private RemnVal RemnValKt;

    private AnlPlan AnlKt2;

    private AnlPlan AnlDb2;

    private EconomicSpecFeature Feature3;

    private RemnAnl RemnAnlKt;

    private EconomicOper EconomicOper;

    private SysClient SysClient;

    private RemnDbKt RemnKt;

    private AnlPlan AnlDb3;

    private AnlPlan AnlKt5;

    private AnlPlan AnlDb4;

    private AnlPlan AnlDb1;

    private AccPlan AccDb;

    private EconomicSpecFeature Feature5;

    private AccBatch AccBatchDb;

    private AccBatch AccBatchKt;

    private AnlPlan AnlKt4;

    private BigDecimal Quantity;

    private BigDecimal SummaNat;

    private BigDecimal SummaCur;

    private BigDecimal CurCource;

    @Transient
    private boolean isBulkOperation;

    public EconomicSpec() {
    }

    public EconomicSpec(EconomicSpecFeature Feature1, AccBatchHistory AccBatchHistoryDb, AccBatchHistory AccBatchHistoryKt, AccPlan AccKt, RemnAnl RemnAnlDb, AnlPlan AnlKt3, EconomicSpecFeature Feature4, RemnDbKt RemnDb, AnlPlan AnlDb5, RemnVal RemnValDb, AnlPlan AnlKt1, RemnAcc RemnAccDb, RemnAcc RemnAccKt, Catalog Catalog, EconomicSpecFeature Feature2, RemnVal RemnValKt, AnlPlan AnlKt2, AnlPlan AnlDb2, EconomicSpecFeature Feature3, RemnAnl RemnAnlKt, EconomicOper EconomicOper, SysClient SysClient, RemnDbKt RemnKt, AnlPlan AnlDb3, AnlPlan AnlKt5, AnlPlan AnlDb4, AnlPlan AnlDb1, AccPlan AccDb, EconomicSpecFeature Feature5, AccBatch AccBatchDb, AccBatch AccBatchKt, AnlPlan AnlKt4, BigDecimal Quantity, BigDecimal SummaNat, BigDecimal SummaCur, BigDecimal CurCource) {
        this.Feature1 = Feature1;
        this.AccBatchHistoryDb = AccBatchHistoryDb;
        this.AccBatchHistoryKt = AccBatchHistoryKt;
        this.AccKt = AccKt;
        this.RemnAnlDb = RemnAnlDb;
        this.AnlKt3 = AnlKt3;
        this.Feature4 = Feature4;
        this.RemnDb = RemnDb;
        this.AnlDb5 = AnlDb5;
        this.RemnValDb = RemnValDb;
        this.AnlKt1 = AnlKt1;
        this.RemnAccDb = RemnAccDb;
        this.RemnAccKt = RemnAccKt;
        this.Catalog = Catalog;
        this.Feature2 = Feature2;
        this.RemnValKt = RemnValKt;
        this.AnlKt2 = AnlKt2;
        this.AnlDb2 = AnlDb2;
        this.Feature3 = Feature3;
        this.RemnAnlKt = RemnAnlKt;
        this.EconomicOper = EconomicOper;
        this.SysClient = SysClient;
        this.RemnKt = RemnKt;
        this.AnlDb3 = AnlDb3;
        this.AnlKt5 = AnlKt5;
        this.AnlDb4 = AnlDb4;
        this.AnlDb1 = AnlDb1;
        this.AccDb = AccDb;
        this.Feature5 = Feature5;
        this.AccBatchDb = AccBatchDb;
        this.AccBatchKt = AccBatchKt;
        this.AnlKt4 = AnlKt4;
        this.Quantity = Quantity;
        this.SummaNat = SummaNat;
        this.SummaCur = SummaCur;
        this.CurCource = CurCource;
    }

    @SequenceGenerator(name = "generator", sequenceName = "ECONOMICSPEC_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEATURE1_ID")
    @DataItemName("Account.EconSpec.Feature1")
    public EconomicSpecFeature getFeature1() {
        return this.Feature1;
    }

    public void setFeature1(EconomicSpecFeature Feature1) {
        this.Feature1 = Feature1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCBATCHHISTORYDB_ID")
    public AccBatchHistory getAccBatchHistoryDb() {
        return this.AccBatchHistoryDb;
    }

    public void setAccBatchHistoryDb(AccBatchHistory AccBatchHistoryDb) {
        this.AccBatchHistoryDb = AccBatchHistoryDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCBATCHHISTORYKT_ID")
    public AccBatchHistory getAccBatchHistoryKt() {
        return this.AccBatchHistoryKt;
    }

    public void setAccBatchHistoryKt(AccBatchHistory AccBatchHistoryKt) {
        this.AccBatchHistoryKt = AccBatchHistoryKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCKT_ID")
    @DataItemName("Account.EconSpec.AccKt")
    public AccPlan getAccKt() {
        return this.AccKt;
    }

    public void setAccKt(AccPlan AccKt) {
        this.AccKt = AccKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNANLDB_ID")
    public RemnAnl getRemnAnlDb() {
        return this.RemnAnlDb;
    }

    public void setRemnAnlDb(RemnAnl RemnAnlDb) {
        this.RemnAnlDb = RemnAnlDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLKT3_ID")
    @DataItemName("Account.EconSpec.AnlKt3")
    public AnlPlan getAnlKt3() {
        return this.AnlKt3;
    }

    public void setAnlKt3(AnlPlan AnlKt3) {
        this.AnlKt3 = AnlKt3;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEATURE4_ID")
    @DataItemName("Account.EconSpec.Feature4")
    public EconomicSpecFeature getFeature4() {
        return this.Feature4;
    }

    public void setFeature4(EconomicSpecFeature Feature4) {
        this.Feature4 = Feature4;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNDB_ID")
    public RemnDbKt getRemnDb() {
        return this.RemnDb;
    }

    public void setRemnDb(RemnDbKt RemnDb) {
        this.RemnDb = RemnDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLDB5_ID")
    @DataItemName("Account.EconSpec.AnlDb5")
    public AnlPlan getAnlDb5() {
        return this.AnlDb5;
    }

    public void setAnlDb5(AnlPlan AnlDb5) {
        this.AnlDb5 = AnlDb5;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNVALDB_ID")
    public RemnVal getRemnValDb() {
        return this.RemnValDb;
    }

    public void setRemnValDb(RemnVal RemnValDb) {
        this.RemnValDb = RemnValDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLKT1_ID")
    @DataItemName("Account.EconSpec.AnlKt1")
    public AnlPlan getAnlKt1() {
        return this.AnlKt1;
    }

    public void setAnlKt1(AnlPlan AnlKt1) {
        this.AnlKt1 = AnlKt1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNACCDB_ID")
    public RemnAcc getRemnAccDb() {
        return this.RemnAccDb;
    }

    public void setRemnAccDb(RemnAcc RemnAccDb) {
        this.RemnAccDb = RemnAccDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNACCKT_ID")
    public RemnAcc getRemnAccKt() {
        return this.RemnAccKt;
    }

    public void setRemnAccKt(RemnAcc RemnAccKt) {
        this.RemnAccKt = RemnAccKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATALOG_ID")
    public Catalog getCatalog() {
        return this.Catalog;
    }

    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEATURE2_ID")
    @DataItemName("Account.EconSpec.Feature2")
    public EconomicSpecFeature getFeature2() {
        return this.Feature2;
    }

    public void setFeature2(EconomicSpecFeature Feature2) {
        this.Feature2 = Feature2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNVALKT_ID")
    public RemnVal getRemnValKt() {
        return this.RemnValKt;
    }

    public void setRemnValKt(RemnVal RemnValKt) {
        this.RemnValKt = RemnValKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLKT2_ID")
    @DataItemName("Account.EconSpec.AnlKt2")
    public AnlPlan getAnlKt2() {
        return this.AnlKt2;
    }

    public void setAnlKt2(AnlPlan AnlKt2) {
        this.AnlKt2 = AnlKt2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLDB2_ID")
    @DataItemName("Account.EconSpec.AnlDb2")
    public AnlPlan getAnlDb2() {
        return this.AnlDb2;
    }

    public void setAnlDb2(AnlPlan AnlDb2) {
        this.AnlDb2 = AnlDb2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEATURE3_ID")
    @DataItemName("Account.EconSpec.Feature3")
    public EconomicSpecFeature getFeature3() {
        return this.Feature3;
    }

    public void setFeature3(EconomicSpecFeature Feature3) {
        this.Feature3 = Feature3;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNANLKT_ID")
    public RemnAnl getRemnAnlKt() {
        return this.RemnAnlKt;
    }

    public void setRemnAnlKt(RemnAnl RemnAnlKt) {
        this.RemnAnlKt = RemnAnlKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ECONOMICOPER_ID")
    public EconomicOper getEconomicOper() {
        return this.EconomicOper;
    }

    public void setEconomicOper(EconomicOper EconomicOper) {
        this.EconomicOper = EconomicOper;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REMNKT_ID")
    public RemnDbKt getRemnKt() {
        return this.RemnKt;
    }

    public void setRemnKt(RemnDbKt RemnKt) {
        this.RemnKt = RemnKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLDB3_ID")
    @DataItemName("Account.EconSpec.AnlDb3")
    public AnlPlan getAnlDb3() {
        return this.AnlDb3;
    }

    public void setAnlDb3(AnlPlan AnlDb3) {
        this.AnlDb3 = AnlDb3;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLKT5_ID")
    @DataItemName("Account.EconSpec.AnlKt5")
    public AnlPlan getAnlKt5() {
        return this.AnlKt5;
    }

    public void setAnlKt5(AnlPlan AnlKt5) {
        this.AnlKt5 = AnlKt5;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLDB4_ID")
    @DataItemName("Account.EconSpec.AnlDb4")
    public AnlPlan getAnlDb4() {
        return this.AnlDb4;
    }

    public void setAnlDb4(AnlPlan AnlDb4) {
        this.AnlDb4 = AnlDb4;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLDB1_ID")
    @DataItemName("Account.EconSpec.AnlDb1")
    public AnlPlan getAnlDb1() {
        return this.AnlDb1;
    }

    public void setAnlDb1(AnlPlan AnlDb1) {
        this.AnlDb1 = AnlDb1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCDB_ID")
    @DataItemName("Account.EconSpec.AccDb")
    public AccPlan getAccDb() {
        return this.AccDb;
    }

    public void setAccDb(AccPlan AccDb) {
        this.AccDb = AccDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEATURE5_ID")
    @DataItemName("Account.EconSpec.Feature5")
    public EconomicSpecFeature getFeature5() {
        return this.Feature5;
    }

    public void setFeature5(EconomicSpecFeature Feature5) {
        this.Feature5 = Feature5;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCBATCHDB_ID")
    @DataItemName("Account.EconSpec.AccBatchDb")
    public AccBatch getAccBatchDb() {
        return this.AccBatchDb;
    }

    public void setAccBatchDb(AccBatch AccBatchDb) {
        this.AccBatchDb = AccBatchDb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCBATCHKT_ID")
    @DataItemName("Account.EconSpec.AccBatchKt")
    public AccBatch getAccBatchKt() {
        return this.AccBatchKt;
    }

    public void setAccBatchKt(AccBatch AccBatchKt) {
        this.AccBatchKt = AccBatchKt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLKT4_ID")
    @DataItemName("Account.EconSpec.AnlKt4")
    public AnlPlan getAnlKt4() {
        return this.AnlKt4;
    }

    public void setAnlKt4(AnlPlan AnlKt4) {
        this.AnlKt4 = AnlKt4;
    }

    @Column(name = "QUANTITY", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Account.EconSpec.Quantity")
    public BigDecimal getQuantity() {
        return this.Quantity;
    }

    public void setQuantity(BigDecimal Quantity) {
        this.Quantity = Quantity;
    }

    @Column(name = "SUMMANAT", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.EconSpec.SummaNat")
    public BigDecimal getSummaNat() {
        return this.SummaNat;
    }

    public void setSummaNat(BigDecimal SummaNat) {
        this.SummaNat = SummaNat;
    }

    @Column(name = "SUMMACUR", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.EconSpec.SummaCur")
    public BigDecimal getSummaCur() {
        return this.SummaCur;
    }

    public void setSummaCur(BigDecimal SummaCur) {
        this.SummaCur = SummaCur;
    }

    @Column(name = "CURCOURCE", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("Account.EconSpec.CurCource")
    public BigDecimal getCurCource() {
        return this.CurCource;
    }

    public void setCurCource(BigDecimal CurCource) {
        this.CurCource = CurCource;
    }

    public boolean isBulkOperation() {
        return isBulkOperation;
    }

    public void setBulkOperation(boolean isBulkOperation) {
        this.isBulkOperation = isBulkOperation;
    }
}

