package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSpec;
import com.mg.merp.document.model.DocumentSpecSerialNum;
import com.mg.merp.document.model.DocumentSpecTax;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Country;
import com.mg.merp.reference.model.CustomsDeclaration;
import com.mg.merp.reference.model.Measure;
import com.mg.merp.reference.model.PriceListSpec;
import com.mg.merp.reference.model.TaxGroup;
import com.mg.merp.reference.model.TimePeriodKind;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InternalInvoiceSpec generated by hbm2java
 */
@Entity
@Table(name = "INTERNALINVOICESPEC")
public class InternalInvoiceSpec extends com.mg.merp.document.model.DocSpec implements java.io.Serializable {

    private BigDecimal RequestQuan;

    private BigDecimal RequestSumma;

    public InternalInvoiceSpec() {
    }

    public InternalInvoiceSpec(TimePeriodKind ShelfLifeMeas) {
        super(ShelfLifeMeas);
    }

    public InternalInvoiceSpec(DocSpec OrderSpec, Catalog Catalog, TaxGroup TaxGroup, Contractor DstMol, Contractor SrcMol, PriceListSpec PriceListSpec, DocHead DocHead, Measure Measure2, SysClient SysClient, Contractor DstStock, Measure Measure1, Contractor SrcStock, BigDecimal Quantity, BigDecimal Price, BigDecimal Summa, BigDecimal Price1, BigDecimal Summa1, BigDecimal Weight, BigDecimal Volume, Date BestBefore, BigDecimal ShelfLife, TimePeriodKind ShelfLifeMeas, Date ProductionDate, BigDecimal Quantity2, String Comment, Contractor Contractor, String UNID, CustomsDeclaration CustomsDeclaration, Country CountryOfOrigin, Set<DocumentSpecTax> Taxes, Set<DocumentSpecSerialNum> SerialNumbers, BigDecimal RequestQuan, BigDecimal RequestSumma) {
        super(OrderSpec, Catalog, TaxGroup, DstMol, SrcMol, PriceListSpec, DocHead, Measure2, SysClient, DstStock, Measure1, SrcStock, Quantity, Price, Summa, Price1, Summa1, Weight, Volume, BestBefore, ShelfLife, ShelfLifeMeas, ProductionDate, Quantity2, Comment, Contractor, UNID, CustomsDeclaration, CountryOfOrigin, Taxes, SerialNumbers);
        this.RequestQuan = RequestQuan;
        this.RequestSumma = RequestSumma;
    }

    @Column(name = "REQUESTQUAN", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Account.InvInvoice.RequestQuan")
    public BigDecimal getRequestQuan() {
        return this.RequestQuan;
    }

    public void setRequestQuan(BigDecimal RequestQuan) {
        this.RequestQuan = RequestQuan;
    }

    @Column(name = "REQUESTSUMMA", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.InvInvoice.RequestSumma")
    public BigDecimal getRequestSumma() {
        return this.RequestSumma;
    }

    public void setRequestSumma(BigDecimal RequestSumma) {
        this.RequestSumma = RequestSumma;
    }
}

