package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHeadModel;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Measure;
import com.mg.merp.reference.model.PriceListSpec;
import com.mg.merp.reference.model.TaxGroup;
import com.mg.merp.reference.model.TimePeriodKind;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InternalInvoiceSpecModel generated by hbm2java
 */
@Entity
@Table(name = "INTERNALINVOICESPECMODEL")
public class InternalInvoiceSpecModel extends com.mg.merp.document.model.DocSpecModel implements java.io.Serializable {

    private BigDecimal RequestQuan;

    private BigDecimal RequestSumma;

    public InternalInvoiceSpecModel() {
    }

    public InternalInvoiceSpecModel(TimePeriodKind ShelfLifeMeas) {
        super(ShelfLifeMeas);
    }

    public InternalInvoiceSpecModel(Catalog Catalog, Contractor DstMol, Contractor SrcMol, DocHeadModel DocHeadModel, Measure Measure2, SysClient SysClient, Contractor DstStock, Measure Measure1, Contractor SrcStock, PriceListSpec PriceListSpec, BigDecimal Quantity, BigDecimal Price, BigDecimal Summa, BigDecimal Price1, BigDecimal Summa1, BigDecimal Weight, BigDecimal Volume, Date BestBefore, TaxGroup TaxGroup, Date ProductionDate, BigDecimal ShelfLife, TimePeriodKind ShelfLifeMeas, BigDecimal Quantity2, String Comment, Contractor Contractor, BigDecimal RequestQuan, BigDecimal RequestSumma) {
        super(Catalog, DstMol, SrcMol, DocHeadModel, Measure2, SysClient, DstStock, Measure1, SrcStock, PriceListSpec, Quantity, Price, Summa, Price1, Summa1, Weight, Volume, BestBefore, TaxGroup, ProductionDate, ShelfLife, ShelfLifeMeas, Quantity2, Comment, Contractor);
        this.RequestQuan = RequestQuan;
        this.RequestSumma = RequestSumma;
    }

    @Column(name = "REQUESTQUAN", columnDefinition = "NUMERIC", precision = 15, scale = 3)
    @DataItemName("Account.InvInvoice.RequestQuan")
    public BigDecimal getRequestQuan() {
        return this.RequestQuan;
    }

    public void setRequestQuan(BigDecimal RequestQuan) {
        this.RequestQuan = RequestQuan;
    }

    @Column(name = "REQUESTSUMMA", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.InvInvoice.RequestSumma")
    public BigDecimal getRequestSumma() {
        return this.RequestSumma;
    }

    public void setRequestSumma(BigDecimal RequestSumma) {
        this.RequestSumma = RequestSumma;
    }
}

