package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.MonthOfYear;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.Formula;

/**
 * InvProduction generated by hbm2java
 */
@Entity
@Table(name = "ACC_INVPRODUCTION")
public class InvProduction extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private InvHead AccInvHead;

    private SysClient SysClient;

    private Integer AMonth;

    private Double Production;

    private MonthOfYear QMonth;

    public InvProduction() {
    }

    public InvProduction(InvHead AccInvHead, SysClient SysClient, Integer AMonth, Double Production) {
        this.AccInvHead = AccInvHead;
        this.SysClient = SysClient;
        this.AMonth = AMonth;
        this.Production = Production;
    }

    @SequenceGenerator(name = "generator", sequenceName = "ACC_INVPRODUCTION_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INVHEAD_ID")
    public InvHead getAccInvHead() {
        return this.AccInvHead;
    }

    public void setAccInvHead(InvHead AccInvHead) {
        this.AccInvHead = AccInvHead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "AMONTH", columnDefinition = "INTEGER")
    public Integer getAMonth() {
        return this.AMonth;
    }

    public void setAMonth(Integer AMonth) {
        this.AMonth = AMonth;
    }

    @Column(name = "PRODUCTION", columnDefinition = "DOUBLE PRECISION")
    public Double getProduction() {
        return this.Production;
    }

    public void setProduction(Double Production) {
        this.Production = Production;
    }

    @Formula(value = "(AMonth - ((AMonth / 12) * 12))")
    public MonthOfYear getQMonth() {
        return this.QMonth;
    }

    public void setQMonth(MonthOfYear QMonth) {
        this.QMonth = QMonth;
    }
}

