package com.mg.merp.account.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Metal generated by hbm2java
 */
@Entity
@Table(name="METAL"
)
public class Metal extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private String UpCode;
     private SysClient SysClient;
     private String Code;
     private String Name;

    public Metal() {
    }

	
    public Metal(String UpCode, String Code) {
        this.UpCode = UpCode;
        this.Code = Code;
    }
    public Metal(String UpCode, SysClient SysClient, String Code, String Name) {
       this.UpCode = UpCode;
       this.SysClient = SysClient;
       this.Code = Code;
       this.Name = Name;
    }
   
     @Id 

    
    @Column(name="UPCODE", unique=true, nullable=false, columnDefinition="CHAR", length=20)
    public String getUpCode() {
        return this.UpCode;
    }
    
    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="MNAME", columnDefinition="VARCHAR", length=80)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }




}


