package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocType;
import com.mg.merp.reference.model.Contractor;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * RemnDbKt generated by hbm2java
 */
@Entity
@Table(name = "REMNDBKT")
public class RemnDbKt extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private AccPlan AccPlan;

    private AnlPlan AnlPlan4;

    private AnlPlan AnlPlan1;

    private SysClient SysClient;

    private AnlPlan AnlPlan2;

    private Contractor Contractor;

    private AnlPlan AnlPlan3;

    private AnlPlan AnlPlan5;

    private Period Period;

    private BigDecimal RemnBeginNatDb;

    private BigDecimal RemnBeginNatKt;

    private BigDecimal RemnBeginCurDb;

    private BigDecimal RemnBeginCurKt;

    private Date RiseDebts;

    private Date ClearDebts;

    private String Comment;

    private DocType DocBaseType;

    private String DocBaseNumber;

    private Date DocBaseDate;

    private DocType DocType;

    private String DocNumber;

    private Date DocDate;

    private BigDecimal RemnEndNatDb;

    private BigDecimal RemnEndNatKt;

    private BigDecimal RemnEndCurKt;

    private BigDecimal RemnEndCurDb;

    private BigDecimal TurnNatKt;

    private BigDecimal TurnNatDb;

    private BigDecimal TurnCurDb;

    private BigDecimal TurnCurKt;

    public RemnDbKt() {
    }

    public RemnDbKt(BigDecimal RemnBeginNatDb, BigDecimal RemnBeginNatKt) {
        this.RemnBeginNatDb = RemnBeginNatDb;
        this.RemnBeginNatKt = RemnBeginNatKt;
    }

    public RemnDbKt(AccPlan AccPlan, AnlPlan AnlPlan4, AnlPlan AnlPlan1, SysClient SysClient, AnlPlan AnlPlan2, Contractor Contractor, AnlPlan AnlPlan3, AnlPlan AnlPlan5, Period Period, BigDecimal RemnBeginNatDb, BigDecimal RemnBeginNatKt, BigDecimal RemnBeginCurDb, BigDecimal RemnBeginCurKt, Date RiseDebts, Date ClearDebts, String Comment, DocType DocBaseType, String DocBaseNumber, Date DocBaseDate, DocType DocType, String DocNumber, Date DocDate, BigDecimal RemnEndNatDb, BigDecimal RemnEndNatKt, BigDecimal RemnEndCurKt, BigDecimal RemnEndCurDb, BigDecimal TurnNatKt, BigDecimal TurnNatDb, BigDecimal TurnCurDb, BigDecimal TurnCurKt) {
        this.AccPlan = AccPlan;
        this.AnlPlan4 = AnlPlan4;
        this.AnlPlan1 = AnlPlan1;
        this.SysClient = SysClient;
        this.AnlPlan2 = AnlPlan2;
        this.Contractor = Contractor;
        this.AnlPlan3 = AnlPlan3;
        this.AnlPlan5 = AnlPlan5;
        this.Period = Period;
        this.RemnBeginNatDb = RemnBeginNatDb;
        this.RemnBeginNatKt = RemnBeginNatKt;
        this.RemnBeginCurDb = RemnBeginCurDb;
        this.RemnBeginCurKt = RemnBeginCurKt;
        this.RiseDebts = RiseDebts;
        this.ClearDebts = ClearDebts;
        this.Comment = Comment;
        this.DocBaseType = DocBaseType;
        this.DocBaseNumber = DocBaseNumber;
        this.DocBaseDate = DocBaseDate;
        this.DocType = DocType;
        this.DocNumber = DocNumber;
        this.DocDate = DocDate;
        this.RemnEndNatDb = RemnEndNatDb;
        this.RemnEndNatKt = RemnEndNatKt;
        this.RemnEndCurKt = RemnEndCurKt;
        this.RemnEndCurDb = RemnEndCurDb;
        this.TurnNatKt = TurnNatKt;
        this.TurnNatDb = TurnNatDb;
        this.TurnCurDb = TurnCurDb;
        this.TurnCurKt = TurnCurKt;
    }

    @SequenceGenerator(name = "generator", sequenceName = "REMNDBKT_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACC_ID")
    public AccPlan getAccPlan() {
        return this.AccPlan;
    }

    public void setAccPlan(AccPlan AccPlan) {
        this.AccPlan = AccPlan;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN4_ID")
    public AnlPlan getAnlPlan4() {
        return this.AnlPlan4;
    }

    public void setAnlPlan4(AnlPlan AnlPlan4) {
        this.AnlPlan4 = AnlPlan4;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN1_ID")
    public AnlPlan getAnlPlan1() {
        return this.AnlPlan1;
    }

    public void setAnlPlan1(AnlPlan AnlPlan1) {
        this.AnlPlan1 = AnlPlan1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN2_ID")
    public AnlPlan getAnlPlan2() {
        return this.AnlPlan2;
    }

    public void setAnlPlan2(AnlPlan AnlPlan2) {
        this.AnlPlan2 = AnlPlan2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONTRACTOR_ID")
    public Contractor getContractor() {
        return this.Contractor;
    }

    public void setContractor(Contractor Contractor) {
        this.Contractor = Contractor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN3_ID")
    public AnlPlan getAnlPlan3() {
        return this.AnlPlan3;
    }

    public void setAnlPlan3(AnlPlan AnlPlan3) {
        this.AnlPlan3 = AnlPlan3;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN5_ID")
    public AnlPlan getAnlPlan5() {
        return this.AnlPlan5;
    }

    public void setAnlPlan5(AnlPlan AnlPlan5) {
        this.AnlPlan5 = AnlPlan5;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERIOD_ID")
    public Period getPeriod() {
        return this.Period;
    }

    public void setPeriod(Period Period) {
        this.Period = Period;
    }

    @Column(name = "REMNBEGINNATDB", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getRemnBeginNatDb() {
        return this.RemnBeginNatDb;
    }

    public void setRemnBeginNatDb(BigDecimal RemnBeginNatDb) {
        this.RemnBeginNatDb = RemnBeginNatDb;
    }

    @Column(name = "REMNBEGINNATKT", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getRemnBeginNatKt() {
        return this.RemnBeginNatKt;
    }

    public void setRemnBeginNatKt(BigDecimal RemnBeginNatKt) {
        this.RemnBeginNatKt = RemnBeginNatKt;
    }

    @Column(name = "REMNBEGINCURDB", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getRemnBeginCurDb() {
        return this.RemnBeginCurDb;
    }

    public void setRemnBeginCurDb(BigDecimal RemnBeginCurDb) {
        this.RemnBeginCurDb = RemnBeginCurDb;
    }

    @Column(name = "REMNBEGINCURKT", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getRemnBeginCurKt() {
        return this.RemnBeginCurKt;
    }

    public void setRemnBeginCurKt(BigDecimal RemnBeginCurKt) {
        this.RemnBeginCurKt = RemnBeginCurKt;
    }

    @Column(name = "RISEDEBTS", columnDefinition = "TIMESTAMP")
    public Date getRiseDebts() {
        return this.RiseDebts;
    }

    public void setRiseDebts(Date RiseDebts) {
        this.RiseDebts = RiseDebts;
    }

    @Column(name = "CLEARDEBTS", columnDefinition = "TIMESTAMP")
    public Date getClearDebts() {
        return this.ClearDebts;
    }

    public void setClearDebts(Date ClearDebts) {
        this.ClearDebts = ClearDebts;
    }

    @Column(name = "COMMENT", columnDefinition = "VARCHAR", length = 256)
    @DataItemName("Account.RemnDbKt.Comment")
    public String getComment() {
        return this.Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCBASETYPE")
    @DataItemName("Document.DocTypeModel")
    public DocType getDocBaseType() {
        return this.DocBaseType;
    }

    public void setDocBaseType(DocType DocBaseType) {
        this.DocBaseType = DocBaseType;
    }

    @Column(name = "DOCBASENUMBER", columnDefinition = "CHAR", length = 20)
    @DataItemName("Document.BaseDocNumber")
    public String getDocBaseNumber() {
        return this.DocBaseNumber;
    }

    public void setDocBaseNumber(String DocBaseNumber) {
        this.DocBaseNumber = DocBaseNumber;
    }

    @Column(name = "DOCBASEDATE", columnDefinition = "TIMESTAMP")
    @DataItemName("Document.BaseDocDate")
    public Date getDocBaseDate() {
        return this.DocBaseDate;
    }

    public void setDocBaseDate(Date DocBaseDate) {
        this.DocBaseDate = DocBaseDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCTYPE")
    @DataItemName("Document.DocTypeModel")
    public DocType getDocType() {
        return this.DocType;
    }

    public void setDocType(DocType DocType) {
        this.DocType = DocType;
    }

    @Column(name = "DOCNUMBER", columnDefinition = "CHAR", length = 20)
    @DataItemName("Document.ContractNumber")
    public String getDocNumber() {
        return this.DocNumber;
    }

    public void setDocNumber(String DocNumber) {
        this.DocNumber = DocNumber;
    }

    @Column(name = "DOCDATE", columnDefinition = "TIMESTAMP")
    @DataItemName("Document.ContractDate")
    public Date getDocDate() {
        return this.DocDate;
    }

    public void setDocDate(Date DocDate) {
        this.DocDate = DocDate;
    }

    @Column(name = "RemnEndNatDb", insertable = false, updatable = false)
    public BigDecimal getRemnEndNatDb() {
        return this.RemnEndNatDb;
    }

    public void setRemnEndNatDb(BigDecimal RemnEndNatDb) {
        this.RemnEndNatDb = RemnEndNatDb;
    }

    @Column(name = "RemnEndNatKt", insertable = false, updatable = false)
    public BigDecimal getRemnEndNatKt() {
        return this.RemnEndNatKt;
    }

    public void setRemnEndNatKt(BigDecimal RemnEndNatKt) {
        this.RemnEndNatKt = RemnEndNatKt;
    }

    @Column(name = "RemnEndCurKt", insertable = false, updatable = false)
    public BigDecimal getRemnEndCurKt() {
        return this.RemnEndCurKt;
    }

    public void setRemnEndCurKt(BigDecimal RemnEndCurKt) {
        this.RemnEndCurKt = RemnEndCurKt;
    }

    @Column(name = "RemnEndCurDb", insertable = false, updatable = false)
    public BigDecimal getRemnEndCurDb() {
        return this.RemnEndCurDb;
    }

    public void setRemnEndCurDb(BigDecimal RemnEndCurDb) {
        this.RemnEndCurDb = RemnEndCurDb;
    }

    @Column(name = "TurnNatKt", insertable = false, updatable = false)
    public BigDecimal getTurnNatKt() {
        return this.TurnNatKt;
    }

    public void setTurnNatKt(BigDecimal TurnNatKt) {
        this.TurnNatKt = TurnNatKt;
    }

    @Column(name = "TurnNatDb", insertable = false, updatable = false)
    public BigDecimal getTurnNatDb() {
        return this.TurnNatDb;
    }

    public void setTurnNatDb(BigDecimal TurnNatDb) {
        this.TurnNatDb = TurnNatDb;
    }

    @Column(name = "TurnCurDb", insertable = false, updatable = false)
    public BigDecimal getTurnCurDb() {
        return this.TurnCurDb;
    }

    public void setTurnCurDb(BigDecimal TurnCurDb) {
        this.TurnCurDb = TurnCurDb;
    }

    @Column(name = "TurnCurKt", insertable = false, updatable = false)
    public BigDecimal getTurnCurKt() {
        return this.TurnCurKt;
    }

    public void setTurnCurKt(BigDecimal TurnCurKt) {
        this.TurnCurKt = TurnCurKt;
    }
}

