package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * RemnAcc generated by hbm2java
 */
@Entity
@Table(name = "REMNACC")
public class RemnAcc extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private AccPlan AccPlan;

    private SysClient SysClient;

    private Period Period;

    private BigDecimal RemnBeginNatDb;

    private BigDecimal RemnBeginNatKt;

    private BigDecimal RemnBeginCurDb;

    private BigDecimal RemnBeginCurKt;

    private BigDecimal RemnEndNatDb;

    private BigDecimal RemnEndNatKt;

    private BigDecimal RemnEndCurKt;

    private BigDecimal RemnEndCurDb;

    private BigDecimal TurnNatKt;

    private BigDecimal TurnNatDb;

    private BigDecimal TurnCurDb;

    private BigDecimal TurnCurKt;

    public RemnAcc() {
    }

    public RemnAcc(BigDecimal RemnBeginNatDb, BigDecimal RemnBeginNatKt, BigDecimal RemnBeginCurDb, BigDecimal RemnBeginCurKt) {
        this.RemnBeginNatDb = RemnBeginNatDb;
        this.RemnBeginNatKt = RemnBeginNatKt;
        this.RemnBeginCurDb = RemnBeginCurDb;
        this.RemnBeginCurKt = RemnBeginCurKt;
    }

    public RemnAcc(AccPlan AccPlan, SysClient SysClient, Period Period, BigDecimal RemnBeginNatDb, BigDecimal RemnBeginNatKt, BigDecimal RemnBeginCurDb, BigDecimal RemnBeginCurKt, BigDecimal RemnEndNatDb, BigDecimal RemnEndNatKt, BigDecimal RemnEndCurKt, BigDecimal RemnEndCurDb, BigDecimal TurnNatKt, BigDecimal TurnNatDb, BigDecimal TurnCurDb, BigDecimal TurnCurKt) {
        this.AccPlan = AccPlan;
        this.SysClient = SysClient;
        this.Period = Period;
        this.RemnBeginNatDb = RemnBeginNatDb;
        this.RemnBeginNatKt = RemnBeginNatKt;
        this.RemnBeginCurDb = RemnBeginCurDb;
        this.RemnBeginCurKt = RemnBeginCurKt;
        this.RemnEndNatDb = RemnEndNatDb;
        this.RemnEndNatKt = RemnEndNatKt;
        this.RemnEndCurKt = RemnEndCurKt;
        this.RemnEndCurDb = RemnEndCurDb;
        this.TurnNatKt = TurnNatKt;
        this.TurnNatDb = TurnNatDb;
        this.TurnCurDb = TurnCurDb;
        this.TurnCurKt = TurnCurKt;
    }

    @SequenceGenerator(name = "generator", sequenceName = "REMNACC_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACC_ID", updatable = false)
    public AccPlan getAccPlan() {
        return this.AccPlan;
    }

    public void setAccPlan(AccPlan AccPlan) {
        this.AccPlan = AccPlan;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERIOD_ID", updatable = false)
    public Period getPeriod() {
        return this.Period;
    }

    public void setPeriod(Period Period) {
        this.Period = Period;
    }

    @Column(name = "REMNBEGINNATDB", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.RemnAcc.RemnBeginNatDb")
    public BigDecimal getRemnBeginNatDb() {
        return this.RemnBeginNatDb;
    }

    public void setRemnBeginNatDb(BigDecimal RemnBeginNatDb) {
        this.RemnBeginNatDb = RemnBeginNatDb;
    }

    @Column(name = "REMNBEGINNATKT", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.RemnAcc.RemnBeginNatKt")
    public BigDecimal getRemnBeginNatKt() {
        return this.RemnBeginNatKt;
    }

    public void setRemnBeginNatKt(BigDecimal RemnBeginNatKt) {
        this.RemnBeginNatKt = RemnBeginNatKt;
    }

    @Column(name = "REMNBEGINCURDB", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.RemnAcc.RemnBeginCurDb")
    public BigDecimal getRemnBeginCurDb() {
        return this.RemnBeginCurDb;
    }

    public void setRemnBeginCurDb(BigDecimal RemnBeginCurDb) {
        this.RemnBeginCurDb = RemnBeginCurDb;
    }

    @Column(name = "REMNBEGINCURKT", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Account.RemnAcc.RemnBeginCurKt")
    public BigDecimal getRemnBeginCurKt() {
        return this.RemnBeginCurKt;
    }

    public void setRemnBeginCurKt(BigDecimal RemnBeginCurKt) {
        this.RemnBeginCurKt = RemnBeginCurKt;
    }

    @Column(name = "RemnEndNatDb", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.RemnEndNatDb")
    public BigDecimal getRemnEndNatDb() {
        return this.RemnEndNatDb;
    }

    public void setRemnEndNatDb(BigDecimal RemnEndNatDb) {
        this.RemnEndNatDb = RemnEndNatDb;
    }

    @Column(name = "RemnEndNatKt", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.RemnEndNatKt")
    public BigDecimal getRemnEndNatKt() {
        return this.RemnEndNatKt;
    }

    public void setRemnEndNatKt(BigDecimal RemnEndNatKt) {
        this.RemnEndNatKt = RemnEndNatKt;
    }

    @Column(name = "RemnEndCurKt", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.RemnEndCurKt")
    public BigDecimal getRemnEndCurKt() {
        return this.RemnEndCurKt;
    }

    public void setRemnEndCurKt(BigDecimal RemnEndCurKt) {
        this.RemnEndCurKt = RemnEndCurKt;
    }

    @Column(name = "RemnEndCurDb", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.RemnEndCurDb")
    public BigDecimal getRemnEndCurDb() {
        return this.RemnEndCurDb;
    }

    public void setRemnEndCurDb(BigDecimal RemnEndCurDb) {
        this.RemnEndCurDb = RemnEndCurDb;
    }

    @Column(name = "TurnNatKt", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.TurnNatKt")
    public BigDecimal getTurnNatKt() {
        return this.TurnNatKt;
    }

    public void setTurnNatKt(BigDecimal TurnNatKt) {
        this.TurnNatKt = TurnNatKt;
    }

    @Column(name = "TurnNatDb", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.TurnNatDb")
    public BigDecimal getTurnNatDb() {
        return this.TurnNatDb;
    }

    public void setTurnNatDb(BigDecimal TurnNatDb) {
        this.TurnNatDb = TurnNatDb;
    }

    @Column(name = "TurnCurDb", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.TurnCurDb")
    public BigDecimal getTurnCurDb() {
        return this.TurnCurDb;
    }

    public void setTurnCurDb(BigDecimal TurnCurDb) {
        this.TurnCurDb = TurnCurDb;
    }

    @Column(name = "TurnCurKt", insertable = false, updatable = false)
    @DataItemName("Account.RemnAcc.TurnCurKt")
    public BigDecimal getTurnCurKt() {
        return this.TurnCurKt;
    }

    public void setTurnCurKt(BigDecimal TurnCurKt) {
        this.TurnCurKt = TurnCurKt;
    }
}

