package com.mg.merp.account.model;

import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RemnAnl generated by hbm2java
 */
@Entity
@Table(name = "REMNANL")
public class RemnAnl extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private AccPlan AccPlan;

    private AnlPlan AnlPlan4;

    private AnlPlan AnlPlan1;

    private SysClient SysClient;

    private AnlPlan AnlPlan2;

    private AnlPlan AnlPlan3;

    private AnlPlan AnlPlan5;

    private Period Period;

    private BigDecimal RemnBeginNatDb;

    private BigDecimal RemnBeginNatKt;

    private BigDecimal RemnBeginCurDb;

    private BigDecimal RemnBeginCurKt;

    private BigDecimal RemnEndNatDb;

    private BigDecimal RemnEndNatKt;

    private BigDecimal RemnEndCurKt;

    private BigDecimal RemnEndCurDb;

    private BigDecimal TurnNatKt;

    private BigDecimal TurnNatDb;

    private BigDecimal TurnCurDb;

    private BigDecimal TurnCurKt;

    public RemnAnl() {
    }

    public RemnAnl(BigDecimal RemnBeginNatDb, BigDecimal RemnBeginNatKt, BigDecimal RemnBeginCurDb, BigDecimal RemnBeginCurKt) {
        this.RemnBeginNatDb = RemnBeginNatDb;
        this.RemnBeginNatKt = RemnBeginNatKt;
        this.RemnBeginCurDb = RemnBeginCurDb;
        this.RemnBeginCurKt = RemnBeginCurKt;
    }

    public RemnAnl(AccPlan AccPlan, AnlPlan AnlPlan4, AnlPlan AnlPlan1, SysClient SysClient, AnlPlan AnlPlan2, AnlPlan AnlPlan3, AnlPlan AnlPlan5, Period Period, BigDecimal RemnBeginNatDb, BigDecimal RemnBeginNatKt, BigDecimal RemnBeginCurDb, BigDecimal RemnBeginCurKt, BigDecimal RemnEndNatDb, BigDecimal RemnEndNatKt, BigDecimal RemnEndCurKt, BigDecimal RemnEndCurDb, BigDecimal TurnNatKt, BigDecimal TurnNatDb, BigDecimal TurnCurDb, BigDecimal TurnCurKt) {
        this.AccPlan = AccPlan;
        this.AnlPlan4 = AnlPlan4;
        this.AnlPlan1 = AnlPlan1;
        this.SysClient = SysClient;
        this.AnlPlan2 = AnlPlan2;
        this.AnlPlan3 = AnlPlan3;
        this.AnlPlan5 = AnlPlan5;
        this.Period = Period;
        this.RemnBeginNatDb = RemnBeginNatDb;
        this.RemnBeginNatKt = RemnBeginNatKt;
        this.RemnBeginCurDb = RemnBeginCurDb;
        this.RemnBeginCurKt = RemnBeginCurKt;
        this.RemnEndNatDb = RemnEndNatDb;
        this.RemnEndNatKt = RemnEndNatKt;
        this.RemnEndCurKt = RemnEndCurKt;
        this.RemnEndCurDb = RemnEndCurDb;
        this.TurnNatKt = TurnNatKt;
        this.TurnNatDb = TurnNatDb;
        this.TurnCurDb = TurnCurDb;
        this.TurnCurKt = TurnCurKt;
    }

    @SequenceGenerator(name = "generator", sequenceName = "REMNANL_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    //$NON-NLS-1$
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACC_ID")
    public AccPlan getAccPlan() {
        return this.AccPlan;
    }

    public void setAccPlan(AccPlan AccPlan) {
        this.AccPlan = AccPlan;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN4_ID")
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.AnlPlan4")
    public AnlPlan getAnlPlan4() {
        return this.AnlPlan4;
    }

    public void setAnlPlan4(AnlPlan AnlPlan4) {
        this.AnlPlan4 = AnlPlan4;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN1_ID")
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.AnlPlan1")
    public AnlPlan getAnlPlan1() {
        return this.AnlPlan1;
    }

    public void setAnlPlan1(AnlPlan AnlPlan1) {
        this.AnlPlan1 = AnlPlan1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN2_ID")
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.AnlPlan2")
    public AnlPlan getAnlPlan2() {
        return this.AnlPlan2;
    }

    public void setAnlPlan2(AnlPlan AnlPlan2) {
        this.AnlPlan2 = AnlPlan2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN3_ID")
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.AnlPlan3")
    public AnlPlan getAnlPlan3() {
        return this.AnlPlan3;
    }

    public void setAnlPlan3(AnlPlan AnlPlan3) {
        this.AnlPlan3 = AnlPlan3;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANLPLAN5_ID")
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.AnlPlan5")
    public AnlPlan getAnlPlan5() {
        return this.AnlPlan5;
    }

    public void setAnlPlan5(AnlPlan AnlPlan5) {
        this.AnlPlan5 = AnlPlan5;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERIOD_ID")
    public Period getPeriod() {
        return this.Period;
    }

    public void setPeriod(Period Period) {
        this.Period = Period;
    }

    @Column(name = "REMNBEGINNATDB", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnBeginNatDb")
    public BigDecimal getRemnBeginNatDb() {
        return this.RemnBeginNatDb;
    }

    public void setRemnBeginNatDb(BigDecimal RemnBeginNatDb) {
        this.RemnBeginNatDb = RemnBeginNatDb;
    }

    @Column(name = "REMNBEGINNATKT", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnBeginNatKt")
    public BigDecimal getRemnBeginNatKt() {
        return this.RemnBeginNatKt;
    }

    public void setRemnBeginNatKt(BigDecimal RemnBeginNatKt) {
        this.RemnBeginNatKt = RemnBeginNatKt;
    }

    @Column(name = "REMNBEGINCURDB", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnBeginCurDb")
    public BigDecimal getRemnBeginCurDb() {
        return this.RemnBeginCurDb;
    }

    public void setRemnBeginCurDb(BigDecimal RemnBeginCurDb) {
        this.RemnBeginCurDb = RemnBeginCurDb;
    }

    @Column(name = "REMNBEGINCURKT", nullable = false, columnDefinition = "NUMERIC", precision = 15, scale = 4)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnBeginCurKt")
    public BigDecimal getRemnBeginCurKt() {
        return this.RemnBeginCurKt;
    }

    public void setRemnBeginCurKt(BigDecimal RemnBeginCurKt) {
        this.RemnBeginCurKt = RemnBeginCurKt;
    }

    @Column(name = "RemnEndNatDb", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnEndNatDb")
    public BigDecimal getRemnEndNatDb() {
        return this.RemnEndNatDb;
    }

    public void setRemnEndNatDb(BigDecimal RemnEndNatDb) {
        this.RemnEndNatDb = RemnEndNatDb;
    }

    @Column(name = "RemnEndNatKt", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnEndNatKt")
    public BigDecimal getRemnEndNatKt() {
        return this.RemnEndNatKt;
    }

    public void setRemnEndNatKt(BigDecimal RemnEndNatKt) {
        this.RemnEndNatKt = RemnEndNatKt;
    }

    @Column(name = "RemnEndCurKt", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnEndCurKt")
    public BigDecimal getRemnEndCurKt() {
        return this.RemnEndCurKt;
    }

    public void setRemnEndCurKt(BigDecimal RemnEndCurKt) {
        this.RemnEndCurKt = RemnEndCurKt;
    }

    @Column(name = "RemnEndCurDb", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.RemnEndCurDb")
    public BigDecimal getRemnEndCurDb() {
        return this.RemnEndCurDb;
    }

    public void setRemnEndCurDb(BigDecimal RemnEndCurDb) {
        this.RemnEndCurDb = RemnEndCurDb;
    }

    @Column(name = "TurnNatKt", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.TurnNatKt")
    public BigDecimal getTurnNatKt() {
        return this.TurnNatKt;
    }

    public void setTurnNatKt(BigDecimal TurnNatKt) {
        this.TurnNatKt = TurnNatKt;
    }

    @Column(name = "TurnNatDb", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.TurnNatDb")
    public BigDecimal getTurnNatDb() {
        return this.TurnNatDb;
    }

    public void setTurnNatDb(BigDecimal TurnNatDb) {
        this.TurnNatDb = TurnNatDb;
    }

    @Column(name = "TurnCurDb", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.TurnCurDb")
    public BigDecimal getTurnCurDb() {
        return this.TurnCurDb;
    }

    public void setTurnCurDb(BigDecimal TurnCurDb) {
        this.TurnCurDb = TurnCurDb;
    }

    @Column(name = "TurnCurKt", insertable = false, updatable = false)
    //$NON-NLS-1$
    @DataItemName("Account.RemnAnl.TurnCurKt")
    public BigDecimal getTurnCurKt() {
        return this.TurnCurKt;
    }

    public void setTurnCurKt(BigDecimal TurnCurKt) {
        this.TurnCurKt = TurnCurKt;
    }
}

