package com.mg.merp.account.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TurnOnEsFeatures generated by hbm2java
 */
@Entity
@Table(name="TURNONESFEATURES"
)
public class TurnOnEsFeatures extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private SysClient SysClient;
     private String UserName;
     private String AccDbCode;
     private String AccKtCode;
     private Integer AnlDb1Id;
     private Integer AnlDb2Id;
     private Integer AnlDb3Id;
     private Integer AnlDb4Id;
     private Integer AnlDb5Id;
     private Integer AnlKt1Id;
     private Integer AnlKt2Id;
     private Integer AnlKt3Id;
     private Integer AnlKt4Id;
     private Integer AnlKt5Id;
     private Integer Feature1Id;
     private Integer Feature2Id;
     private Integer Feature3Id;
     private Integer Feature4Id;
     private Integer Feature5Id;
     private Integer OrgUnitId;
     private BigDecimal SummNat;
     private BigDecimal SummCur;
     private Date OperDate;
     private Short TotalSign;

    public TurnOnEsFeatures() {
    }

	
    public TurnOnEsFeatures(Integer Id) {
        this.Id = Id;
    }
    public TurnOnEsFeatures(Integer Id, SysClient SysClient, String UserName, String AccDbCode, String AccKtCode, Integer AnlDb1Id, Integer AnlDb2Id, Integer AnlDb3Id, Integer AnlDb4Id, Integer AnlDb5Id, Integer AnlKt1Id, Integer AnlKt2Id, Integer AnlKt3Id, Integer AnlKt4Id, Integer AnlKt5Id, Integer Feature1Id, Integer Feature2Id, Integer Feature3Id, Integer Feature4Id, Integer Feature5Id, Integer OrgUnitId, BigDecimal SummNat, BigDecimal SummCur, Date OperDate, Short TotalSign) {
       this.Id = Id;
       this.SysClient = SysClient;
       this.UserName = UserName;
       this.AccDbCode = AccDbCode;
       this.AccKtCode = AccKtCode;
       this.AnlDb1Id = AnlDb1Id;
       this.AnlDb2Id = AnlDb2Id;
       this.AnlDb3Id = AnlDb3Id;
       this.AnlDb4Id = AnlDb4Id;
       this.AnlDb5Id = AnlDb5Id;
       this.AnlKt1Id = AnlKt1Id;
       this.AnlKt2Id = AnlKt2Id;
       this.AnlKt3Id = AnlKt3Id;
       this.AnlKt4Id = AnlKt4Id;
       this.AnlKt5Id = AnlKt5Id;
       this.Feature1Id = Feature1Id;
       this.Feature2Id = Feature2Id;
       this.Feature3Id = Feature3Id;
       this.Feature4Id = Feature4Id;
       this.Feature5Id = Feature5Id;
       this.OrgUnitId = OrgUnitId;
       this.SummNat = SummNat;
       this.SummCur = SummCur;
       this.OperDate = OperDate;
       this.TotalSign = TotalSign;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="USERNAME", columnDefinition="CHAR", length=31)
    public String getUserName() {
        return this.UserName;
    }
    
    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    
    @Column(name="ACCDB_CODE", columnDefinition="CHAR", length=20)
    public String getAccDbCode() {
        return this.AccDbCode;
    }
    
    public void setAccDbCode(String AccDbCode) {
        this.AccDbCode = AccDbCode;
    }

    
    @Column(name="ACCKT_CODE", columnDefinition="CHAR", length=20)
    public String getAccKtCode() {
        return this.AccKtCode;
    }
    
    public void setAccKtCode(String AccKtCode) {
        this.AccKtCode = AccKtCode;
    }

    
    @Column(name="ANLDB1_ID", columnDefinition="INTEGER")
    public Integer getAnlDb1Id() {
        return this.AnlDb1Id;
    }
    
    public void setAnlDb1Id(Integer AnlDb1Id) {
        this.AnlDb1Id = AnlDb1Id;
    }

    
    @Column(name="ANLDB2_ID", columnDefinition="INTEGER")
    public Integer getAnlDb2Id() {
        return this.AnlDb2Id;
    }
    
    public void setAnlDb2Id(Integer AnlDb2Id) {
        this.AnlDb2Id = AnlDb2Id;
    }

    
    @Column(name="ANLDB3_ID", columnDefinition="INTEGER")
    public Integer getAnlDb3Id() {
        return this.AnlDb3Id;
    }
    
    public void setAnlDb3Id(Integer AnlDb3Id) {
        this.AnlDb3Id = AnlDb3Id;
    }

    
    @Column(name="ANLDB4_ID", columnDefinition="INTEGER")
    public Integer getAnlDb4Id() {
        return this.AnlDb4Id;
    }
    
    public void setAnlDb4Id(Integer AnlDb4Id) {
        this.AnlDb4Id = AnlDb4Id;
    }

    
    @Column(name="ANLDB5_ID", columnDefinition="INTEGER")
    public Integer getAnlDb5Id() {
        return this.AnlDb5Id;
    }
    
    public void setAnlDb5Id(Integer AnlDb5Id) {
        this.AnlDb5Id = AnlDb5Id;
    }

    
    @Column(name="ANLKT1_ID", columnDefinition="INTEGER")
    public Integer getAnlKt1Id() {
        return this.AnlKt1Id;
    }
    
    public void setAnlKt1Id(Integer AnlKt1Id) {
        this.AnlKt1Id = AnlKt1Id;
    }

    
    @Column(name="ANLKT2_ID", columnDefinition="INTEGER")
    public Integer getAnlKt2Id() {
        return this.AnlKt2Id;
    }
    
    public void setAnlKt2Id(Integer AnlKt2Id) {
        this.AnlKt2Id = AnlKt2Id;
    }

    
    @Column(name="ANLKT3_ID", columnDefinition="INTEGER")
    public Integer getAnlKt3Id() {
        return this.AnlKt3Id;
    }
    
    public void setAnlKt3Id(Integer AnlKt3Id) {
        this.AnlKt3Id = AnlKt3Id;
    }

    
    @Column(name="ANLKT4_ID", columnDefinition="INTEGER")
    public Integer getAnlKt4Id() {
        return this.AnlKt4Id;
    }
    
    public void setAnlKt4Id(Integer AnlKt4Id) {
        this.AnlKt4Id = AnlKt4Id;
    }

    
    @Column(name="ANLKT5_ID", columnDefinition="INTEGER")
    public Integer getAnlKt5Id() {
        return this.AnlKt5Id;
    }
    
    public void setAnlKt5Id(Integer AnlKt5Id) {
        this.AnlKt5Id = AnlKt5Id;
    }

    
    @Column(name="FEATURE1_ID", columnDefinition="INTEGER")
    public Integer getFeature1Id() {
        return this.Feature1Id;
    }
    
    public void setFeature1Id(Integer Feature1Id) {
        this.Feature1Id = Feature1Id;
    }

    
    @Column(name="FEATURE2_ID", columnDefinition="INTEGER")
    public Integer getFeature2Id() {
        return this.Feature2Id;
    }
    
    public void setFeature2Id(Integer Feature2Id) {
        this.Feature2Id = Feature2Id;
    }

    
    @Column(name="FEATURE3_ID", columnDefinition="INTEGER")
    public Integer getFeature3Id() {
        return this.Feature3Id;
    }
    
    public void setFeature3Id(Integer Feature3Id) {
        this.Feature3Id = Feature3Id;
    }

    
    @Column(name="FEATURE4_ID", columnDefinition="INTEGER")
    public Integer getFeature4Id() {
        return this.Feature4Id;
    }
    
    public void setFeature4Id(Integer Feature4Id) {
        this.Feature4Id = Feature4Id;
    }

    
    @Column(name="FEATURE5_ID", columnDefinition="INTEGER")
    public Integer getFeature5Id() {
        return this.Feature5Id;
    }
    
    public void setFeature5Id(Integer Feature5Id) {
        this.Feature5Id = Feature5Id;
    }

    
    @Column(name="ORGUNIT_ID", columnDefinition="INTEGER")
    public Integer getOrgUnitId() {
        return this.OrgUnitId;
    }
    
    public void setOrgUnitId(Integer OrgUnitId) {
        this.OrgUnitId = OrgUnitId;
    }

    
    @Column(name="SUMMNAT", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSummNat() {
        return this.SummNat;
    }
    
    public void setSummNat(BigDecimal SummNat) {
        this.SummNat = SummNat;
    }

    
    @Column(name="SUMMCUR", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSummCur() {
        return this.SummCur;
    }
    
    public void setSummCur(BigDecimal SummCur) {
        this.SummCur = SummCur;
    }

    
    @Column(name="OPERDATE", columnDefinition="TIMESTAMP")
    public Date getOperDate() {
        return this.OperDate;
    }
    
    public void setOperDate(Date OperDate) {
        this.OperDate = OperDate;
    }

    
    @Column(name="TOTAL_SIGN", columnDefinition="SMALLINT")
    public Short getTotalSign() {
        return this.TotalSign;
    }
    
    public void setTotalSign(Short TotalSign) {
        this.TotalSign = TotalSign;
    }




}


