package com.mg.merp.finance.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Analytics generated by hbm2java
 */
@Entity
@Table(name="FINANL"
)
public class Analytics extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Account FinAcc;
     private Analytics Parent;
     private SysClient SysClient;
     private String Code;
     private String UpCode;
     private String AnlName;
     private short AnlLevel;

    public Analytics() {
    }

	
    public Analytics(String Code, String UpCode, short AnlLevel) {
        this.Code = Code;
        this.UpCode = UpCode;
        this.AnlLevel = AnlLevel;
    }
    public Analytics(Account FinAcc, Analytics Parent, SysClient SysClient, String Code, String UpCode, String AnlName, short AnlLevel) {
       this.FinAcc = FinAcc;
       this.Parent = Parent;
       this.SysClient = SysClient;
       this.Code = Code;
       this.UpCode = UpCode;
       this.AnlName = AnlName;
       this.AnlLevel = AnlLevel;
    }
   
     @SequenceGenerator(name="generator", sequenceName="FINANL_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FINACC_ID")
    public Account getFinAcc() {
        return this.FinAcc;
    }
    
    public void setFinAcc(Account FinAcc) {
        this.FinAcc = FinAcc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARENT_ID")
    public Analytics getParent() {
        return this.Parent;
    }
    
    public void setParent(Analytics Parent) {
        this.Parent = Parent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="UPCODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getUpCode() {
        return this.UpCode;
    }
    
    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

    
    @Column(name="ANLNAME", columnDefinition="VARCHAR", length=80)
    public String getAnlName() {
        return this.AnlName;
    }
    
    public void setAnlName(String AnlName) {
        this.AnlName = AnlName;
    }

    
    @Column(name="ANLLEVEL", nullable=false, columnDefinition="SMALLINT")
    public short getAnlLevel() {
        return this.AnlLevel;
    }
    
    public void setAnlLevel(short AnlLevel) {
        this.AnlLevel = AnlLevel;
    }




}


