package com.mg.merp.mfreference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Measure;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BomRoute generated by hbm2java
 */
@Entity
@Table(name="MF_BOM_ROUTE"
)
public class BomRoute extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Bom Bom;
     private Measure SchedOffSetTimeUM;
     private Measure SetupTimeUM;
     private Measure MoveTimeUM;
     private SysClient SysClient;
     private CostDetail StandartCostDetail;
     private Measure SchedTimeUM;
     private WorkCenter WorkCenter;
     private Measure RunTimeUM;
     private Measure QueueTimeUM;
     private Integer OperNum;
     private String Description;
     private Date EffOnDate;
     private Date EffOffDate;
     private BigDecimal Efficiency;
     private Long MoveTicks;
     private Long SetupTicks;
     private Long RunTicks;
     private Long SchedTicks;
     private Long SchedOffsetTicks;
     private Long QueueTicks;
     private boolean ControlPointFlag;
     private String Comment;
     private Set<BomRouteResource> RouteResources = new HashSet<BomRouteResource>(0);

    public BomRoute() {
    }

    public BomRoute(Bom Bom, Measure SchedOffSetTimeUM, Measure SetupTimeUM, Measure MoveTimeUM, SysClient SysClient, CostDetail StandartCostDetail, Measure SchedTimeUM, WorkCenter WorkCenter, Measure RunTimeUM, Measure QueueTimeUM, Integer OperNum, String Description, Date EffOnDate, Date EffOffDate, BigDecimal Efficiency, Long MoveTicks, Long SetupTicks, Long RunTicks, Long SchedTicks, Long SchedOffsetTicks, Long QueueTicks, boolean ControlPointFlag, String Comment, Set<BomRouteResource> RouteResources) {
       this.Bom = Bom;
       this.SchedOffSetTimeUM = SchedOffSetTimeUM;
       this.SetupTimeUM = SetupTimeUM;
       this.MoveTimeUM = MoveTimeUM;
       this.SysClient = SysClient;
       this.StandartCostDetail = StandartCostDetail;
       this.SchedTimeUM = SchedTimeUM;
       this.WorkCenter = WorkCenter;
       this.RunTimeUM = RunTimeUM;
       this.QueueTimeUM = QueueTimeUM;
       this.OperNum = OperNum;
       this.Description = Description;
       this.EffOnDate = EffOnDate;
       this.EffOffDate = EffOffDate;
       this.Efficiency = Efficiency;
       this.MoveTicks = MoveTicks;
       this.SetupTicks = SetupTicks;
       this.RunTicks = RunTicks;
       this.SchedTicks = SchedTicks;
       this.SchedOffsetTicks = SchedOffsetTicks;
       this.QueueTicks = QueueTicks;
       this.ControlPointFlag = ControlPointFlag;
       this.Comment = Comment;
       this.RouteResources = RouteResources;
    }
   
     @SequenceGenerator(name="generator", sequenceName="MF_BOM_ROUTE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BOM_ID")
    public Bom getBom() {
        return this.Bom;
    }
    
    public void setBom(Bom Bom) {
        this.Bom = Bom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SCHED_OFFSET_TIME_UM")
    public Measure getSchedOffSetTimeUM() {
        return this.SchedOffSetTimeUM;
    }
    
    public void setSchedOffSetTimeUM(Measure SchedOffSetTimeUM) {
        this.SchedOffSetTimeUM = SchedOffSetTimeUM;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SETUP_TIME_UM")
    public Measure getSetupTimeUM() {
        return this.SetupTimeUM;
    }
    
    public void setSetupTimeUM(Measure SetupTimeUM) {
        this.SetupTimeUM = SetupTimeUM;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MOVE_TIME_UM")
    public Measure getMoveTimeUM() {
        return this.MoveTimeUM;
    }
    
    public void setMoveTimeUM(Measure MoveTimeUM) {
        this.MoveTimeUM = MoveTimeUM;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STD_COST_DETAIL_ID")
    public CostDetail getStandartCostDetail() {
        return this.StandartCostDetail;
    }
    
    public void setStandartCostDetail(CostDetail StandartCostDetail) {
        this.StandartCostDetail = StandartCostDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SCHED_TIME_UM")
    public Measure getSchedTimeUM() {
        return this.SchedTimeUM;
    }
    
    public void setSchedTimeUM(Measure SchedTimeUM) {
        this.SchedTimeUM = SchedTimeUM;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WC_ID")
    public WorkCenter getWorkCenter() {
        return this.WorkCenter;
    }
    
    public void setWorkCenter(WorkCenter WorkCenter) {
        this.WorkCenter = WorkCenter;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RUN_TIME_UM")
    public Measure getRunTimeUM() {
        return this.RunTimeUM;
    }
    
    public void setRunTimeUM(Measure RunTimeUM) {
        this.RunTimeUM = RunTimeUM;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QUEUE_TIME_UM")
    public Measure getQueueTimeUM() {
        return this.QueueTimeUM;
    }
    
    public void setQueueTimeUM(Measure QueueTimeUM) {
        this.QueueTimeUM = QueueTimeUM;
    }

    
    @Column(name="OPER_NUM", columnDefinition="INTEGER")
    public Integer getOperNum() {
        return this.OperNum;
    }
    
    public void setOperNum(Integer OperNum) {
        this.OperNum = OperNum;
    }

    
    @Column(name="DESCRIPTION", columnDefinition="VARCHAR", length=256)
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    
    @Column(name="EFF_ON_DATE", columnDefinition="TIMESTAMP")
    public Date getEffOnDate() {
        return this.EffOnDate;
    }
    
    public void setEffOnDate(Date EffOnDate) {
        this.EffOnDate = EffOnDate;
    }

    
    @Column(name="EFF_OFF_DATE", columnDefinition="TIMESTAMP")
    public Date getEffOffDate() {
        return this.EffOffDate;
    }
    
    public void setEffOffDate(Date EffOffDate) {
        this.EffOffDate = EffOffDate;
    }

    
    @Column(name="EFFICIENCY", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getEfficiency() {
        return this.Efficiency;
    }
    
    public void setEfficiency(BigDecimal Efficiency) {
        this.Efficiency = Efficiency;
    }

    
    @Column(name="MOVE_TICKS", columnDefinition="NUMERIC", precision=18, scale=0)
    public Long getMoveTicks() {
        return this.MoveTicks;
    }
    
    public void setMoveTicks(Long MoveTicks) {
        this.MoveTicks = MoveTicks;
    }

    
    @Column(name="SETUP_TICKS", columnDefinition="NUMERIC", precision=18, scale=0)
    public Long getSetupTicks() {
        return this.SetupTicks;
    }
    
    public void setSetupTicks(Long SetupTicks) {
        this.SetupTicks = SetupTicks;
    }

    
    @Column(name="RUN_TICKS", columnDefinition="NUMERIC", precision=18, scale=0)
    public Long getRunTicks() {
        return this.RunTicks;
    }
    
    public void setRunTicks(Long RunTicks) {
        this.RunTicks = RunTicks;
    }

    
    @Column(name="SCHED_TICKS", columnDefinition="NUMERIC", precision=18, scale=0)
    public Long getSchedTicks() {
        return this.SchedTicks;
    }
    
    public void setSchedTicks(Long SchedTicks) {
        this.SchedTicks = SchedTicks;
    }

    
    @Column(name="SCHED_OFFSET_TICKS", columnDefinition="NUMERIC", precision=18, scale=0)
    public Long getSchedOffsetTicks() {
        return this.SchedOffsetTicks;
    }
    
    public void setSchedOffsetTicks(Long SchedOffsetTicks) {
        this.SchedOffsetTicks = SchedOffsetTicks;
    }

    
    @Column(name="QUEUE_TICKS", columnDefinition="NUMERIC", precision=18, scale=0)
    public Long getQueueTicks() {
        return this.QueueTicks;
    }
    
    public void setQueueTicks(Long QueueTicks) {
        this.QueueTicks = QueueTicks;
    }

    
    @Column(name="CONTROL_POINT_FLAG", columnDefinition="SMALLINT")
    public boolean isControlPointFlag() {
        return this.ControlPointFlag;
    }
    
    public void setControlPointFlag(boolean ControlPointFlag) {
        this.ControlPointFlag = ControlPointFlag;
    }

    
    @Column(name="COMMENT", columnDefinition="VARCHAR", length=256)
    public String getComment() {
        return this.Comment;
    }
    
    public void setComment(String Comment) {
        this.Comment = Comment;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="BomRoute")
    public Set<BomRouteResource> getRouteResources() {
        return this.RouteResources;
    }
    
    public void setRouteResources(Set<BomRouteResource> RouteResources) {
        this.RouteResources = RouteResources;
    }




}


