package com.mg.merp.mfreference.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Currency;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CostDetailLine generated by hbm2java
 */
@Entity
@Table(name="MF_COST_DETAIL_LINE"
)
public class CostDetailLine extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private SysClient SysClient;
     private CostCategories CostCategories;
     private Currency Currency;
     private CostDetail CostDetail;
     private BigDecimal Summa;

    public CostDetailLine() {
    }

    public CostDetailLine(SysClient SysClient, CostCategories CostCategories, Currency Currency, CostDetail CostDetail, BigDecimal Summa) {
       this.SysClient = SysClient;
       this.CostCategories = CostCategories;
       this.Currency = Currency;
       this.CostDetail = CostDetail;
       this.Summa = Summa;
    }
   
     @SequenceGenerator(name="generator", sequenceName="MF_COST_DETAIL_LINE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_CATEGORIES_ID")
    public CostCategories getCostCategories() {
        return this.CostCategories;
    }
    
    public void setCostCategories(CostCategories CostCategories) {
        this.CostCategories = CostCategories;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURRENCY_CODE")
    public Currency getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(Currency Currency) {
        this.Currency = Currency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_DETAIL_ID")
    public CostDetail getCostDetail() {
        return this.CostDetail;
    }
    
    public void setCostDetail(CostDetail CostDetail) {
        this.CostDetail = CostDetail;
    }

    
    @Column(name="SUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSumma() {
        return this.Summa;
    }
    
    public void setSumma(BigDecimal Summa) {
        this.Summa = Summa;
    }




}


