package com.mg.merp.mfreference.model;

import com.mg.merp.baiengine.model.Repository;
import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CostCategories generated by hbm2java
 */
@Entity
@Table(name = "MF_COST_CATEGORIES")
@DataItemName("MfReference.CostCategories")
public class CostCategories extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Repository AlgRepository;

    private SysClient SysClient;

    private String Code;

    private String Description;

    private Integer ViewOrder;

    private Integer CalculationSequence;

    public CostCategories() {
    }

    public CostCategories(Repository AlgRepository, SysClient SysClient, String Code, String Description, Integer ViewOrder, Integer CalculationSequence) {
        this.AlgRepository = AlgRepository;
        this.SysClient = SysClient;
        this.Code = Code;
        this.Description = Description;
        this.ViewOrder = ViewOrder;
        this.CalculationSequence = CalculationSequence;
    }

    @SequenceGenerator(name = "generator", sequenceName = "MF_COST_CATEGORIES_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FORMULA_ID")
    @DataItemName("MfReference.CostCateg.AlgRepos")
    public Repository getAlgRepository() {
        return this.AlgRepository;
    }

    public void setAlgRepository(Repository AlgRepository) {
        this.AlgRepository = AlgRepository;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", columnDefinition = "CHAR", length = 20)
    @DataItemName("MfReference.CostCateg.Code")
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 256)
    @DataItemName("MfReference.CostCateg.Descr")
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    @Column(name = "VIEW_ORDER", columnDefinition = "INTEGER")
    @DataItemName("MfReference.CostCateg.ViewOrder")
    public Integer getViewOrder() {
        return this.ViewOrder;
    }

    public void setViewOrder(Integer ViewOrder) {
        this.ViewOrder = ViewOrder;
    }

    @Column(name = "CALCULATION_SEQUENCE", columnDefinition = "INTEGER")
    @DataItemName("MfReference.CostCateg.CalcSeq")
    public Integer getCalculationSequence() {
        return this.CalculationSequence;
    }

    public void setCalculationSequence(Integer CalculationSequence) {
        this.CalculationSequence = CalculationSequence;
    }
}

