package com.mg.merp.mfreference.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.Measure;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * LaborClass generated by hbm2java
 */
@Entity
@Table(name = "MF_LABOR_CLASS")
@DataItemName("MfReference.LaborClass")
public class LaborClass extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Measure LbrOhTimeUm;

    private Currency LbrOhRateCurrency;

    private SysClient SysClient;

    private CostCategories LbrCostCategory;

    private CostCategories LbrOhCostCategory;

    private Measure LbrTimeUm;

    private Currency LbrRateCurrency;

    private String Description;

    private TimeRateFlag TimeRateFlag;

    private BigDecimal LbrRate;

    private LaborOverheadAllocationFlag LbrOhAllocationFlag;

    private BigDecimal LbrOhRate;

    private BigDecimal LbrOhRatio;

    public LaborClass() {
    }

    public LaborClass(Measure LbrOhTimeUm, Currency LbrOhRateCurrency, SysClient SysClient, CostCategories LbrCostCategory, CostCategories LbrOhCostCategory, Measure LbrTimeUm, Currency LbrRateCurrency, String Description, TimeRateFlag TimeRateFlag, BigDecimal LbrRate, LaborOverheadAllocationFlag LbrOhAllocationFlag, BigDecimal LbrOhRate, BigDecimal LbrOhRatio) {
        this.LbrOhTimeUm = LbrOhTimeUm;
        this.LbrOhRateCurrency = LbrOhRateCurrency;
        this.SysClient = SysClient;
        this.LbrCostCategory = LbrCostCategory;
        this.LbrOhCostCategory = LbrOhCostCategory;
        this.LbrTimeUm = LbrTimeUm;
        this.LbrRateCurrency = LbrRateCurrency;
        this.Description = Description;
        this.TimeRateFlag = TimeRateFlag;
        this.LbrRate = LbrRate;
        this.LbrOhAllocationFlag = LbrOhAllocationFlag;
        this.LbrOhRate = LbrOhRate;
        this.LbrOhRatio = LbrOhRatio;
    }

    @SequenceGenerator(name = "generator", sequenceName = "MF_LABOR_CLASS_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LBR_OH_TIME_UM")
    @DataItemName("MfReference.LbrCl.LbrOhTimeUm")
    public Measure getLbrOhTimeUm() {
        return this.LbrOhTimeUm;
    }

    public void setLbrOhTimeUm(Measure LbrOhTimeUm) {
        this.LbrOhTimeUm = LbrOhTimeUm;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LBR_OH_RATE_CUR_CODE")
    @DataItemName("MfReference.LbrCl.LbrOhRatCurCod")
    public Currency getLbrOhRateCurrency() {
        return this.LbrOhRateCurrency;
    }

    public void setLbrOhRateCurrency(Currency LbrOhRateCurrency) {
        this.LbrOhRateCurrency = LbrOhRateCurrency;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LBR_COST_CATEGORY_ID")
    @DataItemName("MfReference.LbrCl.LbrCostCategId")
    public CostCategories getLbrCostCategory() {
        return this.LbrCostCategory;
    }

    public void setLbrCostCategory(CostCategories LbrCostCategory) {
        this.LbrCostCategory = LbrCostCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LBR_OH_COST_CATEGORY_ID")
    @DataItemName("MfReference.LbrCl.LbrOhCostCatId")
    public CostCategories getLbrOhCostCategory() {
        return this.LbrOhCostCategory;
    }

    public void setLbrOhCostCategory(CostCategories LbrOhCostCategory) {
        this.LbrOhCostCategory = LbrOhCostCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LBR_TIME_UM")
    @DataItemName("MfReference.LbrCl.LbrTimeUm")
    public Measure getLbrTimeUm() {
        return this.LbrTimeUm;
    }

    public void setLbrTimeUm(Measure LbrTimeUm) {
        this.LbrTimeUm = LbrTimeUm;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LBR_RATE_CUR_CODE")
    @DataItemName("MfReference.LbrCl.LbrRateCurCode")
    public Currency getLbrRateCurrency() {
        return this.LbrRateCurrency;
    }

    public void setLbrRateCurrency(Currency LbrRateCurrency) {
        this.LbrRateCurrency = LbrRateCurrency;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 256)
    @DataItemName("MfReference.LbrCl.Descript")
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    @Column(name = "TIME_RATE_FLAG")
    @Enumerated(EnumType.ORDINAL)
    public TimeRateFlag getTimeRateFlag() {
        return this.TimeRateFlag;
    }

    public void setTimeRateFlag(TimeRateFlag TimeRateFlag) {
        this.TimeRateFlag = TimeRateFlag;
    }

    @Column(name = "LBR_RATE", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.LbrCl.LbrRate")
    public BigDecimal getLbrRate() {
        return this.LbrRate;
    }

    public void setLbrRate(BigDecimal LbrRate) {
        this.LbrRate = LbrRate;
    }

    @Column(name = "LBR_OH_ALLOCATION_FLAG")
    @Enumerated(EnumType.ORDINAL)
    public LaborOverheadAllocationFlag getLbrOhAllocationFlag() {
        return this.LbrOhAllocationFlag;
    }

    public void setLbrOhAllocationFlag(LaborOverheadAllocationFlag LbrOhAllocationFlag) {
        this.LbrOhAllocationFlag = LbrOhAllocationFlag;
    }

    @Column(name = "LBR_OH_RATE", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.LbrCl.LbrOhRate")
    public BigDecimal getLbrOhRate() {
        return this.LbrOhRate;
    }

    public void setLbrOhRate(BigDecimal LbrOhRate) {
        this.LbrOhRate = LbrOhRate;
    }

    @Column(name = "LBR_OH_RATIO", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.LbrCl.LbrOhRatio")
    public BigDecimal getLbrOhRatio() {
        return this.LbrOhRatio;
    }

    public void setLbrOhRatio(BigDecimal LbrOhRatio) {
        this.LbrOhRatio = LbrOhRatio;
    }
}

