package com.mg.merp.mfreference.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ResourceGroupCapacity generated by hbm2java
 */
@Entity
@Table(name="MF_RESOURCE_GROUP_CAPACITY"
)
public class ResourceGroupCapacity extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private ResourceGroup ResourceGroup;
     private SysClient SysClient;
     private BigDecimal PlanningCapacity;
     private BigDecimal MaximumCapacity;
     private Date EffOnDate;
     private Date EffOffDate;

    public ResourceGroupCapacity() {
    }

    public ResourceGroupCapacity(ResourceGroup ResourceGroup, SysClient SysClient, BigDecimal PlanningCapacity, BigDecimal MaximumCapacity, Date EffOnDate, Date EffOffDate) {
       this.ResourceGroup = ResourceGroup;
       this.SysClient = SysClient;
       this.PlanningCapacity = PlanningCapacity;
       this.MaximumCapacity = MaximumCapacity;
       this.EffOnDate = EffOnDate;
       this.EffOffDate = EffOffDate;
    }
   
     @SequenceGenerator(name="generator", sequenceName="MF_RESOURCE_GROUP_CAP_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_GROUP_ID")
    public ResourceGroup getResourceGroup() {
        return this.ResourceGroup;
    }
    
    public void setResourceGroup(ResourceGroup ResourceGroup) {
        this.ResourceGroup = ResourceGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="PLANNING_CAPACITY", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getPlanningCapacity() {
        return this.PlanningCapacity;
    }
    
    public void setPlanningCapacity(BigDecimal PlanningCapacity) {
        this.PlanningCapacity = PlanningCapacity;
    }

    
    @Column(name="MAXIMUM_CAPACITY", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getMaximumCapacity() {
        return this.MaximumCapacity;
    }
    
    public void setMaximumCapacity(BigDecimal MaximumCapacity) {
        this.MaximumCapacity = MaximumCapacity;
    }

    
    @Column(name="EFF_ON_DATE", columnDefinition="TIMESTAMP")
    public Date getEffOnDate() {
        return this.EffOnDate;
    }
    
    public void setEffOnDate(Date EffOnDate) {
        this.EffOnDate = EffOnDate;
    }

    
    @Column(name="EFF_OFF_DATE", columnDefinition="TIMESTAMP")
    public Date getEffOffDate() {
        return this.EffOffDate;
    }
    
    public void setEffOffDate(Date EffOffDate) {
        this.EffOffDate = EffOffDate;
    }




}


