package com.mg.merp.mfreference.model;

import com.mg.merp.core.model.SysClient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * WeekCalendarChange generated by hbm2java
 */
@Entity
@Table(name = "MF_WEEK_CAL_CHANGE")
public class WeekCalendarChange extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private DayCalendar DayCalThu;

    private DayCalendar DayCalSat;

    private WeekCalendar WeekCal;

    private SysClient SysClient;

    private DayCalendar DayCalMon;

    private DayCalendar DayCalWed;

    private DayCalendar DayCalSun;

    private DayCalendar DayCalTue;

    private DayCalendar DayCalFri;

    private Date EffOnDate;

    private Date EffOffDate;

    public WeekCalendarChange() {
    }

    public WeekCalendarChange(DayCalendar DayCalThu, DayCalendar DayCalSat, WeekCalendar WeekCal, DayCalendar DayCalMon, DayCalendar DayCalWed, DayCalendar DayCalSun, DayCalendar DayCalTue, DayCalendar DayCalFri) {
        this.DayCalThu = DayCalThu;
        this.DayCalSat = DayCalSat;
        this.WeekCal = WeekCal;
        this.DayCalMon = DayCalMon;
        this.DayCalWed = DayCalWed;
        this.DayCalSun = DayCalSun;
        this.DayCalTue = DayCalTue;
        this.DayCalFri = DayCalFri;
    }

    public WeekCalendarChange(DayCalendar DayCalThu, DayCalendar DayCalSat, WeekCalendar WeekCal, SysClient SysClient, DayCalendar DayCalMon, DayCalendar DayCalWed, DayCalendar DayCalSun, DayCalendar DayCalTue, DayCalendar DayCalFri, Date EffOnDate, Date EffOffDate) {
        this.DayCalThu = DayCalThu;
        this.DayCalSat = DayCalSat;
        this.WeekCal = WeekCal;
        this.SysClient = SysClient;
        this.DayCalMon = DayCalMon;
        this.DayCalWed = DayCalWed;
        this.DayCalSun = DayCalSun;
        this.DayCalTue = DayCalTue;
        this.DayCalFri = DayCalFri;
        this.EffOnDate = EffOnDate;
        this.EffOffDate = EffOffDate;
    }

    @SequenceGenerator(name = "generator", sequenceName = "MF_WEEK_CAL_CHANGE_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_THU", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalThu")
    public DayCalendar getDayCalThu() {
        return this.DayCalThu;
    }

    public void setDayCalThu(DayCalendar DayCalThu) {
        this.DayCalThu = DayCalThu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_SAT", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalSat")
    public DayCalendar getDayCalSat() {
        return this.DayCalSat;
    }

    public void setDayCalSat(DayCalendar DayCalSat) {
        this.DayCalSat = DayCalSat;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WEEK_CAL_ID", nullable = false)
    public WeekCalendar getWeekCal() {
        return this.WeekCal;
    }

    public void setWeekCal(WeekCalendar WeekCal) {
        this.WeekCal = WeekCal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_MON", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalMon")
    public DayCalendar getDayCalMon() {
        return this.DayCalMon;
    }

    public void setDayCalMon(DayCalendar DayCalMon) {
        this.DayCalMon = DayCalMon;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_WED", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalWed")
    public DayCalendar getDayCalWed() {
        return this.DayCalWed;
    }

    public void setDayCalWed(DayCalendar DayCalWed) {
        this.DayCalWed = DayCalWed;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_SUN", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalSun")
    public DayCalendar getDayCalSun() {
        return this.DayCalSun;
    }

    public void setDayCalSun(DayCalendar DayCalSun) {
        this.DayCalSun = DayCalSun;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_TUE", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalTue")
    public DayCalendar getDayCalTue() {
        return this.DayCalTue;
    }

    public void setDayCalTue(DayCalendar DayCalTue) {
        this.DayCalTue = DayCalTue;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DAY_CAL_FRI", nullable = false)
    @DataItemName("MfReference.WeekCalendarChange.DayCalFri")
    public DayCalendar getDayCalFri() {
        return this.DayCalFri;
    }

    public void setDayCalFri(DayCalendar DayCalFri) {
        this.DayCalFri = DayCalFri;
    }

    @Column(name = "EFF_ON_DATE", columnDefinition = "TIMESTAMP")
    @DataItemName("MfReference.WeekCalendarChange.EffOnDate")
    public Date getEffOnDate() {
        return this.EffOnDate;
    }

    public void setEffOnDate(Date EffOnDate) {
        this.EffOnDate = EffOnDate;
    }

    @Column(name = "EFF_OFF_DATE", columnDefinition = "TIMESTAMP")
    @DataItemName("MfReference.WeekCalendarChange.EffOffDate")
    public Date getEffOffDate() {
        return this.EffOffDate;
    }

    public void setEffOffDate(Date EffOffDate) {
        this.EffOffDate = EffOffDate;
    }
}

