package com.mg.merp.mfreference.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Contractor;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * WorkCenter generated by hbm2java
 */
@Entity
@Table(name = "MF_WORK_CENTER")
@DataItemName("MfReference.WorkCenter")
public class WorkCenter extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private CostDetail ActCostDetail;

    private WeekCalendar WeekCal;

    private SysClient SysClient;

    private CostDetail StdCostDetail;

    private Cell Cell;

    private Contractor Contractor;

    private ResourceGroup ResourceGroup;

    private String WcCode;

    private String WcName;

    private BigDecimal Efficiency;

    private BigDecimal Utilization;

    private boolean CapacityPlan;

    private boolean CapacitySchedule;

    private boolean MchFlag;

    private Integer MchNumber;

    private boolean LbrFlag;

    private BigDecimal LbrNumber;

    private BigDecimal SchTolerance;

    private BigDecimal QueueTicks;

    private BigDecimal MchRunTotalHrs;

    private BigDecimal LbrSetupTotalHrs;

    private BigDecimal LbrRunTotalHrs;

    private BigDecimal QueueTotalQty;

    private BigDecimal QueueAvgHrs;

    private boolean OutsideFlag;

    private boolean MchBackflushFlag;

    private boolean LbrBackflushFlag;

    private boolean MchBaseOhFlag;

    private boolean LbrBaseOhFlag;

    private boolean MtlBaseOhFlag;

    private boolean ControlPointFlag;

    private BigDecimal WipLbrTotal;

    private BigDecimal WipMtlTotal;

    private BigDecimal WipFohTotal;

    private BigDecimal WipVohTotal;

    private BigDecimal WipOutTotal;

    private BigDecimal LbrSetupAvgRate;

    private BigDecimal LbrRunAvgRate;

    private String Comment;

    public WorkCenter() {
    }

    public WorkCenter(String WcCode) {
        this.WcCode = WcCode;
    }

    public WorkCenter(CostDetail ActCostDetail, WeekCalendar WeekCal, SysClient SysClient, CostDetail StdCostDetail, Cell Cell, Contractor Contractor, ResourceGroup ResourceGroup, String WcCode, String WcName, BigDecimal Efficiency, BigDecimal Utilization, boolean CapacityPlan, boolean CapacitySchedule, boolean MchFlag, Integer MchNumber, boolean LbrFlag, BigDecimal LbrNumber, BigDecimal SchTolerance, BigDecimal QueueTicks, BigDecimal MchRunTotalHrs, BigDecimal LbrSetupTotalHrs, BigDecimal LbrRunTotalHrs, BigDecimal QueueTotalQty, BigDecimal QueueAvgHrs, boolean OutsideFlag, boolean MchBackflushFlag, boolean LbrBackflushFlag, boolean MchBaseOhFlag, boolean LbrBaseOhFlag, boolean MtlBaseOhFlag, boolean ControlPointFlag, BigDecimal WipLbrTotal, BigDecimal WipMtlTotal, BigDecimal WipFohTotal, BigDecimal WipVohTotal, BigDecimal WipOutTotal, BigDecimal LbrSetupAvgRate, BigDecimal LbrRunAvgRate, String Comment) {
        this.ActCostDetail = ActCostDetail;
        this.WeekCal = WeekCal;
        this.SysClient = SysClient;
        this.StdCostDetail = StdCostDetail;
        this.Cell = Cell;
        this.Contractor = Contractor;
        this.ResourceGroup = ResourceGroup;
        this.WcCode = WcCode;
        this.WcName = WcName;
        this.Efficiency = Efficiency;
        this.Utilization = Utilization;
        this.CapacityPlan = CapacityPlan;
        this.CapacitySchedule = CapacitySchedule;
        this.MchFlag = MchFlag;
        this.MchNumber = MchNumber;
        this.LbrFlag = LbrFlag;
        this.LbrNumber = LbrNumber;
        this.SchTolerance = SchTolerance;
        this.QueueTicks = QueueTicks;
        this.MchRunTotalHrs = MchRunTotalHrs;
        this.LbrSetupTotalHrs = LbrSetupTotalHrs;
        this.LbrRunTotalHrs = LbrRunTotalHrs;
        this.QueueTotalQty = QueueTotalQty;
        this.QueueAvgHrs = QueueAvgHrs;
        this.OutsideFlag = OutsideFlag;
        this.MchBackflushFlag = MchBackflushFlag;
        this.LbrBackflushFlag = LbrBackflushFlag;
        this.MchBaseOhFlag = MchBaseOhFlag;
        this.LbrBaseOhFlag = LbrBaseOhFlag;
        this.MtlBaseOhFlag = MtlBaseOhFlag;
        this.ControlPointFlag = ControlPointFlag;
        this.WipLbrTotal = WipLbrTotal;
        this.WipMtlTotal = WipMtlTotal;
        this.WipFohTotal = WipFohTotal;
        this.WipVohTotal = WipVohTotal;
        this.WipOutTotal = WipOutTotal;
        this.LbrSetupAvgRate = LbrSetupAvgRate;
        this.LbrRunAvgRate = LbrRunAvgRate;
        this.Comment = Comment;
    }

    @SequenceGenerator(name = "generator", sequenceName = "MF_WORK_CENTER_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACT_COST_DETAIL_ID")
    public CostDetail getActCostDetail() {
        return this.ActCostDetail;
    }

    public void setActCostDetail(CostDetail ActCostDetail) {
        this.ActCostDetail = ActCostDetail;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WEEK_CAL_ID")
    @DataItemName("MfReference.WorkCenter.WeekCal")
    public WeekCalendar getWeekCal() {
        return this.WeekCal;
    }

    public void setWeekCal(WeekCalendar WeekCal) {
        this.WeekCal = WeekCal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STD_COST_DETAIL_ID")
    public CostDetail getStdCostDetail() {
        return this.StdCostDetail;
    }

    public void setStdCostDetail(CostDetail StdCostDetail) {
        this.StdCostDetail = StdCostDetail;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CELL_ID")
    @DataItemName("MfReference.WorkCenter.Cell")
    public Cell getCell() {
        return this.Cell;
    }

    public void setCell(Cell Cell) {
        this.Cell = Cell;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONTRACTOR_ID")
    @DataItemName("MfReference.WorkCenter.Contractor")
    public Contractor getContractor() {
        return this.Contractor;
    }

    public void setContractor(Contractor Contractor) {
        this.Contractor = Contractor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RESOURCE_GROUP_ID")
    @DataItemName("MfReference.WorkCenter.ResourceGroup")
    public ResourceGroup getResourceGroup() {
        return this.ResourceGroup;
    }

    public void setResourceGroup(ResourceGroup ResourceGroup) {
        this.ResourceGroup = ResourceGroup;
    }

    @Column(name = "WC_CODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 20)
    @DataItemName("MfReference.WorkCenter.WcCode")
    public String getWcCode() {
        return this.WcCode;
    }

    public void setWcCode(String WcCode) {
        this.WcCode = WcCode;
    }

    @Column(name = "WC_NAME", columnDefinition = "VARCHAR", length = 80)
    @DataItemName("MfReference.WorkCenter.WcName")
    public String getWcName() {
        return this.WcName;
    }

    public void setWcName(String WcName) {
        this.WcName = WcName;
    }

    @Column(name = "EFFICIENCY", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.Efficiency")
    public BigDecimal getEfficiency() {
        return this.Efficiency;
    }

    public void setEfficiency(BigDecimal Efficiency) {
        this.Efficiency = Efficiency;
    }

    @Column(name = "UTILIZATION", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.Utilization")
    public BigDecimal getUtilization() {
        return this.Utilization;
    }

    public void setUtilization(BigDecimal Utilization) {
        this.Utilization = Utilization;
    }

    @Column(name = "CAPACITY_PLAN", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.CapacityPlan")
    public boolean isCapacityPlan() {
        return this.CapacityPlan;
    }

    public void setCapacityPlan(boolean CapacityPlan) {
        this.CapacityPlan = CapacityPlan;
    }

    @Column(name = "CAPACITY_SCHEDULE", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.CapacitySchedule")
    public boolean isCapacitySchedule() {
        return this.CapacitySchedule;
    }

    public void setCapacitySchedule(boolean CapacitySchedule) {
        this.CapacitySchedule = CapacitySchedule;
    }

    @Column(name = "MCH_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.MchFlag")
    public boolean isMchFlag() {
        return this.MchFlag;
    }

    public void setMchFlag(boolean MchFlag) {
        this.MchFlag = MchFlag;
    }

    @Column(name = "MCH_NUMBER", columnDefinition = "INTEGER")
    @DataItemName("MfReference.WorkCenter.MchNumber")
    public Integer getMchNumber() {
        return this.MchNumber;
    }

    public void setMchNumber(Integer MchNumber) {
        this.MchNumber = MchNumber;
    }

    @Column(name = "LBR_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.LbrFlag")
    public boolean isLbrFlag() {
        return this.LbrFlag;
    }

    public void setLbrFlag(boolean LbrFlag) {
        this.LbrFlag = LbrFlag;
    }

    @Column(name = "LBR_NUMBER", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("MfReference.WorkCenter.LbrNumber")
    public BigDecimal getLbrNumber() {
        return this.LbrNumber;
    }

    public void setLbrNumber(BigDecimal LbrNumber) {
        this.LbrNumber = LbrNumber;
    }

    @Column(name = "SCH_TOLERANCE", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.SchTolerance")
    public BigDecimal getSchTolerance() {
        return this.SchTolerance;
    }

    public void setSchTolerance(BigDecimal SchTolerance) {
        this.SchTolerance = SchTolerance;
    }

    @Column(name = "QUEUE_TICKS", columnDefinition = "NUMERIC", precision = 18, scale = 0)
    @DataItemName("MfReference.WorkCenter.QueueTicks")
    public BigDecimal getQueueTicks() {
        return this.QueueTicks;
    }

    public void setQueueTicks(BigDecimal QueueTicks) {
        this.QueueTicks = QueueTicks;
    }

    @Column(name = "MCH_RUN_TOTAL_HRS", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.MchRunTotalHrs")
    public BigDecimal getMchRunTotalHrs() {
        return this.MchRunTotalHrs;
    }

    public void setMchRunTotalHrs(BigDecimal MchRunTotalHrs) {
        this.MchRunTotalHrs = MchRunTotalHrs;
    }

    @Column(name = "LBR_SETUP_TOTAL_HRS", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.LbrSetupTotalHrs")
    public BigDecimal getLbrSetupTotalHrs() {
        return this.LbrSetupTotalHrs;
    }

    public void setLbrSetupTotalHrs(BigDecimal LbrSetupTotalHrs) {
        this.LbrSetupTotalHrs = LbrSetupTotalHrs;
    }

    @Column(name = "LBR_RUN_TOTAL_HRS", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.LbrRunTotalHrs")
    public BigDecimal getLbrRunTotalHrs() {
        return this.LbrRunTotalHrs;
    }

    public void setLbrRunTotalHrs(BigDecimal LbrRunTotalHrs) {
        this.LbrRunTotalHrs = LbrRunTotalHrs;
    }

    @Column(name = "QUEUE_TOTAL_QTY", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    @DataItemName("MfReference.WorkCenter.QueueTotalQty")
    public BigDecimal getQueueTotalQty() {
        return this.QueueTotalQty;
    }

    public void setQueueTotalQty(BigDecimal QueueTotalQty) {
        this.QueueTotalQty = QueueTotalQty;
    }

    @Column(name = "QUEUE_AVG_HRS", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("MfReference.WorkCenter.QueueAvgHrs")
    public BigDecimal getQueueAvgHrs() {
        return this.QueueAvgHrs;
    }

    public void setQueueAvgHrs(BigDecimal QueueAvgHrs) {
        this.QueueAvgHrs = QueueAvgHrs;
    }

    @Column(name = "OUTSIDE_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.OutsideFlag")
    public boolean isOutsideFlag() {
        return this.OutsideFlag;
    }

    public void setOutsideFlag(boolean OutsideFlag) {
        this.OutsideFlag = OutsideFlag;
    }

    @Column(name = "MCH_BACKFLUSH_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.MchBackflushFlag")
    public boolean isMchBackflushFlag() {
        return this.MchBackflushFlag;
    }

    public void setMchBackflushFlag(boolean MchBackflushFlag) {
        this.MchBackflushFlag = MchBackflushFlag;
    }

    @Column(name = "LBR_BACKFLUSH_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.LbrBackflushFlag")
    public boolean isLbrBackflushFlag() {
        return this.LbrBackflushFlag;
    }

    public void setLbrBackflushFlag(boolean LbrBackflushFlag) {
        this.LbrBackflushFlag = LbrBackflushFlag;
    }

    @Column(name = "MCH_BASE_OH_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.MchBaseOhFlag")
    public boolean isMchBaseOhFlag() {
        return this.MchBaseOhFlag;
    }

    public void setMchBaseOhFlag(boolean MchBaseOhFlag) {
        this.MchBaseOhFlag = MchBaseOhFlag;
    }

    @Column(name = "LBR_BASE_OH_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.LbrBaseOhFlag")
    public boolean isLbrBaseOhFlag() {
        return this.LbrBaseOhFlag;
    }

    public void setLbrBaseOhFlag(boolean LbrBaseOhFlag) {
        this.LbrBaseOhFlag = LbrBaseOhFlag;
    }

    @Column(name = "MTL_BASE_OH_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.MtlBaseOhFlag")
    public boolean isMtlBaseOhFlag() {
        return this.MtlBaseOhFlag;
    }

    public void setMtlBaseOhFlag(boolean MtlBaseOhFlag) {
        this.MtlBaseOhFlag = MtlBaseOhFlag;
    }

    @Column(name = "CONTROL_POINT_FLAG", columnDefinition = "SMALLINT")
    @DataItemName("MfReference.WorkCenter.ControlPointFlag")
    public boolean isControlPointFlag() {
        return this.ControlPointFlag;
    }

    public void setControlPointFlag(boolean ControlPointFlag) {
        this.ControlPointFlag = ControlPointFlag;
    }

    @Column(name = "WIP_LBR_TOTAL", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getWipLbrTotal() {
        return this.WipLbrTotal;
    }

    public void setWipLbrTotal(BigDecimal WipLbrTotal) {
        this.WipLbrTotal = WipLbrTotal;
    }

    @Column(name = "WIP_MTL_TOTAL", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getWipMtlTotal() {
        return this.WipMtlTotal;
    }

    public void setWipMtlTotal(BigDecimal WipMtlTotal) {
        this.WipMtlTotal = WipMtlTotal;
    }

    @Column(name = "WIP_FOH_TOTAL", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getWipFohTotal() {
        return this.WipFohTotal;
    }

    public void setWipFohTotal(BigDecimal WipFohTotal) {
        this.WipFohTotal = WipFohTotal;
    }

    @Column(name = "WIP_VOH_TOTAL", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getWipVohTotal() {
        return this.WipVohTotal;
    }

    public void setWipVohTotal(BigDecimal WipVohTotal) {
        this.WipVohTotal = WipVohTotal;
    }

    @Column(name = "WIP_OUT_TOTAL", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getWipOutTotal() {
        return this.WipOutTotal;
    }

    public void setWipOutTotal(BigDecimal WipOutTotal) {
        this.WipOutTotal = WipOutTotal;
    }

    @Column(name = "LBR_SETUP_AVG_RATE", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("MfReference.WorkCenter.LbrSetupAvgRate")
    public BigDecimal getLbrSetupAvgRate() {
        return this.LbrSetupAvgRate;
    }

    public void setLbrSetupAvgRate(BigDecimal LbrSetupAvgRate) {
        this.LbrSetupAvgRate = LbrSetupAvgRate;
    }

    @Column(name = "LBR_RUN_AVG_RATE", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("MfReference.WorkCenter.LbrRunAvgRate")
    public BigDecimal getLbrRunAvgRate() {
        return this.LbrRunAvgRate;
    }

    public void setLbrRunAvgRate(BigDecimal LbrRunAvgRate) {
        this.LbrRunAvgRate = LbrRunAvgRate;
    }

    @Column(name = "COMMENT", columnDefinition = "VARCHAR", length = 256)
    @DataItemName("MfReference.WorkCenter.Comment")
    public String getComment() {
        return this.Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }
}

