package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="REF_BANK"
)
public class Bank extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Currency Currency;
     private Country Country;
     private SysClient SysClient;
     private String BIK;
     private boolean BikUnique;
     private String Name;
     private String Branch;
     private String CityType;
     private String City;
     private String Address;
     private String Zip;
     private String CorrAcc;
     private String CorrName;
     private String CorrAddress;
     private String Swift;
     private String Iban;
     private String Bsc;
     private String Phone;
     private String Fax;
     private String Email;
     private String Www;
     private String Comments;

    public Bank() {
    }

    public Bank(Currency Currency, Country Country, SysClient SysClient, String BIK, boolean BikUnique, String Name, String Branch, String CityType, String City, String Address, String Zip, String CorrAcc, String CorrName, String CorrAddress, String Swift, String Iban, String Bsc, String Phone, String Fax, String Email, String Www, String Comments) {
       this.Currency = Currency;
       this.Country = Country;
       this.SysClient = SysClient;
       this.BIK = BIK;
       this.BikUnique = BikUnique;
       this.Name = Name;
       this.Branch = Branch;
       this.CityType = CityType;
       this.City = City;
       this.Address = Address;
       this.Zip = Zip;
       this.CorrAcc = CorrAcc;
       this.CorrName = CorrName;
       this.CorrAddress = CorrAddress;
       this.Swift = Swift;
       this.Iban = Iban;
       this.Bsc = Bsc;
       this.Phone = Phone;
       this.Fax = Fax;
       this.Email = Email;
       this.Www = Www;
       this.Comments = Comments;
    }
   
     @SequenceGenerator(name="generator", sequenceName="REF_BANK_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CORR_ACC_CURRENCY")
    public Currency getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(Currency Currency) {
        this.Currency = Currency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COUNTRY_ID")
    public Country getCountry() {
        return this.Country;
    }
    
    public void setCountry(Country Country) {
        this.Country = Country;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="BIK", columnDefinition="VARCHAR", length=30)
    public String getBIK() {
        return this.BIK;
    }
    
    public void setBIK(String BIK) {
        this.BIK = BIK;
    }

    
    @Column(name="BIK_UNIQUE", columnDefinition="SMALLINT")
    public boolean isBikUnique() {
        return this.BikUnique;
    }
    
    public void setBikUnique(boolean BikUnique) {
        this.BikUnique = BikUnique;
    }

    
    @Column(name="NAME", columnDefinition="VARCHAR", length=256)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    
    @Column(name="BRANCH", columnDefinition="VARCHAR", length=256)
    public String getBranch() {
        return this.Branch;
    }
    
    public void setBranch(String Branch) {
        this.Branch = Branch;
    }

    
    @Column(name="CITY_TYPE", columnDefinition="VARCHAR", length=80)
    public String getCityType() {
        return this.CityType;
    }
    
    public void setCityType(String CityType) {
        this.CityType = CityType;
    }

    
    @Column(name="CITY", columnDefinition="VARCHAR", length=256)
    public String getCity() {
        return this.City;
    }
    
    public void setCity(String City) {
        this.City = City;
    }

    
    @Column(name="ADDRESS", columnDefinition="VARCHAR", length=256)
    public String getAddress() {
        return this.Address;
    }
    
    public void setAddress(String Address) {
        this.Address = Address;
    }

    
    @Column(name="ZIP", columnDefinition="VARCHAR", length=20)
    public String getZip() {
        return this.Zip;
    }
    
    public void setZip(String Zip) {
        this.Zip = Zip;
    }

    
    @Column(name="CORR_ACC", columnDefinition="VARCHAR", length=30)
    public String getCorrAcc() {
        return this.CorrAcc;
    }
    
    public void setCorrAcc(String CorrAcc) {
        this.CorrAcc = CorrAcc;
    }

    
    @Column(name="CORR_NAME", columnDefinition="VARCHAR", length=256)
    public String getCorrName() {
        return this.CorrName;
    }
    
    public void setCorrName(String CorrName) {
        this.CorrName = CorrName;
    }

    
    @Column(name="CORR_ADDRESS", columnDefinition="VARCHAR", length=256)
    public String getCorrAddress() {
        return this.CorrAddress;
    }
    
    public void setCorrAddress(String CorrAddress) {
        this.CorrAddress = CorrAddress;
    }

    
    @Column(name="SWIFT", columnDefinition="VARCHAR", length=30)
    public String getSwift() {
        return this.Swift;
    }
    
    public void setSwift(String Swift) {
        this.Swift = Swift;
    }

    
    @Column(name="IBAN", columnDefinition="VARCHAR", length=256)
    public String getIban() {
        return this.Iban;
    }
    
    public void setIban(String Iban) {
        this.Iban = Iban;
    }

    
    @Column(name="BSC", columnDefinition="VARCHAR", length=30)
    public String getBsc() {
        return this.Bsc;
    }
    
    public void setBsc(String Bsc) {
        this.Bsc = Bsc;
    }

    
    @Column(name="PHONE", columnDefinition="VARCHAR", length=80)
    public String getPhone() {
        return this.Phone;
    }
    
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    
    @Column(name="FAX", columnDefinition="VARCHAR", length=80)
    public String getFax() {
        return this.Fax;
    }
    
    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    
    @Column(name="EMAIL", columnDefinition="VARCHAR", length=50)
    public String getEmail() {
        return this.Email;
    }
    
    public void setEmail(String Email) {
        this.Email = Email;
    }

    
    @Column(name="WWW", columnDefinition="VARCHAR", length=50)
    public String getWww() {
        return this.Www;
    }
    
    public void setWww(String Www) {
        this.Www = Www;
    }

    
    @Column(name="COMMENTS", columnDefinition="VARCHAR", length=256)
    public String getComments() {
        return this.Comments;
    }
    
    public void setComments(String Comments) {
        this.Comments = Comments;
    }




}


