package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name="REF_BANK_ACCOUNT"
)
public class BankAccount extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Bank Bank;
     private SysClient SysClient;
     private Contractor Contractor;
     private Currency Currency;
     private BankAccountType BankAccountType;
     private String Name;
     private String Account;
     private boolean IsDefault;
     private String Unid;

    public BankAccount() {
    }

    public BankAccount(Bank Bank, SysClient SysClient, Contractor Contractor, Currency Currency, BankAccountType BankAccountType, String Name, String Account, boolean IsDefault, String Unid) {
       this.Bank = Bank;
       this.SysClient = SysClient;
       this.Contractor = Contractor;
       this.Currency = Currency;
       this.BankAccountType = BankAccountType;
       this.Name = Name;
       this.Account = Account;
       this.IsDefault = IsDefault;
       this.Unid = Unid;
    }
   
     @SequenceGenerator(name="generator", sequenceName="REF_BANK_ACCOUNT_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BANK_ID")
    public Bank getBank() {
        return this.Bank;
    }
    
    public void setBank(Bank Bank) {
        this.Bank = Bank;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRACTOR_ID")
    public Contractor getContractor() {
        return this.Contractor;
    }
    
    public void setContractor(Contractor Contractor) {
        this.Contractor = Contractor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURCODE")
    public Currency getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(Currency Currency) {
        this.Currency = Currency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_TYPE_ID")
    public BankAccountType getBankAccountType() {
        return this.BankAccountType;
    }
    
    public void setBankAccountType(BankAccountType BankAccountType) {
        this.BankAccountType = BankAccountType;
    }

    
    @Column(name="NAME", columnDefinition="VARCHAR", length=80)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    
    @Column(name="ACCOUNT", columnDefinition="VARCHAR", length=30)
    public String getAccount() {
        return this.Account;
    }
    
    public void setAccount(String Account) {
        this.Account = Account;
    }

    
    @Column(name="IS_DEFAULT", columnDefinition="SMALLINT")
    public boolean isIsDefault() {
        return this.IsDefault;
    }
    
    public void setIsDefault(boolean IsDefault) {
        this.IsDefault = IsDefault;
    }

    
    @Column(name="UNID", unique=true, updatable=false, columnDefinition="VARCHAR", length=32)
    public String getUnid() {
        return this.Unid;
    }
    
    public void setUnid(String Unid) {
        this.Unid = Unid;
    }




}


