package com.mg.merp.reference.model;

import com.mg.merp.baiengine.model.Repository;
import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CatalogFolder generated by hbm2java
 */
@Entity
@Table(name = "CATALOGFOLDER")
@DataItemName("Reference.CatalogFolder")
public class CatalogFolder extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private CatalogFolder CatalogFolder;

    private SysClient SysClient;

    private Repository AlgRepository;

    private String FName;

    private String GroupCode;

    private String BarCode;

    private String PluCode;

    private String FolderTag;

    public CatalogFolder() {
    }

    public CatalogFolder(String FName, String GroupCode) {
        this.FName = FName;
        this.GroupCode = GroupCode;
    }

    public CatalogFolder(CatalogFolder CatalogFolder, SysClient SysClient, Repository AlgRepository, String FName, String GroupCode, String BarCode, String PluCode, String FolderTag) {
        this.CatalogFolder = CatalogFolder;
        this.SysClient = SysClient;
        this.AlgRepository = AlgRepository;
        this.FName = FName;
        this.GroupCode = GroupCode;
        this.BarCode = BarCode;
        this.PluCode = PluCode;
        this.FolderTag = FolderTag;
    }

    @SequenceGenerator(name = "generator", sequenceName = "CATALOGFOLDER_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARENT_ID")
    public CatalogFolder getCatalogFolder() {
        return this.CatalogFolder;
    }

    public void setCatalogFolder(CatalogFolder CatalogFolder) {
        this.CatalogFolder = CatalogFolder;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NUMBERING_ALG_ID")
    @DataItemName("Reference.CatFolder.AlgRepository")
    public Repository getAlgRepository() {
        return this.AlgRepository;
    }

    public void setAlgRepository(Repository AlgRepository) {
        this.AlgRepository = AlgRepository;
    }

    @Column(name = "FNAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Reference.CatFolder.Name")
    public String getFName() {
        return this.FName;
    }

    public void setFName(String FName) {
        this.FName = FName;
    }

    @Column(name = "GROUPCODE", nullable = false, columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.CatFolder.Code")
    public String getGroupCode() {
        return this.GroupCode;
    }

    public void setGroupCode(String GroupCode) {
        this.GroupCode = GroupCode;
    }

    @Column(name = "BARCODE", columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.CatFolder.BarCode")
    public String getBarCode() {
        return this.BarCode;
    }

    public void setBarCode(String BarCode) {
        this.BarCode = BarCode;
    }

    @Column(name = "PLUCODE", columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.CatFolder.PluCode")
    public String getPluCode() {
        return this.PluCode;
    }

    public void setPluCode(String PluCode) {
        this.PluCode = PluCode;
    }

    @Column(name = "FOLDER_TAG", columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Reference.FolderTag")
    public String getFolderTag() {
        return this.FolderTag;
    }

    public void setFolderTag(String FolderTag) {
        this.FolderTag = FolderTag;
    }
}

