package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Contractor generated by hbm2java
 */
@Entity
@Table(name="CONTRACTOR"
)
public class Contractor extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private SysClient SysClient;
     private String Code;
     private String UpCode;
     private String FullName;
     private Integer FolderId;
     private short Kind;

    public Contractor() {
    }

	
    public Contractor(String Code, String UpCode, String FullName, short Kind) {
        this.Code = Code;
        this.UpCode = UpCode;
        this.FullName = FullName;
        this.Kind = Kind;
    }
    public Contractor(SysClient SysClient, String Code, String UpCode, String FullName, Integer FolderId, short Kind) {
       this.SysClient = SysClient;
       this.Code = Code;
       this.UpCode = UpCode;
       this.FullName = FullName;
       this.FolderId = FolderId;
       this.Kind = Kind;
    }
   
     @SequenceGenerator(name="generator", sequenceName="CONTRACTOR_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="UPCODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getUpCode() {
        return this.UpCode;
    }
    
    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

    
    @Column(name="CNAME", nullable=false, columnDefinition="VARCHAR", length=256)
    public String getFullName() {
        return this.FullName;
    }
    
    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    
    @Column(name="FOLDER_ID")
    public Integer getFolderId() {
        return this.FolderId;
    }
    
    public void setFolderId(Integer FolderId) {
        this.FolderId = FolderId;
    }

    
    @Column(name="KIND", nullable=false, columnDefinition="SMALLINT")
    public short getKind() {
        return this.Kind;
    }
    
    public void setKind(short Kind) {
        this.Kind = Kind;
    }




}


