package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "CURRENCY")
public class Currency extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private String UpCode;

    private SysClient SysClient;

    private String Code;

    private String Iso;

    private String BankCode;

    private String FullName;

    private CurrencyGender Gender;

    private String AltName1;

    private String AltName2;

    private String AltName3;

    private String AltUnitName1;

    private String AltUnitName2;

    private String AltUnitName3;

    private BigDecimal RoundPrice;

    private BigDecimal RoundSum;

    private Integer ViewPriority;

    public Currency() {
    }

    public Currency(String UpCode, String Code, String Iso, String BankCode, CurrencyGender Gender, String AltName1, String AltName2, String AltName3, String AltUnitName1, String AltUnitName2, String AltUnitName3, BigDecimal RoundPrice, BigDecimal RoundSum) {
        this.UpCode = UpCode;
        this.Code = Code;
        this.Iso = Iso;
        this.BankCode = BankCode;
        this.Gender = Gender;
        this.AltName1 = AltName1;
        this.AltName2 = AltName2;
        this.AltName3 = AltName3;
        this.AltUnitName1 = AltUnitName1;
        this.AltUnitName2 = AltUnitName2;
        this.AltUnitName3 = AltUnitName3;
        this.RoundPrice = RoundPrice;
        this.RoundSum = RoundSum;
    }

    public Currency(String UpCode, SysClient SysClient, String Code, String Iso, String BankCode, String FullName, CurrencyGender Gender, String AltName1, String AltName2, String AltName3, String AltUnitName1, String AltUnitName2, String AltUnitName3, BigDecimal RoundPrice, BigDecimal RoundSum, Integer ViewPriority) {
        this.UpCode = UpCode;
        this.SysClient = SysClient;
        this.Code = Code;
        this.Iso = Iso;
        this.BankCode = BankCode;
        this.FullName = FullName;
        this.Gender = Gender;
        this.AltName1 = AltName1;
        this.AltName2 = AltName2;
        this.AltName3 = AltName3;
        this.AltUnitName1 = AltUnitName1;
        this.AltUnitName2 = AltUnitName2;
        this.AltUnitName3 = AltUnitName3;
        this.RoundPrice = RoundPrice;
        this.RoundSum = RoundSum;
        this.ViewPriority = ViewPriority;
    }

    @SequenceGenerator(name = "generator", sequenceName = "CURRENCY_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @Column(name = "UPCODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 5)
    public String getUpCode() {
        return this.UpCode;
    }

    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", nullable = false, columnDefinition = "CHAR", length = 5)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "ISO", unique = true, nullable = false, columnDefinition = "CHAR", length = 5)
    public String iso() {
        return this.Iso;
    }

    public void seto(String Iso) {
        this.Iso = Iso;
    }

    @Column(name = "BANK_CODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 5)
    public String getBankCode() {
        return this.BankCode;
    }

    public void setBankCode(String BankCode) {
        this.BankCode = BankCode;
    }

    @Column(name = "CNAME", columnDefinition = "VARCHAR", length = 40)
    public String getFullName() {
        return this.FullName;
    }

    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    @Column(name = "MEN", nullable = false, columnDefinition = "SMALLINT")
    public CurrencyGender getGender() {
        return this.Gender;
    }

    public void setGender(CurrencyGender Gender) {
        this.Gender = Gender;
    }

    @Column(name = "ALTNAME1", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getAltName1() {
        return this.AltName1;
    }

    public void setAltName1(String AltName1) {
        this.AltName1 = AltName1;
    }

    @Column(name = "ALTNAME2", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getAltName2() {
        return this.AltName2;
    }

    public void setAltName2(String AltName2) {
        this.AltName2 = AltName2;
    }

    @Column(name = "ALTNAME3", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getAltName3() {
        return this.AltName3;
    }

    public void setAltName3(String AltName3) {
        this.AltName3 = AltName3;
    }

    @Column(name = "ALTUNITNAME1", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getAltUnitName1() {
        return this.AltUnitName1;
    }

    public void setAltUnitName1(String AltUnitName1) {
        this.AltUnitName1 = AltUnitName1;
    }

    @Column(name = "ALTUNITNAME2", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getAltUnitName2() {
        return this.AltUnitName2;
    }

    public void setAltUnitName2(String AltUnitName2) {
        this.AltUnitName2 = AltUnitName2;
    }

    @Column(name = "ALTUNITNAME3", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getAltUnitName3() {
        return this.AltUnitName3;
    }

    public void setAltUnitName3(String AltUnitName3) {
        this.AltUnitName3 = AltUnitName3;
    }

    @Column(name = "ROUNDPRICE", nullable = false, columnDefinition = "NUMERIC", precision = 18, scale = 6)
    public BigDecimal getRoundPrice() {
        return this.RoundPrice;
    }

    public void setRoundPrice(BigDecimal RoundPrice) {
        this.RoundPrice = RoundPrice;
    }

    @Column(name = "ROUNDSUM", nullable = false, columnDefinition = "NUMERIC", precision = 18, scale = 6)
    public BigDecimal getRoundSum() {
        return this.RoundSum;
    }

    public void setRoundSum(BigDecimal RoundSum) {
        this.RoundSum = RoundSum;
    }

    @Column(name = "VIEWPRIORITY", columnDefinition = "INTEGER")
    public Integer getViewPriority() {
        return this.ViewPriority;
    }

    public void setViewPriority(Integer ViewPriority) {
        this.ViewPriority = ViewPriority;
    }
}

