package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CurrencyRate generated by hbm2java
 */
@Entity
@Table(name = "REF_CURRENCY_RATE")
@DataItemName("Reference.CurrencyRate")
public class CurrencyRate extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Currency Currency2;

    private Currency Currency1;

    private CurrencyRateType CurrencyRateType;

    private CurrencyRateAuthority CurrencyRateAuthority;

    private SysClient SysClient;

    private BigDecimal Rate;

    private Date EffectiveDate;

    public CurrencyRate() {
    }

    public CurrencyRate(BigDecimal Rate, Date EffectiveDate) {
        this.Rate = Rate;
        this.EffectiveDate = EffectiveDate;
    }

    public CurrencyRate(Currency Currency2, Currency Currency1, CurrencyRateType CurrencyRateType, CurrencyRateAuthority CurrencyRateAuthority, SysClient SysClient, BigDecimal Rate, Date EffectiveDate) {
        this.Currency2 = Currency2;
        this.Currency1 = Currency1;
        this.CurrencyRateType = CurrencyRateType;
        this.CurrencyRateAuthority = CurrencyRateAuthority;
        this.SysClient = SysClient;
        this.Rate = Rate;
        this.EffectiveDate = EffectiveDate;
    }

    @SequenceGenerator(name = "generator", sequenceName = "REF_CUR_RATE_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CURRENCY_CODE2")
    public Currency getCurrency2() {
        return this.Currency2;
    }

    public void setCurrency2(Currency Currency2) {
        this.Currency2 = Currency2;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CURRENCY_CODE1")
    public Currency getCurrency1() {
        return this.Currency1;
    }

    public void setCurrency1(Currency Currency1) {
        this.Currency1 = Currency1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RATE_TYPE_ID")
    public CurrencyRateType getCurrencyRateType() {
        return this.CurrencyRateType;
    }

    public void setCurrencyRateType(CurrencyRateType CurrencyRateType) {
        this.CurrencyRateType = CurrencyRateType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RATE_AUTHORITY_ID")
    public CurrencyRateAuthority getCurrencyRateAuthority() {
        return this.CurrencyRateAuthority;
    }

    public void setCurrencyRateAuthority(CurrencyRateAuthority CurrencyRateAuthority) {
        this.CurrencyRateAuthority = CurrencyRateAuthority;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "RATE", nullable = false, columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("Reference.CurRate.Rate")
    public BigDecimal getRate() {
        return this.Rate;
    }

    public void setRate(BigDecimal Rate) {
        this.Rate = Rate;
    }

    @Column(name = "EFFECTIVE_DATE", nullable = false, columnDefinition = "TIMESTAMP")
    @DataItemName("Reference.CurRate.EffectiveDate")
    public Date getEffectiveDate() {
        return this.EffectiveDate;
    }

    public void setEffectiveDate(Date EffectiveDate) {
        this.EffectiveDate = EffectiveDate;
    }
}

