package com.mg.merp.reference.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FamilyMember generated by hbm2java
 */
@Entity
@Table(name="REF_FAMILY_MEMBER"
)
public class FamilyMember extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private NaturalPerson NaturalPerson;
     private SysClient SysClient;
     private FamilyRelation FamilyRelation;
     private String FName;
     private String Patronymic;
     private String Surname;
     private Date Birthdate;

    public FamilyMember() {
    }

	
    public FamilyMember(String FName, String Patronymic, String Surname) {
        this.FName = FName;
        this.Patronymic = Patronymic;
        this.Surname = Surname;
    }
    public FamilyMember(NaturalPerson NaturalPerson, SysClient SysClient, FamilyRelation FamilyRelation, String FName, String Patronymic, String Surname, Date Birthdate) {
       this.NaturalPerson = NaturalPerson;
       this.SysClient = SysClient;
       this.FamilyRelation = FamilyRelation;
       this.FName = FName;
       this.Patronymic = Patronymic;
       this.Surname = Surname;
       this.Birthdate = Birthdate;
    }
   
     @SequenceGenerator(name="generator", sequenceName="REF_FAMILY_MEMBER_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_ID")
    public NaturalPerson getNaturalPerson() {
        return this.NaturalPerson;
    }
    
    public void setNaturalPerson(NaturalPerson NaturalPerson) {
        this.NaturalPerson = NaturalPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RELATION_ID")
    public FamilyRelation getFamilyRelation() {
        return this.FamilyRelation;
    }
    
    public void setFamilyRelation(FamilyRelation FamilyRelation) {
        this.FamilyRelation = FamilyRelation;
    }

    
    @Column(name="FNAME", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }

    
    @Column(name="PATRONYMIC", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getPatronymic() {
        return this.Patronymic;
    }
    
    public void setPatronymic(String Patronymic) {
        this.Patronymic = Patronymic;
    }

    
    @Column(name="SURNAME", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getSurname() {
        return this.Surname;
    }
    
    public void setSurname(String Surname) {
        this.Surname = Surname;
    }

    
    @Column(name="BIRTHDATE", columnDefinition="TIMESTAMP")
    public Date getBirthdate() {
        return this.Birthdate;
    }
    
    public void setBirthdate(Date Birthdate) {
        this.Birthdate = Birthdate;
    }




}


