package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FamilyStatus generated by hbm2java
 */
@Entity
@Table(name="REF_FAMILY_STATUS"
)
public class FamilyStatus extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private NaturalPerson NaturalPerson;
     private SysClient SysClient;
     private FamilyStatusKind FamilyStatusKind;
     private Date BeginDate;

    public FamilyStatus() {
    }

	
    public FamilyStatus(FamilyStatusKind FamilyStatusKind, Date BeginDate) {
        this.FamilyStatusKind = FamilyStatusKind;
        this.BeginDate = BeginDate;
    }
    public FamilyStatus(NaturalPerson NaturalPerson, SysClient SysClient, FamilyStatusKind FamilyStatusKind, Date BeginDate) {
       this.NaturalPerson = NaturalPerson;
       this.SysClient = SysClient;
       this.FamilyStatusKind = FamilyStatusKind;
       this.BeginDate = BeginDate;
    }
   
     @SequenceGenerator(name="generator", sequenceName="REF_FAMILY_STATUS_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_ID")
    public NaturalPerson getNaturalPerson() {
        return this.NaturalPerson;
    }
    
    public void setNaturalPerson(NaturalPerson NaturalPerson) {
        this.NaturalPerson = NaturalPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUSKIND_ID", nullable=false)
    public FamilyStatusKind getFamilyStatusKind() {
        return this.FamilyStatusKind;
    }
    
    public void setFamilyStatusKind(FamilyStatusKind FamilyStatusKind) {
        this.FamilyStatusKind = FamilyStatusKind;
    }

    
    @Column(name="BEGINDATE", nullable=false, columnDefinition="TIMESTAMP")
    public Date getBeginDate() {
        return this.BeginDate;
    }
    
    public void setBeginDate(Date BeginDate) {
        this.BeginDate = BeginDate;
    }




}


