package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formula generated by hbm2java
 */
@Entity
@Table(name = "FORMULA")
public class Formula extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private String UpCode;

    private SysClient SysClient;

    private String Code;

    private String FName;

    private String StoredProcedure;

    private short Context;

    public Formula() {
    }

    public Formula(String UpCode, String Code, short Context) {
        this.UpCode = UpCode;
        this.Code = Code;
        this.Context = Context;
    }

    public Formula(String UpCode, SysClient SysClient, String Code, String FName, String StoredProcedure, short Context) {
        this.UpCode = UpCode;
        this.SysClient = SysClient;
        this.Code = Code;
        this.FName = FName;
        this.StoredProcedure = StoredProcedure;
        this.Context = Context;
    }

    @Id
    @Column(name = "UPCODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 20)
    public String getUpCode() {
        return this.UpCode;
    }

    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "FNAME", columnDefinition = "VARCHAR", length = 80)
    public String getFName() {
        return this.FName;
    }

    public void setFName(String FName) {
        this.FName = FName;
    }

    @Column(name = "STOREDPROCEDURE", columnDefinition = "CHAR", length = 31)
    public String getStoredProcedure() {
        return this.StoredProcedure;
    }

    public void setStoredProcedure(String StoredProcedure) {
        this.StoredProcedure = StoredProcedure;
    }

    @Column(name = "CONTEXT", nullable = false, columnDefinition = "SMALLINT")
    public short getContext() {
        return this.Context;
    }

    public void setContext(short Context) {
        this.Context = Context;
    }
}

