package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * IdentDocKind generated by hbm2java
 */
@Entity
@Table(name = "REF_IDENT_DOC_KIND")
@DataItemName("Reference.IdentDocKind")
public class IdentDocKind extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private SysClient SysClient;

    private String KCode;

    private String KName;

    private Integer LSeriesLength;

    private Integer RSeriesLength;

    private String SeriesDivider;

    private Integer NumberLength;

    public IdentDocKind() {
    }

    public IdentDocKind(String KCode, String KName) {
        this.KCode = KCode;
        this.KName = KName;
    }

    public IdentDocKind(SysClient SysClient, String KCode, String KName, Integer LSeriesLength, Integer RSeriesLength, String SeriesDivider, Integer NumberLength) {
        this.SysClient = SysClient;
        this.KCode = KCode;
        this.KName = KName;
        this.LSeriesLength = LSeriesLength;
        this.RSeriesLength = RSeriesLength;
        this.SeriesDivider = SeriesDivider;
        this.NumberLength = NumberLength;
    }

    @SequenceGenerator(name = "generator", sequenceName = "REF_IDENT_DOC_KIND_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "KCODE", nullable = false, columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.BigCode")
    public String getKCode() {
        return this.KCode;
    }

    public void setKCode(String KCode) {
        this.KCode = KCode;
    }

    @Column(name = "KNAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Reference.Name")
    public String getKName() {
        return this.KName;
    }

    public void setKName(String KName) {
        this.KName = KName;
    }

    @Column(name = "LSERIES_LENGTH", columnDefinition = "INTEGER")
    @DataItemName("Reference.IdentKind.LSeriesLength")
    public Integer getLSeriesLength() {
        return this.LSeriesLength;
    }

    public void setLSeriesLength(Integer LSeriesLength) {
        this.LSeriesLength = LSeriesLength;
    }

    @Column(name = "RSERIES_LENGTH", columnDefinition = "INTEGER")
    @DataItemName("Reference.IdentKind.RSeriesLength")
    public Integer getRSeriesLength() {
        return this.RSeriesLength;
    }

    public void setRSeriesLength(Integer RSeriesLength) {
        this.RSeriesLength = RSeriesLength;
    }

    @Column(name = "SERIES_DIVIDER", columnDefinition = "CHAR", length = 5)
    @DataItemName("Reference.IdentKind.SeriesDivider")
    public String getSeriesDivider() {
        return this.SeriesDivider;
    }

    public void setSeriesDivider(String SeriesDivider) {
        this.SeriesDivider = SeriesDivider;
    }

    @Column(name = "NUMBER_LENGTH", columnDefinition = "INTEGER")
    @DataItemName("Reference.IdentKind.NumberLength")
    public Integer getNumberLength() {
        return this.NumberLength;
    }

    public void setNumberLength(Integer NumberLength) {
        this.NumberLength = NumberLength;
    }
}

