package com.mg.merp.reference.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaturalPersonHist generated by hbm2java
 */
@Entity
@Table(name="REF_NATURAL_PERSON_HIST"
)
public class NaturalPersonHist extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private NaturalPerson NaturalPerson;
     private SysClient SysClient;
     private Date ActDate;
     private String Surname;
     private String Name;
     private String Patronymic;
     private String Inn;

    public NaturalPersonHist() {
    }

    public NaturalPersonHist(NaturalPerson NaturalPerson, SysClient SysClient, Date ActDate, String Surname, String Name, String Patronymic, String Inn) {
       this.NaturalPerson = NaturalPerson;
       this.SysClient = SysClient;
       this.ActDate = ActDate;
       this.Surname = Surname;
       this.Name = Name;
       this.Patronymic = Patronymic;
       this.Inn = Inn;
    }
   
     @SequenceGenerator(name="generator", sequenceName="REF_NATURAL_PERSON_HIST_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_ID")
    public NaturalPerson getNaturalPerson() {
        return this.NaturalPerson;
    }
    
    public void setNaturalPerson(NaturalPerson NaturalPerson) {
        this.NaturalPerson = NaturalPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="ACT_DATE", columnDefinition="TIMESTAMP")
    public Date getActDate() {
        return this.ActDate;
    }
    
    public void setActDate(Date ActDate) {
        this.ActDate = ActDate;
    }

    
    @Column(name="SURNAME", columnDefinition="VARCHAR", length=80)
    public String getSurname() {
        return this.Surname;
    }
    
    public void setSurname(String Surname) {
        this.Surname = Surname;
    }

    
    @Column(name="NAME", columnDefinition="VARCHAR", length=80)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    
    @Column(name="PATRONYMIC", columnDefinition="VARCHAR", length=80)
    public String getPatronymic() {
        return this.Patronymic;
    }
    
    public void setPatronymic(String Patronymic) {
        this.Patronymic = Patronymic;
    }

    
    @Column(name="INN", columnDefinition="CHAR", length=20)
    public String getInn() {
        return this.Inn;
    }
    
    public void setInn(String Inn) {
        this.Inn = Inn;
    }




}


