package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Okdp generated by hbm2java
 */
@Entity
@Table(name = "OKDP")
public class Okdp extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private String UpCode;

    private SysClient SysClient;

    private String Code;

    private String OName;

    public Okdp() {
    }

    public Okdp(String UpCode, String Code, String OName) {
        this.UpCode = UpCode;
        this.Code = Code;
        this.OName = OName;
    }

    public Okdp(String UpCode, SysClient SysClient, String Code, String OName) {
        this.UpCode = UpCode;
        this.SysClient = SysClient;
        this.Code = Code;
        this.OName = OName;
    }

    @Id
    @Column(name = "UPCODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 20)
    public String getUpCode() {
        return this.UpCode;
    }

    public void setUpCode(String UpCode) {
        this.UpCode = UpCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "ONAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    public String getOName() {
        return this.OName;
    }

    public void setOName(String OName) {
        this.OName = OName;
    }
}

