package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * OrgUnit generated by hbm2java
 */
@Entity
@Table(name = "ORGUNIT")
@DataItemName("Reference.OrgUnit")
public class OrgUnit extends com.mg.merp.reference.model.Contractor implements java.io.Serializable {

    private Contractor Partner;

    private OrgUnitType OrgUnitKind;

    private Boolean IsOffice;

    private Boolean IsStore;

    private String FolderTag;

    public OrgUnit() {
    }

    public OrgUnit(String Code, String UpCode, String FullName, short Kind) {
        super(Code, UpCode, FullName, Kind);
    }

    public OrgUnit(SysClient SysClient, String Code, String UpCode, String FullName, Integer FolderId, short Kind, Contractor Partner, OrgUnitType OrgUnitKind, Boolean IsOffice, Boolean IsStore, String FolderTag) {
        super(SysClient, Code, UpCode, FullName, FolderId, Kind);
        this.Partner = Partner;
        this.OrgUnitKind = OrgUnitKind;
        this.IsOffice = IsOffice;
        this.IsStore = IsStore;
        this.FolderTag = FolderTag;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARTNER_ID")
    @DataItemName("Reference.OrgUnit.Partner")
    public Contractor getPartner() {
        return this.Partner;
    }

    public void setPartner(Contractor Partner) {
        this.Partner = Partner;
    }

    @Column(name = "KIND")
    @Enumerated(EnumType.ORDINAL)
    public OrgUnitType getOrgUnitKind() {
        return this.OrgUnitKind;
    }

    public void setOrgUnitKind(OrgUnitType OrgUnitKind) {
        this.OrgUnitKind = OrgUnitKind;
    }

    @Column(name = "IS_OFFICE", columnDefinition = "SMALLINT")
    @DataItemName("Reference.OrgUnit.IsOffice")
    public Boolean isOffice() {
        return this.IsOffice;
    }

    public void setOffice(Boolean IsOffice) {
        this.IsOffice = IsOffice;
    }

    @Column(name = "IS_STORE", columnDefinition = "SMALLINT")
    @DataItemName("Reference.OrgUnit.IsStore")
    public Boolean isStore() {
        return this.IsStore;
    }

    public void setStore(Boolean IsStore) {
        this.IsStore = IsStore;
    }

    @Column(name = "FOLDER_TAG", columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Reference.FolderTag")
    public String getFolderTag() {
        return this.FolderTag;
    }

    public void setFolderTag(String FolderTag) {
        this.FolderTag = FolderTag;
    }
}

