package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PartnEmplEmail generated by hbm2java
 */
@Entity
@Table(name = "REF_PARTN_EMPL_EMAIL")
public class PartnEmplEmail extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private PartnerEmpl PartnEmpl;

    private SysClient SysClient;

    private String EMail;

    private Short IsActive;

    public PartnEmplEmail() {
    }

    public PartnEmplEmail(int Id, String EMail) {
        this.Id = Id;
        this.EMail = EMail;
    }

    public PartnEmplEmail(int Id, PartnerEmpl PartnEmpl, SysClient SysClient, String EMail, Short IsActive) {
        this.Id = Id;
        this.PartnEmpl = PartnEmpl;
        this.SysClient = SysClient;
        this.EMail = EMail;
        this.IsActive = IsActive;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARTNEMPL_ID")
    public PartnerEmpl getPartnEmpl() {
        return this.PartnEmpl;
    }

    public void setPartnEmpl(PartnerEmpl PartnEmpl) {
        this.PartnEmpl = PartnEmpl;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "EMAIL", nullable = false, columnDefinition = "VARCHAR", length = 50)
    public String getEMail() {
        return this.EMail;
    }

    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    @Column(name = "IS_ACTIVE", columnDefinition = "SMALLINT")
    public Short getIsActive() {
        return this.IsActive;
    }

    public void setIsActive(Short IsActive) {
        this.IsActive = IsActive;
    }
}

