package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "PARTNER")
@DataItemName("Reference.Partner")
public class Partner extends com.mg.merp.reference.model.Contractor implements java.io.Serializable {

    private Region Region1;

    private Country Country1;

    private District District1;

    private Country Country;

    private Place Place1;

    private ZipCode ZipCode;

    private Region Region;

    private Currency MaxSupCreditCur;

    private ZipCode ZipCode1;

    private Currency MaxCusCreditCur;

    private District District;

    private NaturalPerson NaturalPerson;

    private Place Place;

    private String INN;

    private String OKONH;

    private String OKPO;

    private String City;

    private String Area;

    private String Address;

    private String CityLegal;

    private String AreaLegal;

    private String AddressLegal;

    private String Comment;

    private BigDecimal MaxSupCredit;

    private Short TermSupCredit;

    private BigDecimal PenaltySup;

    private BigDecimal MaxCusCredit;

    private Short TermCusCredit;

    private BigDecimal PenaltyCus;

    private String KPP;

    private String Zip;

    private String ZipLegal;

    private Boolean INNUnique;

    private String OKVED;

    private String Street;

    private String House;

    private String Building;

    private String Room;

    private String Street1;

    private String House1;

    private String Building1;

    private String Room1;

    private Set<PartnEmplLink> SetOfRefPartnEmplLink = new HashSet<PartnEmplLink>(0);

    private Set<ConfidentialData> SetOfRefConfidentialData = new HashSet<ConfidentialData>(0);

    private Set<PartnerEmpl> SetOfPartnEmpl = new HashSet<PartnerEmpl>(0);

    public Partner() {
    }

    public Partner(String Code, String UpCode, String FullName, short Kind, String INN, String OKONH, String OKPO, String City, String Area, String Address, String CityLegal, String AreaLegal, String AddressLegal) {
        super(Code, UpCode, FullName, Kind);
        this.INN = INN;
        this.OKONH = OKONH;
        this.OKPO = OKPO;
        this.City = City;
        this.Area = Area;
        this.Address = Address;
        this.CityLegal = CityLegal;
        this.AreaLegal = AreaLegal;
        this.AddressLegal = AddressLegal;
    }

    public Partner(SysClient SysClient, String Code, String UpCode, String FullName, Integer FolderId, short Kind, Region Region1, Country Country1, District District1, Country Country, Place Place1, ZipCode ZipCode, Region Region, Currency MaxSupCreditCur, ZipCode ZipCode1, Currency MaxCusCreditCur, District District, NaturalPerson NaturalPerson, Place Place, String INN, String OKONH, String OKPO, String City, String Area, String Address, String CityLegal, String AreaLegal, String AddressLegal, String Comment, BigDecimal MaxSupCredit, Short TermSupCredit, BigDecimal PenaltySup, BigDecimal MaxCusCredit, Short TermCusCredit, BigDecimal PenaltyCus, String KPP, String Zip, String ZipLegal, Boolean INNUnique, String OKVED, String Street, String House, String Building, String Room, String Street1, String House1, String Building1, String Room1, Set<PartnEmplLink> SetOfRefPartnEmplLink, Set<ConfidentialData> SetOfRefConfidentialData, Set<PartnerEmpl> SetOfPartnEmpl) {
        super(SysClient, Code, UpCode, FullName, FolderId, Kind);
        this.Region1 = Region1;
        this.Country1 = Country1;
        this.District1 = District1;
        this.Country = Country;
        this.Place1 = Place1;
        this.ZipCode = ZipCode;
        this.Region = Region;
        this.MaxSupCreditCur = MaxSupCreditCur;
        this.ZipCode1 = ZipCode1;
        this.MaxCusCreditCur = MaxCusCreditCur;
        this.District = District;
        this.NaturalPerson = NaturalPerson;
        this.Place = Place;
        this.INN = INN;
        this.OKONH = OKONH;
        this.OKPO = OKPO;
        this.City = City;
        this.Area = Area;
        this.Address = Address;
        this.CityLegal = CityLegal;
        this.AreaLegal = AreaLegal;
        this.AddressLegal = AddressLegal;
        this.Comment = Comment;
        this.MaxSupCredit = MaxSupCredit;
        this.TermSupCredit = TermSupCredit;
        this.PenaltySup = PenaltySup;
        this.MaxCusCredit = MaxCusCredit;
        this.TermCusCredit = TermCusCredit;
        this.PenaltyCus = PenaltyCus;
        this.KPP = KPP;
        this.Zip = Zip;
        this.ZipLegal = ZipLegal;
        this.INNUnique = INNUnique;
        this.OKVED = OKVED;
        this.Street = Street;
        this.House = House;
        this.Building = Building;
        this.Room = Room;
        this.Street1 = Street1;
        this.House1 = House1;
        this.Building1 = Building1;
        this.Room1 = Room1;
        this.SetOfRefPartnEmplLink = SetOfRefPartnEmplLink;
        this.SetOfRefConfidentialData = SetOfRefConfidentialData;
        this.SetOfPartnEmpl = SetOfPartnEmpl;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REGION1_ID")
    public Region getRegion1() {
        return this.Region1;
    }

    public void setRegion1(Region Region1) {
        this.Region1 = Region1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY1_ID")
    public Country getCountry1() {
        return this.Country1;
    }

    public void setCountry1(Country Country1) {
        this.Country1 = Country1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DISTRICT1_ID")
    public District getDistrict1() {
        return this.District1;
    }

    public void setDistrict1(District District1) {
        this.District1 = District1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    public Country getCountry() {
        return this.Country;
    }

    public void setCountry(Country Country) {
        this.Country = Country;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PLACE1_ID")
    public Place getPlace1() {
        return this.Place1;
    }

    public void setPlace1(Place Place1) {
        this.Place1 = Place1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ZIPCODE_ID")
    public ZipCode getZipCode() {
        return this.ZipCode;
    }

    public void setZipCode(ZipCode ZipCode) {
        this.ZipCode = ZipCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REGION_ID")
    public Region getRegion() {
        return this.Region;
    }

    public void setRegion(Region Region) {
        this.Region = Region;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MAXSUPCREDITCUR")
    @DataItemName("Reference.Partner.SupCurrency")
    public Currency getMaxSupCreditCur() {
        return this.MaxSupCreditCur;
    }

    public void setMaxSupCreditCur(Currency MaxSupCreditCur) {
        this.MaxSupCreditCur = MaxSupCreditCur;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ZIPCODE1_ID")
    public ZipCode getZipCode1() {
        return this.ZipCode1;
    }

    public void setZipCode1(ZipCode ZipCode1) {
        this.ZipCode1 = ZipCode1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MAXCUSCREDITCUR")
    @DataItemName("Reference.Partner.CusCurrency")
    public Currency getMaxCusCreditCur() {
        return this.MaxCusCreditCur;
    }

    public void setMaxCusCreditCur(Currency MaxCusCreditCur) {
        this.MaxCusCreditCur = MaxCusCreditCur;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DISTRICT_ID")
    public District getDistrict() {
        return this.District;
    }

    public void setDistrict(District District) {
        this.District = District;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PERSON_ID")
    public NaturalPerson getNaturalPerson() {
        return this.NaturalPerson;
    }

    public void setNaturalPerson(NaturalPerson NaturalPerson) {
        this.NaturalPerson = NaturalPerson;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PLACE_ID")
    public Place getPlace() {
        return this.Place;
    }

    public void setPlace(Place Place) {
        this.Place = Place;
    }

    @Column(name = "INN", nullable = false, columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.Partner.Inn")
    public String getINN() {
        return this.INN;
    }

    public void setINN(String INN) {
        this.INN = INN;
    }

    @Column(name = "OKONH", nullable = false, columnDefinition = "VARCHAR", length = 40)
    @DataItemName("Reference.Partner.OKONH")
    public String getOKONH() {
        return this.OKONH;
    }

    public void setOKONH(String OKONH) {
        this.OKONH = OKONH;
    }

    @Column(name = "OKPO", nullable = false, columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.Partner.OKPO")
    public String getOKPO() {
        return this.OKPO;
    }

    public void setOKPO(String OKPO) {
        this.OKPO = OKPO;
    }

    @Column(name = "CITY", nullable = false, columnDefinition = "VARCHAR", length = 40)
    @DataItemName("Reference.City")
    public String getCity() {
        return this.City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    @Column(name = "AREA", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getArea() {
        return this.Area;
    }

    public void setArea(String Area) {
        this.Area = Area;
    }

    @Column(name = "ADDRESS", nullable = false, columnDefinition = "VARCHAR", length = 256)
    public String getAddress() {
        return this.Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    @Column(name = "CITYLEGAL", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getCityLegal() {
        return this.CityLegal;
    }

    public void setCityLegal(String CityLegal) {
        this.CityLegal = CityLegal;
    }

    @Column(name = "AREALEGAL", nullable = false, columnDefinition = "VARCHAR", length = 40)
    public String getAreaLegal() {
        return this.AreaLegal;
    }

    public void setAreaLegal(String AreaLegal) {
        this.AreaLegal = AreaLegal;
    }

    @Column(name = "ADDRESSLEGAL", nullable = false, columnDefinition = "VARCHAR", length = 256)
    public String getAddressLegal() {
        return this.AddressLegal;
    }

    public void setAddressLegal(String AddressLegal) {
        this.AddressLegal = AddressLegal;
    }

    @Column(name = "COMMENT", columnDefinition = "VARCHAR", length = 256)
    @DataItemName("Reference.Partner.Comment")
    public String getComment() {
        return this.Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }

    @Column(name = "MAXSUPCREDIT", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Reference.Partner.SupKredit")
    public BigDecimal getMaxSupCredit() {
        return this.MaxSupCredit;
    }

    public void setMaxSupCredit(BigDecimal MaxSupCredit) {
        this.MaxSupCredit = MaxSupCredit;
    }

    @Column(name = "TERMSUPCREDIT", columnDefinition = "SMALLINT")
    @DataItemName("Reference.Partner.TermSupCredit")
    public Short getTermSupCredit() {
        return this.TermSupCredit;
    }

    public void setTermSupCredit(Short TermSupCredit) {
        this.TermSupCredit = TermSupCredit;
    }

    @Column(name = "PENALTYSUP", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("Reference.Partner.PenaltySup")
    public BigDecimal getPenaltySup() {
        return this.PenaltySup;
    }

    public void setPenaltySup(BigDecimal PenaltySup) {
        this.PenaltySup = PenaltySup;
    }

    @Column(name = "MAXCUSCREDIT", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    @DataItemName("Reference.Partner.CusKredit")
    public BigDecimal getMaxCusCredit() {
        return this.MaxCusCredit;
    }

    public void setMaxCusCredit(BigDecimal MaxCusCredit) {
        this.MaxCusCredit = MaxCusCredit;
    }

    @Column(name = "TERMCUSCREDIT", columnDefinition = "SMALLINT")
    @DataItemName("Reference.Partner.TermCusCredit")
    public Short getTermCusCredit() {
        return this.TermCusCredit;
    }

    public void setTermCusCredit(Short TermCusCredit) {
        this.TermCusCredit = TermCusCredit;
    }

    @Column(name = "PENALTYCUS", columnDefinition = "NUMERIC", precision = 18, scale = 6)
    @DataItemName("Reference.Partner.PenaltyCus")
    public BigDecimal getPenaltyCus() {
        return this.PenaltyCus;
    }

    public void setPenaltyCus(BigDecimal PenaltyCus) {
        this.PenaltyCus = PenaltyCus;
    }

    @Column(name = "KPP", columnDefinition = "CHAR", length = 20)
    @DataItemName("Reference.Partner.Kpp")
    public String getKPP() {
        return this.KPP;
    }

    public void setKPP(String KPP) {
        this.KPP = KPP;
    }

    @Column(name = "ZIP", columnDefinition = "VARCHAR", length = 20)
    public String getZip() {
        return this.Zip;
    }

    public void setZip(String Zip) {
        this.Zip = Zip;
    }

    @Column(name = "ZIPLEGAL", columnDefinition = "VARCHAR", length = 20)
    public String getZipLegal() {
        return this.ZipLegal;
    }

    public void setZipLegal(String ZipLegal) {
        this.ZipLegal = ZipLegal;
    }

    @Column(name = "INN_UNIQUE", columnDefinition = "SMALLINT")
    @DataItemName("Reference.Partner.INNUnique")
    public Boolean getINNUnique() {
        return this.INNUnique;
    }

    public void setINNUnique(Boolean INNUnique) {
        this.INNUnique = INNUnique;
    }

    @Column(name = "OKVED", columnDefinition = "VARCHAR", length = 40)
    @DataItemName("Reference.Partner.OKVED")
    public String getOKVED() {
        return this.OKVED;
    }

    public void setOKVED(String OKVED) {
        this.OKVED = OKVED;
    }

    @Column(name = "STREET", columnDefinition = "VARCHAR", length = 128)
    @DataItemName("Reference.Street")
    public String getStreet() {
        return this.Street;
    }

    public void setStreet(String Street) {
        this.Street = Street;
    }

    @Column(name = "HOUSE", columnDefinition = "VARCHAR", length = 20)
    @DataItemName("Reference.House")
    public String getHouse() {
        return this.House;
    }

    public void setHouse(String House) {
        this.House = House;
    }

    @Column(name = "BUILDING", columnDefinition = "VARCHAR", length = 20)
    @DataItemName("Reference.Block")
    public String getBuilding() {
        return this.Building;
    }

    public void setBuilding(String Building) {
        this.Building = Building;
    }

    @Column(name = "ROOM", columnDefinition = "VARCHAR", length = 20)
    @DataItemName("Reference.Flat")
    public String getRoom() {
        return this.Room;
    }

    public void setRoom(String Room) {
        this.Room = Room;
    }

    @Column(name = "STREET1", columnDefinition = "VARCHAR", length = 128)
    @DataItemName("Reference.Street")
    public String getStreet1() {
        return this.Street1;
    }

    public void setStreet1(String Street1) {
        this.Street1 = Street1;
    }

    @Column(name = "HOUSE1", columnDefinition = "VARCHAR", length = 20)
    @DataItemName("Reference.House")
    public String getHouse1() {
        return this.House1;
    }

    public void setHouse1(String House1) {
        this.House1 = House1;
    }

    @Column(name = "BUILDING1", columnDefinition = "VARCHAR", length = 20)
    @DataItemName("Reference.Block")
    public String getBuilding1() {
        return this.Building1;
    }

    public void setBuilding1(String Building1) {
        this.Building1 = Building1;
    }

    @Column(name = "ROOM1", columnDefinition = "VARCHAR", length = 20)
    @DataItemName("Reference.Flat")
    public String getRoom1() {
        return this.Room1;
    }

    public void setRoom1(String Room1) {
        this.Room1 = Room1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Partner")
    public Set<PartnEmplLink> getSetOfRefPartnEmplLink() {
        return this.SetOfRefPartnEmplLink;
    }

    public void setSetOfRefPartnEmplLink(Set<PartnEmplLink> SetOfRefPartnEmplLink) {
        this.SetOfRefPartnEmplLink = SetOfRefPartnEmplLink;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Partner")
    public Set<ConfidentialData> getSetOfRefConfidentialData() {
        return this.SetOfRefConfidentialData;
    }

    public void setSetOfRefConfidentialData(Set<ConfidentialData> SetOfRefConfidentialData) {
        this.SetOfRefConfidentialData = SetOfRefConfidentialData;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Partner")
    public Set<PartnerEmpl> getSetOfPartnEmpl() {
        return this.SetOfPartnEmpl;
    }

    public void setSetOfPartnEmpl(Set<PartnerEmpl> SetOfPartnEmpl) {
        this.SetOfPartnEmpl = SetOfPartnEmpl;
    }
}

