package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PriceListSpecPriceId generated by hbm2java
 */
@Embeddable
public class PriceListSpecPriceId extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private PriceListSpec PriceListSpec;
     private PriceType PriceType;
     private SysClient SysClient;

    public PriceListSpecPriceId() {
    }

    public PriceListSpecPriceId(PriceListSpec PriceListSpec, PriceType PriceType, SysClient SysClient) {
       this.PriceListSpec = PriceListSpec;
       this.PriceType = PriceType;
       this.SysClient = SysClient;
    }
   


    @Column(name="PRICELISTSPEC_ID", nullable=false)
    public PriceListSpec getPriceListSpec() {
        return this.PriceListSpec;
    }
    
    public void setPriceListSpec(PriceListSpec PriceListSpec) {
        this.PriceListSpec = PriceListSpec;
    }


    @Column(name="PRICETYPE_ID", nullable=false)
    public PriceType getPriceType() {
        return this.PriceType;
    }
    
    public void setPriceType(PriceType PriceType) {
        this.PriceType = PriceType;
    }


    @Column(name="CLIENT_ID", nullable=false)
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }




}


