package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PriceListSpecPrice generated by hbm2java
 */
@Entity
@Table(name="PRICELISTSPEC_PRICE"
)
public class PriceListSpecPrice extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private PriceListSpecPriceId Id;
     private BigDecimal Price;

    public PriceListSpecPrice() {
    }

    public PriceListSpecPrice(PriceListSpecPriceId Id, BigDecimal Price) {
       this.Id = Id;
       this.Price = Price;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="PriceListSpec", column=@Column(name="PRICELISTSPEC_ID", nullable=false) ), 
        @AttributeOverride(name="PriceType", column=@Column(name="PRICETYPE_ID", nullable=false) ), 
        @AttributeOverride(name="SysClient", column=@Column(name="CLIENT_ID", nullable=false) ) } )
    public PriceListSpecPriceId getId() {
        return this.Id;
    }
    
    public void setId(PriceListSpecPriceId Id) {
        this.Id = Id;
    }

    
    @Column(name="PRICE", nullable=false, columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getPrice() {
        return this.Price;
    }
    
    public void setPrice(BigDecimal Price) {
        this.Price = Price;
    }




}


