package com.mg.merp.reference.model;

import static javax.persistence.GenerationType.SEQUENCE;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.merp.core.model.SysClient;

/**
 * PriceListSpec generated by hbm2java
 */
@Entity
@Table(name = "PRICELISTSPEC")
public class PriceListSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Catalog Catalog;

    private PriceListFolder Folder;

    private SysClient SysClient;

    private BigDecimal Price;

    private BigDecimal LastCost;

    private String SName;

    private boolean Canceled;

    private String Unid;

    private Integer PriceListHeadId;

    private Date ActDate;

    private Date ActDateTill;

    private String InternalCode;

    private List<PriceListSpecPrice> PriceListSpecPrice = new ArrayList<PriceListSpecPrice>(0);

    public PriceListSpec() {
    }

    public PriceListSpec(Date ActDate, Date ActDateTill) {
        this.ActDate = ActDate;
        this.ActDateTill = ActDateTill;
    }

    public PriceListSpec(Catalog Catalog, PriceListFolder Folder, SysClient SysClient, BigDecimal Price, BigDecimal LastCost, String SName, boolean Canceled, String Unid, Integer PriceListHeadId, Date ActDate, Date ActDateTill, String InternalCode, List<PriceListSpecPrice> PriceListSpecPrice) {
        this.Catalog = Catalog;
        this.Folder = Folder;
        this.SysClient = SysClient;
        this.Price = Price;
        this.LastCost = LastCost;
        this.SName = SName;
        this.Canceled = Canceled;
        this.Unid = Unid;
        this.PriceListHeadId = PriceListHeadId;
        this.ActDate = ActDate;
        this.ActDateTill = ActDateTill;
        this.InternalCode = InternalCode;
        this.PriceListSpecPrice = PriceListSpecPrice;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PRICELISTSPEC_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATALOG_ID")
    public Catalog getCatalog() {
        return this.Catalog;
    }

    public void setCatalog(Catalog Catalog) {
        this.Catalog = Catalog;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FOLDER_ID")
    public PriceListFolder getFolder() {
        return this.Folder;
    }

    public void setFolder(PriceListFolder Folder) {
        this.Folder = Folder;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "PRICE", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getPrice() {
        return this.Price;
    }

    public void setPrice(BigDecimal Price) {
        this.Price = Price;
    }

    @Column(name = "LASTCOST", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getLastCost() {
        return this.LastCost;
    }

    public void setLastCost(BigDecimal LastCost) {
        this.LastCost = LastCost;
    }

    @Column(name = "SNAME", columnDefinition = "VARCHAR", length = 80)
    public String getSName() {
        return this.SName;
    }

    public void setSName(String SName) {
        this.SName = SName;
    }

    @Column(name = "CANCELED", columnDefinition = "SMALLINT")
    public boolean isCanceled() {
        return this.Canceled;
    }

    public void setCanceled(boolean Canceled) {
        this.Canceled = Canceled;
    }

    @Column(name = "UNID", unique = true, updatable = false, columnDefinition = "VARCHAR", length = 32)
    public String getUnid() {
        return this.Unid;
    }

    public void setUnid(String Unid) {
        this.Unid = Unid;
    }

    @Column(name = "PRICELISTHEAD_ID", columnDefinition = "INTEGER")
    public Integer getPriceListHeadId() {
        return this.PriceListHeadId;
    }

    public void setPriceListHeadId(Integer PriceListHeadId) {
        this.PriceListHeadId = PriceListHeadId;
    }

    @Column(name = "ACTDATE", nullable = false, columnDefinition = "TIMESTAMP")
    public Date getActDate() {
        return this.ActDate;
    }

    public void setActDate(Date ActDate) {
        this.ActDate = ActDate;
    }

    @Column(name = "ACTDATETILL", nullable = false, columnDefinition = "TIMESTAMP")
    public Date getActDateTill() {
        return this.ActDateTill;
    }

    public void setActDateTill(Date ActDateTill) {
        this.ActDateTill = ActDateTill;
    }

    @Column(name = "INTERNALCODE", columnDefinition = "VARCHAR", length = 80)
    public String getInternalCode() {
        return this.InternalCode;
    }

    public void setInternalCode(String InternalCode) {
        this.InternalCode = InternalCode;
    }

    @OneToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY, mappedBy = "unresolved")
    public List<PriceListSpecPrice> getPriceListSpecPrice() {
        return this.PriceListSpecPrice;
    }

    public void setPriceListSpecPrice(List<PriceListSpecPrice> PriceListSpecPrice) {
        this.PriceListSpecPrice = PriceListSpecPrice;
    }
}

