package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TaxGroup generated by hbm2java
 */
@Entity
@Table(name="TAXGROUP"
)
public class TaxGroup extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private SysClient SysClient;
     private String Code;
     private String TgName;
     private Set<TaxLink> TaxLinks = new HashSet<TaxLink>(0);

    public TaxGroup() {
    }

    public TaxGroup(SysClient SysClient, String Code, String TgName, Set<TaxLink> TaxLinks) {
       this.SysClient = SysClient;
       this.Code = Code;
       this.TgName = TgName;
       this.TaxLinks = TaxLinks;
    }
   
     @SequenceGenerator(name="generator", sequenceName="TAXGROUP_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="CODE", columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="TGNAME", columnDefinition="VARCHAR", length=80)
    public String getTgName() {
        return this.TgName;
    }
    
    public void setTgName(String TgName) {
        this.TgName = TgName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="TaxGroup")
    public Set<TaxLink> getTaxLinks() {
        return this.TaxLinks;
    }
    
    public void setTaxLinks(Set<TaxLink> TaxLinks) {
        this.TaxLinks = TaxLinks;
    }




}


