package com.mg.merp.reference.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TaxSumBuf generated by hbm2java
 */
@Entity
@Table(name="TAXSUM_BUF"
)
public class TaxSumBuf extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private TaxSumBufId id;

    public TaxSumBuf() {
    }

    public TaxSumBuf(TaxSumBufId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="SysClient", column=@Column(name="CLIENT_ID", nullable=false) ), 
        @AttributeOverride(name="SpecificationId", column=@Column(name="SPECIFICATION_ID", nullable=false) ), 
        @AttributeOverride(name="TaxId", column=@Column(name="TAX_ID", nullable=false) ), 
        @AttributeOverride(name="Summ", column=@Column(name="SUMM", nullable=false) ) } )
    public TaxSumBufId getId() {
        return this.id;
    }
    
    public void setId(TaxSumBufId id) {
        this.id = id;
    }




}


