package com.mg.merp.reference.model;

import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ZipCode generated by hbm2java
 */
@Entity
@Table(name = "REF_ZIPCODE")
public class ZipCode extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private District District;

    private Country Country;

    private SysClient SysClient;

    private Place Place;

    private Region Region;

    private String Code;

    public ZipCode() {
    }

    public ZipCode(String Code) {
        this.Code = Code;
    }

    public ZipCode(District District, Country Country, SysClient SysClient, Place Place, Region Region, String Code) {
        this.District = District;
        this.Country = Country;
        this.SysClient = SysClient;
        this.Place = Place;
        this.Region = Region;
        this.Code = Code;
    }

    @SequenceGenerator(name = "generator", sequenceName = "REF_ZIPCODE_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DISTRICT_ID")
    public District getDistrict() {
        return this.District;
    }

    public void setDistrict(District District) {
        this.District = District;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUNTRY_ID")
    public Country getCountry() {
        return this.Country;
    }

    public void setCountry(Country Country) {
        this.Country = Country;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PLACE_ID")
    public Place getPlace() {
        return this.Place;
    }

    public void setPlace(Place Place) {
        this.Place = Place;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REGION_ID")
    public Region getRegion() {
        return this.Region;
    }

    public void setRegion(Region Region) {
        this.Region = Region;
    }

    @Column(name = "CODE", nullable = false, columnDefinition = "VARCHAR", length = 20)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }
}

