package com.mg.merp.salary.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CalcListSection generated by hbm2java
 */
@Entity
@Table(name="SAL_CALC_LIST_SECTION"
)
public class CalcListSection extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private CalcList CalcList;
     private SysClient SysClient;
     private CalcListSectionRef CalcListSectionRef;
     private BigDecimal TotalSumma;
     private Set<CalcListFee> CalcListFees = new HashSet<CalcListFee>(0);

    public CalcListSection() {
    }

    public CalcListSection(CalcList CalcList, SysClient SysClient, CalcListSectionRef CalcListSectionRef, BigDecimal TotalSumma, Set<CalcListFee> CalcListFees) {
       this.CalcList = CalcList;
       this.SysClient = SysClient;
       this.CalcListSectionRef = CalcListSectionRef;
       this.TotalSumma = TotalSumma;
       this.CalcListFees = CalcListFees;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SAL_CALC_LIST_SECTION_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALC_LIST_ID")
    public CalcList getCalcList() {
        return this.CalcList;
    }
    
    public void setCalcList(CalcList CalcList) {
        this.CalcList = CalcList;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALC_LIST_SECTION_REF_ID")
    public CalcListSectionRef getCalcListSectionRef() {
        return this.CalcListSectionRef;
    }
    
    public void setCalcListSectionRef(CalcListSectionRef CalcListSectionRef) {
        this.CalcListSectionRef = CalcListSectionRef;
    }

    
    @Column(name="TOTAL_SUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getTotalSumma() {
        return this.TotalSumma;
    }
    
    public void setTotalSumma(BigDecimal TotalSumma) {
        this.TotalSumma = TotalSumma;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="CalcListSection")
    public Set<CalcListFee> getCalcListFees() {
        return this.CalcListFees;
    }
    
    public void setCalcListFees(Set<CalcListFee> CalcListFees) {
        this.CalcListFees = CalcListFees;
    }




}


