package com.mg.merp.salary.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DiscountKind generated by hbm2java
 */
@Entity
@Table(name="SAL_DISCOUNTKIND"
)
public class DiscountKind extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private SysClient SysClient;
     private String DCode;
     private String DName;
     private BigDecimal MinSalaryNumber;
     private BigDecimal FixedSum;
     private Date BeginDate;
     private BigDecimal ActionPeriod;
     private boolean IsAccumulating;

    public DiscountKind() {
    }

	
    public DiscountKind(String DCode, String DName, Date BeginDate) {
        this.DCode = DCode;
        this.DName = DName;
        this.BeginDate = BeginDate;
    }
    public DiscountKind(SysClient SysClient, String DCode, String DName, BigDecimal MinSalaryNumber, BigDecimal FixedSum, Date BeginDate, BigDecimal ActionPeriod, boolean IsAccumulating) {
       this.SysClient = SysClient;
       this.DCode = DCode;
       this.DName = DName;
       this.MinSalaryNumber = MinSalaryNumber;
       this.FixedSum = FixedSum;
       this.BeginDate = BeginDate;
       this.ActionPeriod = ActionPeriod;
       this.IsAccumulating = IsAccumulating;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SAL_DISCOUNTKIND_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="DCODE", nullable=false, columnDefinition="CHAR", length=20)
    public String getDCode() {
        return this.DCode;
    }
    
    public void setDCode(String DCode) {
        this.DCode = DCode;
    }

    
    @Column(name="DNAME", nullable=false, columnDefinition="VARCHAR", length=80)
    public String getDName() {
        return this.DName;
    }
    
    public void setDName(String DName) {
        this.DName = DName;
    }

    
    @Column(name="MINSALARYNUMBER", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getMinSalaryNumber() {
        return this.MinSalaryNumber;
    }
    
    public void setMinSalaryNumber(BigDecimal MinSalaryNumber) {
        this.MinSalaryNumber = MinSalaryNumber;
    }

    
    @Column(name="FIXEDSUM", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getFixedSum() {
        return this.FixedSum;
    }
    
    public void setFixedSum(BigDecimal FixedSum) {
        this.FixedSum = FixedSum;
    }

    
    @Column(name="BEGINDATE", nullable=false, columnDefinition="TIMESTAMP")
    public Date getBeginDate() {
        return this.BeginDate;
    }
    
    public void setBeginDate(Date BeginDate) {
        this.BeginDate = BeginDate;
    }

    
    @Column(name="ACTIONPERIOD", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getActionPeriod() {
        return this.ActionPeriod;
    }
    
    public void setActionPeriod(BigDecimal ActionPeriod) {
        this.ActionPeriod = ActionPeriod;
    }

    
    @Column(name="IS_ACCUMULATING", columnDefinition="SMALLINT")
    public boolean isIsAccumulating() {
        return this.IsAccumulating;
    }
    
    public void setIsAccumulating(boolean IsAccumulating) {
        this.IsAccumulating = IsAccumulating;
    }




}


