package com.mg.merp.salary.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.personnelref.model.CalcPeriod;
import com.mg.merp.personnelref.model.CostsAnl;
import com.mg.merp.personnelref.model.PersonalAccount;
import com.mg.merp.personnelref.model.PositionFill;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FeeModel generated by hbm2java
 */
@Entity
@Table(name="SAL_FEE_MODEL"
)
public class FeeModel extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private CostsAnl CostsAnl1;
     private CostsAnl CostsAnl3;
     private CostsAnl CostsAnl2;
     private CostsAnl CostsAnl4;
     private PersonalAccount PersonalAccount;
     private FeeRef FeeRef;
     private PositionFill PositionFill;
     private SysClient SysClient;
     private CostsAnl CostsAnl5;
     private RollKind RollKind;
     private CalcPeriod CalcPeriod;
     private Date BeginDate;
     private Date EndDate;
     private BigDecimal Summa;
     private boolean UseBasicPosition;
     private Set<FeeModelParam> FeeModelParams = new HashSet<FeeModelParam>(0);

    public FeeModel() {
    }

    public FeeModel(CostsAnl CostsAnl1, CostsAnl CostsAnl3, CostsAnl CostsAnl2, CostsAnl CostsAnl4, PersonalAccount PersonalAccount, FeeRef FeeRef, PositionFill PositionFill, SysClient SysClient, CostsAnl CostsAnl5, RollKind RollKind, CalcPeriod CalcPeriod, Date BeginDate, Date EndDate, BigDecimal Summa, boolean UseBasicPosition, Set<FeeModelParam> FeeModelParams) {
       this.CostsAnl1 = CostsAnl1;
       this.CostsAnl3 = CostsAnl3;
       this.CostsAnl2 = CostsAnl2;
       this.CostsAnl4 = CostsAnl4;
       this.PersonalAccount = PersonalAccount;
       this.FeeRef = FeeRef;
       this.PositionFill = PositionFill;
       this.SysClient = SysClient;
       this.CostsAnl5 = CostsAnl5;
       this.RollKind = RollKind;
       this.CalcPeriod = CalcPeriod;
       this.BeginDate = BeginDate;
       this.EndDate = EndDate;
       this.Summa = Summa;
       this.UseBasicPosition = UseBasicPosition;
       this.FeeModelParams = FeeModelParams;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SAL_FEE_MODEL_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTS_ANL1_ID")
    public CostsAnl getCostsAnl1() {
        return this.CostsAnl1;
    }
    
    public void setCostsAnl1(CostsAnl CostsAnl1) {
        this.CostsAnl1 = CostsAnl1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTS_ANL3_ID")
    public CostsAnl getCostsAnl3() {
        return this.CostsAnl3;
    }
    
    public void setCostsAnl3(CostsAnl CostsAnl3) {
        this.CostsAnl3 = CostsAnl3;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTS_ANL2_ID")
    public CostsAnl getCostsAnl2() {
        return this.CostsAnl2;
    }
    
    public void setCostsAnl2(CostsAnl CostsAnl2) {
        this.CostsAnl2 = CostsAnl2;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTS_ANL4_ID")
    public CostsAnl getCostsAnl4() {
        return this.CostsAnl4;
    }
    
    public void setCostsAnl4(CostsAnl CostsAnl4) {
        this.CostsAnl4 = CostsAnl4;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSONALACCOUNT_ID")
    public PersonalAccount getPersonalAccount() {
        return this.PersonalAccount;
    }
    
    public void setPersonalAccount(PersonalAccount PersonalAccount) {
        this.PersonalAccount = PersonalAccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FEE_REF_ID")
    public FeeRef getFeeRef() {
        return this.FeeRef;
    }
    
    public void setFeeRef(FeeRef FeeRef) {
        this.FeeRef = FeeRef;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="POSITIONFILL_ID")
    public PositionFill getPositionFill() {
        return this.PositionFill;
    }
    
    public void setPositionFill(PositionFill PositionFill) {
        this.PositionFill = PositionFill;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COSTS_ANL5_ID")
    public CostsAnl getCostsAnl5() {
        return this.CostsAnl5;
    }
    
    public void setCostsAnl5(CostsAnl CostsAnl5) {
        this.CostsAnl5 = CostsAnl5;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLL_KIND_ID")
    public RollKind getRollKind() {
        return this.RollKind;
    }
    
    public void setRollKind(RollKind RollKind) {
        this.RollKind = RollKind;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALC_PERIOD_ID")
    public CalcPeriod getCalcPeriod() {
        return this.CalcPeriod;
    }
    
    public void setCalcPeriod(CalcPeriod CalcPeriod) {
        this.CalcPeriod = CalcPeriod;
    }

    
    @Column(name="BEGINDATE", columnDefinition="TIMESTAMP")
    public Date getBeginDate() {
        return this.BeginDate;
    }
    
    public void setBeginDate(Date BeginDate) {
        this.BeginDate = BeginDate;
    }

    
    @Column(name="ENDDATE", columnDefinition="TIMESTAMP")
    public Date getEndDate() {
        return this.EndDate;
    }
    
    public void setEndDate(Date EndDate) {
        this.EndDate = EndDate;
    }

    
    @Column(name="SUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getSumma() {
        return this.Summa;
    }
    
    public void setSumma(BigDecimal Summa) {
        this.Summa = Summa;
    }

    
    @Column(name="USE_BASIC_POSITION", columnDefinition="SMALLINT")
    public boolean isUseBasicPosition() {
        return this.UseBasicPosition;
    }
    
    public void setUseBasicPosition(boolean UseBasicPosition) {
        this.UseBasicPosition = UseBasicPosition;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="FeeModel")
    public Set<FeeModelParam> getFeeModelParams() {
        return this.FeeModelParams;
    }
    
    public void setFeeModelParams(Set<FeeModelParam> FeeModelParams) {
        this.FeeModelParams = FeeModelParams;
    }




}


