package com.mg.merp.salary.model;

import com.mg.merp.baiengine.model.Repository;
import com.mg.merp.core.model.SysClient;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FeeRefParam generated by hbm2java
 */
@Entity
@Table(name = "SAL_FEE_REF_PARAM")
public class FeeRefParam extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private FeeRef FeeRef;

    private Repository CalcAlg;

    private SysClient SysClient;

    private String PCode;

    private String PName;

    private Integer Priority;

    private FeeParamType ParamType;

    private boolean CalcOnce;

    public FeeRefParam() {
    }

    public FeeRefParam(String PCode) {
        this.PCode = PCode;
    }

    public FeeRefParam(FeeRef FeeRef, Repository CalcAlg, SysClient SysClient, String PCode, String PName, Integer Priority, FeeParamType ParamType, boolean CalcOnce) {
        this.FeeRef = FeeRef;
        this.CalcAlg = CalcAlg;
        this.SysClient = SysClient;
        this.PCode = PCode;
        this.PName = PName;
        this.Priority = Priority;
        this.ParamType = ParamType;
        this.CalcOnce = CalcOnce;
    }

    @SequenceGenerator(name = "generator", sequenceName = "SAL_FEE_REF_PARAM_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FEE_REF_ID")
    public FeeRef getFeeRef() {
        return this.FeeRef;
    }

    public void setFeeRef(FeeRef FeeRef) {
        this.FeeRef = FeeRef;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CALC_ALG_ID")
    public Repository getCalcAlg() {
        return this.CalcAlg;
    }

    public void setCalcAlg(Repository CalcAlg) {
        this.CalcAlg = CalcAlg;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "PCODE", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getPCode() {
        return this.PCode;
    }

    public void setPCode(String PCode) {
        this.PCode = PCode;
    }

    @Column(name = "PNAME", columnDefinition = "VARCHAR", length = 80)
    public String getPName() {
        return this.PName;
    }

    public void setPName(String PName) {
        this.PName = PName;
    }

    @Column(name = "PRIORITY", columnDefinition = "INTEGER")
    public Integer getPriority() {
        return this.Priority;
    }

    public void setPriority(Integer Priority) {
        this.Priority = Priority;
    }

    @Column(name = "PARAM_TYPE", columnDefinition = "SMALLINT")
    public FeeParamType getParamType() {
        return this.ParamType;
    }

    public void setParamType(FeeParamType ParamType) {
        this.ParamType = ParamType;
    }

    @Column(name = "CALC_ONCE", columnDefinition = "SMALLINT")
    public boolean isCalcOnce() {
        return this.CalcOnce;
    }

    public void setCalcOnce(boolean CalcOnce) {
        this.CalcOnce = CalcOnce;
    }
}

