package com.mg.merp.salary.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.personnelref.model.PositionFill;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PaySheetSpec generated by hbm2java
 */
@Entity
@Table(name = "SAL_PAY_SHEET_SPEC")
public class PaySheetSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private PositionFill PositionFill;

    private PaySheet PaySheet;

    private BigDecimal SummaFull;

    private BigDecimal SummaPaidOut;

    private BigDecimal SummaDeposited;

    private BigDecimal SummaRest;

    public PaySheetSpec() {
    }

    public PaySheetSpec(SysClient SysClient, PositionFill PositionFill, PaySheet PaySheet, BigDecimal SummaFull, BigDecimal SummaPaidOut, BigDecimal SummaDeposited, BigDecimal SummaRest) {
        this.SysClient = SysClient;
        this.PositionFill = PositionFill;
        this.PaySheet = PaySheet;
        this.SummaFull = SummaFull;
        this.SummaPaidOut = SummaPaidOut;
        this.SummaDeposited = SummaDeposited;
        this.SummaRest = SummaRest;
    }

    @SequenceGenerator(name = "generator", sequenceName = "SAL_PAY_SHEET_SPEC_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "POSITION_FILL_ID")
    public PositionFill getPositionFill() {
        return this.PositionFill;
    }

    public void setPositionFill(PositionFill PositionFill) {
        this.PositionFill = PositionFill;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAY_SHEET_ID")
    public PaySheet getPaySheet() {
        return this.PaySheet;
    }

    public void setPaySheet(PaySheet PaySheet) {
        this.PaySheet = PaySheet;
    }

    @Column(name = "SUMMA_FULL", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getSummaFull() {
        return this.SummaFull;
    }

    public void setSummaFull(BigDecimal SummaFull) {
        this.SummaFull = SummaFull;
    }

    @Column(name = "SUMMA_PAID_OUT", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getSummaPaidOut() {
        return this.SummaPaidOut;
    }

    public void setSummaPaidOut(BigDecimal SummaPaidOut) {
        this.SummaPaidOut = SummaPaidOut;
    }

    @Column(name = "SUMMA_DEPOSITED", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getSummaDeposited() {
        return this.SummaDeposited;
    }

    public void setSummaDeposited(BigDecimal SummaDeposited) {
        this.SummaDeposited = SummaDeposited;
    }

    @Column(name = "SUMMA_REST", columnDefinition = "NUMERIC", precision = 15, scale = 4)
    public BigDecimal getSummaRest() {
        return this.SummaRest;
    }

    public void setSummaRest(BigDecimal SummaRest) {
        this.SummaRest = SummaRest;
    }
}

