package com.mg.merp.salary.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TaxRate generated by hbm2java
 */
@Entity
@Table(name="SAL_TAXRATE"
)
public class TaxRate extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int Id;
     private TaxScale TaxScale;
     private SysClient SysClient;
     private Integer RNumber;
     private BigDecimal MinIncome;
     private BigDecimal MaxIncome;
     private BigDecimal TaxPercent;
     private BigDecimal ConstValue;
     private BigDecimal Privilegeratio;

    public TaxRate() {
    }

	
    public TaxRate(Integer RNumber) {
        this.RNumber = RNumber;
    }
    public TaxRate(TaxScale TaxScale, SysClient SysClient, Integer RNumber, BigDecimal MinIncome, BigDecimal MaxIncome, BigDecimal TaxPercent, BigDecimal ConstValue, BigDecimal Privilegeratio) {
       this.TaxScale = TaxScale;
       this.SysClient = SysClient;
       this.RNumber = RNumber;
       this.MinIncome = MinIncome;
       this.MaxIncome = MaxIncome;
       this.TaxPercent = TaxPercent;
       this.ConstValue = ConstValue;
       this.Privilegeratio = Privilegeratio;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SAL_TAXRATE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public int getId() {
        return this.Id;
    }
    
    public void setId(int Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TAXSCALE_ID")
    public TaxScale getTaxScale() {
        return this.TaxScale;
    }
    
    public void setTaxScale(TaxScale TaxScale) {
        this.TaxScale = TaxScale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="RNUMBER", nullable=false, columnDefinition="INTEGER")
    public Integer getRNumber() {
        return this.RNumber;
    }
    
    public void setRNumber(Integer RNumber) {
        this.RNumber = RNumber;
    }

    
    @Column(name="MININCOME", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getMinIncome() {
        return this.MinIncome;
    }
    
    public void setMinIncome(BigDecimal MinIncome) {
        this.MinIncome = MinIncome;
    }

    
    @Column(name="MAXINCOME", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getMaxIncome() {
        return this.MaxIncome;
    }
    
    public void setMaxIncome(BigDecimal MaxIncome) {
        this.MaxIncome = MaxIncome;
    }

    
    @Column(name="TAX_PERCENT", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getTaxPercent() {
        return this.TaxPercent;
    }
    
    public void setTaxPercent(BigDecimal TaxPercent) {
        this.TaxPercent = TaxPercent;
    }

    
    @Column(name="CONSTVALUE", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getConstValue() {
        return this.ConstValue;
    }
    
    public void setConstValue(BigDecimal ConstValue) {
        this.ConstValue = ConstValue;
    }

    
    @Column(name="PRIVILEGERATIO", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getPrivilegeratio() {
        return this.Privilegeratio;
    }
    
    public void setPrivilegeratio(BigDecimal Privilegeratio) {
        this.Privilegeratio = Privilegeratio;
    }




}


