package com.mg.merp.core.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.framework.api.orm.DatabaseAuditType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DatabaseAudit generated by hbm2java
 */
@Entity
@Table(name="SYS_DB_AUDIT"
)
public class DatabaseAudit extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Long Id;
     private SysClient SysClient;
     private String UserName;
     private Date EventDateTime;
     private DatabaseAuditType AuditType;
     private String AuditedEntityName;

    public DatabaseAudit() {
    }

	
    public DatabaseAudit(String UserName, Date EventDateTime, DatabaseAuditType AuditType, String AuditedEntityName) {
        this.UserName = UserName;
        this.EventDateTime = EventDateTime;
        this.AuditType = AuditType;
        this.AuditedEntityName = AuditedEntityName;
    }
    public DatabaseAudit(SysClient SysClient, String UserName, Date EventDateTime, DatabaseAuditType AuditType, String AuditedEntityName) {
       this.SysClient = SysClient;
       this.UserName = UserName;
       this.EventDateTime = EventDateTime;
       this.AuditType = AuditType;
       this.AuditedEntityName = AuditedEntityName;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SYS_DB_AUDIT_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="NUMERIC")
    public Long getId() {
        return this.Id;
    }
    
    public void setId(Long Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="USER_NAME", nullable=false, columnDefinition="CHAR", length=31)
    public String getUserName() {
        return this.UserName;
    }
    
    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    
    @Column(name="EVENT_DATETIME", nullable=false, columnDefinition="TIMESTAMP")
    public Date getEventDateTime() {
        return this.EventDateTime;
    }
    
    public void setEventDateTime(Date EventDateTime) {
        this.EventDateTime = EventDateTime;
    }

    
    @Column(name="AUDIT_TYPE", nullable=false, columnDefinition="SMALLINT")
    public DatabaseAuditType getAuditType() {
        return this.AuditType;
    }
    
    public void setAuditType(DatabaseAuditType AuditType) {
        this.AuditType = AuditType;
    }

    
    @Column(name="ENTITY_NAME", nullable=false, columnDefinition="VARCHAR", length=256)
    public String getAuditedEntityName() {
        return this.AuditedEntityName;
    }
    
    public void setAuditedEntityName(String AuditedEntityName) {
        this.AuditedEntityName = AuditedEntityName;
    }




}


