package com.mg.merp.core.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.framework.api.metadata.ApplicationLayer;
import com.mg.merp.security.model.Groups;
import com.mg.merp.security.model.SecUser;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Form generated by hbm2java
 */
@Entity
@Table(name="SYS_FORM"
)
public class Form extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private ApplicationLayer ApplicationLayer;
     private Groups Role;
     private SecUser User;
     private String Name;
     private String Description;
     private String Implementation;
     private SysClass SysClass;

    public Form() {
    }

	
    public Form(ApplicationLayer ApplicationLayer, String Name, String Implementation, SysClass SysClass) {
        this.ApplicationLayer = ApplicationLayer;
        this.Name = Name;
        this.Implementation = Implementation;
        this.SysClass = SysClass;
    }
    public Form(ApplicationLayer ApplicationLayer, Groups Role, SecUser User, String Name, String Description, String Implementation, SysClass SysClass) {
       this.ApplicationLayer = ApplicationLayer;
       this.Role = Role;
       this.User = User;
       this.Name = Name;
       this.Description = Description;
       this.Implementation = Implementation;
       this.SysClass = SysClass;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SYS_FORM_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, nullable=false, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

    
    @Column(name="APP_LAYER", nullable=false, columnDefinition="SMALLINT")
    public ApplicationLayer getApplicationLayer() {
        return this.ApplicationLayer;
    }
    
    public void setApplicationLayer(ApplicationLayer ApplicationLayer) {
        this.ApplicationLayer = ApplicationLayer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_ID")
    public Groups getRole() {
        return this.Role;
    }
    
    public void setRole(Groups Role) {
        this.Role = Role;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public SecUser getUser() {
        return this.User;
    }
    
    public void setUser(SecUser User) {
        this.User = User;
    }

    
    @Column(name="NAME", unique=true, nullable=false, columnDefinition="VARCHAR", length=80)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    
    @Column(name="DESCRIPTION", columnDefinition="VARCHAR", length=1024)
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }

    
    @Column(name="IMPL_NAME", nullable=false, columnDefinition="VARCHAR", length=256)
    public String getImplementation() {
        return this.Implementation;
    }
    
    public void setImplementation(String Implementation) {
        this.Implementation = Implementation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLASS_ID", nullable=false)
    public SysClass getSysClass() {
        return this.SysClass;
    }
    
    public void setSysClass(SysClass SysClass) {
        this.SysClass = SysClass;
    }




}


