package com.mg.merp.core.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StringsId generated by hbm2java
 */
@Embeddable
public class StringsId extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Section;
     private Integer Val;

    public StringsId() {
    }

    public StringsId(Integer Section, Integer Val) {
       this.Section = Section;
       this.Val = Val;
    }
   


    @Column(name="SECTION", columnDefinition="INTEGER")
    public Integer getSection() {
        return this.Section;
    }
    
    public void setSection(Integer Section) {
        this.Section = Section;
    }


    @Column(name="VAL", columnDefinition="INTEGER")
    public Integer getVal() {
        return this.Val;
    }
    
    public void setVal(Integer Val) {
        this.Val = Val;
    }




}


