package com.mg.merp.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * SysCompany generated by hbm2java
 */
@Entity
@Table(name = "SYS_COMPANY")
@DataItemName("Core.SysCompany")
public class SysCompany extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private String Code;

    private String Name;

    private String Description;

    private boolean Active;

    public SysCompany() {
    }

    public SysCompany(String Code) {
        this.Code = Code;
    }

    public SysCompany(SysClient SysClient, String Code, String Name, String Description, boolean Active) {
        this.SysClient = SysClient;
        this.Code = Code;
        this.Name = Name;
        this.Description = Description;
        this.Active = Active;
    }

    @SequenceGenerator(name = "generator", sequenceName = "SYS_COMPANY_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 5)
    @DataItemName("Reference.BigCode")
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "NAME", columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Reference.Name")
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 1024)
    @DataItemName("Core.Description")
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    @Column(name = "IS_ACTIVE", columnDefinition = "SMALLINT")
    @DataItemName("Core.Active")
    public boolean isActive() {
        return this.Active;
    }

    public void setActive(boolean Active) {
        this.Active = Active;
    }
}

