package com.mg.merp.core.model;

import com.mg.merp.security.model.ModuleAccess;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.mg.framework.api.annotations.DataItemName;

/**
 * SysModule generated by hbm2java
 */
@Entity
@Table(name = "SYS_MODULE")
@DataItemName("Core.Subsystem")
public class SysModule extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private int Id;

    private String Name;

    private String Description;

    private Short MajorVersion;

    private Short MinorVersion;

    private Short Release;

    private Set<ModuleAccess> Permissions = new HashSet<ModuleAccess>(0);

    private Set<SysClass> Beans = new HashSet<SysClass>(0);

    public SysModule() {
    }

    public SysModule(int Id, String Name) {
        this.Id = Id;
        this.Name = Name;
    }

    public SysModule(int Id, String Name, String Description, Short MajorVersion, Short MinorVersion, Short Release, Set<ModuleAccess> Permissions, Set<SysClass> Beans) {
        this.Id = Id;
        this.Name = Name;
        this.Description = Description;
        this.MajorVersion = MajorVersion;
        this.MinorVersion = MinorVersion;
        this.Release = Release;
        this.Permissions = Permissions;
        this.Beans = Beans;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public int getId() {
        return this.Id;
    }

    public void setId(int Id) {
        this.Id = Id;
    }

    @Column(name = "NAME", unique = true, nullable = false, columnDefinition = "VARCHAR", length = 80)
    @DataItemName("Core.Subsystem.Name")
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 100)
    @DataItemName("Core.Subsystem.Description")
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    @Column(name = "MAJOR_VERSION", columnDefinition = "SMALLINT")
    @DataItemName("Core.Subsystem.MajorVersion")
    public Short getMajorVersion() {
        return this.MajorVersion;
    }

    public void setMajorVersion(Short MajorVersion) {
        this.MajorVersion = MajorVersion;
    }

    @Column(name = "MINOR_VERSION", columnDefinition = "SMALLINT")
    @DataItemName("Core.Subsystem.MinorVersion")
    public Short getMinorVersion() {
        return this.MinorVersion;
    }

    public void setMinorVersion(Short MinorVersion) {
        this.MinorVersion = MinorVersion;
    }

    @Column(name = "RELEASE", columnDefinition = "SMALLINT")
    @DataItemName("Core.Subsystem.Release")
    public Short getRelease() {
        return this.Release;
    }

    public void setRelease(Short Release) {
        this.Release = Release;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Module")
    public Set<ModuleAccess> getPermissions() {
        return this.Permissions;
    }

    public void setPermissions(Set<ModuleAccess> Permissions) {
        this.Permissions = Permissions;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "MODULE_ID", updatable = false)
    public Set<SysClass> getBeans() {
        return this.Beans;
    }

    public void setBeans(Set<SysClass> Beans) {
        this.Beans = Beans;
    }
}

