package com.mg.merp.core.model;

import com.mg.framework.api.metadata.ApplicationLayer;
import com.mg.merp.security.model.Groups;
import com.mg.merp.security.model.SecUser;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Window generated by hbm2java
 */
@Entity
@Table(name = "SYS_WINDOW")
public class Window extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private ApplicationLayer ApplicationLayer;

    private Groups Role;

    private SecUser User;

    private String Name;

    private String Implementation;

    private String Description;

    public Window() {
    }

    public Window(ApplicationLayer ApplicationLayer, String Name) {
        this.ApplicationLayer = ApplicationLayer;
        this.Name = Name;
    }

    public Window(ApplicationLayer ApplicationLayer, Groups Role, SecUser User, String Name, String Implementation, String Description) {
        this.ApplicationLayer = ApplicationLayer;
        this.Role = Role;
        this.User = User;
        this.Name = Name;
        this.Implementation = Implementation;
        this.Description = Description;
    }

    @SequenceGenerator(name = "generator", sequenceName = "SYS_WINDOW_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, nullable = false, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @Column(name = "APP_LAYER", nullable = false, columnDefinition = "SMALLINT")
    public ApplicationLayer getApplicationLayer() {
        return this.ApplicationLayer;
    }

    public void setApplicationLayer(ApplicationLayer ApplicationLayer) {
        this.ApplicationLayer = ApplicationLayer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ROLE_ID")
    public Groups getRole() {
        return this.Role;
    }

    public void setRole(Groups Role) {
        this.Role = Role;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    public SecUser getUser() {
        return this.User;
    }

    public void setUser(SecUser User) {
        this.User = User;
    }

    @Column(name = "NAME", unique = true, nullable = false, columnDefinition = "VARCHAR", length = 256)
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "IMPL_NAME", columnDefinition = "VARCHAR", length = 256)
    public String getImplementation() {
        return this.Implementation;
    }

    public void setImplementation(String Implementation) {
        this.Implementation = Implementation;
    }

    @Column(name = "DESCRIPTION", columnDefinition = "VARCHAR", length = 1024)
    public String getDescription() {
        return this.Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }
}

