package com.mg.merp.table.model;

import com.mg.merp.core.model.SysClient;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ScheduleSpec generated by hbm2java
 */
@Entity
@Table(name = "TAB_SCHEDULE_SPEC")
public class ScheduleSpec extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private TimeKind TimeKind;

    private ScheduleHead ScheduleHead;

    private SysClient SysClient;

    private BigDecimal HoursQuantity;

    private Date ScheduleDate;

    public ScheduleSpec() {
    }

    public ScheduleSpec(TimeKind TimeKind, ScheduleHead ScheduleHead, SysClient SysClient, BigDecimal HoursQuantity, Date ScheduleDate) {
        this.TimeKind = TimeKind;
        this.ScheduleHead = ScheduleHead;
        this.SysClient = SysClient;
        this.HoursQuantity = HoursQuantity;
        this.ScheduleDate = ScheduleDate;
    }

    @SequenceGenerator(name = "generator", sequenceName = "TAB_SCHEDULE_SPEC_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIME_KIND_ID")
    public TimeKind getTimeKind() {
        return this.TimeKind;
    }

    public void setTimeKind(TimeKind TimeKind) {
        this.TimeKind = TimeKind;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SCHEDULE_HEAD_ID")
    public ScheduleHead getScheduleHead() {
        return this.ScheduleHead;
    }

    public void setScheduleHead(ScheduleHead ScheduleHead) {
        this.ScheduleHead = ScheduleHead;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "HOURS_QUANTITY", columnDefinition = "NUMERIC", precision = 18, scale = 3)
    public BigDecimal getHoursQuantity() {
        return this.HoursQuantity;
    }

    public void setHoursQuantity(BigDecimal HoursQuantity) {
        this.HoursQuantity = HoursQuantity;
    }

    @Column(name = "SCHEDULE_DATE", columnDefinition = "TIMESTAMP")
    public Date getScheduleDate() {
        return this.ScheduleDate;
    }

    public void setScheduleDate(Date ScheduleDate) {
        this.ScheduleDate = ScheduleDate;
    }
}

