package com.mg.merp.table.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.personnelref.model.CalcPeriod;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TimeBoardHead generated by hbm2java
 */
@Entity
@Table(name="TAB_TIME_BOARD_HEAD"
)
public class TimeBoardHead extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private SysClient SysClient;
     private CalcPeriod CalcPeriod;
     private String BNumber;
     private String Comments;
     private Set<TimeBoardPosition> TimeBoardPositions = new HashSet<TimeBoardPosition>(0);

    public TimeBoardHead() {
    }

    public TimeBoardHead(SysClient SysClient, CalcPeriod CalcPeriod, String BNumber, String Comments, Set<TimeBoardPosition> TimeBoardPositions) {
       this.SysClient = SysClient;
       this.CalcPeriod = CalcPeriod;
       this.BNumber = BNumber;
       this.Comments = Comments;
       this.TimeBoardPositions = TimeBoardPositions;
    }
   
     @SequenceGenerator(name="generator", sequenceName="TAB_TIME_BOARD_HEAD_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CALC_PERIOD_ID", unique=true)
    public CalcPeriod getCalcPeriod() {
        return this.CalcPeriod;
    }
    
    public void setCalcPeriod(CalcPeriod CalcPeriod) {
        this.CalcPeriod = CalcPeriod;
    }

    
    @Column(name="BNUMBER", columnDefinition="CHAR", length=20)
    public String getBNumber() {
        return this.BNumber;
    }
    
    public void setBNumber(String BNumber) {
        this.BNumber = BNumber;
    }

    
    @Column(name="COMMENTS", columnDefinition="VARCHAR", length=256)
    public String getComments() {
        return this.Comments;
    }
    
    public void setComments(String Comments) {
        this.Comments = Comments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="TimeBoardHead")
    public Set<TimeBoardPosition> getTimeBoardPositions() {
        return this.TimeBoardPositions;
    }
    
    public void setTimeBoardPositions(Set<TimeBoardPosition> TimeBoardPositions) {
        this.TimeBoardPositions = TimeBoardPositions;
    }




}


