package com.mg.merp.crm.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContactLink generated by hbm2java
 */
@Entity
@Table(name="CRM_CONTACT_LINK"
)
public class ContactLink extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private ContactLinkId Id;

    public ContactLink() {
    }

    public ContactLink(ContactLinkId Id) {
       this.Id = Id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="SysClient", column=@Column(name="CLIENT_ID", nullable=false) ), 
        @AttributeOverride(name="CrmContact", column=@Column(name="CONTACT_ID", nullable=false) ), 
        @AttributeOverride(name="CrmRelation", column=@Column(name="RELATION_ID", nullable=false) ) } )
    public ContactLinkId getId() {
        return this.Id;
    }
    
    public void setId(ContactLinkId Id) {
        this.Id = Id;
    }




}


