package com.mg.merp.crm.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.OriginalDocument;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LinkedDocument generated by hbm2java
 */
@Entity
@Table(name="CRM_LINKED_DOC"
)
public class LinkedDocument extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Solution Solution;
     private Offer Offer;
     private Problem Problem;
     private Operation Operation;
     private SysClient SysClient;
     private Contact Contact;
     private OriginalDocument Original;
     private Relation Relation;

    public LinkedDocument() {
    }

    public LinkedDocument(Solution Solution, Offer Offer, Problem Problem, Operation Operation, SysClient SysClient, Contact Contact, OriginalDocument Original, Relation Relation) {
       this.Solution = Solution;
       this.Offer = Offer;
       this.Problem = Problem;
       this.Operation = Operation;
       this.SysClient = SysClient;
       this.Contact = Contact;
       this.Original = Original;
       this.Relation = Relation;
    }
   
     @SequenceGenerator(name="generator", sequenceName="CRM_LINKED_DOC_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SOLUTION_ID")
    public Solution getSolution() {
        return this.Solution;
    }
    
    public void setSolution(Solution Solution) {
        this.Solution = Solution;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OFFER_ID")
    public Offer getOffer() {
        return this.Offer;
    }
    
    public void setOffer(Offer Offer) {
        this.Offer = Offer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROBLEM_ID")
    public Problem getProblem() {
        return this.Problem;
    }
    
    public void setProblem(Problem Problem) {
        this.Problem = Problem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OPERATION_ID")
    public Operation getOperation() {
        return this.Operation;
    }
    
    public void setOperation(Operation Operation) {
        this.Operation = Operation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTACT_ID")
    public Contact getContact() {
        return this.Contact;
    }
    
    public void setContact(Contact Contact) {
        this.Contact = Contact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORIGINAL_ID")
    public OriginalDocument getOriginal() {
        return this.Original;
    }
    
    public void setOriginal(OriginalDocument Original) {
        this.Original = Original;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RELATION_ID")
    public Relation getRelation() {
        return this.Relation;
    }
    
    public void setRelation(Relation Relation) {
        this.Relation = Relation;
    }




}


