package com.mg.merp.crm.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.Folder;
import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.NaturalPerson;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Relation generated by hbm2java
 */
@Entity
@Table(name="CRM_RELATION"
)
public class Relation extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private RelationStatus Status;
     private OwnershipForm OwnershipForm;
     private Folder Folder;
     private ClientType ClientType;
     private Market Market;
     private Relation Parent;
     private NaturalPerson NaturalPerson;
     private User Curator;
     private User Responsible;
     private ActivityKind ActivityKind;
     private SysClient SysClient;
     private PersonTitle PersonTitle;
     private ClientRank ClientRank;
     private Contractor LegalPerson;
     private ActivitySphere ActivitySphere;
     private Branch Branch;
     private DeliveryKind DeliveryKind;
     private PaymentCond PaymentCond;
     private String Code;
     private String Name;
     private boolean IsLegalPerson;
     private String Info;
     private String NickName;
     private String Uin;

    public Relation() {
    }

    public Relation(RelationStatus Status, OwnershipForm OwnershipForm, Folder Folder, ClientType ClientType, Market Market, Relation Parent, NaturalPerson NaturalPerson, User Curator, User Responsible, ActivityKind ActivityKind, SysClient SysClient, PersonTitle PersonTitle, ClientRank ClientRank, Contractor LegalPerson, ActivitySphere ActivitySphere, Branch Branch, DeliveryKind DeliveryKind, PaymentCond PaymentCond, String Code, String Name, boolean IsLegalPerson, String Info, String NickName, String Uin) {
       this.Status = Status;
       this.OwnershipForm = OwnershipForm;
       this.Folder = Folder;
       this.ClientType = ClientType;
       this.Market = Market;
       this.Parent = Parent;
       this.NaturalPerson = NaturalPerson;
       this.Curator = Curator;
       this.Responsible = Responsible;
       this.ActivityKind = ActivityKind;
       this.SysClient = SysClient;
       this.PersonTitle = PersonTitle;
       this.ClientRank = ClientRank;
       this.LegalPerson = LegalPerson;
       this.ActivitySphere = ActivitySphere;
       this.Branch = Branch;
       this.DeliveryKind = DeliveryKind;
       this.PaymentCond = PaymentCond;
       this.Code = Code;
       this.Name = Name;
       this.IsLegalPerson = IsLegalPerson;
       this.Info = Info;
       this.NickName = NickName;
       this.Uin = Uin;
    }
   
     @SequenceGenerator(name="generator", sequenceName="CRM_RELATION_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_ID")
    public RelationStatus getStatus() {
        return this.Status;
    }
    
    public void setStatus(RelationStatus Status) {
        this.Status = Status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OWNERSHIP_FORM_ID")
    public OwnershipForm getOwnershipForm() {
        return this.OwnershipForm;
    }
    
    public void setOwnershipForm(OwnershipForm OwnershipForm) {
        this.OwnershipForm = OwnershipForm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FOLDER_ID")
    public Folder getFolder() {
        return this.Folder;
    }
    
    public void setFolder(Folder Folder) {
        this.Folder = Folder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_TYPE_ID")
    public ClientType getClientType() {
        return this.ClientType;
    }
    
    public void setClientType(ClientType ClientType) {
        this.ClientType = ClientType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MARKET_ID")
    public Market getMarket() {
        return this.Market;
    }
    
    public void setMarket(Market Market) {
        this.Market = Market;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARENT_ID")
    public Relation getParent() {
        return this.Parent;
    }
    
    public void setParent(Relation Parent) {
        this.Parent = Parent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NATURAL_PERSON_ID")
    public NaturalPerson getNaturalPerson() {
        return this.NaturalPerson;
    }
    
    public void setNaturalPerson(NaturalPerson NaturalPerson) {
        this.NaturalPerson = NaturalPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURATOR_ID")
    public User getCurator() {
        return this.Curator;
    }
    
    public void setCurator(User Curator) {
        this.Curator = Curator;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESPONSIBLE_ID")
    public User getResponsible() {
        return this.Responsible;
    }
    
    public void setResponsible(User Responsible) {
        this.Responsible = Responsible;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTIVITY_KIND_ID")
    public ActivityKind getActivityKind() {
        return this.ActivityKind;
    }
    
    public void setActivityKind(ActivityKind ActivityKind) {
        this.ActivityKind = ActivityKind;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PERSON_TITLE_ID")
    public PersonTitle getPersonTitle() {
        return this.PersonTitle;
    }
    
    public void setPersonTitle(PersonTitle PersonTitle) {
        this.PersonTitle = PersonTitle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_RANK_ID")
    public ClientRank getClientRank() {
        return this.ClientRank;
    }
    
    public void setClientRank(ClientRank ClientRank) {
        this.ClientRank = ClientRank;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LEGAL_PERSON_ID")
    public Contractor getLegalPerson() {
        return this.LegalPerson;
    }
    
    public void setLegalPerson(Contractor LegalPerson) {
        this.LegalPerson = LegalPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTIVITY_SPHERE_ID")
    public ActivitySphere getActivitySphere() {
        return this.ActivitySphere;
    }
    
    public void setActivitySphere(ActivitySphere ActivitySphere) {
        this.ActivitySphere = ActivitySphere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BRANCH_ID")
    public Branch getBranch() {
        return this.Branch;
    }
    
    public void setBranch(Branch Branch) {
        this.Branch = Branch;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DELIVERY_KIND_ID")
    public DeliveryKind getDeliveryKind() {
        return this.DeliveryKind;
    }
    
    public void setDeliveryKind(DeliveryKind DeliveryKind) {
        this.DeliveryKind = DeliveryKind;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAYMENT_COND_ID")
    public PaymentCond getPaymentCond() {
        return this.PaymentCond;
    }
    
    public void setPaymentCond(PaymentCond PaymentCond) {
        this.PaymentCond = PaymentCond;
    }

    
    @Column(name="CODE", columnDefinition="CHAR", length=20)
    public String getCode() {
        return this.Code;
    }
    
    public void setCode(String Code) {
        this.Code = Code;
    }

    
    @Column(name="NAME", columnDefinition="VARCHAR", length=256)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    
    @Column(name="IS_LEGAL_PERSON", columnDefinition="SMALLINT")
    public boolean isIsLegalPerson() {
        return this.IsLegalPerson;
    }
    
    public void setIsLegalPerson(boolean IsLegalPerson) {
        this.IsLegalPerson = IsLegalPerson;
    }

    
    @Column(name="INFO", columnDefinition="VARCHAR", length=2048)
    public String getInfo() {
        return this.Info;
    }
    
    public void setInfo(String Info) {
        this.Info = Info;
    }

    
    @Column(name="NICKNAME", columnDefinition="VARCHAR", length=80)
    public String getNickName() {
        return this.NickName;
    }
    
    public void setNickName(String NickName) {
        this.NickName = NickName;
    }

    
    @Column(name="UIN", columnDefinition="VARCHAR", length=50)
    public String getUin() {
        return this.Uin;
    }
    
    public void setUin(String Uin) {
        this.Uin = Uin;
    }




}


