package com.mg.merp.crm.model;

import com.mg.merp.core.model.Folder;
import com.mg.merp.core.model.SysClient;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Solution generated by hbm2java
 */
@Entity
@Table(name = "CRM_SOLUTION")
public class Solution extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SolutionType SolutionType;

    private Folder Folder;

    private SysClient SysClient;

    private User Creator;

    private String Name;

    private String Info;

    private Integer Priority;

    private Date ValidFrom;

    private Date ValidTo;

    private Set<LinkProblemSolution> LinkProblemSolutions = new HashSet<LinkProblemSolution>(0);

    private Set<LinkedDocument> LinkedDocs = new HashSet<LinkedDocument>(0);

    public Solution() {
    }

    public Solution(SolutionType SolutionType, Folder Folder, SysClient SysClient, User Creator, String Name, String Info, Integer Priority, Date ValidFrom, Date ValidTo, Set<LinkProblemSolution> LinkProblemSolutions, Set<LinkedDocument> LinkedDocs) {
        this.SolutionType = SolutionType;
        this.Folder = Folder;
        this.SysClient = SysClient;
        this.Creator = Creator;
        this.Name = Name;
        this.Info = Info;
        this.Priority = Priority;
        this.ValidFrom = ValidFrom;
        this.ValidTo = ValidTo;
        this.LinkProblemSolutions = LinkProblemSolutions;
        this.LinkedDocs = LinkedDocs;
    }

    @SequenceGenerator(name = "generator", sequenceName = "CRM_SOLUTION_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOLUTION_TYPE_ID")
    public SolutionType getSolutionType() {
        return this.SolutionType;
    }

    public void setSolutionType(SolutionType SolutionType) {
        this.SolutionType = SolutionType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FOLDER_ID")
    public Folder getFolder() {
        return this.Folder;
    }

    public void setFolder(Folder Folder) {
        this.Folder = Folder;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATOR_ID")
    @DataItemName("CRM.Solution.Creator")
    public User getCreator() {
        return this.Creator;
    }

    public void setCreator(User Creator) {
        this.Creator = Creator;
    }

    @Column(name = "NAME", columnDefinition = "VARCHAR", length = 256)
    @DataItemName("CRM.BigName")
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "INFO", columnDefinition = "VARCHAR", length = 2048)
    @DataItemName("CRM.Solution.Info")
    public String getInfo() {
        return this.Info;
    }

    public void setInfo(String Info) {
        this.Info = Info;
    }

    @Column(name = "PRIORITY", columnDefinition = "INTEGER")
    public Integer getPriority() {
        return this.Priority;
    }

    public void setPriority(Integer Priority) {
        this.Priority = Priority;
    }

    @Column(name = "VALID_FROM", columnDefinition = "TIMESTAMP")
    @DataItemName("CRM.Solution.ValidFrom")
    public Date getValidFrom() {
        return this.ValidFrom;
    }

    public void setValidFrom(Date ValidFrom) {
        this.ValidFrom = ValidFrom;
    }

    @Column(name = "VALID_TO", columnDefinition = "TIMESTAMP")
    @DataItemName("CRM.Solution.ValidTo")
    public Date getValidTo() {
        return this.ValidTo;
    }

    public void setValidTo(Date ValidTo) {
        this.ValidTo = ValidTo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "unresolved")
    public Set<LinkProblemSolution> getLinkProblemSolutions() {
        return this.LinkProblemSolutions;
    }

    public void setLinkProblemSolutions(Set<LinkProblemSolution> LinkProblemSolutions) {
        this.LinkProblemSolutions = LinkProblemSolutions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "Solution")
    public Set<LinkedDocument> getLinkedDocs() {
        return this.LinkedDocs;
    }

    public void setLinkedDocs(Set<LinkedDocument> LinkedDocs) {
        this.LinkedDocs = LinkedDocs;
    }
}

