
/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN D_ABBREVIATION AS
CHAR(11);

CREATE DOMAIN D_ACCOUNT AS
VARCHAR(30);

CREATE DOMAIN D_ADDRESS AS
VARCHAR(256);

CREATE DOMAIN D_ADDR_BUILDING AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_HOUSE AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_PREFIX AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_ROOM AS
VARCHAR(20);

CREATE DOMAIN D_ADDR_STREET AS
VARCHAR(128);

CREATE DOMAIN D_ALGORITHM AS
text;

CREATE DOMAIN D_ANLCODE AS
CHAR(15);

CREATE DOMAIN D_APP_LAYER AS
SMALLINT;

CREATE DOMAIN D_AUDIT_EVENT AS
SMALLINT;

CREATE DOMAIN D_BEAN_NAME AS
VARCHAR(128);

CREATE DOMAIN D_BIGCODE AS
CHAR(20);

CREATE DOMAIN D_BIGNAME AS
VARCHAR(256);

CREATE DOMAIN D_BIG_INT_IDEN AS
NUMERIC(18,0);

CREATE DOMAIN D_BOOLEAN AS
BOOLEAN
default FALSE;

CREATE DOMAIN D_CALCTAXESSUBJECT AS
SMALLINT
CHECK (value between 0 and 1);

CREATE DOMAIN D_CATALOG_GROUPS_TYPE AS
SMALLINT;

CREATE DOMAIN D_CLASS_IMPL_KIND AS
SMALLINT;

CREATE DOMAIN D_COMMENT AS
VARCHAR(256);

CREATE DOMAIN D_CONST_VAL AS
VARCHAR(80);

CREATE DOMAIN D_CONTARCT_CALC_SUM_KIND AS
SMALLINT;

CREATE DOMAIN D_CONTPHASE_CALC_SUM_KIND AS
SMALLINT;

CREATE DOMAIN D_CONTRACTORCARD_HIST_KIND AS
SMALLINT
DEFAULT 0
CHECK(VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_CONTRACTORCARD_PLAN_KIND AS
SMALLINT
DEFAULT 0
CHECK(VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_CONTRACTOR_KIND AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK (value between 0 and 2);

CREATE DOMAIN D_CONTRACTSTATUS AS
SMALLINT;

CREATE DOMAIN D_CONTRACT_COMMENT AS
VARCHAR(2048);

CREATE DOMAIN D_CRM_INFO AS
VARCHAR(2048);

CREATE DOMAIN D_CRM_SWOT AS
VARCHAR(1024);

CREATE DOMAIN D_CURCOURCE AS
NUMERIC(15,5);

CREATE DOMAIN D_CUSTOMALGORITHM AS
VARCHAR(8196);

CREATE DOMAIN D_DATE AS
TIMESTAMP;

CREATE DOMAIN D_DATENOTNULL AS
TIMESTAMP
NOT NULL;

CREATE DOMAIN D_DATETIME AS
TIMESTAMP;

CREATE DOMAIN D_DESCRIPTION AS
VARCHAR(1024);

CREATE DOMAIN D_DISABLE_EXCEED_QUANT AS
SMALLINT
default 0
NOT NULL
check (value between 0 and 2);

CREATE DOMAIN D_DOCDATE AS
TIMESTAMP
DEFAULT 'today';

CREATE DOMAIN D_DOCKIND AS
SMALLINT;

CREATE DOMAIN D_DOCNUMBER AS
CHAR(20);

CREATE DOMAIN D_DOCSECTION AS
SMALLINT;

CREATE DOMAIN D_DOCTYPE AS
CHAR(15);

CREATE DOMAIN D_ECONSPEC_FEATURE_CODE AS
CHAR(10);

CREATE DOMAIN D_EMAIL AS
VARCHAR(50);

CREATE DOMAIN D_EXCH_EXPORT_STATUS AS
SMALLINT
default 0
check (value between 0 and 4);

CREATE DOMAIN D_EXP_DATE_CALC_KIND AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK (value between 0 and 2);

CREATE DOMAIN D_FEATURE AS
VARCHAR(80);

CREATE DOMAIN D_FEATURE_INT AS
INTEGER;

CREATE DOMAIN D_FEATURE_STR AS
VARCHAR(2048);

CREATE DOMAIN D_FILENAME AS
VARCHAR(256);

CREATE DOMAIN D_FINANL_KIND AS
SMALLINT;

CREATE DOMAIN D_FINCENTER_KIND AS
SMALLINT;

CREATE DOMAIN D_FORMAT AS
VARCHAR(80);

CREATE DOMAIN D_FORMULA AS
VARCHAR(2048);

CREATE DOMAIN D_HOUR AS
NUMERIC(18,6)
DEFAULT 0;

CREATE DOMAIN D_INT AS
INTEGER;

CREATE DOMAIN D_INT_IDEN AS
INTEGER
NOT NULL;

CREATE DOMAIN D_JAVA_CLASS_NAME AS
VARCHAR(256);

CREATE DOMAIN D_LARGECODE AS
CHAR(40);

CREATE DOMAIN D_MASS AS
NUMERIC(15,3);

CREATE DOMAIN D_MEASURE_CONTROL AS
SMALLINT;

CREATE DOMAIN D_MEASURE_CONVERSION AS
VARCHAR(512);

CREATE DOMAIN D_MEDIUMCODE AS
CHAR(10);

CREATE DOMAIN D_MF_BOM_STATUS AS
SMALLINT;

CREATE DOMAIN D_MF_BOM_TYPE AS
SMALLINT;

CREATE DOMAIN D_MF_CAPACITY AS
NUMERIC(18,0)
DEFAULT 0;

CREATE DOMAIN D_MF_JOB_STATUS AS
SMALLINT;

CREATE DOMAIN D_MF_LBR_OH_ALLOC_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_LBR_TIME_RATE_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MCH_OH_ALLOCATION_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MCH_RECOVERY_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MTL_OH_ACCLOC_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_MTL_QUAN_RATE_FLAG AS
SMALLINT;

CREATE DOMAIN D_MF_RESOURCE_TYPE AS
SMALLINT;

CREATE DOMAIN D_MF_SCHEDULE_DIR AS
SMALLINT;

CREATE DOMAIN D_MF_TICK AS
NUMERIC(18,0);

CREATE DOMAIN D_MONTH AS
SMALLINT
default 1
CHECK (VALUE BETWEEN 1 AND 12);

CREATE DOMAIN D_NAME AS
VARCHAR(80)
NOT NULL;

CREATE DOMAIN D_NAME_N AS
VARCHAR(80);

CREATE DOMAIN D_ORDER_STATUS AS
SMALLINT;

CREATE DOMAIN D_ORIGINAL AS
bytea;

CREATE DOMAIN D_PASSWORD AS
VARCHAR(80);

CREATE DOMAIN D_PHASEITEMKIND AS
SMALLINT;

CREATE DOMAIN D_PHONE AS
VARCHAR(80);

CREATE DOMAIN D_PHONELIST AS
VARCHAR(40);

CREATE DOMAIN D_PROCESSMGR_STATE AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_QUANTITY AS
NUMERIC(18,3);

CREATE DOMAIN D_QUANTITY_EXT AS
NUMERIC(18,6);

CREATE DOMAIN D_QUERY AS
VARCHAR(8192);

CREATE DOMAIN D_RATIO AS
NUMERIC(18,6);

CREATE DOMAIN D_RPT_ENUMVALUES AS
VARCHAR(1024);

CREATE DOMAIN D_SERIAL_NUMBER AS
VARCHAR(50);

CREATE DOMAIN D_SHORT AS
SMALLINT;

CREATE DOMAIN D_SIZE AS
VARCHAR(15);

CREATE DOMAIN D_SMALLCODE AS
CHAR(5);

CREATE DOMAIN D_SMALLNAME AS
VARCHAR(40)
NOT NULL;

CREATE DOMAIN D_STOCKBATCHHISTORY_KIND AS
SMALLINT
NOT NULL
CHECK (VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_STOCKPOLICY AS
SMALLINT
default 0
check (value between 0 and 2);

CREATE DOMAIN D_STORED_PROC_NAME AS
CHAR(31);

CREATE DOMAIN D_SUMMA AS
NUMERIC(15,4)
default 0;

CREATE DOMAIN D_SUMMA_EXT AS
NUMERIC(18,6);

CREATE DOMAIN D_SYSPART_NODE AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK(VALUE BETWEEN 0 AND 3);

CREATE DOMAIN D_SYS_DATAITEM_KIND AS
SMALLINT
DEFAULT 0
CHECK (VALUE BETWEEN 0 AND 1);

CREATE DOMAIN D_SYS_VERSION AS
TIMESTAMP
default 'NOW';

CREATE DOMAIN D_TABLE_NAME AS
CHAR(31);

CREATE DOMAIN D_TIME_PERIOD_KIND AS
SMALLINT
DEFAULT 0
CHECK (VALUE BETWEEN 0 AND 4);

CREATE DOMAIN D_USERNAME AS
CHAR(31);

CREATE DOMAIN D_VOLUME AS
NUMERIC(15,3);

CREATE DOMAIN D_WEIGHT AS
NUMERIC(15,3);

CREATE DOMAIN D_WF_EVENT AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_WF_HOW_CLOSED AS
SMALLINT;

CREATE DOMAIN D_WF_PRIORITY AS
SMALLINT
NOT NULL
CHECK (value between 1 and 5);

CREATE DOMAIN D_WF_PROCESS_RESULT AS
VARCHAR(1024)
NOT NULL;

CREATE DOMAIN D_WF_REQUESTER_KIND AS
SMALLINT;

CREATE DOMAIN D_WF_RESOURCE_KIND AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_WF_STATE_STR AS
VARCHAR(100);

CREATE DOMAIN D_WF_TIME AS
TIMESTAMP;

CREATE DOMAIN D_WF_WHILE_OPEN AS
SMALLINT;

CREATE DOMAIN D_WF_WHY_NOT_RUNNING AS
SMALLINT;

CREATE DOMAIN D_WF_WHY_SUSPENDED AS
SMALLINT;

CREATE DOMAIN D_WORKFLOW_STATE AS
SMALLINT
NOT NULL;

CREATE DOMAIN D_ZIPCODE AS
VARCHAR(20);



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE SEQUENCE ACCBATCHHISTORY_ID_GEN;
CREATE SEQUENCE ACCBATCH_ID_GEN;
CREATE SEQUENCE ACCPLAN_ID_GEN;
CREATE SEQUENCE ACC_ACCGROUP_ID_GEN;
CREATE SEQUENCE ACC_ACCKIND_ID_GEN;
CREATE SEQUENCE ACC_ADVANCEREPHEADMODEL_ID_GEN;
CREATE SEQUENCE ACC_ADVANCEREPHEAD_ID_GEN;
CREATE SEQUENCE ACC_ADVANCEREPSPEC_ID_GEN;
CREATE SEQUENCE ACC_AMCODE_ID_GEN;
CREATE SEQUENCE ACC_AMORTIZATION_BATCH_GEN;
CREATE SEQUENCE ACC_AMORTIZATION_ID_GEN;
CREATE SEQUENCE ACC_AMRATE_ID_GEN;
CREATE SEQUENCE ACC_INVHEAD_ID_GEN;
CREATE SEQUENCE ACC_INVPRODUCTION_ID_GEN;
CREATE SEQUENCE ALG_CONST_ID_GEN;
CREATE SEQUENCE ALG_CONST_VAL_ID_GEN;
CREATE SEQUENCE ALG_CUSTOM_USER_ACTION_ID_GEN;
CREATE SEQUENCE ALG_REPOSITORY_ID_GEN;
CREATE SEQUENCE ALG_USER_ACT_PERM_ID_GEN;
CREATE SEQUENCE ANLPLAN_ID_GEN;
CREATE SEQUENCE AUDITINGCOMMISSION_ID_GEN;
CREATE SEQUENCE BANKDOCUMENTMODEL_ID_GEN;
CREATE SEQUENCE BANKDOCUMENT_ID_GEN;
CREATE SEQUENCE BANKREQUIS_ID_GEN;
CREATE SEQUENCE BILLHEADMODEL_ID_GEN;
CREATE SEQUENCE BILLHEAD_ID_GEN;
CREATE SEQUENCE BILLSPECMODEL_ID_GEN;
CREATE SEQUENCE BILLSPEC_ID_GEN;
CREATE SEQUENCE BUYBOOK_ID_GEN;
CREATE SEQUENCE CALCTAXESKIND_ID_GEN;
CREATE SEQUENCE CALCTAXESLINK_ID_GEN;
CREATE SEQUENCE CASHDOCUMENTMODEL_ID_GEN;
CREATE SEQUENCE CASHDOCUMENT_ID_GEN;
CREATE SEQUENCE CATALOGFOLDER_ID_GEN;
CREATE SEQUENCE CATALOGPRICE_ID_GEN;
CREATE SEQUENCE CATALOG_ID_GEN;
CREATE SEQUENCE CONTRACTMODIFYDOC_ID_GEN;
CREATE SEQUENCE CONTRACTORCARDHIST_ID_GEN;
CREATE SEQUENCE CONTRACTORCARDPLAN_ID_GEN;
CREATE SEQUENCE CONTRACTORCARD_ID_GEN;
CREATE SEQUENCE CONTRACTOR_ID_GEN;
CREATE SEQUENCE CONTRACTPHASE_ID_GEN;
CREATE SEQUENCE CONTRACTSPEC_ID_GEN;
CREATE SEQUENCE CONTRACT_CATEGORY_ID_GEN;
CREATE SEQUENCE CONTRACT_ID_GEN;
CREATE SEQUENCE CONTRACT_KIND_ID_GEN;
CREATE SEQUENCE CRM_ACTIVITY_KIND_ID_GEN;
CREATE SEQUENCE CRM_ACTIVITY_SPHERE_ID_GEN;
CREATE SEQUENCE CRM_BRANCH_ID_GEN;
CREATE SEQUENCE CRM_CLIENT_RANK_ID_GEN;
CREATE SEQUENCE CRM_CLIENT_TYPE_ID_GEN;
CREATE SEQUENCE CRM_CONTACT_ID_GEN;
CREATE SEQUENCE CRM_DELIVERY_KIND_ID_GEN;
CREATE SEQUENCE CRM_LINKED_DOC_ID_GEN;
CREATE SEQUENCE CRM_MARKET_ID_GEN;
CREATE SEQUENCE CRM_OFFER_FORECAST_ID_GEN;
CREATE SEQUENCE CRM_OFFER_ID_GEN;
CREATE SEQUENCE CRM_OFFER_KIND_ID_GEN;
CREATE SEQUENCE CRM_OFFER_REASON_ID_GEN;
CREATE SEQUENCE CRM_OFFER_STATUS_ID_GEN;
CREATE SEQUENCE CRM_OPERATION_ID_GEN;
CREATE SEQUENCE CRM_OPERATION_KIND_ID_GEN;
CREATE SEQUENCE CRM_OPERATION_PRIORITY_ID_GEN;
CREATE SEQUENCE CRM_OPERATION_PURPOSE_ID_GEN;
CREATE SEQUENCE CRM_OPERATION_STATUS_ID_GEN;
CREATE SEQUENCE CRM_OWNERSHIP_FORM_ID_GEN;
CREATE SEQUENCE CRM_PAYMENT_COND_ID_GEN;
CREATE SEQUENCE CRM_PERSON_REFER_ID_GEN;
CREATE SEQUENCE CRM_PERSON_TITLE_ID_GEN;
CREATE SEQUENCE CRM_POSITION_ID_GEN;
CREATE SEQUENCE CRM_PROBLEM_ID_GEN;
CREATE SEQUENCE CRM_PROBLEM_TYPE_ID_GEN;
CREATE SEQUENCE CRM_RELATION_ID_GEN;
CREATE SEQUENCE CRM_RELATION_STATUS_ID_GEN;
CREATE SEQUENCE CRM_SOLUTION_ID_GEN;
CREATE SEQUENCE CRM_SOLUTION_TYPE_ID_GEN;
CREATE SEQUENCE CRM_SYMPTOM_ID_GEN;
CREATE SEQUENCE CRM_USER_ID_GEN;
CREATE SEQUENCE CURRENCYCOUR_ID_GEN;
CREATE SEQUENCE CURRENCY_ID_GEN;
CREATE SEQUENCE DISCOUNT_ID_GEN;
CREATE SEQUENCE DIS_CARD_HIST_ID_GEN;
CREATE SEQUENCE DIS_CARD_ID_GEN;
CREATE SEQUENCE DIS_CARD_USER_ID_GEN;
CREATE SEQUENCE DIS_COEF_ID_GEN;
CREATE SEQUENCE DIS_EXTRA_DISCOUNT_ID_GEN;
CREATE SEQUENCE DIS_PROMOTION_ID_GEN;
CREATE SEQUENCE DIS_PROMOTION_LINE_ID_GEN;
CREATE SEQUENCE DIS_PROMOTION_TYPE_ID_GEN;
CREATE SEQUENCE DOCACTION_ID_GEN;
CREATE SEQUENCE DOCHEADMODEL_ID_GEN;
CREATE SEQUENCE DOCHEADSTATE_ID_GEN;
CREATE SEQUENCE DOCHEAD_ID_GEN;
CREATE SEQUENCE DOCPROCESSSTAGERIGHTS_ID_GEN;
CREATE SEQUENCE DOCPROCESSSTAGE_ID_GEN;
CREATE SEQUENCE DOCSPECMODEL_ID_GEN;
CREATE SEQUENCE DOCSPECSTATE_ID_GEN;
CREATE SEQUENCE DOCSPEC_ID_GEN;
CREATE SEQUENCE DOCSPEC_PACKAGE_ID_GEN;
CREATE SEQUENCE DOCTYPE_DOCSECTION_LINK_ID_GEN;
CREATE SEQUENCE DOCTYPE_RIGHTS_ID_GEN;
CREATE SEQUENCE DOCUMENT_LINK_ID_GEN;
CREATE SEQUENCE DOC_SPEC_PACKAGE_ID_GEN;
CREATE SEQUENCE DOC_SPEC_SERIAL_NUM_ID_GEN;
CREATE SEQUENCE ECONOMICOPERMODEL_ID_GEN;
CREATE SEQUENCE ECONOMICOPER_ID_GEN;
CREATE SEQUENCE ECONOMICSPECMODEL_ID_GEN;
CREATE SEQUENCE ECONOMICSPEC_ID_GEN;
CREATE SEQUENCE ECONSPECFEATURE_ID_GEN;
CREATE SEQUENCE EMPLOYEE_ID_GEN;
CREATE SEQUENCE ENTITY_TRANSFORMER_MPNG_ID_GEN;
CREATE SEQUENCE EXCH_EXPORT_ID_GEN;
CREATE SEQUENCE EXCH_IMPORT_ID_GEN;
CREATE SEQUENCE EXCH_SITE_ID_GEN;
CREATE SEQUENCE FACTURAHEADIN_ID_GEN;
CREATE SEQUENCE FACTURAHEADMODEL_ID_GEN;
CREATE SEQUENCE FACTURAHEAD_ID_GEN;
CREATE SEQUENCE FACTURAINSPEC_ID_GEN;
CREATE SEQUENCE FACTURASPECMODEL_ID_GEN;
CREATE SEQUENCE FACTURASPEC_ID_GEN;
CREATE SEQUENCE FEATURELINK_ID_GEN;
CREATE SEQUENCE FEATUREVAL_ID_GEN;
CREATE SEQUENCE FEATURE_DOCSECTION_LINK_ID_GEN;
CREATE SEQUENCE FEATURE_ID_GEN;
CREATE SEQUENCE FINACCOUNT_ID_GEN;
CREATE SEQUENCE FINANL_ID_GEN;
CREATE SEQUENCE FINOPERMODEL_ID_GEN;
CREATE SEQUENCE FINOPER_ID_GEN;
CREATE SEQUENCE FINPERIOD_ID_GEN;
CREATE SEQUENCE FINSPECMODEL_ID_GEN;
CREATE SEQUENCE FINSPEC_ID_GEN;
CREATE SEQUENCE FINSTRUCTURE_ID_GEN;
CREATE SEQUENCE FINTURNACC_ID_GEN;
CREATE SEQUENCE FINTURNFEAT_ID_GEN;
CREATE SEQUENCE FINTURN_ID_GEN;
CREATE SEQUENCE FOLDER_ID_GEN;
CREATE SEQUENCE FOLDER_RIGHTS_ID_GEN;
CREATE SEQUENCE FUEL_DENSITY_HEAD_ID_GEN;
CREATE SEQUENCE FUEL_DENSITY_SPEC_ID_GEN;
CREATE SEQUENCE GROUPS_ID_GEN;
CREATE SEQUENCE HIBERNATE_SEQUENCE;
CREATE SEQUENCE HR_ORDER_ID_GEN;
CREATE SEQUENCE HR_ORDER_IKIND_PARAM_ID_GEN;
CREATE SEQUENCE HR_ORDER_ITEM_ID_GEN;
CREATE SEQUENCE HR_ORDER_ITEM_KIND_ID_GEN;
CREATE SEQUENCE HR_ORDER_ITEM_PARAM_ID_GEN;
CREATE SEQUENCE HR_ORDER_ITEM_ROLLBACK_ID_GEN;
CREATE SEQUENCE HR_ORDER_MODEL_ID_GEN;
CREATE SEQUENCE HR_ORDER_MODEL_ITEM_ID_GEN;
CREATE SEQUENCE HR_ORD_MODEL_ITEM_PARAM_ID_GEN;
CREATE SEQUENCE INTERNALACTHEADMODEL_ID_GEN;
CREATE SEQUENCE INTERNALACTHEAD_ID_GEN;
CREATE SEQUENCE INTERNALACTSPECMODEL_ID_GEN;
CREATE SEQUENCE INTERNALACTSPEC_ID_GEN;
CREATE SEQUENCE INTERNALINVOICEHEADMODEL_ID_GEN;
CREATE SEQUENCE INTERNALINVOICEHEAD_ID_GEN;
CREATE SEQUENCE INTERNALINVOICESPECMODEL_ID_GEN;
CREATE SEQUENCE INTERNALINVOICESPEC_ID_GEN;
CREATE SEQUENCE INVENTORYACTHEAD_ID_GEN;
CREATE SEQUENCE INVENTORYACTSPEC_ID_GEN;
CREATE SEQUENCE INVENTORY_ID_GEN;
CREATE SEQUENCE INVHISTORY_ID_GEN;
CREATE SEQUENCE INVLOCATION_ID_GEN;
CREATE SEQUENCE INVMETAL_ID_GEN;
CREATE SEQUENCE INVOICEHEADMODEL_ID_GEN;
CREATE SEQUENCE INVOICEHEAD_ID_GEN;
CREATE SEQUENCE INVOICESPECMODEL_ID_GEN;
CREATE SEQUENCE INVOICESPEC_ID_GEN;
CREATE SEQUENCE JG_APP_PRINCIPAL_SEQ;
CREATE SEQUENCE JG_CREDENTIAL_SEQ;
CREATE SEQUENCE JG_DOMAIN_SEQ;
CREATE SEQUENCE JG_PERMISSION_SEQ;
CREATE SEQUENCE JG_PRINCIPAL_SEQ;
CREATE SEQUENCE JG_ST_CREDENTIAL_SEQ;
CREATE SEQUENCE JG_ST_PRINCIPAL_SEQ;
CREATE SEQUENCE JG_ST_USER_SEQ;
CREATE SEQUENCE JG_USER_SEQ;
CREATE SEQUENCE LINKSTAGE_ID_GEN;
CREATE SEQUENCE LS_ITEMKIND_ID_GEN;
CREATE SEQUENCE LS_ITEMSPECALT_ID_GEN;
CREATE SEQUENCE LS_ITEMSPECTAX_ID_GEN;
CREATE SEQUENCE LS_ITEMSPEC_ID_GEN;
CREATE SEQUENCE LS_ITEM_ID_GEN;
CREATE SEQUENCE LS_SCHEDULE_DOCHEAD_ID_GEN;
CREATE SEQUENCE LS_SCHEDULE_ID_GEN;
CREATE SEQUENCE MBPM_RESOURCE_GROUP_LINK_ID_GEN;
CREATE SEQUENCE MBPM_RESOURCE_ID_GEN;
CREATE SEQUENCE MEASURE_ID_GEN;
CREATE SEQUENCE MF_BOM_ID_GEN;
CREATE SEQUENCE MF_BOM_LABOR_ID_GEN;
CREATE SEQUENCE MF_BOM_MACHINE_ID_GEN;
CREATE SEQUENCE MF_BOM_MATERIAL_ID_GEN;
CREATE SEQUENCE MF_BOM_ROUTE_ID_GEN;
CREATE SEQUENCE MF_BOM_ROUTE_RESOURCE_ID_GEN;
CREATE SEQUENCE MF_CELL_ID_GEN;
CREATE SEQUENCE MF_COST_CATEGORIES_ID_GEN;
CREATE SEQUENCE MF_COST_DETAIL_ID_GEN;
CREATE SEQUENCE MF_COST_DETAIL_LINE_ID_GEN;
CREATE SEQUENCE MF_CREW_ID_GEN;
CREATE SEQUENCE MF_DAY_CAL_ID_GEN;
CREATE SEQUENCE MF_DAY_TIME_ID_GEN;
CREATE SEQUENCE MF_INPUT_DOC_HEAD_ID_GEN;
CREATE SEQUENCE MF_INPUT_DOC_HEAD_MODEL_ID_GEN;
CREATE SEQUENCE MF_INPUT_DOC_SPEC_ID_GEN;
CREATE SEQUENCE MF_JOB_ID_GEN;
CREATE SEQUENCE MF_JOB_LABOR_ID_GEN;
CREATE SEQUENCE MF_JOB_MACHINE_ID_GEN;
CREATE SEQUENCE MF_JOB_MATERIAL_ID_GEN;
CREATE SEQUENCE MF_JOB_ROUTE_ID_GEN;
CREATE SEQUENCE MF_JOB_ROUTE_RESOURCE_ID_GEN;
CREATE SEQUENCE MF_LABOR_CLASS_ID_GEN;
CREATE SEQUENCE MF_OUTPUT_DOC_HEAD_ID_GEN;
CREATE SEQUENCE MF_OUTPUT_DOC_HEAD_MODEL_ID_GEN;
CREATE SEQUENCE MF_RESOURCE_FAMILY_ID_GEN;
CREATE SEQUENCE MF_RESOURCE_GROUP_CAP_ID_GEN;
CREATE SEQUENCE MF_RESOURCE_GROUP_ID_GEN;
CREATE SEQUENCE MF_ROUTE_ID_GEN;
CREATE SEQUENCE MF_SCRAP_DOC_HEAD_ID_GEN;
CREATE SEQUENCE MF_SCRAP_DOC_HEAD_MODEL_ID_GEN;
CREATE SEQUENCE MF_SCRAP_DOC_SPEC_ID_GEN;
CREATE SEQUENCE MF_TRANSACTION_ID_GEN;
CREATE SEQUENCE MF_VARIANCE_DOC_HEAD_ID_GEN;
CREATE SEQUENCE MF_VARIANCE_DOC_SPEC_ID_GEN;
CREATE SEQUENCE MF_VARIANCE_D_H_MODEL_ID_GEN;
CREATE SEQUENCE MF_WC_RATES_ID_GEN;
CREATE SEQUENCE MF_WEEK_CAL_CHANGE_ID_GEN;
CREATE SEQUENCE MF_WEEK_CAL_ID_GEN;
CREATE SEQUENCE MF_WORK_CENTER_ID_GEN;
CREATE SEQUENCE NORMAMOR_ID_GEN;
CREATE SEQUENCE OKOF_ID_GEN;
CREATE SEQUENCE OLAP_DATAPUMP_ID_GEN;
CREATE SEQUENCE ORDERHEADMODEL_ID_GEN;
CREATE SEQUENCE ORDERHEAD_ID_GEN;
CREATE SEQUENCE ORDERSPECMODEL_ID_GEN;
CREATE SEQUENCE ORDERSPEC_ID_GEN;
CREATE SEQUENCE ORGUNIT_ID_GEN;
CREATE SEQUENCE OVR_CANCELLATION_ID_GEN;
CREATE SEQUENCE OVR_CARD_DOCUMENT_LINK_ID_GEN;
CREATE SEQUENCE OVR_CARD_HIST_ID_GEN;
CREATE SEQUENCE OVR_CARD_ID_GEN;
CREATE SEQUENCE OVR_CHIST_DOCSPEC_LINK_ID_GEN;
CREATE SEQUENCE OVR_HIST_STATUS_ID_GEN;
CREATE SEQUENCE OVR_NORM_HEAD_ID_GEN;
CREATE SEQUENCE OVR_NORM_SPEC_ID_GEN;
CREATE SEQUENCE OVR_NORM_SPEC_LINK_ID_GEN;
CREATE SEQUENCE OVR_N_SPEC_D_SPEC_LINK_ID_GEN;
CREATE SEQUENCE OVR_SIZE_ID_GEN;
CREATE SEQUENCE PACKING_ID_GEN;
CREATE SEQUENCE PARTNEMPL_ID_GEN;
CREATE SEQUENCE PARTNER_ID_GEN;
CREATE SEQUENCE PERIOD_ID_GEN;
CREATE SEQUENCE PERMISSIBLEACCOUNTS_ID_GEN;
CREATE SEQUENCE PHASEITEMFACT_ID_GEN;
CREATE SEQUENCE PHASEITEMPLAN_ID_GEN;
CREATE SEQUENCE PHASEITEM_LINK_ID_GEN;
CREATE SEQUENCE PMA_DOCGROUPLINK_ID_GEN;
CREATE SEQUENCE PMA_DOCGROUP_ID_GEN;
CREATE SEQUENCE PMA_PAYMENT_ID_GEN;
CREATE SEQUENCE PMA_TRHEAD_ID_GEN;
CREATE SEQUENCE PMA_TRSPEC_ID_GEN;
CREATE SEQUENCE PMA_TRTAX_ID_GEN;
CREATE SEQUENCE PMC_EXECUTION_ID_GEN;
CREATE SEQUENCE PMC_LIABILITY_ID_GEN;
CREATE SEQUENCE PMC_PERIOD_ID_GEN;
CREATE SEQUENCE PMC_PLAN_ID_GEN;
CREATE SEQUENCE PMC_RESOURCE_ID_GEN;
CREATE SEQUENCE PMC_VERSION_ID_GEN;
CREATE SEQUENCE PMC_VERSTATUS_ID_GEN;
CREATE SEQUENCE PP_CATALOG_WAREHOUSE_ID_GEN;
CREATE SEQUENCE PP_FIRM_PLANNED_ORDER_ID_GEN;
CREATE SEQUENCE PP_FORECAST_VERSION_ID_GEN;
CREATE SEQUENCE PP_GENERIC_ITEM_ID_GEN;
CREATE SEQUENCE PP_INVENTORY_FORECAST_ID_GEN;
CREATE SEQUENCE PP_INV_FORECAST_LINE_ID_GEN;
CREATE SEQUENCE PP_ITEM_FAMILY_ID_GEN;
CREATE SEQUENCE PP_MPS_ID_GEN;
CREATE SEQUENCE PP_MPS_LINE_ID_GEN;
CREATE SEQUENCE PP_MRP_INPUTS_ID_GEN;
CREATE SEQUENCE PP_MRP_OUTPUTS_ID_GEN;
CREATE SEQUENCE PP_MRP_RECOMMENDATION_ID_GEN;
CREATE SEQUENCE PP_MRP_REPORT_ID_GEN;
CREATE SEQUENCE PP_MRP_SHORTAGE_ID_GEN;
CREATE SEQUENCE PP_MRP_TOTALS_BY_DATE_ID_GEN;
CREATE SEQUENCE PP_MRP_VERSION_CONTROL_ID_GEN;
CREATE SEQUENCE PP_MRP_VERSION_FORECAST_ID_GEN;
CREATE SEQUENCE PP_MRP_VERSION_MPS_ID_GEN;
CREATE SEQUENCE PP_PLANNING_FORECAST_ID_GEN;
CREATE SEQUENCE PP_PLANNING_LEVEL_BUCKT_ID_GEN;
CREATE SEQUENCE PP_PLANNING_LEVEL_ID_GEN;
CREATE SEQUENCE PP_PRODUCTION_PROFILE_ID_GEN;
CREATE SEQUENCE PP_RCCP_DETAIL_ID_GEN;
CREATE SEQUENCE PP_RCCP_HEADER_ID_GEN;
CREATE SEQUENCE PP_RCCP_RESOURCE_LOAD_ID_GEN;
CREATE SEQUENCE PREF_ABBREVIATION_ID_GEN;
CREATE SEQUENCE PREF_ADDRESS_ID_GEN;
CREATE SEQUENCE PREF_ADD_EDUCATION_KIND_ID_GEN;
CREATE SEQUENCE PREF_AREA_ID_GEN;
CREATE SEQUENCE PREF_CALC_PERIOD_ID_GEN;
CREATE SEQUENCE PREF_CITY_ID_GEN;
CREATE SEQUENCE PREF_COSTS_ANL_ID_GEN;
CREATE SEQUENCE PREF_COUNTRY_ID_GEN;
CREATE SEQUENCE PREF_DEDUCTION_KIND_ID_GEN;
CREATE SEQUENCE PREF_DISTRICT_ID_GEN;
CREATE SEQUENCE PREF_EDUCATION_DEGREE_ID_GEN;
CREATE SEQUENCE PREF_FAMILYDEDUCTIONS_ID_GEN;
CREATE SEQUENCE PREF_FAMILYMEMBERS_ID_GEN;
CREATE SEQUENCE PREF_FAMILYRELATION_ID_GEN;
CREATE SEQUENCE PREF_FAMILYSTATUS_ID_GEN;
CREATE SEQUENCE PREF_FAMILYSTATUS_KIND_ID_GEN;
CREATE SEQUENCE PREF_FOREIGN_LANGUAGE_ID_GEN;
CREATE SEQUENCE PREF_IDENTDOC_ID_GEN;
CREATE SEQUENCE PREF_IDENTDOC_KIND_ID_GEN;
CREATE SEQUENCE PREF_INSUREDCLASS_ID_GEN;
CREATE SEQUENCE PREF_JOB_ID_GEN;
CREATE SEQUENCE PREF_KLADR_ID_GEN;
CREATE SEQUENCE PREF_LANGUAGE_KNOWLEDGE_ID_GEN;
CREATE SEQUENCE PREF_LEAVE_KIND_ID_GEN;
CREATE SEQUENCE PREF_MILITARY_RANK_ID_GEN;
CREATE SEQUENCE PREF_MILITARY_RANK_KIND_ID_GEN;
CREATE SEQUENCE PREF_MILITARY_VALIDITY_ID_GEN;
CREATE SEQUENCE PREF_NATIONALITY_ID_GEN;
CREATE SEQUENCE PREF_PCK_IN_SERVICEKIND_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_GROUP_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_GROUP_TYPE_GEN;
CREATE SEQUENCE PREF_PERSONNEL_HIST_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_LANGUAGE_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_LEAVE_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_PHONE_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_RECORD_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_REWARD_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_SERVICE_ID_GEN;
CREATE SEQUENCE PREF_PERSONNEL_TRANSFER_ID_GEN;
CREATE SEQUENCE PREF_PERS_ATTESTATION_ID_GEN;
CREATE SEQUENCE PREF_PERS_EDUCATION_ID_GEN;
CREATE SEQUENCE PREF_PERS_LAB_CONTRACT_ID_GEN;
CREATE SEQUENCE PREF_PERS_PROFESSION_ID_GEN;
CREATE SEQUENCE PREF_PERS_SKILL_RAISING_ID_GEN;
CREATE SEQUENCE PREF_PERS_SOC_BENEFIT_ID_GEN;
CREATE SEQUENCE PREF_PERS_VOCATNL_TRAIN_ID_GEN;
CREATE SEQUENCE PREF_PFCODE_IN_SERVICE_ID_GEN;
CREATE SEQUENCE PREF_POSITION_FILL_KIND_ID_GEN;
CREATE SEQUENCE PREF_POSITION_ID_GEN;
CREATE SEQUENCE PREF_REGION_ID_GEN;
CREATE SEQUENCE PREF_RESERVE_CATEGORY_ID_GEN;
CREATE SEQUENCE PREF_RISE_ID_GEN;
CREATE SEQUENCE PREF_RISE_PERCENT_ID_GEN;
CREATE SEQUENCE PREF_RISE_SCALE_ID_GEN;
CREATE SEQUENCE PREF_SERVICE_KIND_ID_GEN;
CREATE SEQUENCE PREF_SERVICE_PFCODE_ID_GEN;
CREATE SEQUENCE PREF_SKILL_RAISING_KIND_ID_GEN;
CREATE SEQUENCE PREF_SL_POSITION_UNIQUE_ID_GEN;
CREATE SEQUENCE PREF_SPECIALITY_ID_GEN;
CREATE SEQUENCE PREF_STAFF_CATEGORY_ID_GEN;
CREATE SEQUENCE PREF_STAFF_LIST_ID_GEN;
CREATE SEQUENCE PREF_STAFF_LIST_POSITION_ID_GEN;
CREATE SEQUENCE PREF_STAFF_LIST_UNIT_ID_GEN;
CREATE SEQUENCE PREF_STAFF_LST_POSITION_ID_GEN;
CREATE SEQUENCE PREF_STREET_ID_GEN;
CREATE SEQUENCE PREF_TARIFFING_CATEGORY_ID_GEN;
CREATE SEQUENCE PREF_TARIFFING_ID_GEN;
CREATE SEQUENCE PREF_TARIFF_SCALE_CLASS_ID_GEN;
CREATE SEQUENCE PREF_TARIFF_SCALE_ID_GEN;
CREATE SEQUENCE PREF_TAX_CALC_KIND_ID_GEN;
CREATE SEQUENCE PREF_WORKTIME_NORM_ID_GEN;
CREATE SEQUENCE PREF_WORK_CONDITION_ID_GEN;
CREATE SEQUENCE PREF_WORK_SCHEDULE_ID_GEN;
CREATE SEQUENCE PRICELISTFOLDER_ID_GEN;
CREATE SEQUENCE PRICELISTHEAD_ID_GEN;
CREATE SEQUENCE PRICELISTHEAD_RIGHTS_ID_GEN;
CREATE SEQUENCE PRICELISTSPEC_ID_GEN;
CREATE SEQUENCE PRICELIST_PT_LINK_ID_GEN;
CREATE SEQUENCE PRICETYPE_ID_GEN;
CREATE SEQUENCE PROVIDER_PRICELISTFOLDER_ID_GEN;
CREATE SEQUENCE PROVIDER_PRICELISTHEAD_ID_GEN;
CREATE SEQUENCE PROVIDER_PRICELISTSPEC_ID_GEN;
CREATE SEQUENCE PR_CONTACT_HIST_FILES_ID_GEN;
CREATE SEQUENCE PR_CONTACT_HIST_ID_GEN;
CREATE SEQUENCE PR_CONTACT_KIND_ID_GEN;
CREATE SEQUENCE PR_POSSIBLE_RESULT_ID_GEN;
CREATE SEQUENCE QC_SCRAP_REASON_ID_GEN;
CREATE SEQUENCE QC_SCRAP_TYPE_ID_GEN;
CREATE SEQUENCE REF_BANK_ACCOUNT_ID_GEN;
CREATE SEQUENCE REF_BANK_ACCOUNT_TYPE_ID_GEN;
CREATE SEQUENCE REF_BANK_ID_GEN;
CREATE SEQUENCE REF_CONFIDENTIAL_DATA_ID_GEN;
CREATE SEQUENCE REF_CONTRACTOR_EADDRESS_ID_GEN;
CREATE SEQUENCE REF_CONTRACTOR_PHONE_ID_GEN;
CREATE SEQUENCE REF_COUNTRY_ID_GEN;
CREATE SEQUENCE REF_CUR_RATE_AUTHORITY_ID_GEN;
CREATE SEQUENCE REF_CUR_RATE_ID_GEN;
CREATE SEQUENCE REF_CUR_RATE_TYPE_ID_GEN;
CREATE SEQUENCE REF_CUSTOMS_DECLARATION_ID_GEN;
CREATE SEQUENCE REF_DISTRICT_ID_GEN;
CREATE SEQUENCE REF_EADDRESS_KIND_ID_GEN;
CREATE SEQUENCE REF_FAMILY_MEMBER_ID_GEN;
CREATE SEQUENCE REF_FAMILY_RELATION_ID_GEN;
CREATE SEQUENCE REF_FAMILY_STATUS_ID_GEN;
CREATE SEQUENCE REF_FAMILY_STATUS_KIND_ID_GEN;
CREATE SEQUENCE REF_HOLIDAYS_ID_GEN;
CREATE SEQUENCE REF_IDENT_DOC_ID_GEN;
CREATE SEQUENCE REF_IDENT_DOC_KIND_ID_GEN;
CREATE SEQUENCE REF_KBK_ID_GEN;
CREATE SEQUENCE REF_MEASURE_CONV_ID_GEN;
CREATE SEQUENCE REF_NATIONALITY_ID_GEN;
CREATE SEQUENCE REF_NATURAL_PERSON_HIST_ID_GEN;
CREATE SEQUENCE REF_NATURAL_PERSON_ID_GEN;
CREATE SEQUENCE REF_OKATO_ID_GEN;
CREATE SEQUENCE REF_OKP_ID_GEN;
CREATE SEQUENCE REF_ORIGINAL_DOCUMENT_ID_GEN;
CREATE SEQUENCE REF_PARTN_EMPL_EMAIL_ID_GEN;
CREATE SEQUENCE REF_PARTN_EMPL_LINK_ID_GEN;
CREATE SEQUENCE REF_PARTN_EMPL_PHONE_ID_GEN;
CREATE SEQUENCE REF_PERSON_ADDRESS_ID_GEN;
CREATE SEQUENCE REF_PERSON_EADDRESS_ID_GEN;
CREATE SEQUENCE REF_PERSON_EMAIL_ID_GEN;
CREATE SEQUENCE REF_PERSON_PHONE_ID_GEN;
CREATE SEQUENCE REF_PHONE_KIND_ID_GEN;
CREATE SEQUENCE REF_PLACE_ID_GEN;
CREATE SEQUENCE REF_REGION_ID_GEN;
CREATE SEQUENCE REF_ZIPCODE_ID_GEN;
CREATE SEQUENCE REMNACC_ID_GEN;
CREATE SEQUENCE REMNANL_ID_GEN;
CREATE SEQUENCE REMNDBKT_ID_GEN;
CREATE SEQUENCE REMNVAL_ID_GEN;
CREATE SEQUENCE RPTBANDS_ID_GEN;
CREATE SEQUENCE RPTFIELDS_ID_GEN;
CREATE SEQUENCE RPTPARAMS_ID_GEN;
CREATE SEQUENCE RPTQUERIES_ID_GEN;
CREATE SEQUENCE RPT_CLASS_LINK_ID_GEN;
CREATE SEQUENCE RPT_MAIN_ID_GEN;
CREATE SEQUENCE RPT_RIGHTS_ID_GEN;
CREATE SEQUENCE RPT_TEMPLATE_ID_GEN;
CREATE SEQUENCE RTL_INVOICEHEADMODEL_ID_GEN;
CREATE SEQUENCE RTL_INVOICEHEAD_ID_GEN;
CREATE SEQUENCE RTL_INVOICESPEC_ID_GEN;
CREATE SEQUENCE SALEBOOK_ID_GEN;
CREATE SEQUENCE SAL_CALC_LIST_FEE_ID_GEN;
CREATE SEQUENCE SAL_CALC_LIST_FEE_PARAM_ID_GEN;
CREATE SEQUENCE SAL_CALC_LIST_ID_GEN;
CREATE SEQUENCE SAL_CALC_LIST_SECTION_ID_GEN;
CREATE SEQUENCE SAL_CLIST_SECTION_REF_ID_GEN;
CREATE SEQUENCE SAL_DISCOUNTKIND_ID_GEN;
CREATE SEQUENCE SAL_FEE_MODEL_ID_GEN;
CREATE SEQUENCE SAL_FEE_MODEL_PARAM_ID_GEN;
CREATE SEQUENCE SAL_FEE_REF_ID_GEN;
CREATE SEQUENCE SAL_FEE_REF_PARAM_ID_GEN;
CREATE SEQUENCE SAL_FEE_SUMMARY_HEAD_ID_GEN;
CREATE SEQUENCE SAL_FEE_SUMMARY_SPEC_ID_GEN;
CREATE SEQUENCE SAL_GNS_CODE_ID_GEN;
CREATE SEQUENCE SAL_INCLUDED_FEE_ID_GEN;
CREATE SEQUENCE SAL_INCOMEKIND_ID_GEN;
CREATE SEQUENCE SAL_MINSALARY_ID_GEN;
CREATE SEQUENCE SAL_PAY_ROLL_ID_GEN;
CREATE SEQUENCE SAL_PAY_SHEET_ID_GEN;
CREATE SEQUENCE SAL_PAY_SHEET_SPEC_ID_GEN;
CREATE SEQUENCE SAL_PERSONAL_ACCOUNT_ID_GEN;
CREATE SEQUENCE SAL_POSITION_FILL_ID_GEN;
CREATE SEQUENCE SAL_REPLACED_FEE_ID_GEN;
CREATE SEQUENCE SAL_ROLL_KIND_ID_GEN;
CREATE SEQUENCE SAL_TARIFFING_IN_FEE_ID_GEN;
CREATE SEQUENCE SAL_TAXHEAD_ID_GEN;
CREATE SEQUENCE SAL_TAXRATE_ID_GEN;
CREATE SEQUENCE SAL_TAXSCALE_ID_GEN;
CREATE SEQUENCE SCH_TASK_ID_GEN;
CREATE SEQUENCE SEC_GROUPS_ID_GEN;
CREATE SEQUENCE SEC_LINK_USERS_GROUPS_ID_GEN;
CREATE SEQUENCE SEC_METHOD_ACCESS_ID_GEN;
CREATE SEQUENCE SEC_MODULE_ACCESS_ID_GEN;
CREATE SEQUENCE SEC_USER_ID_GEN;
CREATE SEQUENCE SEC_USER_PROFILE_ID_GEN;
CREATE SEQUENCE SEC_USER_PROFILE_ITEM_ID_GEN;
CREATE SEQUENCE SETOFGOOD_ID_GEN;
CREATE SEQUENCE SPECMARK_ID_GEN;
CREATE SEQUENCE STOCKBATCHHISTORY_ID_GEN;
CREATE SEQUENCE STOCKBATCH_ID_GEN;
CREATE SEQUENCE STOCKCARD_ID_GEN;
CREATE SEQUENCE STOCKDOCUMENTHEADMODEL_ID_GEN;
CREATE SEQUENCE STOCKDOCUMENTHEAD_ID_GEN;
CREATE SEQUENCE STOCKDOCUMENTSPECMODEL_ID_GEN;
CREATE SEQUENCE STOCKDOCUMENTSPEC_ID_GEN;
CREATE SEQUENCE STOCKPLANHISTORY_ID_GEN;
CREATE SEQUENCE SYSPART_METHOD_ID_GEN;
CREATE SEQUENCE SYSPART_RIGHTS_ID_GEN;
CREATE SEQUENCE SYS_AUDIT_ID_GEN;
CREATE SEQUENCE SYS_CLASS_ID_GEN;
CREATE SEQUENCE SYS_CLASS_IMPL_ID_GEN;
CREATE SEQUENCE SYS_CLIENT_ID_GEN;
CREATE SEQUENCE SYS_COMPANY_ID_GEN;
CREATE SEQUENCE SYS_DATAITEM_ID_GEN;
CREATE SEQUENCE SYS_DB_AUDIT_DETAIL_ID_GEN;
CREATE SEQUENCE SYS_DB_AUDIT_ID_GEN;
CREATE SEQUENCE SYS_DB_AUDIT_SETUP_ID_GEN;
CREATE SEQUENCE SYS_DOMAIN_ID_GEN;
CREATE SEQUENCE SYS_FORM_ID_GEN;
CREATE SEQUENCE SYS_METHOD_ID_GEN;
CREATE SEQUENCE SYS_MODULE_ID_GEN;
CREATE SEQUENCE SYS_SECURITY_AUDIT_ID_GEN;
CREATE SEQUENCE SYS_WINDOW_ID_GEN;
CREATE SEQUENCE TAB_PATTERN_HEAD_ID_GEN;
CREATE SEQUENCE TAB_PATTERN_SPEC_ID_GEN;
CREATE SEQUENCE TAB_SCHEDULE_HEAD_ID_GEN;
CREATE SEQUENCE TAB_SCHEDULE_SPEC_ID_GEN;
CREATE SEQUENCE TAB_TIME_BOARD_HEAD_ID_GEN;
CREATE SEQUENCE TAB_TIME_BOARD_POSITION_ID_GEN;
CREATE SEQUENCE TAB_TIME_BOARD_SPEC_ID_GEN;
CREATE SEQUENCE TAB_TIME_KIND_ID_GEN;
CREATE SEQUENCE TAXGROUP_ID_GEN;
CREATE SEQUENCE TAXLINK_ID_GEN;
CREATE SEQUENCE TAXSUMM_ID_GEN;
CREATE SEQUENCE TAX_ID_GEN;
CREATE SEQUENCE TURNONESFEATURES_ID_GEN;
CREATE SEQUENCE TURNVAL_ID_GEN;
CREATE SEQUENCE TURNVAL_SESSION_GEN;
CREATE SEQUENCE TYPEDOC_ID_GEN;
CREATE SEQUENCE WF_ACTIVITY_ID_GEN;
CREATE SEQUENCE WF_ACTIVITY_MODEL_ID_GEN;
CREATE SEQUENCE WF_ASSIGNMENT_ID_GEN;
CREATE SEQUENCE WF_AUDIT_ID_GEN;
CREATE SEQUENCE WF_AVAILABLE_RESOURCE_ID_GEN;
CREATE SEQUENCE WF_LINK_GROUP_RESOURCE_ID_GEN;
CREATE SEQUENCE WF_MAP_EDGE_ID_GEN;
CREATE SEQUENCE WF_PROCESS_ID_GEN;
CREATE SEQUENCE WF_PROCESS_MGR_ID_GEN;
CREATE SEQUENCE WF_REQUESTER_ID_GEN;
CREATE SEQUENCE WF_RESOURCE_ID_GEN;
CREATE SEQUENCE WF_RESULT_ID_GEN;
CREATE SEQUENCE WF_ROLLBACK_SEGMENT_ID_GEN;
CREATE SEQUENCE WH_BIN_LOCATION_DETAIL_ID_GEN;
CREATE SEQUENCE WH_BIN_LOCATION_ID_GEN;
CREATE SEQUENCE WH_BIN_LOCATION_TYPE_ID_GEN;
CREATE SEQUENCE WH_BT_CAP_BY_PRODUCT_ID_GEN;
CREATE SEQUENCE WH_INVACT_COMMISSION_ID_GEN;
CREATE SEQUENCE WH_SECURITY_ID_GEN;
CREATE SEQUENCE WH_SERIAL_NUM_ID_GEN;
CREATE SEQUENCE WH_STOCK_KIND_ID_GEN;
CREATE SEQUENCE WH_WAREHOUSE_ID_GEN;
CREATE SEQUENCE WH_WAREHOUSE_TR_DAY_ID_GEN;
CREATE SEQUENCE WH_WAREHOUSE_TYPE_ID_GEN;
CREATE SEQUENCE WH_ZONE_ID_GEN;


/******************************************************************************/
/****                             Descriptions                             ****/
/******************************************************************************/

