package com.mg.merp.humanresources.model;

import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OrderItemKindParam generated by hbm2java
 */
@Entity
@Table(name = "HR_ORDER_ITEM_KIND_PARAM")
public class OrderItemKindParam extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private OrderItemKind ItemKind;

    private String Code;

    private String Name;

    private Integer Priority;

    private Short ParamType;

    private String SysCode;

    private Set<OrderModelItemParam> OrderModelItemParams = new HashSet<OrderModelItemParam>(0);

    private Set<OrderItemParam> OrderItemParams = new HashSet<OrderItemParam>(0);

    public OrderItemKindParam() {
    }

    public OrderItemKindParam(OrderItemKind ItemKind, String Code, String Name, String SysCode) {
        this.ItemKind = ItemKind;
        this.Code = Code;
        this.Name = Name;
        this.SysCode = SysCode;
    }

    public OrderItemKindParam(SysClient SysClient, OrderItemKind ItemKind, String Code, String Name, Integer Priority, Short ParamType, String SysCode, Set<OrderModelItemParam> OrderModelItemParams, Set<OrderItemParam> OrderItemParams) {
        this.SysClient = SysClient;
        this.ItemKind = ItemKind;
        this.Code = Code;
        this.Name = Name;
        this.Priority = Priority;
        this.ParamType = ParamType;
        this.SysCode = SysCode;
        this.OrderModelItemParams = OrderModelItemParams;
        this.OrderItemParams = OrderItemParams;
    }

    @SequenceGenerator(name = "generator", sequenceName = "HR_ORDER_ITEM_KIND_PARAM_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    //$NON-NLS-1$
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ITEM_KIND_ID", nullable = false)
    public OrderItemKind getItemKind() {
        return this.ItemKind;
    }

    public void setItemKind(OrderItemKind ItemKind) {
        this.ItemKind = ItemKind;
    }

    @Column(name = "CODE", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "NAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "PRIORITY", columnDefinition = "INTEGER")
    public Integer getPriority() {
        return this.Priority;
    }

    public void setPriority(Integer Priority) {
        this.Priority = Priority;
    }

    @Column(name = "PARAM_TYPE", columnDefinition = "SMALLINT")
    public Short getParamType() {
        return this.ParamType;
    }

    public void setParamType(Short ParamType) {
        this.ParamType = ParamType;
    }

    @Column(name = "SYS_CODE", nullable = false, columnDefinition = "CHAR", length = 20)
    public String getSysCode() {
        return this.SysCode;
    }

    public void setSysCode(String SysCode) {
        this.SysCode = SysCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ItemKindParam")
    public Set<OrderModelItemParam> getOrderModelItemParams() {
        return this.OrderModelItemParams;
    }

    public void setOrderModelItemParams(Set<OrderModelItemParam> OrderModelItemParams) {
        this.OrderModelItemParams = OrderModelItemParams;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ItemKindParam")
    public Set<OrderItemParam> getOrderItemParams() {
        return this.OrderItemParams;
    }

    public void setOrderItemParams(Set<OrderItemParam> OrderItemParams) {
        this.OrderItemParams = OrderItemParams;
    }
}

