package com.mg.merp.humanresources.model;

import com.mg.merp.core.model.SysClient;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OrderItemKind generated by hbm2java
 */
@Entity
@Table(name = "HR_ORDER_ITEM_KIND")
public class OrderItemKind extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private String Code;

    private String Name;

    private Integer Priority;

    private String SysCode;

    private Set<OrderItemKindParam> OrderItemKindParams = new HashSet<OrderItemKindParam>(0);

    private Set<OrderModelItem> OrderModelItems = new HashSet<OrderModelItem>(0);

    private Set<OrderItem> OrderItems = new HashSet<OrderItem>(0);

    public OrderItemKind() {
    }

    public OrderItemKind(String Code, String Name, String SysCode) {
        this.Code = Code;
        this.Name = Name;
        this.SysCode = SysCode;
    }

    public OrderItemKind(SysClient SysClient, String Code, String Name, Integer Priority, String SysCode, Set<OrderItemKindParam> OrderItemKindParams, Set<OrderModelItem> OrderModelItems, Set<OrderItem> OrderItems) {
        this.SysClient = SysClient;
        this.Code = Code;
        this.Name = Name;
        this.Priority = Priority;
        this.SysCode = SysCode;
        this.OrderItemKindParams = OrderItemKindParams;
        this.OrderModelItems = OrderModelItems;
        this.OrderItems = OrderItems;
    }

    @SequenceGenerator(name = "generator", sequenceName = "HR_ORDER_ITEM_KIND_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @Column(name = "CODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 20)
    public String getCode() {
        return this.Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    @Column(name = "NAME", nullable = false, columnDefinition = "VARCHAR", length = 80)
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "PRIORITY", columnDefinition = "INTEGER")
    public Integer getPriority() {
        return this.Priority;
    }

    public void setPriority(Integer Priority) {
        this.Priority = Priority;
    }

    @Column(name = "SYS_CODE", unique = true, nullable = false, columnDefinition = "CHAR", length = 20)
    public String getSysCode() {
        return this.SysCode;
    }

    public void setSysCode(String SysCode) {
        this.SysCode = SysCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ItemKind")
    public Set<OrderItemKindParam> getOrderItemKindParams() {
        return this.OrderItemKindParams;
    }

    public void setOrderItemKindParams(Set<OrderItemKindParam> OrderItemKindParams) {
        this.OrderItemKindParams = OrderItemKindParams;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ItemKind")
    public Set<OrderModelItem> getOrderModelItems() {
        return this.OrderModelItems;
    }

    public void setOrderModelItems(Set<OrderModelItem> OrderModelItems) {
        this.OrderModelItems = OrderModelItems;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "OrderItemKind")
    public Set<OrderItem> getOrderItems() {
        return this.OrderItems;
    }

    public void setOrderItems(Set<OrderItem> OrderItems) {
        this.OrderItems = OrderItems;
    }
}

