CREATE DOMAIN D_CURCOURCE AS
NUMERIC(15,5);

CREATE DOMAIN D_DESCRIPTION AS
VARCHAR(1024);

CREATE DOMAIN D_DOCNUMBER AS
VARCHAR(20);

CREATE DOMAIN D_DOCTYPE AS
VARCHAR(15);

CREATE DOMAIN D_ECONSPEC_FEATURE_CODE AS
VARCHAR(10);

CREATE DOMAIN D_EMAIL AS
VARCHAR(50);

CREATE DOMAIN D_FEATURE AS
VARCHAR(80);

CREATE DOMAIN D_FEATURE_INT AS
INTEGER;

CREATE DOMAIN D_FEATURE_STR AS
VARCHAR(2048);

CREATE DOMAIN D_FILENAME AS
VARCHAR(256);

CREATE DOMAIN D_FORMAT AS
VARCHAR(80);

CREATE DOMAIN D_FORMULA AS
VARCHAR(2048);

CREATE DOMAIN D_HOUR AS
NUMERIC(18,6);

CREATE DOMAIN D_LARGECODE AS
VARCHAR(40);

CREATE DOMAIN D_MEASURE_CONTROL AS
SMALLINT;

CREATE DOMAIN D_MEASURE_CONVERSION AS
VARCHAR(512);

CREATE DOMAIN D_MEDIUMCODE AS
VARCHAR(10);

CREATE DOMAIN D_NAME AS
VARCHAR(80);

CREATE DOMAIN D_PHONE AS
VARCHAR(80);

CREATE DOMAIN D_PHONELIST AS
VARCHAR(40);

CREATE DOMAIN D_QUANTITY AS
NUMERIC(18,3);

CREATE DOMAIN D_QUANTITY_EXT AS
NUMERIC(18,6);

CREATE DOMAIN D_QUERY AS
VARCHAR(8192);

CREATE DOMAIN D_RATIO AS
NUMERIC(18,6);

CREATE DOMAIN D_RPT_ENUMVALUES AS
VARCHAR(1024);

CREATE DOMAIN D_SUMMA AS
NUMERIC(18,6);