/*
 * Generated by XDoclet - Do not edit!
 */
package com.mg.merp.manufacture;

import com.mg.merp.document.DocumentPattern;
import com.mg.merp.manufacture.model.InputDocumentModel;

/**
 * Local interface for InputMaterialModelService.
 *
 * @xdoclet-generated at 28-02-06
 * @since 12.10.2004
 */
public interface InputMaterialModelServiceLocal
    extends DocumentPattern<InputDocumentModel, Integer> {
  /**
   * тип папки для образцов актов на списание времени, отработанного РС в НЗП
   */
  final static short FOLDER_PART = 12511;
}