package com.mg.merp.manufacture.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.mfreference.model.CostDetail;
import com.mg.merp.mfreference.model.ResourceGroup;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * JobRouteResource generated by hbm2java
 */
@Entity
@Table(name="MF_JOB_ROUTE_RESOURCE"
)
public class JobRouteResource extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private ResourceGroup ResourceGroup;
     private CostDetail ActCostDetail;
     private SysClient SysClient;
     private CostDetail StdCostDetail;
     private JobRoute Oper;
     private Short ResourceType;
     private Integer TimeSequence;
     private Date EffOnDate;
     private Date EffOffDate;
     private String Comment;

    public JobRouteResource() {
    }

    public JobRouteResource(ResourceGroup ResourceGroup, CostDetail ActCostDetail, SysClient SysClient, CostDetail StdCostDetail, JobRoute Oper, Short ResourceType, Integer TimeSequence, Date EffOnDate, Date EffOffDate, String Comment) {
       this.ResourceGroup = ResourceGroup;
       this.ActCostDetail = ActCostDetail;
       this.SysClient = SysClient;
       this.StdCostDetail = StdCostDetail;
       this.Oper = Oper;
       this.ResourceType = ResourceType;
       this.TimeSequence = TimeSequence;
       this.EffOnDate = EffOnDate;
       this.EffOffDate = EffOffDate;
       this.Comment = Comment;
    }
   
     @SequenceGenerator(name="generator", sequenceName="MF_JOB_ROUTE_RESOURCE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCE_GROUP_ID")
    public ResourceGroup getResourceGroup() {
        return this.ResourceGroup;
    }
    
    public void setResourceGroup(ResourceGroup ResourceGroup) {
        this.ResourceGroup = ResourceGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACT_COST_DETAIL_ID")
    public CostDetail getActCostDetail() {
        return this.ActCostDetail;
    }
    
    public void setActCostDetail(CostDetail ActCostDetail) {
        this.ActCostDetail = ActCostDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STD_COST_DETAIL_ID")
    public CostDetail getStdCostDetail() {
        return this.StdCostDetail;
    }
    
    public void setStdCostDetail(CostDetail StdCostDetail) {
        this.StdCostDetail = StdCostDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OPER_ID")
    public JobRoute getOper() {
        return this.Oper;
    }
    
    public void setOper(JobRoute Oper) {
        this.Oper = Oper;
    }

    
    @Column(name="RESOURCE_TYPE", columnDefinition="SMALLINT")
    public Short getResourceType() {
        return this.ResourceType;
    }
    
    public void setResourceType(Short ResourceType) {
        this.ResourceType = ResourceType;
    }

    
    @Column(name="TIME_SEQUENCE", columnDefinition="INTEGER")
    public Integer getTimeSequence() {
        return this.TimeSequence;
    }
    
    public void setTimeSequence(Integer TimeSequence) {
        this.TimeSequence = TimeSequence;
    }

    
    @Column(name="EFF_ON_DATE", columnDefinition="TIMESTAMP")
    public Date getEffOnDate() {
        return this.EffOnDate;
    }
    
    public void setEffOnDate(Date EffOnDate) {
        this.EffOnDate = EffOnDate;
    }

    
    @Column(name="EFF_OFF_DATE", columnDefinition="TIMESTAMP")
    public Date getEffOffDate() {
        return this.EffOffDate;
    }
    
    public void setEffOffDate(Date EffOffDate) {
        this.EffOffDate = EffOffDate;
    }

    
    @Column(name="COMMENT", columnDefinition="VARCHAR", length=256)
    public String getComment() {
        return this.Comment;
    }
    
    public void setComment(String Comment) {
        this.Comment = Comment;
    }




}


