package com.mg.merp.manufacture.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.framework.support.orm.EnumUserType;
import com.mg.merp.core.model.SysClient;
import com.mg.merp.document.model.DocHead;
import com.mg.merp.document.model.DocSpec;
import com.mg.merp.document.model.DocumentSpecSerialNum;
import com.mg.merp.document.model.DocumentSpecTax;
import com.mg.merp.mfreference.model.CostCategories;
import com.mg.merp.reference.model.Catalog;
import com.mg.merp.reference.model.Contractor;
import com.mg.merp.reference.model.Country;
import com.mg.merp.reference.model.CustomsDeclaration;
import com.mg.merp.reference.model.Measure;
import com.mg.merp.reference.model.PriceListSpec;
import com.mg.merp.reference.model.TaxGroup;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VarianceDocumentSpec generated by hbm2java
 */
@Entity
@Table(name="MF_VARIANCE_DOC_SPEC"
)
public class VarianceDocumentSpec extends com.mg.merp.document.model.DocSpec implements java.io.Serializable {


     private CostCategories CostCategory;
     private EnumUserType VarianceType;

    public VarianceDocumentSpec() {
    }

	
    public VarianceDocumentSpec(EnumUserType ShelfLifeMeas, EnumUserType VarianceType) {
        super(ShelfLifeMeas);        
        this.VarianceType = VarianceType;
    }
    public VarianceDocumentSpec(DocSpec OrderSpec, Catalog Catalog, TaxGroup TaxGroup, Contractor DstMol, Contractor SrcMol, PriceListSpec PriceListSpec, DocHead DocHead, Measure Measure2, SysClient SysClient, Contractor DstStock, Measure Measure1, Contractor SrcStock, BigDecimal Quantity, BigDecimal Price, BigDecimal Summa, BigDecimal Price1, BigDecimal Summa1, BigDecimal Weight, BigDecimal Volume, Date BestBefore, BigDecimal ShelfLife, EnumUserType ShelfLifeMeas, Date ProductionDate, BigDecimal Quantity2, String Comment, Contractor Contractor, String UNID, CustomsDeclaration CustomsDeclaration, Country CountryOfOrigin, Set<DocumentSpecTax> Taxes, Set<DocumentSpecSerialNum> SerialNumbers, CostCategories CostCategory, EnumUserType VarianceType) {
        super(OrderSpec, Catalog, TaxGroup, DstMol, SrcMol, PriceListSpec, DocHead, Measure2, SysClient, DstStock, Measure1, SrcStock, Quantity, Price, Summa, Price1, Summa1, Weight, Volume, BestBefore, ShelfLife, ShelfLifeMeas, ProductionDate, Quantity2, Comment, Contractor, UNID, CustomsDeclaration, CountryOfOrigin, Taxes, SerialNumbers);        
       this.CostCategory = CostCategory;
       this.VarianceType = VarianceType;
    }
   

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COST_CATEGORY_ID")
    public CostCategories getCostCategory() {
        return this.CostCategory;
    }
    
    public void setCostCategory(CostCategories CostCategory) {
        this.CostCategory = CostCategory;
    }

    
    @Column(name="VARIANCE_TYPE", nullable=false, columnDefinition="SMALLINT")
    public EnumUserType getVarianceType() {
        return this.VarianceType;
    }
    
    public void setVarianceType(EnumUserType VarianceType) {
        this.VarianceType = VarianceType;
    }




}


