/*
 * Generated by XDoclet - Do not edit!
 */
package com.mg.merp.core;

/**
 * Local interface for LicenseKeeper.
 * @xdoclet-generated at 1-03-06
 */
public interface LicenseKeeperLocal
   extends javax.ejb.EJBLocalObject, com.mg.framework.service.SessionPinger
{

}
