INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Партнеры', 1, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'План счетов', 2, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Хозяйственные операции', 6, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Прочие банковские документы', 8, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Входящие банковские документы', 9, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Исходящие банковские документы', 10, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Приходные кассовые ордера', 11, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Расходные кассовые ордера', 12, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Прочие банковские документы', 13, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Входящие банковские документы', 14, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Исходящие банковские документы', 15, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Приходные кассовые ордера', 16, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Расходные кассовые ордера', 17, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы хозяйственных операций', 18, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Внутренние накладные', 19, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы внутренних накладных', 20, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Инвентарная картотека', 7, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Входящие счета-фактуры', 21, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Исходящие счета фактуры', 23, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы входящих счетов - фактур', 22, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы исходящих счетов - фактур', 24, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Книга покупок', 26, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Книга продаж', 27, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты', 28, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы актов', 29, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Приходные ордера', 30, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Расходные ордера', 31, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы приходных ордеров', 32, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы расходных ордеров', 33, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты инвентаризации', 34, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Контракты', 35, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы договоров', 36, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Скидки/наценки', 13101, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Счета финансового учета', 38, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Признаки финансового учета', 39, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Финансовые операции', 40, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Заказы поставщикам', 41, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Заказы покупателей', 42, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы заказов поставщикам', 43, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы заказов покупателей', 44, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Входящие накладные', 45, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Исходящие накладные', 46, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы входящих накладных', 47, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы исходящих накладных', 48, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Входящие счета', 49, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Исходящие счета', 50, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы входящих счетов', 51, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы исходящих счетов', 52, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы финансовых операций', 53, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Менеджеры потоков', 54, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Журналы плотностей', 1000, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'История контактов', 2000, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Нормы выдачи', 55, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Коды стажа для ПФ', 3001, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Репозиторий алгоритмов', 9500, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Отчеты', 5001, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Задания планировщика', 13000, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Константы', 9510, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Дисконтные карты', 13100, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Документы на отпуск', 13200, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы документов на отпуск', 13201, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Своды начислений/удержаний по аналитике', 10501, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Своды начислений/удержаний по аналитике', 10502, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Заказ - наряды на производство', 12501, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Спецификация продукции', 12001, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты выпуска продукции', 12502, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты на списание материалов в НЗП', 12503, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты на списание времени, отработанного РС в НЗП', 12504, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание времени, отработанного оборудованием в НЗП', 12505, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь с операции', 12506, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь материалов', 12507, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь времени, отработанного РС', 12508, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь времени, отработанного оборудованием', 12509, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты выпуска продукции', 12510, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание материалов в НЗП', 12511, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акты на списание времени, отработанного РС в НЗП', 12512, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание времени, отработанного оборудованием в НЗП', 12513, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь с операции', 12514, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь материалов', 12515, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь времени, отработанного РС', 12516, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Акт на списание потерь времени, отработанного оборудованием', 12517, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Документы по отклонениям', 12518, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы документов по отклонениям', 12519, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Журнал платежей', 13300, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы записей журнала платежей', 13301, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Оригиналы документов', 2501, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Авансовые отчеты', 6001, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы авансовых отчетов', 6002, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Варианты штатного расписания', 3002, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Физические лица', 2502, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Приказы', 11501, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Средства платежа', 13400, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Реестр обязательств', 13401, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы обязательств', 13402, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Графики исполнения обязательств', 13600, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Образцы приказов', 11502, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Отношения', 13500, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Симптомы', 13501, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Проблемы', 13502, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);
INSERT INTO FOLDER (ID, PARENT_ID, FNAME, FOLDERTYPE, DATA, FOLDER_TAG, CLIENT_ID) VALUES (nextval('folder_id_gen'), NULL, 'Решения', 13503, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 0, currval('folder_id_gen'), true, 1);

INSERT INTO CATALOGFOLDER (ID, PARENT_ID, FNAME, GROUPCODE, BARCODE, PLUCODE, NUMBERING_ALG_ID, FOLDER_TAG, CLIENT_ID) VALUES (nextval('catalogfolder_id_gen'), NULL, 'Каталог', 'Каталог', NULL, NULL, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 1, (select cf.id from catalogfolder cf where cf.parent_id is null), true, 1);

INSERT INTO CONTRACTOR (ID, CODE, UPCODE, CNAME, FOLDER_ID, KIND, CLIENT_ID) VALUES (nextval('contractor_id_gen'), 'Холдинг', 'ХОЛДИНГ', 'Холдинг', NULL, 1, 1);
INSERT INTO ORGUNIT (KIND, IS_OFFICE, IS_STORE, PARTNER_ID, CONTRACTOR_ID, RESOURCE_GROUP_ID, FOLDER_TAG) VALUES (0, true, false, NULL, currval('contractor_id_gen'), NULL, NULL);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 4, currval('contractor_id_gen'), true, 1);

INSERT INTO PREF_PERSONNEL_GROUP (ID, FLDNAME, GROUPTYPE_ID, PARENT_ID, FOLDER_TAG, CLIENT_ID) VALUES (nextval('pref_personnel_group_id_gen'), 'Основные сведения о сотрудниках', NULL, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 5, currval('pref_personnel_group_id_gen'), true, 1);

INSERT INTO PREF_SERVICE_KIND (ID, KNAME, PARENT_ID, KCODE, BEGINSERVICE_ALG_ID, ENDSERVICE_ALG_ID, LENGTHSERVICE_ALG_ID, FOLDER_TAG, CLIENT_ID) VALUES (nextval('pref_service_kind_id_gen'), 'Виды стажа', NULL, '1', NULL, NULL, NULL, NULL, 1);
INSERT INTO FOLDER_RIGHTS (ID, GROUP_ID, FOLDERPART, FOLDER_ID, RIGHTS, CLIENT_ID) VALUES (nextval('folder_rights_id_gen'), 1, 7, currval('pref_service_kind_id_gen'), true, 1);

INSERT INTO FINSTRUCTURE (ID, PARENT_ID, CODE, UPCODE, SNAME, KIND, CLIENT_ID) VALUES (nextval('finstructure_id_gen'), NULL, 'Холдинг', 'ХОЛДИНГ', 'Холдинг', 0, 1);
