INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (1, 'Создание', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (2, 'Создание на основе', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (3, 'Создание документа на основании текущего', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (4, 'Связать с другим документом', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13, 'Создать хозяйственную операцию', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (14, 'Регистрация счета фактуры', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (15, 'Регистрация даты оприходования', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (16, 'Регистрация даты оплаты', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (17, 'Регистрация в книге покупок', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (18, 'Регистрация в книге продаж', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (19, 'Отработка по складу', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (20, 'Электронная подпись', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (21, 'Отработка планируемого движения по складу', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (22, 'Снятие с плана движения по складу', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (23, 'Резервирование по складу', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (24, 'Снятие с резерва по складу', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (25, 'Отработать документ как факт по договору', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (26, 'Отработать документ как план по договору', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (27, 'Собрать комплект', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (28, 'Разобрать комплект', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (29, 'Создать документ на комплектующие', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (30, 'Рассчитать цены в документе на основании данных склада', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (31, 'Отработать в расчетах', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (33, 'Акцептовать счет', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (34, 'Настраиваемый пользователем', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (35, 'Создание финансовой операции', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (36, 'Поставить в план расчетов с партнером', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (37, 'Снять с плана расчетов с партнером', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (50, 'Создание документа пользовательским алгоритмом', true);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (60, 'Завершение документооборота', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10001, 'Отработка по складу интерактивная', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10002, 'Отработка по складу с вычислением цены списания', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10003, 'Отработка по складу интерактивная с вычислением цены списания', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10004, 'Отработать документ как факт по заказу', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (10005, 'Проставить номер ГТД из складской партии', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (11001, 'Отработать в ЛКС выдачу по норме', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (11002, 'Отработать в ЛКС ввод в эксплуатацию', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (11003, 'Отработать в ЛКС вывод из эксплуатации', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12001, 'Отработка акта выпуска готовой продукции по заказ - наряду на производство', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12002, 'Отработка обратного списания', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12003, 'Отработка по регистру фактической себестоимости', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12004, 'Отработка акта списания потерь по заказ - наряду на производство', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (12005, 'Создание актов на списание потерь', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13000, 'Создание записи журнала платежей', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13001, 'Отработка в журнале платежей', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13002, 'Отработка в журнале платежей интерактивная', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13100, 'Создание записи реестра обязательств', false);
INSERT INTO DP_STAGE_ACTION (ID, NAME, CREATEDOC_FLAG) VALUES (13101, 'Подтверждение исполнения обязательства', true);
