package com.mg.merp.discount.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.security.model.SecUser;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ExtraDiscount generated by hbm2java
 */
@Entity
@Table(name="DIS_EXTRA_DISCOUNT"
)
public class ExtraDiscount extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private Card Card;
     private SysClient SysClient;
     private String Name;
     private BigDecimal Discount;
     private BigDecimal PlanSale;
     private Date DateFrom;
     private Date DateTill;
     private boolean IsActive;
     private SecUser User;
     private BigDecimal FactSale;
     private String Comments;

    public ExtraDiscount() {
    }

    public ExtraDiscount(Card Card, SysClient SysClient, String Name, BigDecimal Discount, BigDecimal PlanSale, Date DateFrom, Date DateTill, boolean IsActive, SecUser User, BigDecimal FactSale, String Comments) {
       this.Card = Card;
       this.SysClient = SysClient;
       this.Name = Name;
       this.Discount = Discount;
       this.PlanSale = PlanSale;
       this.DateFrom = DateFrom;
       this.DateTill = DateTill;
       this.IsActive = IsActive;
       this.User = User;
       this.FactSale = FactSale;
       this.Comments = Comments;
    }
   
     @SequenceGenerator(name="generator", sequenceName="DIS_EXTRA_DISCOUNT_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CARD_ID")
    public Card getCard() {
        return this.Card;
    }
    
    public void setCard(Card Card) {
        this.Card = Card;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    
    @Column(name="NAME", columnDefinition="VARCHAR", length=80)
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }

    
    @Column(name="DISCOUNT", columnDefinition="NUMERIC", precision=18, scale=6)
    public BigDecimal getDiscount() {
        return this.Discount;
    }
    
    public void setDiscount(BigDecimal Discount) {
        this.Discount = Discount;
    }

    
    @Column(name="PLANSALE", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getPlanSale() {
        return this.PlanSale;
    }
    
    public void setPlanSale(BigDecimal PlanSale) {
        this.PlanSale = PlanSale;
    }

    
    @Column(name="DATE_FROM", columnDefinition="TIMESTAMP")
    public Date getDateFrom() {
        return this.DateFrom;
    }
    
    public void setDateFrom(Date DateFrom) {
        this.DateFrom = DateFrom;
    }

    
    @Column(name="DATE_TILL", columnDefinition="TIMESTAMP")
    public Date getDateTill() {
        return this.DateTill;
    }
    
    public void setDateTill(Date DateTill) {
        this.DateTill = DateTill;
    }

    
    @Column(name="IS_ACTIVE", columnDefinition="SMALLINT")
    public boolean isIsActive() {
        return this.IsActive;
    }
    
    public void setIsActive(boolean IsActive) {
        this.IsActive = IsActive;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public SecUser getUser() {
        return this.User;
    }
    
    public void setUser(SecUser User) {
        this.User = User;
    }

    
    @Column(name="FACTSALE", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getFactSale() {
        return this.FactSale;
    }
    
    public void setFactSale(BigDecimal FactSale) {
        this.FactSale = FactSale;
    }

    
    @Column(name="COMMENTS", columnDefinition="VARCHAR", length=256)
    public String getComments() {
        return this.Comments;
    }
    
    public void setComments(String Comments) {
        this.Comments = Comments;
    }




}


