package com.mg.merp.settlement.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.core.model.SysClient;
import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.CurrencyRateAuthority;
import com.mg.merp.reference.model.CurrencyRateType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SettlementConfig generated by hbm2java
 */
@Entity
@Table(name="STL_CONFIG"
)
public class SettlementConfig extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private SysClient SysClient;
     private Currency Currency;
     private Currency NarCurrency;
     private CurrencyRateType RefCurrencyRateType;
     private CurrencyRateAuthority RefCurrencyRateAuthority;
     private Integer CurrencyPrec;

    public SettlementConfig() {
    }

	
    public SettlementConfig(SysClient SysClient) {
        this.SysClient = SysClient;
    }
    public SettlementConfig(SysClient SysClient, Currency Currency, Currency NarCurrency, CurrencyRateType RefCurrencyRateType, CurrencyRateAuthority RefCurrencyRateAuthority, Integer CurrencyPrec) {
       this.SysClient = SysClient;
       this.Currency = Currency;
       this.NarCurrency = NarCurrency;
       this.RefCurrencyRateType = RefCurrencyRateType;
       this.RefCurrencyRateAuthority = RefCurrencyRateAuthority;
       this.CurrencyPrec = CurrencyPrec;
    }
   
     @Id 

    
    @Column(name="CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }
    
    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BASE_CURRENCY")
    public Currency getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(Currency Currency) {
        this.Currency = Currency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NAT_CURRENCY")
    public Currency getNarCurrency() {
        return this.NarCurrency;
    }
    
    public void setNarCurrency(Currency NarCurrency) {
        this.NarCurrency = NarCurrency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_TYPE_ID")
    public CurrencyRateType getRefCurrencyRateType() {
        return this.RefCurrencyRateType;
    }
    
    public void setRefCurrencyRateType(CurrencyRateType RefCurrencyRateType) {
        this.RefCurrencyRateType = RefCurrencyRateType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_AUTHORITY_ID")
    public CurrencyRateAuthority getRefCurrencyRateAuthority() {
        return this.RefCurrencyRateAuthority;
    }
    
    public void setRefCurrencyRateAuthority(CurrencyRateAuthority RefCurrencyRateAuthority) {
        this.RefCurrencyRateAuthority = RefCurrencyRateAuthority;
    }

    
    @Column(name="CURRENCY_PREC", columnDefinition="INTEGER")
    public Integer getCurrencyPrec() {
        return this.CurrencyPrec;
    }
    
    public void setCurrencyPrec(Integer CurrencyPrec) {
        this.CurrencyPrec = CurrencyPrec;
    }




}


