package com.mg.merp.settlement.model;
// Generated Sep 28, 2015 11:47:52 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.CurrencyRateAuthority;
import com.mg.merp.reference.model.CurrencyRateType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StlConfig generated by hbm2java
 */
@Entity
@Table(name="STL_CONFIG"
)
public class StlConfig extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int SysClientId;
     private Currency BaseCurrency;
     private Currency NatCurrency;
     private CurrencyRateType CurrencyRateType;
     private CurrencyRateAuthority CurrencyRateAuthority;
     private Integer CurrencyPrec;

    public StlConfig() {
    }

	
    public StlConfig(int SysClientId) {
        this.SysClientId = SysClientId;
    }
    public StlConfig(int SysClientId, Currency BaseCurrency, Currency NatCurrency, CurrencyRateType CurrencyRateType, CurrencyRateAuthority CurrencyRateAuthority, Integer CurrencyPrec) {
       this.SysClientId = SysClientId;
       this.BaseCurrency = BaseCurrency;
       this.NatCurrency = NatCurrency;
       this.CurrencyRateType = CurrencyRateType;
       this.CurrencyRateAuthority = CurrencyRateAuthority;
       this.CurrencyPrec = CurrencyPrec;
    }
   
     @Id 

    
    @Column(name="CLIENT_ID", unique=true, columnDefinition="INTEGER")
    public int getSysClientId() {
        return this.SysClientId;
    }
    
    public void setSysClientId(int SysClientId) {
        this.SysClientId = SysClientId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BASE_CURRENCY")
    public Currency getBaseCurrency() {
        return this.BaseCurrency;
    }
    
    public void setBaseCurrency(Currency BaseCurrency) {
        this.BaseCurrency = BaseCurrency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NAT_CURRENCY")
    public Currency getNatCurrency() {
        return this.NatCurrency;
    }
    
    public void setNatCurrency(Currency NatCurrency) {
        this.NatCurrency = NatCurrency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_TYPE_ID")
    public CurrencyRateType getCurrencyRateType() {
        return this.CurrencyRateType;
    }
    
    public void setCurrencyRateType(CurrencyRateType CurrencyRateType) {
        this.CurrencyRateType = CurrencyRateType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_AUTHORITY_ID")
    public CurrencyRateAuthority getCurrencyRateAuthority() {
        return this.CurrencyRateAuthority;
    }
    
    public void setCurrencyRateAuthority(CurrencyRateAuthority CurrencyRateAuthority) {
        this.CurrencyRateAuthority = CurrencyRateAuthority;
    }

    
    @Column(name="CURRENCY_PREC", columnDefinition="INTEGER")
    public Integer getCurrencyPrec() {
        return this.CurrencyPrec;
    }
    
    public void setCurrencyPrec(Integer CurrencyPrec) {
        this.CurrencyPrec = CurrencyPrec;
    }




}


