package com.mg.merp.paymentcontrol.model;
// Generated Sep 28, 2015 11:36:59 PM by Hibernate Tools 3.6.0.Final


import com.mg.merp.reference.model.Currency;
import com.mg.merp.reference.model.CurrencyRateAuthority;
import com.mg.merp.reference.model.CurrencyRateType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PmcConfig generated by hbm2java
 */
@Entity
@Table(name="PMC_CONFIG"
)
public class PmcConfig extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private int SysClientId;
     private Currency Currency;
     private CurrencyRateType CurRateType;
     private CurrencyRateAuthority CurRateAuthority;
     private Short CurrencyPrec;

    public PmcConfig() {
    }

	
    public PmcConfig(int SysClientId) {
        this.SysClientId = SysClientId;
    }
    public PmcConfig(int SysClientId, Currency Currency, CurrencyRateType CurRateType, CurrencyRateAuthority CurRateAuthority, Short CurrencyPrec) {
       this.SysClientId = SysClientId;
       this.Currency = Currency;
       this.CurRateType = CurRateType;
       this.CurRateAuthority = CurRateAuthority;
       this.CurrencyPrec = CurrencyPrec;
    }
   
     @Id 

    
    @Column(name="CLIENT_ID", unique=true, columnDefinition="INTEGER")
    public int getSysClientId() {
        return this.SysClientId;
    }
    
    public void setSysClientId(int SysClientId) {
        this.SysClientId = SysClientId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NAT_CURRENCY")
    public Currency getCurrency() {
        return this.Currency;
    }
    
    public void setCurrency(Currency Currency) {
        this.Currency = Currency;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_TYPE_ID")
    public CurrencyRateType getCurRateType() {
        return this.CurRateType;
    }
    
    public void setCurRateType(CurrencyRateType CurRateType) {
        this.CurRateType = CurRateType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUR_RATE_AUTHORITY_ID")
    public CurrencyRateAuthority getCurRateAuthority() {
        return this.CurRateAuthority;
    }
    
    public void setCurRateAuthority(CurrencyRateAuthority CurRateAuthority) {
        this.CurRateAuthority = CurRateAuthority;
    }

    
    @Column(name="CURRENCY_PREC", columnDefinition="SMALLINT")
    public Short getCurrencyPrec() {
        return this.CurrencyPrec;
    }
    
    public void setCurrencyPrec(Short CurrencyPrec) {
        this.CurrencyPrec = CurrencyPrec;
    }




}


