package com.mg.merp.paymentcontrol.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.security.model.SecUser;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name = "PMC_VERSION")
public class Version extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private SysClient SysClient;

    private SecUser Creator;

    private String Name;

    private boolean Available;

    private Date CreateDate;

    private Set<Liability> SetOfPmcLiability = new HashSet<Liability>(0);

    private Set<VersionStatus> SetOfPmcVerstatus = new HashSet<VersionStatus>(0);

    private Set<Execution> SetOfPmcExecution = new HashSet<Execution>(0);

    public Version() {
    }

    public Version(SysClient SysClient, SecUser Creator, String Name, boolean Available, Date CreateDate, Set<Liability> SetOfPmcLiability, Set<VersionStatus> SetOfPmcVerstatus, Set<Execution> SetOfPmcExecution) {
        this.SysClient = SysClient;
        this.Creator = Creator;
        this.Name = Name;
        this.Available = Available;
        this.CreateDate = CreateDate;
        this.SetOfPmcLiability = SetOfPmcLiability;
        this.SetOfPmcVerstatus = SetOfPmcVerstatus;
        this.SetOfPmcExecution = SetOfPmcExecution;
    }

    @SequenceGenerator(name = "generator", sequenceName = "PMC_VERSION_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    @DataItemName("ID")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATOR_ID")
    @DataItemName("PaymentControl.Version.Creator")
    public SecUser getCreator() {
        return this.Creator;
    }

    public void setCreator(SecUser Creator) {
        this.Creator = Creator;
    }

    @Column(name = "NAME", columnDefinition = "VARCHAR", length = 80)
    @DataItemName("PaymentControl.Payment.Name")
    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @Column(name = "AVAILABLE", columnDefinition = "SMALLINT")
    @DataItemName("PaymentControl.Version.Available")
    public boolean isAvailable() {
        return this.Available;
    }

    public void setAvailable(boolean Available) {
        this.Available = Available;
    }

    @Column(name = "CREATEDATE", columnDefinition = "TIMESTAMP")
    @DataItemName("PaymentControl.Version.CreateDate")
    public Date getCreateDate() {
        return this.CreateDate;
    }

    public void setCreateDate(Date CreateDate) {
        this.CreateDate = CreateDate;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "VERSION_ID", updatable = false)
    public Set<Liability> getSetOfPmcLiability() {
        return this.SetOfPmcLiability;
    }

    public void setSetOfPmcLiability(Set<Liability> SetOfPmcLiability) {
        this.SetOfPmcLiability = SetOfPmcLiability;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "VERSION_ID", updatable = false)
    public Set<VersionStatus> getSetOfPmcVerstatus() {
        return this.SetOfPmcVerstatus;
    }

    public void setSetOfPmcVerstatus(Set<VersionStatus> SetOfPmcVerstatus) {
        this.SetOfPmcVerstatus = SetOfPmcVerstatus;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "VERSION_ID", updatable = false)
    public Set<Execution> getSetOfPmcExecution() {
        return this.SetOfPmcExecution;
    }

    public void setSetOfPmcExecution(Set<Execution> SetOfPmcExecution) {
        this.SetOfPmcExecution = SetOfPmcExecution;
    }
}

