package com.mg.merp.docprocess.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.security.model.SecUser;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DocHeadState generated by hbm2java
 */
@Entity
@Table(name="DOCHEADSTATE"
)
public class DocHeadState extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private DocAction DocAction;
     private SecUser User;
     private BigDecimal ReadySum;
     private Integer Data1;
     private Integer Data2;
     private Serializable StateValue;
     private Date DateTime;
     private Set<DocSpecState> DocSpecStates = new HashSet<DocSpecState>(0);

    public DocHeadState() {
    }

    public DocHeadState(DocAction DocAction, SecUser User, BigDecimal ReadySum, Integer Data1, Integer Data2, Serializable StateValue, Date DateTime, Set<DocSpecState> DocSpecStates) {
       this.DocAction = DocAction;
       this.User = User;
       this.ReadySum = ReadySum;
       this.Data1 = Data1;
       this.Data2 = Data2;
       this.StateValue = StateValue;
       this.DateTime = DateTime;
       this.DocSpecStates = DocSpecStates;
    }
   
     @SequenceGenerator(name="generator", sequenceName="DOCHEADSTATE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCACTION_ID")
    public DocAction getDocAction() {
        return this.DocAction;
    }
    
    public void setDocAction(DocAction DocAction) {
        this.DocAction = DocAction;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public SecUser getUser() {
        return this.User;
    }
    
    public void setUser(SecUser User) {
        this.User = User;
    }

    
    @Column(name="READYSUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getReadySum() {
        return this.ReadySum;
    }
    
    public void setReadySum(BigDecimal ReadySum) {
        this.ReadySum = ReadySum;
    }

    
    @Column(name="DATA1", columnDefinition="INTEGER")
    public Integer getData1() {
        return this.Data1;
    }
    
    public void setData1(Integer Data1) {
        this.Data1 = Data1;
    }

    
    @Column(name="DATA2", columnDefinition="INTEGER")
    public Integer getData2() {
        return this.Data2;
    }
    
    public void setData2(Integer Data2) {
        this.Data2 = Data2;
    }

    
    @Column(name="STATE_VALUE", columnDefinition="BLOB")
    public Serializable getStateValue() {
        return this.StateValue;
    }
    
    public void setStateValue(Serializable StateValue) {
        this.StateValue = StateValue;
    }

    
    @Column(name="DATETIME", columnDefinition="TIMESTAMP")
    public Date getDateTime() {
        return this.DateTime;
    }
    
    public void setDateTime(Date DateTime) {
        this.DateTime = DateTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="DocHeadState")
    public Set<DocSpecState> getDocSpecStates() {
        return this.DocSpecStates;
    }
    
    public void setDocSpecStates(Set<DocSpecState> DocSpecStates) {
        this.DocSpecStates = DocSpecStates;
    }




}


