package com.mg.merp.docprocess.model;

import com.mg.merp.core.model.SysClient;
import com.mg.merp.security.model.Groups;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Enumerated;
import javax.persistence.EnumType;

/**
 * DocProcessStageRights generated by hbm2java
 */
@Entity
@Table(name = "DOCPROCESSSTAGE_RIGHTS")
public class DocProcessStageRights extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {

    private Integer Id;

    private Groups SecGroups;

    private SysClient SysClient;

    private DocProcessStage DocProcessStage;

    private ActionUserGrant Grants;

    public DocProcessStageRights() {
    }

    public DocProcessStageRights(Groups SecGroups, SysClient SysClient, DocProcessStage DocProcessStage, ActionUserGrant Grants) {
        this.SecGroups = SecGroups;
        this.SysClient = SysClient;
        this.DocProcessStage = DocProcessStage;
        this.Grants = Grants;
    }

    @SequenceGenerator(name = "generator", sequenceName = "DOCPROCESSSTAGERIGHTS_ID_GEN")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "ID", unique = true, columnDefinition = "INTEGER")
    public Integer getId() {
        return this.Id;
    }

    public void setId(Integer Id) {
        this.Id = Id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GROUP_ID")
    public Groups getSecGroups() {
        return this.SecGroups;
    }

    public void setSecGroups(Groups SecGroups) {
        this.SecGroups = SecGroups;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_ID")
    public SysClient getSysClient() {
        return this.SysClient;
    }

    public void setSysClient(SysClient SysClient) {
        this.SysClient = SysClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STAGE_ID")
    public DocProcessStage getDocProcessStage() {
        return this.DocProcessStage;
    }

    public void setDocProcessStage(DocProcessStage DocProcessStage) {
        this.DocProcessStage = DocProcessStage;
    }

    @Column(name = "GRANTS")
    @Enumerated(EnumType.ORDINAL)
    public ActionUserGrant getGrants() {
        return this.Grants;
    }

    public void setGrants(ActionUserGrant Grants) {
        this.Grants = Grants;
    }
}

