package com.mg.merp.docprocess.model;
// Generated Oct 4, 2015 2:18:05 AM by Hibernate Tools 3.6.0.Final


import com.mg.merp.document.model.DocSpec;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DocSpecState generated by hbm2java
 */
@Entity
@Table(name="DOCSPECSTATE"
)
public class DocSpecState extends com.mg.merp.core.model.AbstractEntity implements java.io.Serializable {


     private Integer Id;
     private DocHeadState DocHeadState;
     private DocSpec DocSpec;
     private BigDecimal ReadyQuantity1;
     private BigDecimal ReadySum;
     private Integer Data1;
     private BigDecimal ReadyQuantity2;
     private Integer Data2;
     private Serializable StateValue;

    public DocSpecState() {
    }

    public DocSpecState(DocHeadState DocHeadState, DocSpec DocSpec, BigDecimal ReadyQuantity1, BigDecimal ReadySum, Integer Data1, BigDecimal ReadyQuantity2, Integer Data2, Serializable StateValue) {
       this.DocHeadState = DocHeadState;
       this.DocSpec = DocSpec;
       this.ReadyQuantity1 = ReadyQuantity1;
       this.ReadySum = ReadySum;
       this.Data1 = Data1;
       this.ReadyQuantity2 = ReadyQuantity2;
       this.Data2 = Data2;
       this.StateValue = StateValue;
    }
   
     @SequenceGenerator(name="generator", sequenceName="DOCSPECSTATE_ID_GEN")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")

    
    @Column(name="ID", unique=true, columnDefinition="INTEGER")
    public Integer getId() {
        return this.Id;
    }
    
    public void setId(Integer Id) {
        this.Id = Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCHEADSTATE_ID")
    public DocHeadState getDocHeadState() {
        return this.DocHeadState;
    }
    
    public void setDocHeadState(DocHeadState DocHeadState) {
        this.DocHeadState = DocHeadState;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DOCSPEC_ID")
    public DocSpec getDocSpec() {
        return this.DocSpec;
    }
    
    public void setDocSpec(DocSpec DocSpec) {
        this.DocSpec = DocSpec;
    }

    
    @Column(name="READYQUANTITY", columnDefinition="NUMERIC", precision=15, scale=3)
    public BigDecimal getReadyQuantity1() {
        return this.ReadyQuantity1;
    }
    
    public void setReadyQuantity1(BigDecimal ReadyQuantity1) {
        this.ReadyQuantity1 = ReadyQuantity1;
    }

    
    @Column(name="READYSUMMA", columnDefinition="NUMERIC", precision=15, scale=4)
    public BigDecimal getReadySum() {
        return this.ReadySum;
    }
    
    public void setReadySum(BigDecimal ReadySum) {
        this.ReadySum = ReadySum;
    }

    
    @Column(name="DATA1", columnDefinition="INTEGER")
    public Integer getData1() {
        return this.Data1;
    }
    
    public void setData1(Integer Data1) {
        this.Data1 = Data1;
    }

    
    @Column(name="READYQUANTITY2", columnDefinition="NUMERIC", precision=18, scale=3)
    public BigDecimal getReadyQuantity2() {
        return this.ReadyQuantity2;
    }
    
    public void setReadyQuantity2(BigDecimal ReadyQuantity2) {
        this.ReadyQuantity2 = ReadyQuantity2;
    }

    
    @Column(name="DATA2", columnDefinition="INTEGER")
    public Integer getData2() {
        return this.Data2;
    }
    
    public void setData2(Integer Data2) {
        this.Data2 = Data2;
    }

    
    @Column(name="STATE_VALUE", columnDefinition="BLOB")
    public Serializable getStateValue() {
        return this.StateValue;
    }
    
    public void setStateValue(Serializable StateValue) {
        this.StateValue = StateValue;
    }




}


